module

/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import Langlib.Grammars.Unrestricted.Definition
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Irrational
import Mathlib.Tactic.NormNum.IsCoprime
import Mathlib.Tactic.NormNum.IsSquare
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.ModEq
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.NatFib
import Mathlib.Tactic.NormNum.NatLog
import Mathlib.Tactic.NormNum.NatSqrt
import Mathlib.Tactic.NormNum.Ordinal
import Mathlib.Tactic.NormNum.Parity
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Topology.Sheaves.Init

@[expose] public section

/-! # Linear Languages

This file defines the class of linear languages. A linear grammar is a context-free
grammar in which every production has **at most one** nonterminal on the right-hand
side. Equivalently, every rule has the form `A → w` or `A → u B v` where `u`, `v`
are terminal strings and `B` is a nonterminal.

Linear languages sit strictly between the regular and the context-free languages
in the Chomsky hierarchy:

    Regular ⊊ Linear ⊊ Context-Free

## Main declarations

- `linear_output`    — Predicate: a symbol string has at most one nonterminal.
- `grammar_linear`   — Predicate: an unrestricted grammar is linear.
- `is_Linear`        — A language is linear.
- `Linear`           — The class of linear languages.
-/

variable {T : Type}

/-- A symbol string has **linear output form** if it contains at most one nonterminal.
Concretely, it is either a purely terminal string or can be decomposed as
`map terminal u ++ [nonterminal B] ++ map terminal v`. -/
def linear_output {N : Type} (s : List (symbol T N)) : Prop :=
  (∀ x ∈ s, ∃ t, x = symbol.terminal t) ∨
  (∃ (u : List T) (B : N) (v : List T),
    s = List.map symbol.terminal u ++ [symbol.nonterminal B] ++ List.map symbol.terminal v)

/-- An unrestricted grammar is **linear** if every rule is context-free
(empty left/right context) and has linear output. -/
def grammar_linear (g : grammar T) : Prop :=
  ∀ r ∈ g.rules,
    r.input_L = [] ∧ r.input_R = [] ∧ linear_output r.output_string

/-- A language is **linear** if it is generated by some linear unrestricted grammar. -/
def is_Linear (L : Language T) : Prop :=
  ∃ g : grammar T, grammar_linear g ∧ grammar_language g = L

/-- The class of linear languages. -/
def Linear : Set (Language T) :=
  setOf is_Linear
