import Mathlib
import Langlib.Classes.Linear.Definition
import Langlib.Classes.ContextFree.Examples.AnBn
import Langlib.Utilities.Tactics

/-! # `a^n b^n` as a Linear Language

This file constructs a linear grammar for `{a^n b^n}` and proves that the
language is linear.

## Main results

- `linear_grammar_anbn_language` — the grammar generates exactly `anbn`
- `anbn_is_Linear`               — `{a^n b^n}` is linear
-/

open Language List Relation Classical

noncomputable section

/-- An unrestricted grammar for the language `{aⁿbⁿ | n ∈ ℕ}` with linear rules.
Rules:
  S → aSb   (i.e., [] S [] → [a, S, b])
  S → ε     (i.e., [] S [] → [])
-/
def linear_grammar_anbn : grammar Bool where
  nt := Unit
  initial := ()
  rules := [
    ⟨[], (), [], [symbol.terminal false, symbol.nonterminal (), symbol.terminal true]⟩,
    ⟨[], (), [], []⟩
  ]

/-- The grammar `linear_grammar_anbn` is linear. -/
theorem linear_grammar_anbn_is_linear :
    grammar_linear linear_grammar_anbn := by
  intro r hr
  simp [linear_grammar_anbn] at hr
  rcases hr with rfl | rfl <;> refine ⟨rfl, rfl, ?_⟩
  · exact Or.inr ⟨[false], (), [true], by simp⟩
  · exact Or.inl (by simp)

/-- Derivation in `linear_grammar_anbn` can produce `aⁿSbⁿ`. -/
lemma linear_grammar_anbn_derives_n (n : ℕ) :
    grammar_derives linear_grammar_anbn
      [symbol.nonterminal ()]
      (List.replicate n (symbol.terminal false) ++
        [symbol.nonterminal ()] ++
        List.replicate n (symbol.terminal true)) := by
  induction n with
  | zero => simp; exact ReflTransGen.refl
  | succ n ih =>
    apply ReflTransGen.trans ih
    apply ReflTransGen.single
    refine ⟨⟨[], (), [], [symbol.terminal false, symbol.nonterminal (), symbol.terminal true]⟩,
      ?_, List.replicate n (symbol.terminal false), List.replicate n (symbol.terminal true), ?_, ?_⟩
    · simp [linear_grammar_anbn]
    · simp
    · simp [List.replicate_succ']
      rw [← List.replicate_succ, ← List.replicate_succ']

/-- Derivation in `linear_grammar_anbn`: apply ε-rule to get `aⁿbⁿ`. -/
lemma linear_grammar_anbn_derives_final (n : ℕ) :
    grammar_derives linear_grammar_anbn
      (List.replicate n (symbol.terminal false) ++
        [symbol.nonterminal ()] ++
        List.replicate n (symbol.terminal true))
      (List.replicate n (symbol.terminal false) ++
        List.replicate n (symbol.terminal true)) := by
  apply ReflTransGen.single
  refine ⟨⟨[], (), [], []⟩, ?_,
    List.replicate n (symbol.terminal false),
    List.replicate n (symbol.terminal true), ?_, ?_⟩
  · simp [linear_grammar_anbn]
  · simp
  · simp

/-- Every word in `anbn` is generated by `linear_grammar_anbn`. -/
lemma anbn_sub_linear_grammar_anbn_language :
    ∀ w, w ∈ anbn → w ∈ grammar_language linear_grammar_anbn := by
  intro w hw
  obtain ⟨n, rfl⟩ := hw
  show grammar_generates linear_grammar_anbn _
  unfold grammar_generates
  have h1 := linear_grammar_anbn_derives_n n
  have h2 := linear_grammar_anbn_derives_final n
  apply ReflTransGen.trans h1
  simp only [List.map_append, List.map_replicate]
  exact h2

/-- A sentential form of `linear_grammar_anbn` is either `aⁿSbⁿ` or `aⁿbⁿ`. -/
private def anbn_sentential (w : List (symbol Bool Unit)) : Prop :=
  (∃ n : ℕ, w = List.replicate n (symbol.terminal false) ++
    [symbol.nonterminal ()] ++
    List.replicate n (symbol.terminal true)) ∨
  (∃ n : ℕ, w = List.map symbol.terminal
    (List.replicate n false ++ List.replicate n true))

/-
One step of derivation preserves `anbn_sentential` form.
-/
private lemma anbn_sentential_step (w w' : List (symbol Bool Unit))
    (hw : anbn_sentential w) (ht : grammar_transforms linear_grammar_anbn w w') :
    anbn_sentential w' := by
      rcases ht with ⟨ r, hr, u, v, hw₁, hw₂ ⟩;
      rcases hw with ( ⟨ n, rfl ⟩ | ⟨ n, rfl ⟩ ) <;> simp_all +decide [ List.append_assoc ];
      · rcases r with ⟨ L, N, R, S ⟩ ; simp_all +decide [ linear_grammar_anbn ];
        rcases hr with ( ⟨ rfl, rfl, rfl, rfl ⟩ | ⟨ rfl, rfl, rfl, rfl ⟩ ) <;> simp_all +decide [ anbn_sentential ];
        · rw [ List.append_eq_append_iff ] at hw₁;
          rcases hw₁ with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h₁, h₂ ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
          · rcases as with ( _ | ⟨ a, as ⟩ ) <;> simp_all +decide [ List.replicate ];
            · refine' Or.inl ⟨ n + 1, Or.inl ⟨ [ symbol.terminal false ], _, _ ⟩ ⟩ <;> simp +decide [ *, List.replicate ];
              exact Nat.recOn n ( by trivial ) fun n ih => by simp +decide [ List.replicate ] at * ; aesop;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ a, bs ⟩ ) <;> simp_all +decide [ List.replicate ];
            · refine Or.inl ⟨ n + 1, ?_ ⟩ ; simp_all +decide [ List.replicate ];
              exact Or.inl ⟨ [ symbol.terminal false ], by rw [ ← h₁ ] ; exact Nat.recOn n ( by simp +decide ) fun n ihn => by simp +decide [ List.replicate ] at * ; aesop ⟩;
            · replace h₁ := congr_arg List.toFinset h₁ ; rw [ Finset.ext_iff ] at h₁ ; specialize h₁ a ; aesop;
        · rw [ List.append_eq_append_iff ] at hw₁;
          rcases hw₁ with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h₁, h₂ ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
          · rcases as with ( _ | ⟨ a, as ⟩ ) <;> simp_all +decide [ List.replicate ];
            · exact Or.inr ⟨ n, Or.inl ⟨ [ ], by simp +decide [ h.symm ] ⟩ ⟩;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ a, bs ⟩ ) <;> simp_all +decide [ List.append_assoc ];
            · exact Or.inr ⟨ n, Or.inl ⟨ [ ], by aesop ⟩ ⟩;
            · replace h₁ := congr_arg List.toFinset h₁ ; rw [ Finset.ext_iff ] at h₁ ; specialize h₁ a ; aesop;
      · replace hw₁ := congr_arg List.toFinset hw₁ ; rw [ Finset.ext_iff ] at hw₁ ; specialize hw₁ ( symbol.nonterminal r.input_N ) ; aesop;

/-- Derivation preserves `anbn_sentential` form. -/
private lemma anbn_sentential_of_derives (w : List (symbol Bool Unit))
    (hd : grammar_derives linear_grammar_anbn [symbol.nonterminal ()] w) :
    anbn_sentential w := by
  induction hd with
  | refl => exact Or.inl ⟨0, by simp⟩
  | tail _ ht ih => exact anbn_sentential_step _ _ ih ht

/-- Every word generated by `linear_grammar_anbn` is in `anbn`. -/
lemma linear_grammar_anbn_language_sub_anbn :
    ∀ w, w ∈ grammar_language linear_grammar_anbn → w ∈ anbn := by
  intro w hw
  have hsf := anbn_sentential_of_derives (List.map symbol.terminal w) hw
  rcases hsf with ⟨n, hn⟩ | ⟨n, hn⟩
  · no_nonterminal
  · have hinj : Function.Injective (symbol.terminal (T := Bool) (N := Unit)) := by
      intro a b h; cases h; rfl
    exact ⟨n, hinj.list_map hn⟩

/-- The grammar `linear_grammar_anbn` generates exactly `{aⁿbⁿ}`. -/
theorem linear_grammar_anbn_language :
    grammar_language linear_grammar_anbn = anbn := by
  ext w
  exact ⟨fun h => linear_grammar_anbn_language_sub_anbn w h,
         fun h => anbn_sub_linear_grammar_anbn_language w h⟩

/-- The language `{aⁿbⁿ}` is linear. -/
theorem anbn_is_Linear : is_Linear anbn :=
  ⟨linear_grammar_anbn, linear_grammar_anbn_is_linear,
   linear_grammar_anbn_language⟩

end
