module -- shake: keep-all

--! Auto-generated import hub for the langlib language classes.
--  Run `scripts/generate_import_hub.py --hub classes` to regenerate.

public import Langlib.Classes.ContextFree.Basics.Elementary
public import Langlib.Classes.ContextFree.Basics.EncodedCFG
public import Langlib.Classes.ContextFree.Basics.FiniteNT
public import Langlib.Classes.ContextFree.Basics.Lifting
public import Langlib.Classes.ContextFree.Basics.Ogden
public import Langlib.Classes.ContextFree.Basics.Pumping
public import Langlib.Classes.ContextFree.Basics.Splitting
public import Langlib.Classes.ContextFree.Closure.Bijection
public import Langlib.Classes.ContextFree.Closure.Complement
public import Langlib.Classes.ContextFree.Closure.Concatenation
public import Langlib.Classes.ContextFree.Closure.ConcatenationBonus
public import Langlib.Classes.ContextFree.Closure.ConverseFailures
public import Langlib.Classes.ContextFree.Closure.Homomorphism
public import Langlib.Classes.ContextFree.Closure.Intersection
public import Langlib.Classes.ContextFree.Closure.IntersectionRegular
public import Langlib.Classes.ContextFree.Closure.InverseHomomorphism
public import Langlib.Classes.ContextFree.Closure.Permutation
public import Langlib.Classes.ContextFree.Closure.Prefix
public import Langlib.Classes.ContextFree.Closure.PrefixBonus
public import Langlib.Classes.ContextFree.Closure.Quotient
public import Langlib.Classes.ContextFree.Closure.Reverse
public import Langlib.Classes.ContextFree.Closure.Star
public import Langlib.Classes.ContextFree.Closure.Substitution.Core
public import Langlib.Classes.ContextFree.Closure.Substitution.Support
public import Langlib.Classes.ContextFree.Closure.Substitution
public import Langlib.Classes.ContextFree.Closure.Suffix
public import Langlib.Classes.ContextFree.Closure.Union
public import Langlib.Classes.ContextFree.Closure.UnionBonus
public import Langlib.Classes.ContextFree.Closure.UnionBonus2
public import Langlib.Classes.ContextFree.Decidability.Characterization
public import Langlib.Classes.ContextFree.Decidability.Emptiness
public import Langlib.Classes.ContextFree.Decidability.Helper
public import Langlib.Classes.ContextFree.Decidability.Membership
public import Langlib.Classes.ContextFree.Decidability.PrimrecSatStep
public import Langlib.Classes.ContextFree.Decidability.UniformMembership
public import Langlib.Classes.ContextFree.Definition
public import Langlib.Classes.ContextFree.Examples.A2nBn
public import Langlib.Classes.ContextFree.Examples.A2nBnPos
public import Langlib.Classes.ContextFree.Examples.A2nBnPosStar
public import Langlib.Classes.ContextFree.Examples.AnBmCm
public import Langlib.Classes.ContextFree.Examples.AnBn
public import Langlib.Classes.ContextFree.Examples.AnBnCm
public import Langlib.Classes.ContextFree.Examples.AnBnCn
public import Langlib.Classes.ContextFree.Examples.AnBnCnPos
public import Langlib.Classes.ContextFree.Examples.BnAn
public import Langlib.Classes.ContextFree.Examples.BnAnPos
public import Langlib.Classes.ContextFree.Examples.BnAnPosStarB
public import Langlib.Classes.ContextFree.Examples.L4
public import Langlib.Classes.ContextFree.Examples.SingletonWord
public import Langlib.Classes.ContextFree.Examples.UnaryA2PowSucc
public import Langlib.Classes.ContextFree.Inclusion.ContextSensitive
public import Langlib.Classes.ContextFree.Inclusion.Indexed
public import Langlib.Classes.ContextFree.Inclusion.Recursive
public import Langlib.Classes.ContextFree.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.ContextFree.Inclusion.StrictContextSensitive
public import Langlib.Classes.ContextFree.Inclusion.StrictIndexed
public import Langlib.Classes.ContextFree.Inclusion.StrictRecursivelyEnumerable
public import Langlib.Classes.ContextFree.NormalForms.ChomskyNormalForm
public import Langlib.Classes.ContextFree.NormalForms.ChomskyNormalFormTranslation
public import Langlib.Classes.ContextFree.Pumping.ChomskyCountingSteps
public import Langlib.Classes.ContextFree.Pumping.CountingSteps
public import Langlib.Classes.ContextFree.Pumping.EpsilonElimination
public import Langlib.Classes.ContextFree.Pumping.LengthRestriction
public import Langlib.Classes.ContextFree.Pumping.ParseTree
public import Langlib.Classes.ContextFree.Pumping.Pumping
public import Langlib.Classes.ContextFree.Pumping.TerminalRestriction
public import Langlib.Classes.ContextFree.Pumping.UnitElimination
public import Langlib.Classes.ContextFree.Pumping.Utils
public import Langlib.Classes.ContextFree.Pumping.toMathlib
public import Langlib.Classes.ContextSensitive.Basics.NonContracting
public import Langlib.Classes.ContextSensitive.Closure.Bijection
public import Langlib.Classes.ContextSensitive.Closure.EmptyWord
public import Langlib.Classes.ContextSensitive.Closure.EpsFreeHomomorphism
public import Langlib.Classes.ContextSensitive.Closure.Reverse
public import Langlib.Classes.ContextSensitive.Decidability.Characterization
public import Langlib.Classes.ContextSensitive.Decidability.Membership
public import Langlib.Classes.ContextSensitive.Definition
public import Langlib.Classes.ContextSensitive.Examples.AnBnCn
public import Langlib.Classes.ContextSensitive.Examples.SingletonWord
public import Langlib.Classes.ContextSensitive.Inclusion.Recursive
public import Langlib.Classes.ContextSensitive.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.ContextSensitive.Inclusion.StrictRecursive
public import Langlib.Classes.DeterministicContextFree.Closure.Bijection
public import Langlib.Classes.DeterministicContextFree.Closure.Complement
public import Langlib.Classes.DeterministicContextFree.Closure.Concatenation
public import Langlib.Classes.DeterministicContextFree.Closure.Homomorphism
public import Langlib.Classes.DeterministicContextFree.Closure.Intersection
public import Langlib.Classes.DeterministicContextFree.Closure.IntersectionRegular
public import Langlib.Classes.DeterministicContextFree.Closure.Quotient
public import Langlib.Classes.DeterministicContextFree.Closure.Star
public import Langlib.Classes.DeterministicContextFree.Closure.Substitution
public import Langlib.Classes.DeterministicContextFree.Closure.Union
public import Langlib.Classes.DeterministicContextFree.Closure.UnionRegular
public import Langlib.Classes.DeterministicContextFree.Definition
public import Langlib.Classes.DeterministicContextFree.Examples.A2nBnPosStar
public import Langlib.Classes.DeterministicContextFree.Examples.AbcPositive
public import Langlib.Classes.DeterministicContextFree.Examples.AbcStack
public import Langlib.Classes.DeterministicContextFree.Examples.AnBmCm
public import Langlib.Classes.DeterministicContextFree.Examples.AnBn
public import Langlib.Classes.DeterministicContextFree.Examples.AnBnCm
public import Langlib.Classes.DeterministicContextFree.Examples.AnBnCn
public import Langlib.Classes.DeterministicContextFree.Examples.BnAnPosStarB
public import Langlib.Classes.DeterministicContextFree.Examples.SingletonWord
public import Langlib.Classes.DeterministicContextFree.Inclusion.ContextFree
public import Langlib.Classes.DeterministicContextFree.Inclusion.StrictContextFree
public import Langlib.Classes.Indexed.Closure.Concatenation
public import Langlib.Classes.Indexed.Closure.Homomorphism
public import Langlib.Classes.Indexed.Closure.Injection
public import Langlib.Classes.Indexed.Closure.Reverse
public import Langlib.Classes.Indexed.Closure.Union
public import Langlib.Classes.Indexed.Definition
public import Langlib.Classes.Indexed.Examples.AnBnCn
public import Langlib.Classes.Indexed.Examples.SingletonWord
public import Langlib.Classes.LR.Closure.Bijection
public import Langlib.Classes.LR.Examples.AnBn
public import Langlib.Classes.Linear.Basics.Map
public import Langlib.Classes.Linear.Closure.Concatenation
public import Langlib.Classes.Linear.Definition
public import Langlib.Classes.Linear.Examples.AnBn
public import Langlib.Classes.Linear.Examples.L4
public import Langlib.Classes.Linear.Examples.SingletonWord
public import Langlib.Classes.Linear.Inclusion.ContextFree
public import Langlib.Classes.Linear.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.Linear.Inclusion.StrictContextFree
public import Langlib.Classes.Linear.Pumping.Pumping
public import Langlib.Classes.Linear.Pumping.Spine
public import Langlib.Classes.Recursive.Basics.Elementary
public import Langlib.Classes.Recursive.Basics.Post
public import Langlib.Classes.Recursive.Closure.Complement
public import Langlib.Classes.Recursive.Closure.Concatenation
public import Langlib.Classes.Recursive.Closure.EpsFreeHomomorphism
public import Langlib.Classes.Recursive.Closure.Homomorphism
public import Langlib.Classes.Recursive.Closure.Intersection
public import Langlib.Classes.Recursive.Closure.IntersectionRegular
public import Langlib.Classes.Recursive.Closure.InverseHomomorphism
public import Langlib.Classes.Recursive.Closure.QuotientRegular
public import Langlib.Classes.Recursive.Closure.Reverse
public import Langlib.Classes.Recursive.Closure.Star
public import Langlib.Classes.Recursive.Closure.Substitution
public import Langlib.Classes.Recursive.Closure.Union
public import Langlib.Classes.Recursive.Decidability.Membership
public import Langlib.Classes.Recursive.Definition
public import Langlib.Classes.Recursive.Examples.SingletonWord
public import Langlib.Classes.Recursive.Inclusion.ByTapeFromComputable
public import Langlib.Classes.Recursive.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.Recursive.Inclusion.StrictRecursivelyEnumerable
public import Langlib.Classes.RecursivelyEnumerable.Basics.Lifting
public import Langlib.Classes.RecursivelyEnumerable.Closure.Bijection
public import Langlib.Classes.RecursivelyEnumerable.Closure.Complement
public import Langlib.Classes.RecursivelyEnumerable.Closure.Concatenation
public import Langlib.Classes.RecursivelyEnumerable.Closure.Homomorphism
public import Langlib.Classes.RecursivelyEnumerable.Closure.Intersection
public import Langlib.Classes.RecursivelyEnumerable.Closure.InverseHomomorphism
public import Langlib.Classes.RecursivelyEnumerable.Closure.Quotient
public import Langlib.Classes.RecursivelyEnumerable.Closure.Reverse
public import Langlib.Classes.RecursivelyEnumerable.Closure.Star.Helpers
public import Langlib.Classes.RecursivelyEnumerable.Closure.Star
public import Langlib.Classes.RecursivelyEnumerable.Closure.Substitution
public import Langlib.Classes.RecursivelyEnumerable.Closure.Union
public import Langlib.Classes.RecursivelyEnumerable.Decidability.Emptiness
public import Langlib.Classes.RecursivelyEnumerable.Decidability.Equivalence
public import Langlib.Classes.RecursivelyEnumerable.Decidability.Helper
public import Langlib.Classes.RecursivelyEnumerable.Decidability.Membership
public import Langlib.Classes.RecursivelyEnumerable.Decidability.Universality
public import Langlib.Classes.RecursivelyEnumerable.Definition
public import Langlib.Classes.RecursivelyEnumerable.Examples.AnBnCn
public import Langlib.Classes.RecursivelyEnumerable.Examples.EmptyWord
public import Langlib.Classes.RecursivelyEnumerable.Examples.Halting
public import Langlib.Classes.RecursivelyEnumerable.Examples.NonHalting
public import Langlib.Classes.RecursivelyEnumerable.Examples.SingletonWord
public import Langlib.Classes.RecursivelyEnumerable.NormalForms.Kuroda
public import Langlib.Classes.Regular.Basics.NonRegular
public import Langlib.Classes.Regular.Closure.Bijection
public import Langlib.Classes.Regular.Closure.Complement
public import Langlib.Classes.Regular.Closure.Concatenation
public import Langlib.Classes.Regular.Closure.Homomorphism
public import Langlib.Classes.Regular.Closure.Intersection
public import Langlib.Classes.Regular.Closure.InverseHomomorphism
public import Langlib.Classes.Regular.Closure.Prefix
public import Langlib.Classes.Regular.Closure.Quotient
public import Langlib.Classes.Regular.Closure.Reverse
public import Langlib.Classes.Regular.Closure.Star
public import Langlib.Classes.Regular.Closure.Substitution
public import Langlib.Classes.Regular.Closure.Suffix
public import Langlib.Classes.Regular.Closure.Union
public import Langlib.Classes.Regular.Decidability.Characterization
public import Langlib.Classes.Regular.Decidability.Emptiness
public import Langlib.Classes.Regular.Decidability.Equivalence
public import Langlib.Classes.Regular.Decidability.Helper
public import Langlib.Classes.Regular.Decidability.Membership
public import Langlib.Classes.Regular.Decidability.Universality
public import Langlib.Classes.Regular.Definition
public import Langlib.Classes.Regular.Examples.AnBn
public import Langlib.Classes.Regular.Examples.EmptyWord
public import Langlib.Classes.Regular.Examples.SingletonWord
public import Langlib.Classes.Regular.Examples.TopBot
public import Langlib.Classes.Regular.Inclusion.ContextFree
public import Langlib.Classes.Regular.Inclusion.DeterministicContextFree
public import Langlib.Classes.Regular.Inclusion.LR
public import Langlib.Classes.Regular.Inclusion.Linear
public import Langlib.Classes.Regular.Inclusion.Recursive
public import Langlib.Classes.Regular.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.Regular.Inclusion.StrictContextFree
public import Langlib.Classes.Regular.Inclusion.StrictDeterministicContextFree
public import Langlib.Classes.Regular.Inclusion.StrictLR
public import Langlib.Classes.Regular.Inclusion.StrictLinear
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Sym.Sym2.Init
import Mathlib.Topology.MetricSpace.Bounded
@[expose]
public section

/-! # Langlib Language Classes

This file is the import hub for the langlib language classes.

## Main declarations

- Imports the regular, context-free, indexed, recursive, recursively enumerable, and context-sensitive language-class developments.
-/
