module

public import Mathlib
@[expose]
public section

/-!
# Strict inclusions in the extended Chomsky hierarchy

This Mathlib-only Palomar challenge states eight strict inclusions between
grammar-defined language classes. Each theorem ranges over an arbitrary finite
terminal alphabet having at least the stated number of elements.

Deterministic context-free languages use their LR-grammar presentation here; the
separate class-equivalence challenge proves that this agrees with deterministic
pushdown-automaton recognition. No finite, pushdown, or linearly bounded machine
definition is part of this challenge. Recursive languages retain the standard
always-halting Mathlib TM0 presentation.
-/

open Relation Turing

/-! ## Grammar-defined language classes -/

/-- A grammar symbol is either a terminal or a nonterminal. -/
inductive symbol (T : Type) (N : Type) where
  | terminal : T -> symbol T N
  | nonterminal : N -> symbol T N
deriving DecidableEq

/-- An unrestricted rule represents `u A v -> w`. -/
structure grule (T : Type) (N : Type) where
  input_L : List (symbol T N)
  input_N : N
  input_R : List (symbol T N)
  output_string : List (symbol T N)

/-- An unrestricted grammar has a nonterminal type, start symbol, and finite rule list. -/
structure grammar (T : Type) where
  nt : Type
  initial : nt
  rules : List (grule T nt)

variable {T : Type}

/-- One unrestricted rewrite step, in an arbitrary surrounding context. -/
def grammar_transforms (g : grammar T) (w1 w2 : List (symbol T g.nt)) : Prop :=
  exists r : grule T g.nt, r ∈ g.rules ∧
    exists u v : List (symbol T g.nt),
      w1 = u ++ r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R ++ v ∧
      w2 = u ++ r.output_string ++ v

/-- Zero or more unrestricted rewrite steps. -/
def grammar_derives (g : grammar T) :
    List (symbol T g.nt) -> List (symbol T g.nt) -> Prop :=
  Relation.ReflTransGen (grammar_transforms g)

/-- An unrestricted grammar generates a terminal word from its start symbol. -/
def grammar_generates (g : grammar T) (w : List T) : Prop :=
  grammar_derives g [symbol.nonterminal g.initial] (List.map symbol.terminal w)

/-- The language generated by an unrestricted grammar. -/
def grammar_language (g : grammar T) : Language T := Set.ofPred (grammar_generates g)

/-- Right-regular outputs are `aB`, `a`, or the empty word. -/
def right_regular_output {N : Type} (s : List (symbol T N)) : Prop :=
  (exists a : T, exists B : N, s = [symbol.terminal a, symbol.nonterminal B]) ∨
  (exists a : T, s = [symbol.terminal a]) ∨ s = []

/-- A right-regular unrestricted grammar has context-free rules with right-regular outputs. -/
def grammar_right_regular (g : grammar T) : Prop :=
  forall r, r ∈ g.rules ->
    r.input_L = [] ∧ r.input_R = [] ∧ right_regular_output r.output_string

/-- A regular language is generated by a right-regular unrestricted grammar. -/
def is_RG (L : Language T) : Prop :=
  exists g : grammar T, grammar_right_regular g ∧ grammar_language g = L

/-- The class of regular languages. -/
def RG : Set (Language T) := Set.ofPred is_RG

/-- A linear output contains at most one nonterminal. -/
def linear_output {N : Type} (s : List (symbol T N)) : Prop :=
  (forall x, x ∈ s -> exists t, x = symbol.terminal t) ∨
  (exists (u : List T) (B : N) (v : List T),
    s = List.map symbol.terminal u ++ [symbol.nonterminal B] ++ List.map symbol.terminal v)

/-- A linear unrestricted grammar has context-free rules with linear outputs. -/
def grammar_linear (g : grammar T) : Prop :=
  forall r, r ∈ g.rules ->
    r.input_L = [] ∧ r.input_R = [] ∧ linear_output r.output_string

/-- A linear language is generated by a linear unrestricted grammar. -/
def is_Linear (L : Language T) : Prop :=
  exists g : grammar T, grammar_linear g ∧ grammar_language g = L

/-- The class of linear languages. -/
def Linear : Set (Language T) := Set.ofPred is_Linear

/-- A context-free unrestricted grammar rewrites one nonterminal without context. -/
def grammar_context_free (g : grammar T) : Prop :=
  forall r, r ∈ g.rules -> r.input_L = [] ∧ r.input_R = []

/-- A context-free language is generated by a context-free unrestricted grammar. -/
def is_CF (L : Language T) : Prop :=
  exists g : grammar T, grammar_context_free g ∧ grammar_language g = L

/-- The class of context-free languages. -/
def CF : Set (Language T) := Set.ofPred is_CF

/-- The optional distinguished erasing rule is exactly `S -> epsilon`. -/
def initial_epsilon_rule (g : grammar T) (r : grule T g.nt) : Prop :=
  r.input_L = [] ∧ r.input_N = g.initial ∧ r.input_R = [] ∧ r.output_string = []

/-- A rule is non-contracting when its output is no shorter than its input. -/
def grule_noncontracting {N : Type} (r : grule T N) : Prop :=
  r.output_string.length ≥ r.input_L.length + 1 + r.input_R.length

/-- The start symbol occurs on no rule's right-hand side. -/
def initial_not_on_rhs (g : grammar T) : Prop :=
  forall r, r ∈ g.rules -> symbol.nonterminal g.initial ∉ r.output_string

/-- A context-sensitive grammar is non-contracting apart from a controlled `S -> epsilon`. -/
def grammar_context_sensitive (g : grammar T) : Prop :=
  (forall r, r ∈ g.rules -> initial_epsilon_rule g r ∨ grule_noncontracting r) ∧
  ((exists r, r ∈ g.rules ∧ initial_epsilon_rule g r) -> initial_not_on_rhs g)

/-- A context-sensitive language is generated by a context-sensitive unrestricted grammar. -/
def is_CS (L : Language T) : Prop :=
  exists g : grammar T, grammar_context_sensitive g ∧ grammar_language g = L

/-- The class of context-sensitive languages. -/
def CS : Set (Language T) := Set.ofPred is_CS

/-- A recursively enumerable language is generated by an unrestricted grammar. -/
def is_RE (L : Language T) : Prop :=
  exists g : grammar T, grammar_language g = L

/-- The class of recursively enumerable languages. -/
def RE : Set (Language T) := Set.ofPred is_RE

/-! ### LR grammars -/

/-- A context-free grammar has rules `A -> w`. -/
structure CF_grammar (T : Type) where
  nt : Type
  initial : nt
  rules : List (nt × List (symbol T nt))

/-- One context-free rewrite step. -/
def CF_transforms (g : CF_grammar T) (w1 w2 : List (symbol T g.nt)) : Prop :=
  exists r : g.nt × List (symbol T g.nt), exists u v : List (symbol T g.nt),
    r ∈ g.rules ∧ w1 = u ++ [symbol.nonterminal r.fst] ++ v ∧ w2 = u ++ r.snd ++ v

/-- Zero or more context-free rewrite steps. -/
def CF_derives (g : CF_grammar T) :
    List (symbol T g.nt) -> List (symbol T g.nt) -> Prop :=
  Relation.ReflTransGen (CF_transforms g)

/-- A sentential form is generated from the context-free grammar's start symbol. -/
def CF_generates_str (g : CF_grammar T) (s : List (symbol T g.nt)) : Prop :=
  CF_derives g [symbol.nonterminal g.initial] s

/-- A terminal word is generated by a context-free grammar. -/
def CF_generates (g : CF_grammar T) (w : List T) : Prop :=
  CF_generates_str g (List.map symbol.terminal w)

/-- A context-free grammar's generated language. -/
def CF_language (g : CF_grammar T) : Language T := Set.ofPred (CF_generates g)

namespace CF_grammar

/-- A rightmost rewrite replaces a nonterminal followed only by terminals. -/
def RewritesRightmost {N : Type} (r : N × List (symbol T N))
    (u v : List (symbol T N)) : Prop :=
  exists (p : List (symbol T N)) (lookahead : List T),
    u = p ++ [symbol.nonterminal r.1] ++ lookahead.map symbol.terminal ∧
    v = p ++ r.2 ++ lookahead.map symbol.terminal

variable (g : CF_grammar T)

/-- A rightmost grammar step. -/
def ProducesRightmost (u v : List (symbol T g.nt)) : Prop :=
  exists r, r ∈ g.rules ∧ RewritesRightmost r u v

/-- Zero or more rightmost grammar steps. -/
abbrev DerivesRightmost : List (symbol T g.nt) -> List (symbol T g.nt) -> Prop :=
  Relation.ReflTransGen g.ProducesRightmost

/-- The first `k` terminals of LR lookahead. -/
def lrLookahead (k : Nat) (w : List T) : List T := w.take k

/-- Embed a symbol into a grammar with a fresh optional start symbol. -/
def augmentSymbol {N : Type} : symbol T N -> symbol T (Option N)
  | symbol.terminal t => symbol.terminal t
  | symbol.nonterminal A => symbol.nonterminal (some A)

/-- Embed a sentential form into the fresh-start grammar. -/
def augmentString {N : Type} (w : List (symbol T N)) : List (symbol T (Option N)) :=
  w.map augmentSymbol

/-- Embed an original production into the fresh-start grammar. -/
def augmentRule {N : Type} (r : N × List (symbol T N)) :
    Option N × List (symbol T (Option N)) := (some r.1, augmentString r.2)

/-- The new start production `S' -> S`. -/
def augmentStartRule : Option g.nt × List (symbol T (Option g.nt)) :=
  (none, [symbol.nonterminal (some g.initial)])

/-- Fresh-start augmentation of a context-free grammar. -/
def augment : CF_grammar T where
  nt := Option g.nt
  initial := none
  rules := augmentStartRule g :: g.rules.map augmentRule

/-- Knuth's semantic LR(k) handle-uniqueness condition before augmentation. -/
def CoreIsLRk (k : Nat) : Prop :=
  forall (r1 r2 : g.nt × List (symbol T g.nt)), r1 ∈ g.rules -> r2 ∈ g.rules ->
    forall (p1 p2 : List (symbol T g.nt)) (s1 s2 y : List T),
      g.DerivesRightmost [symbol.nonterminal g.initial]
          (p1 ++ [symbol.nonterminal r1.1] ++ s1.map symbol.terminal) ->
      g.DerivesRightmost [symbol.nonterminal g.initial]
          (p2 ++ [symbol.nonterminal r2.1] ++ s2.map symbol.terminal) ->
      p2 ++ r2.2 ++ s2.map symbol.terminal = p1 ++ r1.2 ++ y.map symbol.terminal ->
      lrLookahead k s1 = lrLookahead k y -> p1 = p2 ∧ r1 = r2

/-- An LR(k) grammar satisfies handle uniqueness after fresh-start augmentation. -/
def IsLRk (k : Nat) : Prop := g.augment.CoreIsLRk k

end CF_grammar

/-- A language is LR(k) if generated by an LR(k) context-free grammar. -/
def is_LRk (k : Nat) (L : Language T) : Prop :=
  exists g : CF_grammar T, g.IsLRk k ∧ CF_language g = L

/-- The LR(k) language class. -/
def LRk (k : Nat) : Set (Language T) := Set.ofPred (is_LRk k)

/-- A language is LR if it is LR(k) for some finite `k`. -/
def is_LR (L : Language T) : Prop := exists k : Nat, is_LRk k L

/-- The LR language class. -/
def LR : Set (Language T) := Set.ofPred is_LR

/-! ### Indexed grammars -/

/-- An indexed right-hand symbol is a terminal or a nonterminal with an optional pushed flag. -/
inductive IRhsSymbol (T : Type) (N : Type) (F : Type) where
  | terminal : T -> IRhsSymbol T N F
  | nonterminal : N -> Option F -> IRhsSymbol T N F
deriving DecidableEq

/-- An indexed rule may pop one flag and push flags on right-hand nonterminals. -/
structure IRule (T : Type) (N : Type) (F : Type) where
  lhs : N
  consume : Option F
  rhs : List (IRhsSymbol T N F)

/-- An indexed grammar has nonterminals, flags, a start symbol, and finitely many rules. -/
structure IndexedGrammar (T : Type) where
  nt : Type
  flag : Type
  initial : nt
  rules : List (IRule T nt flag)

namespace IndexedGrammar

/-- A sentential symbol is a terminal or a nonterminal carrying its flag stack. -/
inductive ISym (g : IndexedGrammar T) where
  | terminal : T -> ISym g
  | indexed : g.nt -> List g.flag -> ISym g

/-- Expand a rule right-hand side while distributing and optionally extending its stack. -/
def expandRhs (g : IndexedGrammar T) (rhs : List (IRhsSymbol T g.nt g.flag))
    (sigma : List g.flag) : List (ISym g) :=
  rhs.map fun s => match s with
    | IRhsSymbol.terminal t => ISym.terminal t
    | IRhsSymbol.nonterminal n none => ISym.indexed n sigma
    | IRhsSymbol.nonterminal n (some f) => ISym.indexed n (f :: sigma)

/-- One indexed-grammar step, consuming and distributing a nonterminal's stack. -/
def Transforms (g : IndexedGrammar T) (w1 w2 : List (ISym g)) : Prop :=
  exists (r : IRule T g.nt g.flag) (u v : List (ISym g)) (sigma : List g.flag),
    r ∈ g.rules ∧
    (match r.consume with
      | none => w1 = u ++ [ISym.indexed r.lhs sigma] ++ v
      | some f => w1 = u ++ [ISym.indexed r.lhs (f :: sigma)] ++ v) ∧
    w2 = u ++ expandRhs g r.rhs sigma ++ v

/-- Zero or more indexed-grammar steps. -/
def Derives (g : IndexedGrammar T) : List (ISym g) -> List (ISym g) -> Prop :=
  Relation.ReflTransGen (Transforms g)

/-- Generation starts with the initial nonterminal carrying an empty stack. -/
def Generates (g : IndexedGrammar T) (w : List T) : Prop :=
  Derives g [ISym.indexed g.initial []] (w.map ISym.terminal)

/-- The language generated by an indexed grammar. -/
def Language (g : IndexedGrammar T) : _root_.Language T := Set.ofPred (Generates g)

end IndexedGrammar

/-- A language is indexed if it is generated by an indexed grammar. -/
def is_Indexed (L : Language T) : Prop :=
  exists g : IndexedGrammar T, g.Language = L

/-- The indexed language class. -/
def Indexed : Set (Language T) := Set.ofPred is_Indexed

/-- A recursive language has an always-halting Mathlib TM0 decider with Boolean accepting states. -/
def is_Recursive {T : Type} (L : Language T) : Prop :=
  exists (Gamma : Type) (_ : Fintype Gamma)
    (Lambda : Type) (_ : Inhabited Lambda) (_ : Fintype Lambda)
    (M : TM0.Machine (Option (T ⊕ Gamma)) Lambda) (accept : Lambda -> Bool),
    (forall w : List T,
      (StateTransition.eval (TM0.step M)
        (TM0.init (w.map fun t => some (Sum.inl t)))).Dom) ∧
    (forall w : List T,
      forall h : (StateTransition.eval (TM0.step M)
        (TM0.init (w.map fun t => some (Sum.inl t)))).Dom,
      w ∈ L ↔ accept ((StateTransition.eval (TM0.step M)
        (TM0.init (w.map fun t => some (Sum.inl t)))).get h).q = true)

/-- The recursive (decidable-language) class. -/
def Recursive : Set (Language T) := Set.ofPred is_Recursive

/-! ## Strict extended Chomsky hierarchy -/

namespace ChomskyHierarchy

/-- Over every finite alphabet with at least 2 elements, regular languages are
strictly contained in linear languages. -/
theorem RG_strict_subclass_Linear_of_card {T : Type} [Fintype T]
    (hT : 2 ≤ Fintype.card T) :
    (RG : Set (Language T)) ⊂ Linear := by sorry

/-- Over every finite alphabet with at least 4 elements, linear languages are
strictly contained in context-free languages. -/
theorem Linear_strict_subclass_CF_of_card {T : Type} [Fintype T]
    (hT : 4 ≤ Fintype.card T) :
    (Linear : Set (Language T)) ⊂ CF := by sorry

/-- Over every finite alphabet with at least 2 elements, regular languages are
strictly contained in LR languages. -/
theorem RG_strict_subclass_LR_of_card {T : Type} [Fintype T]
    (hT : 2 ≤ Fintype.card T) :
    (RG : Set (Language T)) ⊂ LR := by sorry

/-- Over every finite alphabet with at least 3 elements, LR languages are a
strict subclass of context-free languages. -/
theorem LR_strict_subclass_CF_of_card {T : Type} [Fintype T]
    (hT : 3 ≤ Fintype.card T) :
    (LR : Set (Language T)) ⊂ CF := by sorry

/-- Over every finite alphabet with at least 3 elements, context-free languages are
strictly contained in indexed languages. -/
theorem CF_strict_subclass_Indexed {T : Type} [Fintype T]
    (hT : 3 ≤ Fintype.card T) :
    (CF : Set (Language T)) ⊂ Indexed := by sorry

/-- Over every finite alphabet with at least 2 elements, indexed languages are
strictly contained in context-sensitive languages. -/
theorem Indexed_strict_subclass_CS {T : Type} [Fintype T]
    (hT : 2 ≤ Fintype.card T) :
    (Indexed : Set (Language T)) ⊂ CS := by sorry

/-- Over every finite alphabet with at least 1 element, context-sensitive
languages are strictly contained in recursive languages. -/
theorem CS_strict_subclass_Recursive_of_card {T : Type} [Fintype T]
    (hT : 1 ≤ Fintype.card T) :
    (CS : Set (Language T)) ⊂ Recursive := by sorry

/-- Over every finite alphabet with at least 1 element, recursive languages are
strictly contained in recursively enumerable languages. -/
theorem Recursive_strict_subclass_RE_of_card {T : Type} [Fintype T]
    (hT : 1 ≤ Fintype.card T) :
    (Recursive : Set (Language T)) ⊂ RE := by sorry

end ChomskyHierarchy
