module

public import Langlib.Classes.ContextSensitive.Decidability.Membership
public import Langlib.Automata.Turing.Equivalence.GrammarToTM.MembershipComputability
public import Langlib.Utilities.PrimrecHelpers
public import Mathlib.Computability.Partrec
@[expose]
public section

/-! # Computability of the closed-complement certificate checker

This file proves that `grammarClosedComplementCert` (defined in the `Membership` file),
which checks whether a finite list of sentential forms is a closed certificate witnessing
that a word is *not* generated by a grammar, is computable in its word and certificate
arguments. This is the co-RE half needed for genuine computability of membership.
-/

open List

variable {T : Type} [DecidableEq T]

/-! ## List membership is primrec via `any` -/

/-- For lists over a type with decidable equality and a `Primcodable` structure, the
membership test `decide (x ∈ l)` is primitive recursive in both arguments. -/
public theorem primrec₂_list_mem {α : Type} [DecidableEq α] [Primcodable α] :
    Primrec₂ (fun (x : α) (l : List α) => decide (x ∈ l)) := by
  have hany : Primrec (fun (p : α × List α) => (p.2).any (fun y => p.1 == y)) := by
    apply primrec_list_any (f := fun p : α × List α => p.2)
      (p := fun (p : α × List α) (y : α) => p.1 == y)
    · exact Primrec.snd
    · exact Primrec.beq.comp (Primrec.fst.comp Primrec.fst) Primrec.snd
  have heq : ∀ (p : α × List α),
      (p.2).any (fun y => p.1 == y) = decide (p.1 ∈ p.2) := by
    rintro ⟨x, l⟩
    induction l with
    | nil => simp
    | cons a l ih =>
      rw [List.any_cons, ih]
      rcases eq_or_ne x a with h | h
      · subst h; simp
      · have hba : (x == a) = false := by simpa [beq_iff_eq] using h
        simp [hba, List.mem_cons, h]
  apply Primrec₂.mk
  exact (hany.of_eq heq)

/-! ## `grammarStepSuccessors` is primrec -/

variable [Primcodable T]

/-- `grammarStepSuccessors` (for a fixed rule list) is primitive recursive in its
`bound` and `sf` arguments. -/
public theorem primrec_grammarStepSuccessors {N : Type} [DecidableEq N] [Primcodable N]
    (rules : List (grule T N)) :
    Primrec (fun (p : ℕ × List (symbol T N)) =>
      grammarStepSuccessors rules p.1 p.2) := by
  refine (Primrec.list_flatMap
    (f := fun (_ : ℕ × List (symbol T N)) => List.range rules.length)
    (g := fun (p : ℕ × List (symbol T N)) (ri : ℕ) =>
      (List.range (p.1 + 1)).filterMap fun pos =>
        match rules[ri]? with
        | none => none
        | some r =>
            match applyRuleAt r p.2 pos with
            | none => none
            | some sf' => if sf'.length ≤ p.1 then some sf' else none)
    ?_ ?_).of_eq (fun p => rfl)
  · exact Primrec.const _
  · refine (Primrec.listFilterMap
      (f := fun (q : (ℕ × List (symbol T N)) × ℕ) => List.range (q.1.1 + 1))
      (g := fun (q : (ℕ × List (symbol T N)) × ℕ) (pos : ℕ) =>
        match rules[q.2]? with
        | none => none
        | some r =>
            match applyRuleAt r q.1.2 pos with
            | none => none
            | some sf' => if sf'.length ≤ q.1.1 then some sf' else none)
      ?_ ?_).of_eq (fun q => rfl)
    · exact Primrec.list_range.comp
        (Primrec.nat_add.comp (Primrec.fst.comp Primrec.fst)
          (Primrec.const 1))
    · have key : Primrec (fun (r : ((ℕ × List (symbol T N)) × ℕ) × ℕ) =>
          ((rules[r.1.2]?).bind fun rl =>
            (applyRuleAt rl r.1.1.2 r.2).bind fun sf' =>
              if sf'.length ≤ r.1.1.1 then some sf' else none)) := by
        apply Primrec.option_bind
        · exact (Primrec.list_getElem?.comp (Primrec.const rules)
            (Primrec.snd.comp Primrec.fst))
        · apply Primrec.option_bind
          · have happ := primrec_applyRuleAt (T := T) (N := N)
            exact happ.comp
              (Primrec.pair Primrec.snd
                (Primrec.pair
                  (Primrec.snd.comp (Primrec.fst.comp (Primrec.fst.comp Primrec.fst)))
                  (Primrec.snd.comp Primrec.fst)))
          · apply Primrec.ite
            · exact Primrec.nat_le.comp (Primrec.list_length.comp Primrec.snd)
                (Primrec.fst.comp (Primrec.fst.comp
                  (Primrec.fst.comp (Primrec.fst.comp Primrec.fst))))
            · exact Primrec.option_some.comp Primrec.snd
            · exact Primrec.const none
      apply Primrec₂.mk
      refine key.of_eq ?_
      rintro ⟨⟨⟨bound, sf⟩, ri⟩, pos⟩
      rcases hr : rules[ri]? with _ | r
      · simp
      · rcases ha : applyRuleAt r sf pos with _ | sf'
        · simp [ha]
        · simp [ha]

/-! ## The certificate is computable -/

/-- The closed-complement certificate is computable in the word and certificate. -/
public theorem grammarClosedComplementCert_computable₂
    {T : Type} [DecidableEq T] [Primcodable T]
    (gr : grammar T) [DecidableEq gr.nt] [Primcodable gr.nt] :
    Computable₂ (fun (w : List T) (S : List (List (symbol T gr.nt))) =>
      grammarClosedComplementCert gr (w.length + 1) (w.map symbol.terminal) S) := by
  apply Computable₂.mk
  -- membership tests
  have hmem : Primrec₂ (fun (x : List (symbol T gr.nt))
      (l : List (List (symbol T gr.nt))) => decide (x ∈ l)) :=
    primrec₂_list_mem.of_eq (fun x l => by congr 1)
  -- bound = w.length + 1 as a function of the pair
  have hbound : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
      p.1.length + 1) :=
    Primrec.nat_add.comp (Primrec.list_length.comp Primrec.fst) (Primrec.const 1)
  -- conjunct 1
  have h1 : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
      decide ([symbol.nonterminal gr.initial] ∈ p.2)) :=
    hmem.comp (Primrec.const _) Primrec.snd
  -- conjunct 2
  have hmapterm : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
      p.1.map (symbol.terminal (N := gr.nt))) :=
    Primrec.list_map Primrec.fst
      ((primrec_symbol_terminal (T := T) (N := gr.nt)).comp Primrec.snd)
  have h2 : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
      ! decide (p.1.map (symbol.terminal (N := gr.nt)) ∈ p.2)) :=
    Primrec.not.comp (hmem.comp hmapterm Primrec.snd)
  -- inner `any` over successors, as a Primrec in (p, sf)
  have hsucc : Primrec (fun (q : (List T × List (List (symbol T gr.nt)))
      × List (symbol T gr.nt)) =>
      grammarStepSuccessors gr.rules (q.1.1.length + 1) q.2) := by
    have := primrec_grammarStepSuccessors (T := T) (N := gr.nt) gr.rules
    exact this.comp
      (Primrec.pair (hbound.comp Primrec.fst) Primrec.snd)
  -- any over successors of (! decide (sf' ∈ S))
  have hsuccany : Primrec (fun (q : (List T × List (List (symbol T gr.nt)))
      × List (symbol T gr.nt)) =>
      (grammarStepSuccessors gr.rules (q.1.1.length + 1) q.2).any
        (fun sf' => ! decide (sf' ∈ q.1.2))) := by
    apply primrec_list_any
      (f := fun (q : (List T × List (List (symbol T gr.nt)))
        × List (symbol T gr.nt)) =>
        grammarStepSuccessors gr.rules (q.1.1.length + 1) q.2)
      (p := fun (q : (List T × List (List (symbol T gr.nt)))
        × List (symbol T gr.nt)) (sf' : List (symbol T gr.nt)) =>
        ! decide (sf' ∈ q.1.2))
    · exact hsucc
    · exact Primrec.not.comp (hmem.comp Primrec.snd
        (Primrec.snd.comp (Primrec.fst.comp Primrec.fst)))
  -- per-sf bool, expressed via `any`/`not`
  have hperany : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
      p.2.any (fun sf =>
        ! (decide (sf.length ≤ p.1.length + 1) &&
            ! (grammarStepSuccessors gr.rules (p.1.length + 1) sf).any
                (fun sf' => ! decide (sf' ∈ p.2))))) := by
    apply primrec_list_any
      (f := fun (p : List T × List (List (symbol T gr.nt))) => p.2)
      (p := fun (p : List T × List (List (symbol T gr.nt)))
        (sf : List (symbol T gr.nt)) =>
        ! (decide (sf.length ≤ p.1.length + 1) &&
            ! (grammarStepSuccessors gr.rules (p.1.length + 1) sf).any
                (fun sf' => ! decide (sf' ∈ p.2))))
    · exact Primrec.snd
    · apply Primrec.not.comp
      apply Primrec.and.comp
      · exact (Primrec.nat_le.comp
          ((Primrec.list_length (α := symbol T gr.nt)).comp Primrec.snd)
          (hbound.comp Primrec.fst)).decide
      · exact Primrec.not.comp hsuccany
  -- assemble
  have hcert : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
      grammarClosedComplementCert gr (p.1.length + 1)
        (p.1.map symbol.terminal) p.2) := by
    have hcombine : Primrec (fun (p : List T × List (List (symbol T gr.nt))) =>
        ((decide ([symbol.nonterminal gr.initial] ∈ p.2)
          && ! decide (p.1.map (symbol.terminal (N := gr.nt)) ∈ p.2))
        && ! p.2.any (fun sf =>
            ! (decide (sf.length ≤ p.1.length + 1) &&
                ! (grammarStepSuccessors gr.rules (p.1.length + 1) sf).any
                    (fun sf' => ! decide (sf' ∈ p.2)))))) := by
      apply Primrec.and.comp
      · exact Primrec.and.comp h1 h2
      · exact Primrec.not.comp hperany
    refine hcombine.of_eq ?_
    intro p
    obtain ⟨w, S⟩ := p
    unfold grammarClosedComplementCert
    simp only [List.all_eq_not_any_not, Bool.and_assoc]
  exact hcert.to_comp
