module

public import Langlib.Grammars.Indexed.NormalForm.AhoCompleteness

@[expose]
public section

/-!
# Reduced data-carrying normal-form parses

The parse-directed Aho scheduler does not need to handle gratuitous cycles in a chosen
certificate.  This file makes that reduction precise without assuming decidability of grammar
derivability: among all `NFParse` values with fixed indices, choose one with least constructor
count.

Constructor-count minimality is inherited by every syntactic child.  In particular a proper
unary descendant cannot have exactly the same nonterminal, stack, and yield as its ancestor;
otherwise the descendant itself would be a strictly smaller certificate with the ancestor's
type.

This is deliberately only a cycle-elimination statement.  It does not claim that the number of
unary constructors, or the height of the concrete flag stack, is linear in the terminal yield.
-/

variable {T : Type}

namespace IndexedGrammar
namespace NFParse

/-- A concrete parse is reduced when it has the least constructor count among all parses with
the same grammar, root nonterminal, root stack, and terminal yield. -/
public def IsNodeMinimal
    {g : IndexedGrammar T} {A : g.nt} {stack : List g.flag} {w : List T}
    (parse : NFParse g A stack w) : Prop :=
  ∀ candidate : NFParse g A stack w, parse.nodeCount ≤ candidate.nodeCount

/-- Every inhabited concrete parse type has a constructor-count-minimal representative.  The
argument uses well-foundedness of `Nat`, not decidability of grammar derivability. -/
public theorem exists_nodeMinimal
    {g : IndexedGrammar T} {A : g.nt} {stack : List g.flag} {w : List T}
    (parse : NFParse g A stack w) :
    ∃ reduced : NFParse g A stack w, reduced.IsNodeMinimal := by
  classical
  let P : ℕ → Prop := fun n =>
    ∃ candidate : NFParse g A stack w, candidate.nodeCount = n
  have hP : ∃ n, P n := ⟨parse.nodeCount, parse, rfl⟩
  let n := Nat.find hP
  obtain ⟨reduced, hreduced⟩ := Nat.find_spec hP
  refine ⟨reduced, ?_⟩
  intro candidate
  rw [hreduced]
  exact Nat.find_min' hP ⟨candidate, rfl⟩

/-- Proposition-valued existence form, convenient when the original parse is not needed. -/
public theorem nonempty_nodeMinimal
    {g : IndexedGrammar T} {A : g.nt} {stack : List g.flag} {w : List T}
    (h : Nonempty (NFParse g A stack w)) :
    ∃ reduced : NFParse g A stack w, reduced.IsNodeMinimal := by
  rcases h with ⟨parse⟩
  exact parse.exists_nodeMinimal

/-- Every word generated by a normal-form grammar has a reduced concrete root parse. -/
public theorem exists_nodeMinimal_initial_of_generates
    {g : IndexedGrammar T} [DecidableEq g.nt] (hNF : g.IsNormalForm)
    {w : List T} (hgen : g.Generates w) :
    ∃ reduced : NFParse g g.initial [] w, reduced.IsNodeMinimal := by
  exact nonempty_nodeMinimal ((NFParse.nonempty_initial_iff_generates hNF).2 hgen)

/-- The left child of a reduced binary parse is reduced. -/
public theorem IsNodeMinimal.binary_left
    {g : IndexedGrammar T} {A B C : g.nt} {stack : List g.flag}
    {u v : List T} {r : IRule T g.nt g.flag}
    {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
    {hrhs : r.rhs =
      [IRhsSymbol.nonterminal B none, IRhsSymbol.nonterminal C none]}
    {left : NFParse g B stack u} {right : NFParse g C stack v}
    (hmin : (NFParse.binary hr hlhs hc hrhs left right).IsNodeMinimal) :
    left.IsNodeMinimal := by
  intro candidate
  have h := hmin (NFParse.binary hr hlhs hc hrhs candidate right)
  simp only [NFParse.nodeCount] at h
  omega

/-- The right child of a reduced binary parse is reduced. -/
public theorem IsNodeMinimal.binary_right
    {g : IndexedGrammar T} {A B C : g.nt} {stack : List g.flag}
    {u v : List T} {r : IRule T g.nt g.flag}
    {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
    {hrhs : r.rhs =
      [IRhsSymbol.nonterminal B none, IRhsSymbol.nonterminal C none]}
    {left : NFParse g B stack u} {right : NFParse g C stack v}
    (hmin : (NFParse.binary hr hlhs hc hrhs left right).IsNodeMinimal) :
    right.IsNodeMinimal := by
  intro candidate
  have h := hmin (NFParse.binary hr hlhs hc hrhs left candidate)
  simp only [NFParse.nodeCount] at h
  omega

/-- The child of a reduced pop parse is reduced. -/
public theorem IsNodeMinimal.pop_rest
    {g : IndexedGrammar T} {A B : g.nt} {f : g.flag} {stack : List g.flag}
    {w : List T} {r : IRule T g.nt g.flag}
    {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = some f}
    {hrhs : r.rhs = [IRhsSymbol.nonterminal B none]}
    {rest : NFParse g B stack w}
    (hmin : (NFParse.pop hr hlhs hc hrhs rest).IsNodeMinimal) :
    rest.IsNodeMinimal := by
  intro candidate
  have h := hmin (NFParse.pop hr hlhs hc hrhs candidate)
  simp only [NFParse.nodeCount] at h
  omega

/-- The child of a reduced push parse is reduced. -/
public theorem IsNodeMinimal.push_rest
    {g : IndexedGrammar T} {A B : g.nt} {f : g.flag} {stack : List g.flag}
    {w : List T} {r : IRule T g.nt g.flag}
    {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
    {hrhs : r.rhs = [IRhsSymbol.nonterminal B (some f)]}
    {rest : NFParse g B (f :: stack) w}
    (hmin : (NFParse.push hr hlhs hc hrhs rest).IsNodeMinimal) :
    rest.IsNodeMinimal := by
  intro candidate
  have h := hmin (NFParse.push hr hlhs hc hrhs candidate)
  simp only [NFParse.nodeCount] at h
  omega

/-- Every node in a concrete parse is constructor-count minimal at its own dependent type. -/
public inductive AllNodeMinimal (g : IndexedGrammar T) :
    {A : g.nt} → {stack : List g.flag} → {w : List T} →
      (parse : NFParse g A stack w) → Prop where
  | binary
      {A B C : g.nt} {stack : List g.flag} {u v : List T}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
      {hrhs : r.rhs =
        [IRhsSymbol.nonterminal B none, IRhsSymbol.nonterminal C none]}
      {left : NFParse g B stack u} {right : NFParse g C stack v}
      (hroot : (NFParse.binary hr hlhs hc hrhs left right).IsNodeMinimal)
      (hleft : AllNodeMinimal g left) (hright : AllNodeMinimal g right) :
      AllNodeMinimal g (NFParse.binary hr hlhs hc hrhs left right)
  | pop
      {A B : g.nt} {f : g.flag} {stack : List g.flag} {w : List T}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = some f}
      {hrhs : r.rhs = [IRhsSymbol.nonterminal B none]}
      {rest : NFParse g B stack w}
      (hroot : (NFParse.pop hr hlhs hc hrhs rest).IsNodeMinimal)
      (hrest : AllNodeMinimal g rest) :
      AllNodeMinimal g (NFParse.pop hr hlhs hc hrhs rest)
  | push
      {A B : g.nt} {f : g.flag} {stack : List g.flag} {w : List T}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
      {hrhs : r.rhs = [IRhsSymbol.nonterminal B (some f)]}
      {rest : NFParse g B (f :: stack) w}
      (hroot : (NFParse.push hr hlhs hc hrhs rest).IsNodeMinimal)
      (hrest : AllNodeMinimal g rest) :
      AllNodeMinimal g (NFParse.push hr hlhs hc hrhs rest)
  | terminal
      {A : g.nt} {stack : List g.flag} {a : T}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
      {hrhs : r.rhs = [IRhsSymbol.terminal a]}
      (hroot : (NFParse.terminal (g := g) (σ := stack) hr hlhs hc hrhs).IsNodeMinimal) :
      AllNodeMinimal g (NFParse.terminal (g := g) (σ := stack) hr hlhs hc hrhs)

/-- Root minimality propagates through the whole concrete parse. -/
public theorem IsNodeMinimal.all
    {g : IndexedGrammar T} {A : g.nt} {stack : List g.flag} {w : List T}
    {parse : NFParse g A stack w} (hmin : parse.IsNodeMinimal) :
    parse.AllNodeMinimal := by
  induction parse with
  | binary hr hlhs hc hrhs left right ihleft ihright =>
      exact .binary hmin (ihleft hmin.binary_left) (ihright hmin.binary_right)
  | pop hr hlhs hc hrhs rest ih =>
      exact .pop hmin (ih hmin.pop_rest)
  | push hr hlhs hc hrhs rest ih =>
      exact .push hmin (ih hmin.push_rest)
  | terminal =>
      exact .terminal hmin

/-- A proper descendant reached using only unary (`pop` or `push`) parse constructors.  Binary
forks are intentionally excluded: along such a path the terminal yield stays definitionally
the same. -/
public inductive StrictUnaryDescendant (g : IndexedGrammar T) {w : List T} :
    {A : g.nt} → {stack : List g.flag} → NFParse g A stack w →
    {B : g.nt} → {childStack : List g.flag} → NFParse g B childStack w → Prop where
  | popHere
      {A B : g.nt} {f : g.flag} {stack : List g.flag}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = some f}
      {hrhs : r.rhs = [IRhsSymbol.nonterminal B none]}
      (rest : NFParse g B stack w) :
      StrictUnaryDescendant g (NFParse.pop hr hlhs hc hrhs rest) rest
  | popNext
      {A B C : g.nt} {f : g.flag} {stack childStack : List g.flag}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = some f}
      {hrhs : r.rhs = [IRhsSymbol.nonterminal B none]}
      {rest : NFParse g B stack w} {descendant : NFParse g C childStack w}
      (hdesc : StrictUnaryDescendant g rest descendant) :
      StrictUnaryDescendant g (NFParse.pop hr hlhs hc hrhs rest) descendant
  | pushHere
      {A B : g.nt} {f : g.flag} {stack : List g.flag}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
      {hrhs : r.rhs = [IRhsSymbol.nonterminal B (some f)]}
      (rest : NFParse g B (f :: stack) w) :
      StrictUnaryDescendant g (NFParse.push hr hlhs hc hrhs rest) rest
  | pushNext
      {A B C : g.nt} {f : g.flag} {stack childStack : List g.flag}
      {r : IRule T g.nt g.flag}
      {hr : r ∈ g.rules} {hlhs : r.lhs = A} {hc : r.consume = none}
      {hrhs : r.rhs = [IRhsSymbol.nonterminal B (some f)]}
      {rest : NFParse g B (f :: stack) w}
      {descendant : NFParse g C childStack w}
      (hdesc : StrictUnaryDescendant g rest descendant) :
      StrictUnaryDescendant g (NFParse.push hr hlhs hc hrhs rest) descendant

namespace StrictUnaryDescendant

/-- A proper unary descendant has strictly fewer parse constructors. -/
public theorem nodeCount_lt
    {g : IndexedGrammar T} {w : List T}
    {A B : g.nt} {stack childStack : List g.flag}
    {parse : NFParse g A stack w} {descendant : NFParse g B childStack w}
    (hdesc : StrictUnaryDescendant g parse descendant) :
    descendant.nodeCount < parse.nodeCount := by
  induction hdesc with
  | popHere => simp [NFParse.nodeCount]
  | popNext _ ih =>
      simp only [NFParse.nodeCount]
      omega
  | pushHere => simp [NFParse.nodeCount]
  | pushNext _ ih =>
      simp only [NFParse.nodeCount]
      omega

/-- Reducedness is inherited by every unary descendant, not just the immediate child. -/
public theorem isNodeMinimal
    {g : IndexedGrammar T} {w : List T}
    {A B : g.nt} {stack childStack : List g.flag}
    {parse : NFParse g A stack w} {descendant : NFParse g B childStack w}
    (hdesc : StrictUnaryDescendant g parse descendant)
    (hmin : parse.IsNodeMinimal) :
    descendant.IsNodeMinimal := by
  induction hdesc with
  | popHere => exact hmin.pop_rest
  | popNext hnext ih => exact ih hmin.pop_rest
  | pushHere => exact hmin.push_rest
  | pushNext hnext ih => exact ih hmin.push_rest

end StrictUnaryDescendant

/-- A reduced parse has no proper unary descendant with exactly the same dependent indices.
This is the formal cycle-elimination property: the root nonterminal, complete concrete stack,
and terminal yield cannot all repeat along a unary spine. -/
public theorem IsNodeMinimal.no_strictUnaryDescendant_same
    {g : IndexedGrammar T} {A : g.nt} {stack : List g.flag} {w : List T}
    {parse descendant : NFParse g A stack w}
    (hmin : parse.IsNodeMinimal) :
    ¬ StrictUnaryDescendant g parse descendant := by
  intro hdesc
  have hlt := hdesc.nodeCount_lt
  have hle := hmin descendant
  omega

/-- Generated-word form of the reduction, bundled with the exact unary-cycle exclusion used by
a scheduler restricted to reduced root certificates. -/
public theorem exists_reduced_initial_without_unary_cycle_of_generates
    {g : IndexedGrammar T} [DecidableEq g.nt] (hNF : g.IsNormalForm)
    {w : List T} (hgen : g.Generates w) :
    ∃ reduced : NFParse g g.initial [] w,
      reduced.IsNodeMinimal ∧
      ∀ descendant : NFParse g g.initial [] w,
        ¬ StrictUnaryDescendant g reduced descendant := by
  obtain ⟨reduced, hminimal⟩ :=
    exists_nodeMinimal_initial_of_generates hNF hgen
  exact ⟨reduced, hminimal, fun descendant =>
    hminimal.no_strictUnaryDescendant_same⟩

/-- A generated word has a reduced, cycle-free root parse whose productive-node budget is
linear in the terminal yield.  The linear quantity here is exactly the one used by Aho's owner
accounting; the theorem intentionally makes no linear claim about total unary constructor
count. -/
public theorem exists_reduced_initial_with_linear_productive_bound_of_generates
    {g : IndexedGrammar T} [DecidableEq g.nt] (hNF : g.IsNormalForm)
    {w : List T} (hgen : g.Generates w) :
    w ≠ [] ∧
    ∃ reduced : NFParse g g.initial [] w,
      reduced.IsNodeMinimal ∧
      reduced.productiveCount ≤ 2 * w.length ∧
      ∀ descendant : NFParse g g.initial [] w,
        ¬ StrictUnaryDescendant g reduced descendant := by
  have hwne : w ≠ [] := by
    intro hw
    subst w
    exact g.not_generates_nil_of_noEpsilon
      (g.noEpsilon_of_isNormalForm hNF) hgen
  obtain ⟨reduced, hminimal⟩ :=
    exists_nodeMinimal_initial_of_generates hNF hgen
  exact ⟨hwne, reduced, hminimal, reduced.productiveCount_le_twice_yield_length,
    fun descendant => hminimal.no_strictUnaryDescendant_same⟩

end NFParse
end IndexedGrammar
