module

public import Langlib.Classes.Regular.Definition
public import Langlib.Grammars.LR.Definition
import Langlib.Automata.FiniteState.Equivalence.Regular
import Langlib.Classes.Regular.Inclusion.ContextFree

/-!
# Regular languages are LR(1)

Every regular language is generated by an LR(1) grammar, hence is an LR language.

The construction stays entirely inside this development's own grammars.  In this
repository a regular language is, by definition, one generated by a right-regular
grammar (`is_RG`); the repository proves these coincide with the DFA languages
(`is_RG_iff_isRegular`, built from `RG_of_DFA` / `RG_language = M.accepts`).  Given a
regular language we take the DFA `M` it equals and use the *deterministic* right-regular
grammar `RG_of_DFA M`, whose generated language (`RG_of_DFA_language`) and reachable
sentential forms (`RG_of_DFA_derives_inv`) are already established.  We reinterpret that
right-regular grammar as a context-free grammar via `CF_grammar_of_RG` (the rules are
unchanged) and show its fresh-start augmentation is LR(1).

Because the DFA is deterministic, every rightmost sentential form is `w·q` — terminals
`w` followed by the single state-nonterminal reached after reading `w` — so the prefix
already built determines every ordinary handle and rule. One symbol of lookahead is
needed to distinguish an accepting reduction from shifting another input symbol. The reachable-form
content is borrowed wholesale from the right-regular development; the only new ingredient
is that a rightmost context-free step is a special case of a general one, so a rightmost
derivation of the wrapped grammar is in particular a right-regular derivation.

## Main results

- `is_LRk_one_of_is_RG` — every regular language is LR(1)
- `is_LR_of_is_RG` — every regular language is an LR language
- `RG_subclass_LR` — `RG ⊆ LR`
-/

open CF_grammar

variable {T : Type}

namespace Langlib.RegularLR

/-! ### List helpers -/

/-- A nonterminal symbol never occurs in a list of terminals. -/
private lemma nonterminal_not_mem_map_terminal {N : Type} {Y : N} {wt : List T} :
    symbol.nonterminal Y ∉ wt.map symbol.terminal := by
  simp

/-- The terminal-symbol constructor is injective on lists. -/
private lemma map_terminal_inj {N : Type} {w₁ w₂ : List T}
    (h : w₁.map (symbol.terminal (N := N)) = w₂.map symbol.terminal) : w₁ = w₂ := by
  refine List.map_injective_iff.mpr ?_ h
  intro a b hab
  simpa using hab

/-- If `l₁ ++ [N X] ++ l₂` equals a list of terminals followed by a single trailing
nonterminal `N Y`, then the trailing nonterminal is the one we singled out: `l₂` is
empty, `l₁` is exactly the terminal prefix, and `X = Y`. -/
private lemma eq_map_terminal_append_nt {N : Type} {l₁ l₂ : List (symbol T N)} {X Y : N}
    {wt : List T}
    (h : l₁ ++ [symbol.nonterminal X] ++ l₂ = wt.map symbol.terminal ++ [symbol.nonterminal Y]) :
    l₂ = [] ∧ l₁ = wt.map symbol.terminal ∧ X = Y := by
  induction wt generalizing l₁ with
  | nil =>
    simp only [List.map_nil, List.nil_append] at h
    cases l₁ with
    | nil =>
      simp only [List.nil_append, List.cons_append, List.cons.injEq,
        symbol.nonterminal.injEq] at h
      exact ⟨h.2, rfl, h.1⟩
    | cons c l₁' => simp at h
  | cons t wt' ih =>
    simp only [List.map_cons, List.cons_append] at h
    cases l₁ with
    | nil => simp at h
    | cons c l₁' =>
      simp only [List.cons_append, List.cons.injEq] at h
      obtain ⟨hc, hrest⟩ := h
      obtain ⟨h2, h3, h4⟩ := ih hrest
      exact ⟨h2, by rw [hc, h3]; simp, h4⟩

variable [Fintype T] {σ : Type} [Fintype σ] (M : DFA T σ)

/-- The LR grammar for a DFA: the right-regular grammar `RG_of_DFA M`, viewed as a
context-free grammar (same rules). -/
private noncomputable def lrGrammar : CF_grammar T := CF_grammar_of_RG (RG_of_DFA M)

private lemma lrGrammar_initial : (lrGrammar M).initial = M.start := rfl

/-- Every rule in `RG_of_DFA M` is a transition rule `q → a·(M.step q a)` or an
acceptance rule `q → ε` for an accepting `q`. -/
private lemma RG_of_DFA_rule_cases {rr : RG_rule T σ} (h : rr ∈ (RG_of_DFA M).rules) :
    (∃ q a, rr = RG_rule.cons q a (M.step q a)) ∨ (∃ q, q ∈ M.accept ∧ rr = RG_rule.epsilon q) := by
  simp only [RG_of_DFA] at h
  rw [List.mem_append] at h
  rcases h with h | h
  · rw [List.mem_map] at h
    obtain ⟨qa, _, rfl⟩ := h
    exact Or.inl ⟨qa.1, qa.2, rfl⟩
  · rw [List.mem_filterMap] at h
    obtain ⟨q, _, hq⟩ := h
    by_cases hacc : q ∈ M.accept
    · rw [if_pos hacc] at hq
      obtain rfl := Option.some.inj hq
      exact Or.inr ⟨q, hacc, rfl⟩
    · rw [if_neg hacc] at hq
      exact absurd hq (by simp)

/-- The rules of `lrGrammar M` are exactly the DFA's transition rules
`q → a·(M.step q a)` and the acceptance rules `q → ε` for accepting `q`. -/
private lemma rule_shape {rule : σ × List (symbol T σ)} (hr : rule ∈ (lrGrammar M).rules) :
    (∃ a, rule = (rule.1, [symbol.terminal a, symbol.nonterminal (M.step rule.1 a)])) ∨
      (rule.1 ∈ M.accept ∧ rule = (rule.1, [])) := by
  simp only [lrGrammar, CF_grammar_of_RG, List.mem_map] at hr
  obtain ⟨rr, hrr, rfl⟩ := hr
  rcases RG_of_DFA_rule_cases M hrr with ⟨q, a, rfl⟩ | ⟨q, hq, rfl⟩
  · exact Or.inl ⟨a, by simp [RG_rule.lhs, RG_rule.output]⟩
  · exact Or.inr ⟨by simpa [RG_rule.lhs] using hq, by simp [RG_rule.lhs, RG_rule.output]⟩

/-- A rightmost context-free step of the wrapped grammar is, in particular, a
right-regular derivation step of the underlying grammar, so a rightmost derivation is a
right-regular derivation. -/
private lemma derivesRightmost_RG_derives {u v : List (symbol T σ)}
    (h : (lrGrammar M).DerivesRightmost u v) : RG_derives (RG_of_DFA M) u v := by
  refine (RG_derives_iff_CF_derives (RG_of_DFA M) u v).mpr ?_
  refine Relation.ReflTransGen.mono ?_ h
  intro a b hab
  obtain ⟨r, hr, p, la, hu, hv⟩ := hab
  exact ⟨r, p, la.map symbol.terminal, hr, hu, hv⟩

/-- Reachable rightmost sentential forms: borrowed directly from the right-regular
characterisation `RG_of_DFA_derives_inv`. -/
private lemma formsR {q : σ} {v : List (symbol T σ)}
    (h : (lrGrammar M).DerivesRightmost [symbol.nonterminal q] v) :
    (∃ w : List T, v = w.map symbol.terminal ++ [symbol.nonterminal (M.evalFrom q w)]) ∨
      (∃ w : List T, v = w.map symbol.terminal ∧ M.evalFrom q w ∈ M.accept) :=
  RG_of_DFA_derives_inv M q v (derivesRightmost_RG_derives M h)

/-- A derived configuration carrying a marked handle `p ++ [N rule.1] ++ s` must have empty
terminal suffix, terminal prefix, and handle nonterminal equal to the reached DFA state. -/
private lemma config_extract {rule : σ × List (symbol T σ)} {p : List (symbol T σ)} {s : List T}
    (h : (lrGrammar M).DerivesRightmost [symbol.nonterminal (lrGrammar M).initial]
      (p ++ [symbol.nonterminal rule.1] ++ s.map symbol.terminal)) :
    s = [] ∧ ∃ w, p = w.map symbol.terminal ∧ rule.1 = M.evalFrom (lrGrammar M).initial w := by
  rcases formsR M h with ⟨w, hw⟩ | ⟨w, hw, _⟩
  · obtain ⟨hl₂, hp, hX⟩ := eq_map_terminal_append_nt hw
    exact ⟨by simpa using hl₂, w, hp, hX⟩
  · exfalso
    have : symbol.nonterminal rule.1 ∈ (w.map symbol.terminal) := by rw [← hw]; simp
    exact nonterminal_not_mem_map_terminal this

/-- Ordinary completed handles of the DFA grammar are unique once their complete
post-reduction sentential forms agree. -/
private theorem lrGrammar_reduce_unique
    {r₁ r₂ : σ × List (symbol T σ)}
    (hr₁ : r₁ ∈ (lrGrammar M).rules) (hr₂ : r₂ ∈ (lrGrammar M).rules)
    {p₁ p₂ : List (symbol T σ)} {s₁ s₂ : List T}
    (hd₁ : (lrGrammar M).DerivesRightmost [symbol.nonterminal (lrGrammar M).initial]
      (p₁ ++ [symbol.nonterminal r₁.1] ++ s₁.map symbol.terminal))
    (hd₂ : (lrGrammar M).DerivesRightmost [symbol.nonterminal (lrGrammar M).initial]
      (p₂ ++ [symbol.nonterminal r₂.1] ++ s₂.map symbol.terminal))
    (hcore : p₁ ++ r₁.2 = p₂ ++ r₂.2) :
    p₁ = p₂ ∧ r₁ = r₂ := by
  obtain ⟨hs₁, w₁, hp₁, hin₁⟩ := config_extract M hd₁
  obtain ⟨hs₂, w₂, hp₂, hin₂⟩ := config_extract M hd₂
  have hcore : w₁.map symbol.terminal ++ r₁.2 = w₂.map symbol.terminal ++ r₂.2 := by
    simpa [hp₁, hp₂] using hcore
  suffices h : r₁ = r₂ ∧ w₁ = w₂ by
    exact ⟨by rw [hp₁, hp₂, h.2], h.1⟩
  rcases rule_shape M hr₁ with ⟨a₁, hrule₁⟩ | ⟨hacc₁, hrule₁⟩ <;>
    rcases rule_shape M hr₂ with ⟨a₂, hrule₂⟩ | ⟨hacc₂, hrule₂⟩
  · -- shift / shift
    have ho1 : r₁.2 = [symbol.terminal a₁, symbol.nonterminal (M.step r₁.1 a₁)] :=
      congrArg Prod.snd hrule₁
    have ho2 : r₂.2 = [symbol.terminal a₂, symbol.nonterminal (M.step r₂.1 a₂)] :=
      congrArg Prod.snd hrule₂
    have hlen : w₁.length = w₂.length := by
      have := congrArg List.length hcore
      simp only [List.length_append, List.length_map, List.length_cons, List.length_nil,
        ho1, ho2] at this
      omega
    obtain ⟨hw, hsuf⟩ := List.append_inj hcore (by simp [hlen])
    have hww : w₁ = w₂ := map_terminal_inj hw
    have h1 : r₁.1 = r₂.1 := by rw [hin₁, hin₂, hww]
    exact ⟨Prod.ext_iff.mpr ⟨h1, hsuf⟩, hww⟩
  · -- shift / eps : contradiction (handle ends in a nonterminal, target is all terminals)
    exfalso
    have ho1 : r₁.2 = [symbol.terminal a₁, symbol.nonterminal (M.step r₁.1 a₁)] :=
      congrArg Prod.snd hrule₁
    have ho2 : r₂.2 = [] := congrArg Prod.snd hrule₂
    rw [ho1, ho2, List.append_nil] at hcore
    have hmem : symbol.nonterminal (M.step r₁.1 a₁) ∈ w₂.map symbol.terminal := by
      rw [← hcore]; simp
    exact nonterminal_not_mem_map_terminal hmem
  · -- eps / shift : symmetric contradiction
    exfalso
    have ho1 : r₁.2 = [] := congrArg Prod.snd hrule₁
    have ho2 : r₂.2 = [symbol.terminal a₂, symbol.nonterminal (M.step r₂.1 a₂)] :=
      congrArg Prod.snd hrule₂
    rw [ho1, ho2, List.append_nil] at hcore
    have hmem : symbol.nonterminal (M.step r₂.1 a₂) ∈ w₁.map symbol.terminal := by
      rw [hcore]; simp
    exact nonterminal_not_mem_map_terminal hmem
  · -- eps / eps
    have ho1 : r₁.2 = [] := congrArg Prod.snd hrule₁
    have ho2 : r₂.2 = [] := congrArg Prod.snd hrule₂
    rw [ho1, ho2, List.append_nil, List.append_nil] at hcore
    have hww : w₁ = w₂ := map_terminal_inj hcore
    have h1 : r₁.1 = r₂.1 := by rw [hin₁, hin₂, hww]
    exact ⟨Prod.ext_iff.mpr ⟨h1, ho1.trans ho2.symm⟩, hww⟩

private lemma lrGrammar_post_ne_initial
    {r : σ × List (symbol T σ)} (hr : r ∈ (lrGrammar M).rules)
    (w : List T) :
    w.map symbol.terminal ++ r.2 ≠
      [symbol.nonterminal (lrGrammar M).initial] := by
  intro heq
  rcases rule_shape M hr with ⟨a, hra⟩ | ⟨_, hre⟩
  · have hout : r.2 =
        [symbol.terminal a, symbol.nonterminal (M.step r.1 a)] :=
      congrArg Prod.snd hra
    have hlen := congrArg List.length heq
    simp [hout] at hlen
  · have hout : r.2 = [] := congrArg Prod.snd hre
    rw [hout, List.append_nil] at heq
    have hmem : symbol.nonterminal (lrGrammar M).initial ∈
        w.map (symbol.terminal (N := σ)) := by
      rw [heq]
      simp
    exact nonterminal_not_mem_map_terminal hmem

private lemma project_eq_map_terminal
    {p : List (symbol T (Option σ))} {w : List T}
    (h : (lrGrammar M).projectAugmentString p =
      w.map (symbol.terminal (N := σ))) :
    p = w.map (symbol.terminal (N := Option σ)) := by
  induction p generalizing w with
  | nil =>
      cases w <;> simp [CF_grammar.projectAugmentString] at h ⊢
  | cons a p ih =>
      cases a with
      | terminal t =>
          cases w with
          | nil => simp [CF_grammar.projectAugmentString] at h
          | cons u w =>
              simp only [CF_grammar.projectAugmentString, List.map_cons,
                CF_grammar.projectAugmentSymbol, List.cons.injEq] at h
              have htu : t = u := by simpa using h.1
              subst u
              simp only [List.map_cons, List.cons.injEq, true_and]
              exact ih h.2
      | nonterminal A =>
          cases A <;> cases w <;> simp [CF_grammar.projectAugmentString,
            CF_grammar.projectAugmentSymbol] at h

private lemma augment_rule_no_fresh
    {r : Option σ × List (symbol T (Option σ))}
    (hr : r ∈ (lrGrammar M).augment.rules) :
    symbol.nonterminal none ∉ r.2 := by
  rcases List.mem_cons.mp hr with hstart | hmapped
  · subst r
    simp [CF_grammar.augmentStartRule]
  · rcases List.mem_map.mp hmapped with ⟨r₀, _, rfl⟩
    intro hnone
    simp only [CF_grammar.augmentRule, CF_grammar.augmentString,
      List.mem_map] at hnone
    rcases hnone with ⟨x, _, hx⟩
    cases x <;> simp [CF_grammar.augmentSymbol] at hx

private lemma augment_fresh_invariant
    {v : List (symbol T (Option σ))}
    (h : (lrGrammar M).augment.DerivesRightmost
      [symbol.nonterminal (lrGrammar M).augment.initial] v) :
    v = [symbol.nonterminal none] ∨ symbol.nonterminal none ∉ v := by
  induction h with
  | refl => exact Or.inl rfl
  | tail _ hstep ih =>
      right
      rcases hstep with ⟨r, hr, p, s, hu, hv⟩
      have hrhs := augment_rule_no_fresh M hr
      rcases ih with hinitial | hnofresh
      · rw [hinitial] at hu
        have hlen := congrArg List.length hu
        simp only [List.length_cons, List.length_nil, List.length_append,
          List.length_map] at hlen
        have hp : p = [] := List.eq_nil_of_length_eq_zero (by omega)
        have hs : s = [] := List.eq_nil_of_length_eq_zero (by omega)
        subst p
        subst s
        simpa [hv] using hrhs
      · have hp : symbol.nonterminal none ∉ p := by
          intro hmem
          apply hnofresh
          rw [hu]
          simp [hmem]
        rw [hv]
        simp [hp, hrhs]

/-- Every reachable augmented prehandle either is the untouched fresh start or
is an ordinary DFA prehandle with a terminal prefix and empty terminal suffix. -/
private lemma augment_config_extract
    {rule : Option σ × List (symbol T (Option σ))}
    {p : List (symbol T (Option σ))} {s : List T}
    (h : (lrGrammar M).augment.DerivesRightmost
      [symbol.nonterminal (lrGrammar M).augment.initial]
      (p ++ [symbol.nonterminal rule.1] ++ s.map symbol.terminal)) :
    s = [] ∧
      ((rule.1 = none ∧ p = []) ∨
        ∃ q w, rule.1 = some q ∧
          p = w.map (symbol.terminal (N := Option σ)) ∧
          q = M.evalFrom (lrGrammar M).initial w) := by
  cases hq : rule.1 with
  | none =>
      have hinv := augment_fresh_invariant M h
      have hmem : symbol.nonterminal none ∈
          p ++ [symbol.nonterminal rule.1] ++ s.map symbol.terminal := by
        simp [hq]
      rcases hinv with heq | hnone
      · have hlen := congrArg List.length heq
        simp only [List.length_append, List.length_cons, List.length_nil,
          List.length_map] at hlen
        have hp : p = [] := List.eq_nil_of_length_eq_zero (by omega)
        have hs : s = [] := List.eq_nil_of_length_eq_zero (by omega)
        exact ⟨hs, Or.inl ⟨rfl, hp⟩⟩
      · exact False.elim (hnone hmem)
  | some q =>
      have hproj := CF_grammar.derivesRightmost_project_augment (lrGrammar M) h
      have hproj' :
          (lrGrammar M).DerivesRightmost
            [symbol.nonterminal (lrGrammar M).initial]
            ((lrGrammar M).projectAugmentString p ++
              [symbol.nonterminal q] ++ s.map symbol.terminal) := by
        simpa [CF_grammar.projectAugmentString,
          CF_grammar.projectAugmentSymbol, List.map_append, hq] using hproj
      obtain ⟨hs, w, hp, hstate⟩ :=
        config_extract M (rule := (q, [])) hproj'
      exact ⟨hs, Or.inr ⟨q, w, rfl,
        project_eq_map_terminal M hp, hstate⟩⟩

/-- The deterministic right-linear grammar of a DFA is LR(1). -/
private theorem lrGrammar_isLR1 : (lrGrammar M).IsLRk 1 := by
  change (lrGrammar M).augment.CoreIsLRk 1
  intro r₁ r₂ hr₁ hr₂ p₁ p₂ s₁ s₂ y hd₁ hd₂ hform hlook
  change List (symbol T (Option (lrGrammar M).nt)) at p₁ p₂
  obtain ⟨hs₁, hc₁⟩ := augment_config_extract M hd₁
  obtain ⟨hs₂, hc₂⟩ := augment_config_extract M hd₂
  subst s₁
  subst s₂
  have hy : y = [] := by
    cases y with
    | nil => rfl
    | cons a y => simp [CF_grammar.lrLookahead] at hlook
  subst y
  simp only [List.map_nil, List.append_nil] at hform
  rcases List.mem_cons.mp hr₁ with hstart₁ | hmapped₁ <;>
    rcases List.mem_cons.mp hr₂ with hstart₂ | hmapped₂
  · subst r₁
    subst r₂
    have hp₁ : p₁ = [] := by
      simpa [CF_grammar.augmentStartRule] using hc₁
    have hp₂ : p₂ = [] := by
      simpa [CF_grammar.augmentStartRule] using hc₂
    exact ⟨hp₁.trans hp₂.symm, rfl⟩
  · subst r₁
    rcases List.mem_map.mp hmapped₂ with ⟨r₂', hr₂', rfl⟩
    have hp₁ : p₁ = [] := by
      simpa [CF_grammar.augmentStartRule] using hc₁
    rcases hc₂ with ⟨hbad, _⟩ | ⟨q, w, _, hp₂, _⟩
    · simp [CF_grammar.augmentRule] at hbad
    · have hform' :
          w.map (symbol.terminal (N := Option (lrGrammar M).nt)) ++
              CF_grammar.augmentString r₂'.2 =
            [symbol.nonterminal (some (lrGrammar M).initial)] := by
        simpa [hp₁, hp₂, CF_grammar.augmentStartRule,
          CF_grammar.augmentRule] using hform
      have hpost :
          w.map (symbol.terminal (N := (lrGrammar M).nt)) ++ r₂'.2 =
            [symbol.nonterminal (T := T) (lrGrammar M).initial] := by
        calc
          _ = (lrGrammar M).projectAugmentString
                (w.map (symbol.terminal (N := Option (lrGrammar M).nt))) ++
              (lrGrammar M).projectAugmentString
                (CF_grammar.augmentString r₂'.2) := by
              rw [CF_grammar.projectAugmentString_map_terminal,
                CF_grammar.projectAugmentString_augmentString]
          _ = (lrGrammar M).projectAugmentString
                (w.map symbol.terminal ++ CF_grammar.augmentString r₂'.2) := by
              rw [CF_grammar.projectAugmentString_append]
          _ = (lrGrammar M).projectAugmentString
                [symbol.nonterminal (some (lrGrammar M).initial)] := by
              rw [hform']
          _ = _ := rfl
      exact False.elim (lrGrammar_post_ne_initial M hr₂' w hpost)
  · subst r₂
    rcases List.mem_map.mp hmapped₁ with ⟨r₁', hr₁', rfl⟩
    have hp₂ : p₂ = [] := by
      simpa [CF_grammar.augmentStartRule] using hc₂
    rcases hc₁ with ⟨hbad, _⟩ | ⟨q, w, _, hp₁, _⟩
    · simp [CF_grammar.augmentRule] at hbad
    · have hform' :
          [symbol.nonterminal (some (lrGrammar M).initial)] =
            w.map (symbol.terminal (N := Option (lrGrammar M).nt)) ++
              CF_grammar.augmentString r₁'.2 := by
        simpa [hp₁, hp₂, CF_grammar.augmentStartRule,
          CF_grammar.augmentRule] using hform
      have hpost :
          w.map (symbol.terminal (N := (lrGrammar M).nt)) ++ r₁'.2 =
            [symbol.nonterminal (T := T) (lrGrammar M).initial] := by
        symm
        calc
          _ = (lrGrammar M).projectAugmentString
                [symbol.nonterminal (some (lrGrammar M).initial)] := rfl
          _ = (lrGrammar M).projectAugmentString
                (w.map symbol.terminal ++ CF_grammar.augmentString r₁'.2) := by
              rw [hform']
          _ = (lrGrammar M).projectAugmentString
                (w.map (symbol.terminal (N := Option (lrGrammar M).nt))) ++
              (lrGrammar M).projectAugmentString
                (CF_grammar.augmentString r₁'.2) := by
              rw [CF_grammar.projectAugmentString_append]
          _ = _ := by
              rw [CF_grammar.projectAugmentString_map_terminal,
                CF_grammar.projectAugmentString_augmentString]
      exact False.elim (lrGrammar_post_ne_initial M hr₁' w hpost)
  · rcases List.mem_map.mp hmapped₁ with ⟨r₁', hr₁', rfl⟩
    rcases List.mem_map.mp hmapped₂ with ⟨r₂', hr₂', rfl⟩
    have hd₁' := CF_grammar.derivesRightmost_project_augment (lrGrammar M) hd₁
    have hd₂' := CF_grammar.derivesRightmost_project_augment (lrGrammar M) hd₂
    have hcore :
        (lrGrammar M).projectAugmentString p₁ ++ r₁'.2 =
          (lrGrammar M).projectAugmentString p₂ ++ r₂'.2 := by
      calc
        _ = (lrGrammar M).projectAugmentString
              (p₁ ++ CF_grammar.augmentString r₁'.2) := by
            rw [CF_grammar.projectAugmentString_append,
              CF_grammar.projectAugmentString_augmentString]
        _ = (lrGrammar M).projectAugmentString
              (p₂ ++ CF_grammar.augmentString r₂'.2) := by
            apply congrArg (lrGrammar M).projectAugmentString
            simpa [CF_grammar.augmentRule] using hform.symm
        _ = _ := by
            rw [CF_grammar.projectAugmentString_append,
              CF_grammar.projectAugmentString_augmentString]
    have hd₁'' :
        (lrGrammar M).DerivesRightmost
          [symbol.nonterminal (lrGrammar M).initial]
          ((lrGrammar M).projectAugmentString p₁ ++
            [symbol.nonterminal r₁'.1]) := by
      simpa [CF_grammar.augmentRule, CF_grammar.projectAugmentString,
        CF_grammar.projectAugmentSymbol, List.map_append] using hd₁'
    have hd₂'' :
        (lrGrammar M).DerivesRightmost
          [symbol.nonterminal (lrGrammar M).initial]
          ((lrGrammar M).projectAugmentString p₂ ++
            [symbol.nonterminal r₂'.1]) := by
      simpa [CF_grammar.augmentRule, CF_grammar.projectAugmentString,
        CF_grammar.projectAugmentSymbol, List.map_append] using hd₂'
    obtain ⟨_, hrules⟩ := lrGrammar_reduce_unique M hr₁' hr₂'
      (s₁ := []) (s₂ := [])
      (by simpa using hd₁'') (by simpa using hd₂'')
      hcore
    have hp : p₂ = p₁ := by
      have hsides :
          p₂ ++ CF_grammar.augmentString r₁'.2 =
            p₁ ++ CF_grammar.augmentString r₁'.2 := by
        simpa [CF_grammar.augmentRule, hrules] using hform
      exact List.append_cancel_right hsides
    exact ⟨hp.symm, by simp [hrules]⟩

/-- The language of the DFA-derived grammar is the DFA's language. -/
private lemma lrGrammar_language : CF_language (lrGrammar M) = M.accepts := by
  have hcf : CF_language (lrGrammar M) = RG_language (RG_of_DFA M) := by
    ext w
    simp only [lrGrammar, CF_language, RG_language]
    exact (RG_derives_iff_CF_derives (RG_of_DFA M) _ _).symm
  rw [hcf, RG_of_DFA_language]

end Langlib.RegularLR

/-! ### The inclusion -/

open Langlib.RegularLR

/-- Every regular (right-regular-generated) language is generated by an LR(1) grammar. -/
public theorem is_LRk_one_of_is_RG [Fintype T] {L : Language T} (h : is_RG L) : is_LRk 1 L := by
  obtain ⟨σ, hσ, M, hML⟩ := is_RG_iff_isRegular.mp h
  haveI := hσ
  exact ⟨lrGrammar M, lrGrammar_isLR1 M, (lrGrammar_language M).trans hML⟩

/-- Every regular language is an LR language. -/
public theorem is_LR_of_is_RG [Fintype T] {L : Language T} (h : is_RG L) : is_LR L :=
  ⟨1, is_LRk_one_of_is_RG h⟩

/-- The class of regular languages is contained in the class of LR languages. -/
public theorem RG_subclass_LR [Fintype T] :
    (RG : Set (Language T)) ⊆ (LR : Set (Language T)) :=
  fun _L hL => is_LR_of_is_RG hL
