module

/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import Langlib.Classes.Regular.Definition
public import Langlib.Grammars.LR.Definition
public import Langlib.Examples.AnBn
public import Langlib.Classes.ContextFree.Examples.AnBn
import Langlib.Classes.Regular.Examples.AnBn
import Langlib.Classes.Regular.Inclusion.LR
import Langlib.Classes.Regular.Closure.Bijection
import Langlib.Automata.FiniteState.Equivalence.Regular
import Mathlib

@[expose]
public section

/-! # RG ⊊ LR

This file proves that regular languages form a strict subclass of LR languages.

The witness is the language `{aⁿbⁿ}`, which is LR(0) (via `cfg_anbn`) but not
regular (by the pumping lemma). Combined with the already-established inclusion
`RG ⊆ LR`, this gives strict containment.

## Main results

- `anbn_is_LRk_zero` — `{aⁿbⁿ}` is generated by an LR(0) grammar.
- `anbn_is_LR` — `{aⁿbⁿ}` is an LR language.
- `RG_strict_subclass_LR` — `RG ⊊ LR` over any nontrivial finite alphabet.
-/

open CF_grammar List

/-! ### Rightmost sentential forms of `cfg_anbn`

The grammar `cfg_anbn` has rules `S → aSb` and `S → ε` with a single
nonterminal `()`. Every sentential form has at most one nonterminal,
so every derivation step is automatically rightmost. The reachable
rightmost forms are exactly `aⁿ S bⁿ` and `aⁿ bⁿ`.
-/

/-- Rightmost sentential form predicate for `cfg_anbn`: either `aⁿ S bⁿ` or `aⁿ bⁿ`. -/
private def anbn_rm_form (w : List (symbol Bool Unit)) : Prop :=
  (∃ n : ℕ, w = (replicate n false).map symbol.terminal ++
    [symbol.nonterminal ()] ++
    (replicate n true).map symbol.terminal) ∨
  (∃ n : ℕ, w = (replicate n false ++ replicate n true).map symbol.terminal)

/-- The initial sentential form `[S]` is a rightmost form (n = 0). -/
private lemma anbn_rm_form_initial :
    anbn_rm_form [symbol.nonterminal ()] := by
  left; exact ⟨0, by simp⟩

private lemma anbn_rm_form_step {u v : List (symbol Bool Unit)}
    (hu : anbn_rm_form u) (hstep : cfg_anbn.ProducesRightmost u v) :
    anbn_rm_form v := by
      rcases hu with ( ⟨ n, rfl ⟩ | ⟨ n, rfl ⟩ );
      · rcases hstep with ⟨ r, hr, p, lookahead, hp, hv ⟩ ; simp_all +decide [ cfg_anbn ] ;
        rcases hr with ( rfl | rfl ) <;> simp +decide [ List.append_eq_append_iff ] at hp ⊢;
        · rcases hp with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h₁, h₂ ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
          · cases as <;> simp_all +decide [ anbn_rm_form ];
            · left; use n + 1; simp_all +decide [ List.replicate ] ;
              exact Nat.recOn n ( by simp +decide ) fun n ihn => by simp +decide [ List.replicate ] at ihn ⊢ ; aesop;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ b, bs ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
            · refine' Or.inl ⟨ n + 1, _ ⟩ ; simp +decide [ ← h₁, List.replicate_add ];
              exact Nat.recOn n rfl fun n ih => by simp +decide [ List.replicate ] at * ; aesop;
            · replace h₂ := congr_arg List.toFinset h₂.2; rw [ Finset.ext_iff ] at h₂; specialize h₂ ( symbol.nonterminal () ) ; aesop;
        · rcases hp with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h, h' ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
          · rcases as with ( _ | ⟨ a, as ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
            · exact Or.inr ⟨ n, by aesop ⟩;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ b, bs ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
            · exact Or.inr ⟨ n, by aesop ⟩;
            · replace h' := congr_arg List.toFinset h'.2; rw [ Finset.ext_iff ] at h'; specialize h' ( symbol.nonterminal () ) ; aesop;
      · rcases hstep with ⟨ r, hr, p, lookahead, hp, hv ⟩;
        replace hp := congr_arg List.toFinset hp; rw [ Finset.ext_iff ] at hp; specialize hp ( symbol.nonterminal r.1 ) ; aesop;

/-- Every rightmost derivation from `[S]` produces a rightmost form. -/
private lemma anbn_rm_form_of_derivesRightmost {w : List (symbol Bool Unit)}
    (h : cfg_anbn.DerivesRightmost [symbol.nonterminal ()] w) :
    anbn_rm_form w := by
  induction h with
  | refl => exact anbn_rm_form_initial
  | tail _ hstep ih => exact anbn_rm_form_step ih hstep

private lemma anbn_rm_config {p : List (symbol Bool Unit)} {s : List Bool}
    (h : cfg_anbn.DerivesRightmost [symbol.nonterminal cfg_anbn.initial]
      (p ++ [symbol.nonterminal ()] ++ s.map symbol.terminal)) :
    ∃ n : ℕ, p = (replicate n false).map symbol.terminal ∧
              s = replicate n true := by
                have := anbn_rm_form_of_derivesRightmost h;
                rcases this with ( ⟨ n, hn ⟩ | ⟨ n, hn ⟩ ) <;> simp_all +decide [ List.append_assoc ];
                · have := congr_arg List.reverse hn; norm_num [ List.reverse_append ] at this;
                  replace this := congr_arg ( fun x => x.takeWhile ( fun y => y ≠ symbol.nonterminal () ) ) this ; simp_all +decide [ List.takeWhile_append ];
                  split_ifs at this <;> simp_all +decide [ List.takeWhile_eq_self_iff ];
                  · replace this := congr_arg List.reverse this ; simp_all +decide [ List.reverse_replicate ];
                    exact List.map_injective_iff.mpr ( by aesop_cat ) ( this.trans ( by aesop_cat ) );
                  · replace this := congr_arg List.length this ; simp_all +decide [ List.length_replicate ];
                    rw [ List.takeWhile_eq_self_iff.mpr ] at this <;> aesop;
                · replace hn := congr_arg ( fun x => x.count ( symbol.nonterminal () ) ) hn ; simp_all +decide [ List.count_replicate ] ;

theorem cfg_anbn_isLRk_zero : cfg_anbn.IsLRk 0 := by
  intro r₁ r₂ hr₁ hr₂ p₁ p₂ core s₁ s₂ h₁ h₂ h₃ h₄ h₅; cases h₅;
  cases' anbn_rm_config h₁ with n₁ hn₁ ; cases' anbn_rm_config h₂ with n₂ hn₂ ; simp_all +decide [ cfg_anbn ];
  cases hr₁ <;> cases hr₂ <;> simp_all +decide [ cfg_anbn ];
  · replace h₃ := congr_arg List.length h₃ ; replace h₄ := congr_arg List.length h₄ ; simp_all +decide;
    lia;
  · replace h₄ := congr_arg List.reverse h₄ ; simp_all +decide [ List.reverse_append ];
    replace h₄ := congr_arg List.toFinset h₄ ; simp_all +decide [ Finset.ext_iff ];
    specialize h₄ ( symbol.nonterminal () ) ; aesop;
  · replace h₄ := congr_arg List.reverse h₄ ; simp_all +decide [ List.reverse_append ];
    replace h₄ := congr_arg List.toFinset h₄ ; simp_all +decide [ Finset.ext_iff ];
    specialize h₄ ( symbol.nonterminal () ) ; aesop;
  · replace h₃ := congr_arg List.length h₃ ; replace h₄ := congr_arg List.length h₄ ; aesop

/-- The language `{aⁿbⁿ}` is generated by an LR(0) grammar. -/
public theorem anbn_is_LRk_zero : is_LRk 0 anbn :=
  ⟨cfg_anbn, cfg_anbn_isLRk_zero, CF_language_cfg_anbn⟩

/-- The language `{aⁿbⁿ}` is an LR language. -/
public theorem anbn_is_LR : is_LR anbn :=
  is_LR_of_is_LRk anbn_is_LRk_zero

/-! ### Parameterized grammar for `{xⁿyⁿ}` over an arbitrary alphabet

To show `RG ⊊ LR` over any nontrivial finite alphabet, we need a witness LR
language over that alphabet. We parameterize the grammar by two distinct
terminals `x ≠ y` and show the resulting grammar is LR(0).
-/

/-- Context-free grammar `S → xSy | ε` for two terminals `x, y`. -/
private def cfg_xnyn {T : Type} (x y : T) : CF_grammar T where
  nt := Unit
  initial := ()
  rules := [
    ((), [symbol.terminal x, symbol.nonterminal (), symbol.terminal y]),
    ((), [])
  ]

/-- The language of `cfg_xnyn x y`. -/
private def lang_xnyn {T : Type} (x y : T) : Language T :=
  { w | ∃ n : ℕ, w = replicate n x ++ replicate n y }

/-- Rightmost sentential form predicate for `cfg_xnyn x y`. -/
private def xnyn_rm_form {T : Type} (x y : T) (w : List (symbol T Unit)) : Prop :=
  (∃ n : ℕ, w = (replicate n x).map symbol.terminal ++
    [symbol.nonterminal ()] ++
    (replicate n y).map symbol.terminal) ∨
  (∃ n : ℕ, w = (replicate n x ++ replicate n y).map symbol.terminal)

/-! ### Helper lemmas about symbol discrimination -/

/-- A nonterminal never occurs in a `map terminal` list. -/
private lemma nt_not_mem_map_terminal {T N : Type} {n : N} {l : List T} :
    symbol.nonterminal n ∉ l.map (symbol.terminal (N := N)) := by
  simp [List.mem_map]

/-- `symbol.terminal` is injective. -/
private lemma terminal_injective {T N : Type} : Function.Injective (symbol.terminal (T := T) (N := N)) := by
  intro a b h; cases h; rfl

/-
If `l₁ ++ [nonterminal n] ++ l₂ = r₁ ++ [nonterminal n] ++ r₂` and neither
    `l₂` nor `r₂` contains `nonterminal n`, then `l₁ = r₁` and `l₂ = r₂`.
-/
private lemma append_nt_append_inj {T N : Type} {n : N}
    {l₁ l₂ r₁ r₂ : List (symbol T N)}
    (h : l₁ ++ [symbol.nonterminal n] ++ l₂ = r₁ ++ [symbol.nonterminal n] ++ r₂)
    (hl₂ : symbol.nonterminal n ∉ l₂)
    (hr₂ : symbol.nonterminal n ∉ r₂) :
    l₁ = r₁ ∧ l₂ = r₂ := by
      induction' l₁ with a l₁ ih generalizing r₁ r₂ l₂ <;> induction' r₁ with b r₁ ih' <;> simp_all +decide [ List.append_assoc ];
      · grind +splitImp;
      · exact ih h.2 hl₂ hr₂

/-
A rightmost step in `cfg_xnyn x y` preserves the form property.
-/
private lemma xnyn_rm_form_step {T : Type} {x y : T} (hxy : x ≠ y)
    {u v : List (symbol T Unit)}
    (hu : xnyn_rm_form x y u) (hstep : (cfg_xnyn x y).ProducesRightmost u v) :
    xnyn_rm_form x y v := by
      rcases hu with ( ⟨ n, rfl ⟩ | ⟨ n, rfl ⟩ );
      · obtain ⟨ r, hr, p, lookahead, h₁, h₂ ⟩ := hstep;
        -- Since r.1 = () (the only nonterminal type is Unit), and nonterminal () appears exactly once in u, use append_nt_append_inj to get p = (replicate n x).map terminal and lookahead.map terminal = (replicate n y).map terminal, hence lookahead = replicate n y.
        have hp : p = (replicate n x).map symbol.terminal := by
          have := append_nt_append_inj ( by aesop : p ++ [ symbol.nonterminal () ] ++ map symbol.terminal lookahead = map symbol.terminal ( replicate n x ) ++ [ symbol.nonterminal () ] ++ map symbol.terminal ( replicate n y ) ) ?_ ?_ <;> aesop
        have hlookahead : lookahead = replicate n y := by
          replace h₁ := congr_arg ( fun z => z.drop ( List.length ( replicate n x ) + 1 ) ) h₁ ; simp_all +decide [ List.drop_append ];
          exact List.map_injective_iff.mpr ( terminal_injective ) <| by simpa using h₁.symm;
        rcases r with ⟨ ⟨ ⟩, r ⟩ ; simp_all +decide [ cfg_xnyn ];
        rcases hr with ( rfl | rfl ) <;> simp_all +decide [ xnyn_rm_form ];
        · refine Or.inl ⟨ n + 1, ?_ ⟩ ; simp +decide [ replicate_add ];
          exact Nat.recOn n rfl fun n ih => by simp +decide [ replicate ] at * ; aesop;
        · exact Or.inr ⟨ n, rfl ⟩;
      · obtain ⟨ r, hr, p, lookahead, h₁, h₂ ⟩ := hstep;
        replace h₁ := congr_arg ( fun l => symbol.nonterminal r.1 ∈ l ) h₁ ; simp_all +decide [ List.mem_append ]

/-- Every rightmost derivation from `[S]` in `cfg_xnyn x y` produces a rightmost form. -/
private lemma xnyn_rm_form_of_derivesRightmost {T : Type} {x y : T} (hxy : x ≠ y)
    {w : List (symbol T Unit)}
    (h : (cfg_xnyn x y).DerivesRightmost [symbol.nonterminal ()] w) :
    xnyn_rm_form x y w := by
  induction h with
  | refl => left; exact ⟨0, by simp⟩
  | tail _ hstep ih => exact xnyn_rm_form_step hxy ih hstep

/-
Configuration extraction for `cfg_xnyn`.
-/
private lemma xnyn_rm_config {T : Type} {x y : T} (hxy : x ≠ y)
    {p : List (symbol T Unit)} {s : List T}
    (h : (cfg_xnyn x y).DerivesRightmost [symbol.nonterminal (cfg_xnyn x y).initial]
      (p ++ [symbol.nonterminal ()] ++ s.map symbol.terminal)) :
    ∃ n : ℕ, p = (replicate n x).map symbol.terminal ∧
              s = replicate n y := by
                -- Use the form lemma to get the form of the sentential form.
                obtain ⟨n, hn⟩ : ∃ n : ℕ, p ++ [symbol.nonterminal ()] ++ (map symbol.terminal s) = (replicate n x).map symbol.terminal ++ [symbol.nonterminal ()] ++ (replicate n y).map symbol.terminal := by
                  have := xnyn_rm_form_of_derivesRightmost hxy h;
                  obtain ⟨ n, hn ⟩ | ⟨ n, hn ⟩ := this;
                  · use n;
                  · replace hn := congr_arg ( fun l => symbol.nonterminal () ∈ l ) hn ; simp_all +decide [ List.mem_append, List.mem_map ];
                have := append_nt_append_inj hn (by
                grind) (by
                exact?);
                exact ⟨ n, this.1, by simpa using List.map_injective_iff.mpr ( terminal_injective ) this.2 ⟩

/-
The grammar `cfg_xnyn x y` is LR(0) when `x ≠ y`.
-/
private theorem cfg_xnyn_isLRk_zero {T : Type} {x y : T} (hxy : x ≠ y) :
    (cfg_xnyn x y).IsLRk 0 := by
      intro r₁ r₂ hr₁ hr₂ p₁ p₂ core s₁ s₂ h₁ h₂ h₃ h₄ h₅;
      cases' xnyn_rm_config hxy h₁ with n₁ hn₁
      cases' xnyn_rm_config hxy h₂ with n₂ hn₂
      simp_all +decide [ cfg_xnyn ];
      cases hr₁ <;> cases hr₂ <;> simp_all +decide [ ← h₃, ← h₄ ];
      · replace h₄ := congr_arg List.reverse h₄; simp_all +decide [ List.reverse_append ] ;
        cases n₂ <;> cases n₁ <;> simp_all +decide [ List.replicate ];
      · replace h₄ := congr_arg List.reverse h₄; simp_all +decide [ List.reverse_append ] ;
        cases n₁ <;> cases n₂ <;> simp_all +decide [ List.replicate ]

/-- Sentential form predicate (for general CF derivation, not just rightmost). -/
private def xnyn_sf {T : Type} (x y : T) (w : List (symbol T Unit)) : Prop :=
  (∃ n : ℕ, w = (replicate n x).map symbol.terminal ++
    [symbol.nonterminal ()] ++
    (replicate n y).map symbol.terminal) ∨
  (∃ n : ℕ, w = (replicate n x ++ replicate n y).map symbol.terminal)

/-
A CF_transforms step preserves the sentential form predicate.
-/
private lemma xnyn_sf_step {T : Type} (x y : T)
    {u v : List (symbol T Unit)}
    (hu : xnyn_sf x y u) (hstep : CF_transforms (cfg_xnyn x y) u v) :
    xnyn_sf x y v := by
      obtain ⟨ r, hr, u', v', rfl, rfl ⟩ := hstep;
      cases hu;
      · rcases r with ⟨ ⟨ ⟩, r ⟩ ; simp_all +decide [ cfg_xnyn ];
        obtain ⟨ n, hn ⟩ := ‹_›;
        have h_append_nt_append_inj : hr = (replicate n x).map symbol.terminal ∧ u' = (replicate n y).map symbol.terminal := by
          apply append_nt_append_inj;
          any_goals exact PUnit.unit;
          · simpa using hn;
          · replace hn := congr_arg ( fun z => z.drop ( List.length hr ) ) hn ; simp_all +decide [ List.drop_append ];
            cases h : n - hr.length <;> simp_all +decide [ List.replicate ];
            replace hn := congr_arg List.tail hn ; aesop;
          · grind +suggestions;
        rcases v' with ( rfl | rfl ) <;> simp_all +decide [ xnyn_sf ];
        · refine Or.inl ⟨ n + 1, ?_ ⟩ ; simp +decide [ List.replicate_add ];
          exact Nat.recOn n ( by simp +decide ) fun n ih => by simp +decide [ List.replicate ] at * ; aesop;
        · exact Or.inr ⟨ n, rfl ⟩;
      · rename_i h;
        obtain ⟨ n, hn ⟩ := h;
        replace hn := congr_arg ( fun l => symbol.nonterminal r.1 ∈ l ) hn ; simp_all +decide [ List.mem_append, List.mem_map ]

/-- Every CF derivation from `[S]` produces a sentential form. -/
private lemma xnyn_sf_of_derives {T : Type} (x y : T)
    {w : List (symbol T Unit)}
    (h : CF_derives (cfg_xnyn x y) [symbol.nonterminal ()] w) :
    xnyn_sf x y w := by
  induction h with
  | refl => left; exact ⟨0, by simp⟩
  | tail _ hstep ih => exact xnyn_sf_step x y ih hstep

/-- Forward inclusion: words generated by `cfg_xnyn x y` are in `lang_xnyn x y`. -/
private lemma CF_language_cfg_xnyn_sub {T : Type} (x y : T) :
    ∀ w, w ∈ CF_language (cfg_xnyn x y) → w ∈ lang_xnyn x y := by
  intro w hw
  have hsf := xnyn_sf_of_derives x y hw
  rcases hsf with ⟨n, hn⟩ | ⟨n, hn⟩
  · -- Left disjunct: w.map terminal contains a nonterminal — contradiction
    exfalso
    have : symbol.nonterminal () ∈ w.map symbol.terminal := by rw [hn]; simp
    exact nt_not_mem_map_terminal this
  · -- Right disjunct: w.map terminal = (x^n y^n).map terminal
    exact ⟨n, terminal_injective.list_map hn⟩

/-
Backward inclusion: words in `lang_xnyn x y` are generated by `cfg_xnyn x y`.
-/
private lemma lang_xnyn_sub_CF_language {T : Type} (x y : T) :
    ∀ w, w ∈ lang_xnyn x y → w ∈ CF_language (cfg_xnyn x y) := by
      intro w hw
      obtain ⟨n, hn⟩ := hw;
      -- By induction on $n$, we can show that $x^n S y^n$ can be derived from $S$.
      have h_ind : ∀ n : ℕ, CF_derives (cfg_xnyn x y) [symbol.nonterminal ()] ((replicate n x).map symbol.terminal ++ [symbol.nonterminal ()] ++ (replicate n y).map symbol.terminal) := by
        intro n
        induction' n with n ih;
        · exact Relation.ReflTransGen.refl;
        · convert Relation.ReflTransGen.tail ih _ using 1;
          use ((), [symbol.terminal x, symbol.nonterminal (), symbol.terminal y]);
          use (replicate n x).map symbol.terminal, (replicate n y).map symbol.terminal; simp [cfg_xnyn];
          simp +decide [ List.replicate_add ];
          exact Nat.recOn n rfl fun n ih => by simp +decide [ *, List.replicate ] ;
      convert h_ind n |> fun h => Relation.ReflTransGen.tail h _ using 1;
      use ( (), [] ) ; simp +decide [ cfg_xnyn ] ;
      exact ⟨ replicate n ( symbol.terminal x ), replicate n ( symbol.terminal y ), by aesop ⟩

/-- The grammar `cfg_xnyn x y` generates exactly `lang_xnyn x y`. -/
private theorem CF_language_cfg_xnyn {T : Type} (x y : T) :
    CF_language (cfg_xnyn x y) = lang_xnyn x y := by
  ext w; exact ⟨CF_language_cfg_xnyn_sub x y w, lang_xnyn_sub_CF_language x y w⟩

/-
`lang_xnyn x y` equals `Language.map f anbn` where `f false = x`, `f true = y`.
-/
private lemma lang_xnyn_eq_map {T : Type} {x y : T} (_hxy : x ≠ y) :
    lang_xnyn x y = Language.map (fun b => if b then y else x) anbn := by
      ext w
      simp [Language.map];
      constructor;
      · rintro ⟨ n, rfl ⟩ ; exact ⟨ List.replicate n false ++ List.replicate n true, ⟨ n, rfl ⟩, by aesop ⟩ ;
      · rintro ⟨ w, ⟨ n, rfl ⟩, rfl ⟩ ; exact ⟨ n, by aesop ⟩ ;

/-- `Language.map f anbn` is LR for injective `f : Bool → T`. -/
private theorem map_anbn_is_LR {T : Type} {f : Bool → T} (hf : Function.Injective f) :
    is_LR (Language.map f anbn) := by
  have hne : f false ≠ f true := fun h => Bool.false_ne_true (hf h)
  have heq : Language.map f anbn = lang_xnyn (f false) (f true) := by
    ext w
    simp only [Language.map, anbn, lang_xnyn]
    constructor
    · rintro ⟨w', ⟨n, rfl⟩, rfl⟩
      exact ⟨n, by simp [List.map_append, List.map_replicate]⟩
    · rintro ⟨n, rfl⟩
      exact ⟨replicate n false ++ replicate n true, ⟨n, rfl⟩,
        by simp [List.map_append, List.map_replicate]⟩
  rw [heq]
  exact is_LR_of_is_LRk ⟨cfg_xnyn (f false) (f true), cfg_xnyn_isLRk_zero hne, CF_language_cfg_xnyn _ _⟩

/-- Regular languages are a strict subclass of LR languages
over any nontrivial finite alphabet. -/
public theorem RG_strict_subclass_LR {T : Type} [Fintype T] [Nontrivial T] :
    (RG : Set (Language T)) ⊂ (LR : Set (Language T)) := by
  refine ⟨RG_subclass_LR, ?_⟩
  intro hLRsubsetRG
  obtain ⟨a, b, hab⟩ := exists_pair_ne T
  let f : Bool → T := fun x => if x then b else a
  have hf : Function.Injective f := by
    intro x y hxy
    cases x <;> cases y <;> simp_all [f]
  have hLR : Language.map f anbn ∈ (LR : Set (Language T)) := map_anbn_is_LR hf
  have hRG : Language.map f anbn ∈ (RG : Set (Language T)) := hLRsubsetRG hLR
  have hreg : (Language.map f anbn).IsRegular := isRegular_of_is_RG hRG
  exact anbn_not_isRegular (Language.IsRegular.of_map_injective hf hreg)