module

public import Langlib.Grammars.ContextFree.EquivMathlibCFG
public import Mathlib.Computability.ContextFreeGrammar

/-!
# LR(k) Grammars

This file defines the grammar-side deterministic context-free notion used in
parser theory.  The key definition is `ContextFreeGrammar.IsLRk`: after a
rightmost derivation step, the reducible handle is uniquely determined by the
already-built sentential prefix and by `k` terminal lookahead symbols.

This is the grammar-side class intended to match DPDAs.  The full equivalence
with `is_DCF` requires the two standard constructions:

* an LR(k) parser as a DPDA, proving `is_LR → is_DCF`;
* a deterministic grammar construction from a DPDA, proving `is_DCF → is_LR`.

Those constructions are not encoded here yet.
-/

open Language

namespace ContextFreeRule

variable {T N : Type} (r : ContextFreeRule T N)

/-- A rightmost use of a context-free rule.

The rule rewrites an occurrence of `r.input` whose suffix contains terminals only. -/
public def RewritesRightmost (u v : List (Symbol T N)) : Prop :=
  ∃ (p : List (Symbol T N)) (lookahead : List T),
    u = p ++ [Symbol.nonterminal r.input] ++ lookahead.map Symbol.terminal ∧
      v = p ++ r.output ++ lookahead.map Symbol.terminal

end ContextFreeRule

namespace ContextFreeGrammar

variable {T : Type} (g : ContextFreeGrammar T)

/-- A single rightmost derivation step in a context-free grammar. -/
public def ProducesRightmost (u v : List (Symbol T g.NT)) : Prop :=
  ∃ r ∈ g.rules, ContextFreeRule.RewritesRightmost r u v

/-- Rightmost derivation: reflexive-transitive closure of rightmost production. -/
public abbrev DerivesRightmost :
    List (Symbol T g.NT) → List (Symbol T g.NT) → Prop :=
  Relation.ReflTransGen g.ProducesRightmost

/-- The `k` terminal symbols visible as LR lookahead. -/
public def lrLookahead (k : ℕ) (w : List T) : List T :=
  w.take k

/-- Semantic LR(k) condition for a context-free grammar.

If two rightmost derivations reach configurations where one more rightmost step
creates the same sentential prefix, and their remaining terminal suffixes have
the same `k`-symbol lookahead, then the reducible handle and rule are identical.
The terminal suffixes themselves need not be equal beyond the visible lookahead.
-/
public def IsLRk (k : ℕ) : Prop :=
  ∀ (r₁ r₂ : ContextFreeRule T g.NT), r₁ ∈ g.rules → r₂ ∈ g.rules →
    ∀ (p₁ p₂ core : List (Symbol T g.NT)) (s₁ s₂ : List T),
      g.DerivesRightmost [Symbol.nonterminal g.initial]
        (p₁ ++ [Symbol.nonterminal r₁.input] ++ s₁.map Symbol.terminal) →
      g.DerivesRightmost [Symbol.nonterminal g.initial]
        (p₂ ++ [Symbol.nonterminal r₂.input] ++ s₂.map Symbol.terminal) →
      p₁ ++ r₁.output = core →
      p₂ ++ r₂.output = core →
      lrLookahead k s₁ = lrLookahead k s₂ →
      p₁ = p₂ ∧ r₁ = r₂

end ContextFreeGrammar

variable {T : Type}

/-- Language class generated by an LR(k) grammar. -/
public def is_LRk (k : ℕ) (L : Language T) : Prop :=
  ∃ g : ContextFreeGrammar T, g.IsLRk k ∧ g.language = L

/-- Language class generated by an LR(k) grammar for some finite `k`. -/
public def is_LR (L : Language T) : Prop :=
  ∃ k : ℕ, is_LRk k L

/-- The class of LR languages. -/
public def LR : Set (Language T) :=
  setOf is_LR

/-- Every LR(k) language is context-free. -/
public theorem is_CF_of_is_LRk {k : ℕ} {L : Language T} (h : is_LRk k L) : is_CF L := by
  rcases h with ⟨g, _hg, hL⟩
  rw [is_CF_iff_isContextFree]
  exact ⟨g, hL⟩

/-- Every LR language is context-free. -/
public theorem is_CF_of_is_LR {L : Language T} (h : is_LR L) : is_CF L := by
  rcases h with ⟨k, hk⟩
  exact is_CF_of_is_LRk hk
