module

public import Langlib.Grammars.LR.Equivalence.DPDAToLR.Introductions

/-!
# Source heads along active characteristic spines

The visible prefix alone does not determine an arbitrary active occurrence:
an epsilon edge may leave the terminal prefix unchanged.  What is unique is
the source of two *introducing edges for the same active list child*.  The
parent spines retained by `Introduces` are the history needed to state that
property without losing the partial derivation tree.
-/

@[expose]
public section

open Language

namespace DPDA_to_LR

noncomputable section

variable {Q T S : Type} [Fintype Q] [Fintype T] [Fintype S]

/-- The three kinds of characteristic nonterminal which expose a stack head.
The tag is essential: a single-symbol return and a nonempty-list split may
have the same operational state and top-of-stack while representing different
edges of the characteristic derivation tree. -/
public inductive ActiveParentKind
  | start
  | single
  | list

/-- Parent kind, state, and exposed stack symbol of a characteristic
nonterminal.  Empty-list nodes have no exposed source symbol.  The grammar
root denotes the boot configuration of the normalized empty-stack PDA. -/
@[expose]
public def activeDescriptor (M : DPDA Q T S) :
    Nonterminal M → Option (ActiveParentKind × State M × StackSymbol M)
  | PDA_to_CFG.N.start => some
      (.start, (emptyStackPDA M).initial_state,
        (emptyStackPDA M).start_symbol)
  | PDA_to_CFG.N.single q Z _ => some (.single, q, Z)
  | PDA_to_CFG.N.list q (Z :: _) _ => some (.list, q, Z)
  | PDA_to_CFG.N.list _ [] _ => none

/-- The untagged operational source is occasionally convenient when the
parent form is already known. -/
@[expose]
public def activeSource (M : DPDA Q T S) :
    Nonterminal M → Option (State M × StackSymbol M)
  | PDA_to_CFG.N.start => some
      ((emptyStackPDA M).initial_state, (emptyStackPDA M).start_symbol)
  | PDA_to_CFG.N.single q Z _ => some (q, Z)
  | PDA_to_CFG.N.list q (Z :: _) _ => some (q, Z)
  | PDA_to_CFG.N.list _ [] _ => none

/-- The start symbol occurs only at the root of an active spine. -/
public theorem ActiveSpine.start_eq_nil (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix : List T}
    (h : ActiveSpine M p PDA_to_CFG.N.start suffix) :
    p = [] ∧ suffix = [] := by
  exact start_prehandle_eq_nil M (h.derivesRightmost M)

/-- History-sensitive head uniqueness required by the reverse-edge argument.
The common list child and one symbol of its following input determine the
kind and source configuration head of its two possible parent edges. -/
@[expose]
public def ActiveHeadUnique (M : DPDA Q T S) : Prop :=
  ∀ (childPrefix : List (symbol T (Nonterminal M)))
      (child : Nonterminal M) (suffix₁ suffix₂ : List T)
      (parentPrefix₁ parentPrefix₂ :
        List (symbol T (Nonterminal M)))
      (parent₁ parent₂ : Nonterminal M)
      (rule₁ rule₂ :
        Nonterminal M × List (symbol T (Nonterminal M))),
    IsListSymbol M (symbol.nonterminal child) →
    Introduces M childPrefix child suffix₁
        parentPrefix₁ parent₁ rule₁ →
    Introduces M childPrefix child suffix₂
        parentPrefix₂ parent₂ rule₂ →
    suffix₁.take 1 = suffix₂.take 1 →
    activeDescriptor M parent₁ = activeDescriptor M parent₂

/-- A normalized characteristic rule generated by an epsilon transition. -/
@[expose]
public def IsEpsilonRule (M : DPDA Q T S)
    (rule : Nonterminal M × List (symbol T (Nonterminal M))) : Prop :=
  ∃ (q target next : State M) (Z : StackSymbol M)
      (gamma : List (StackSymbol M)),
    (next, gamma) ∈ (emptyStackPDA M).transition_fun' q Z ∧
    rule = (PDA_to_CFG.N.single q Z target,
      [symbol.nonterminal (PDA_to_CFG.N.list next gamma target)])

/-- The exact epsilon-bearing residual of active-head uniqueness.  All pairs
without an epsilon edge reduce to stable read heads or to syntactic
cancellation; the useful-epsilon-cycle argument proves this remaining part. -/
@[expose]
public def EpsilonIntroducingHeadsUnique (M : DPDA Q T S) : Prop :=
  ∀ (childPrefix : List (symbol T (Nonterminal M)))
      (child : Nonterminal M) (suffix₁ suffix₂ : List T)
      (parentPrefix₁ parentPrefix₂ :
        List (symbol T (Nonterminal M)))
      (parent₁ parent₂ : Nonterminal M)
      (rule₁ rule₂ :
        Nonterminal M × List (symbol T (Nonterminal M))),
    IsListSymbol M (symbol.nonterminal child) →
    Introduces M childPrefix child suffix₁
        parentPrefix₁ parent₁ rule₁ →
    Introduces M childPrefix child suffix₂
        parentPrefix₂ parent₂ rule₂ →
    suffix₁.take 1 = suffix₂.take 1 →
    (IsEpsilonRule M rule₁ ∨ IsEpsilonRule M rule₂) →
    activeDescriptor M parent₁ = activeDescriptor M parent₂

end

end DPDA_to_LR
