module

public import Langlib.Grammars.LR.Equivalence.DPDAToLR.Spine

/-!
# Operational runs for characteristic list introductions

These factorizations expose the hidden stack context of read, epsilon, and
split-right introduction edges after a chosen terminal completion of their
visible prefix.  They form the cycle-free prerequisite shared by spine
synchronization and the final epsilon-head assembly.
-/

@[expose]
public section

open Language PDA

namespace DPDA_to_LR

noncomputable section

variable {Q T S : Type} [Fintype Q] [Fintype T] [Fintype S]

/-- Operational factorization of a non-start list introduction after a
chosen terminal completion of its visible child prefix. -/
public def ListIntroductionRun (M : DPDA Q T S)
    (preWord suffix : List T) (source : State M)
    (top : StackSymbol M) (next : State M)
    (gamma : List (StackSymbol M)) (target : State M) : Prop :=
  ∃ (beforeWord segmentWord : List T)
      (sourceTail context : List (StackSymbol M))
      (final : State M),
    preWord = beforeWord ++ segmentWord ∧
    (emptyStackPDA M).Reaches
      ⟨(emptyStackPDA M).initial_state, beforeWord,
        [(emptyStackPDA M).start_symbol]⟩
      ⟨source, [], top :: sourceTail⟩ ∧
    (emptyStackPDA M).Reaches
      ⟨source, segmentWord, top :: sourceTail⟩
      ⟨next, [], gamma ++ context⟩ ∧
    (emptyStackPDA M).Reaches
      ⟨target, suffix, context⟩ ⟨final, [], []⟩

/-- Stronger factorization for an introduction generated by one actual PDA
transition. -/
public def ListTransitionRun (M : DPDA Q T S)
    (preWord suffix : List T) (source : State M)
    (top : StackSymbol M) (next : State M)
    (gamma : List (StackSymbol M)) (target : State M) : Prop :=
  ∃ (beforeWord segmentWord : List T)
      (context : List (StackSymbol M))
      (final : State M),
    preWord = beforeWord ++ segmentWord ∧
    (emptyStackPDA M).Reaches
      ⟨(emptyStackPDA M).initial_state, beforeWord,
        [(emptyStackPDA M).start_symbol]⟩
      ⟨source, [], top :: context⟩ ∧
    (emptyStackPDA M).Reaches₁
      ⟨source, segmentWord, top :: context⟩
      ⟨next, [], gamma ++ context⟩ ∧
    (emptyStackPDA M).Reaches
      ⟨target, suffix, context⟩ ⟨final, [], []⟩

/-- Forgetting that the middle segment is one step gives the uniform
introduction-run factorization. -/
public theorem ListTransitionRun.introductionRun (M : DPDA Q T S)
    {preWord suffix : List T} {source : State M}
    {top : StackSymbol M} {next : State M}
    {gamma : List (StackSymbol M)} {target : State M}
    (h : ListTransitionRun M preWord suffix source top next gamma target) :
    ListIntroductionRun M preWord suffix source top next gamma target := by
  rcases h with
    ⟨beforeWord, segmentWord, context, final, hpre,
      hprefix, hstep, hcontinuation⟩
  exact ⟨beforeWord, segmentWord, context, context, final, hpre,
    hprefix, Relation.ReflTransGen.single hstep, hcontinuation⟩

/-- Split-right introductions preserve the stronger fact that the source
tail is exactly the child stack followed by the saved outer context. -/
public def ListSplitRun (M : DPDA Q T S)
    (preWord suffix : List T) (source : State M)
    (top : StackSymbol M) (next : State M)
    (gamma : List (StackSymbol M)) (target : State M) : Prop :=
  ∃ (beforeWord segmentWord : List T)
      (context : List (StackSymbol M)) (final : State M),
    preWord = beforeWord ++ segmentWord ∧
    (emptyStackPDA M).Reaches
      ⟨(emptyStackPDA M).initial_state, beforeWord,
        [(emptyStackPDA M).start_symbol]⟩
      ⟨source, [], top :: (gamma ++ context)⟩ ∧
    (emptyStackPDA M).Reaches
      ⟨source, segmentWord, top :: (gamma ++ context)⟩
      ⟨next, [], gamma ++ context⟩ ∧
    (emptyStackPDA M).Reaches
      ⟨target, suffix, context⟩ ⟨final, [], []⟩

/-- Forgetting the split-specific source-tail equation gives a uniform run. -/
public theorem ListSplitRun.introductionRun (M : DPDA Q T S)
    {preWord suffix : List T} {source : State M}
    {top : StackSymbol M} {next : State M}
    {gamma : List (StackSymbol M)} {target : State M}
    (h : ListSplitRun M preWord suffix source top next gamma target) :
    ListIntroductionRun M preWord suffix source top next gamma target := by
  rcases h with
    ⟨beforeWord, segmentWord, context, final, hpre,
      hprefix, hsegment, hcontinuation⟩
  exact ⟨beforeWord, segmentWord, gamma ++ context, context, final,
    hpre, hprefix, hsegment, hcontinuation⟩

private theorem terminal_completion_singleton (M : DPDA Q T S)
    {a : T} {w : List T}
    (h : (characteristicGrammar M).DerivesRightmost
      [symbol.terminal a] (w.map symbol.terminal)) :
    w = [a] := by
  have h' : (characteristicGrammar M).DerivesRightmost
      ([a].map (symbol.terminal (N := Nonterminal M)))
      (w.map symbol.terminal) := by simpa using h
  have heq := h'.eq_of_map_terminal_source
  have hmap : w.map (symbol.terminal (N := Nonterminal M)) =
      [a].map symbol.terminal := by simpa using heq
  exact (List.map_injective_iff.mpr fun _ _ hsymbol =>
    symbol.terminal.inj hsymbol) hmap

/-- Exact factorization for a reading list introduction. -/
public theorem listIntroductionRun_read (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix preWord : List T}
    {q target next : State M} {a : T} {Z : StackSymbol M}
    {gamma : List (StackSymbol M)}
    (hparent : ActiveSpine M p
      (PDA_to_CFG.N.single q Z target) suffix)
    (htransition : (next, gamma) ∈
      (emptyStackPDA M).transition_fun q a Z)
    (hp : (characteristicGrammar M).DerivesRightmost
      (p ++ [symbol.terminal a]) (preWord.map symbol.terminal)) :
    ListIntroductionRun M preWord suffix q Z next gamma target := by
  obtain ⟨beforeWord, segmentWord, hpre, hbase, hsegment⟩ :=
    CF_grammar.DerivesRightmost.append_to_terminals_split hp
  have hsegmentWord : segmentWord = [a] :=
    terminal_completion_singleton M hsegment
  subst segmentWord
  have hfocused := focused_of_prehandle M
    (hparent.derivesRightmost M) hbase
  cases hfocused with
  | single _ _ _ _ _ context final prefixPath continuation =>
      refine ⟨beforeWord, [a], context, context, final,
        hpre, prefixPath, ?_, continuation⟩
      apply Relation.ReflTransGen.single
      exact Or.inl ⟨next, gamma, htransition, by simp⟩

/-- One-step specialization of `listIntroductionRun_read`. -/
public theorem listTransitionRun_read (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix preWord : List T}
    {q target next : State M} {a : T} {Z : StackSymbol M}
    {gamma : List (StackSymbol M)}
    (hparent : ActiveSpine M p
      (PDA_to_CFG.N.single q Z target) suffix)
    (htransition : (next, gamma) ∈
      (emptyStackPDA M).transition_fun q a Z)
    (hp : (characteristicGrammar M).DerivesRightmost
      (p ++ [symbol.terminal a]) (preWord.map symbol.terminal)) :
    ListTransitionRun M preWord suffix q Z next gamma target := by
  obtain ⟨beforeWord, segmentWord, hpre, hbase, hsegment⟩ :=
    CF_grammar.DerivesRightmost.append_to_terminals_split hp
  have hsegmentWord : segmentWord = [a] :=
    terminal_completion_singleton M hsegment
  subst segmentWord
  have hfocused := focused_of_prehandle M
    (hparent.derivesRightmost M) hbase
  cases hfocused with
  | single _ _ _ _ _ context final prefixPath continuation =>
      exact ⟨beforeWord, [a], context, final,
        hpre, prefixPath, Or.inl ⟨next, gamma, htransition, by simp⟩,
        continuation⟩

/-- Exact factorization for an epsilon list introduction. -/
public theorem listIntroductionRun_epsilon (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix preWord : List T}
    {q target next : State M} {Z : StackSymbol M}
    {gamma : List (StackSymbol M)}
    (hparent : ActiveSpine M p
      (PDA_to_CFG.N.single q Z target) suffix)
    (htransition : (next, gamma) ∈
      (emptyStackPDA M).transition_fun' q Z)
    (hp : (characteristicGrammar M).DerivesRightmost
      p (preWord.map symbol.terminal)) :
    ListIntroductionRun M preWord suffix q Z next gamma target := by
  have hfocused := focused_of_prehandle M
    (hparent.derivesRightmost M) hp
  cases hfocused with
  | single _ _ _ _ _ context final prefixPath continuation =>
      refine ⟨preWord, [], context, context, final, by simp,
        prefixPath, ?_, continuation⟩
      apply Relation.ReflTransGen.single
      exact ⟨next, gamma, htransition, by simp⟩

/-- One-step specialization of `listIntroductionRun_epsilon`. -/
public theorem listTransitionRun_epsilon (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix preWord : List T}
    {q target next : State M} {Z : StackSymbol M}
    {gamma : List (StackSymbol M)}
    (hparent : ActiveSpine M p
      (PDA_to_CFG.N.single q Z target) suffix)
    (htransition : (next, gamma) ∈
      (emptyStackPDA M).transition_fun' q Z)
    (hp : (characteristicGrammar M).DerivesRightmost
      p (preWord.map symbol.terminal)) :
    ListTransitionRun M preWord suffix q Z next gamma target := by
  have hfocused := focused_of_prehandle M
    (hparent.derivesRightmost M) hp
  cases hfocused with
  | single _ _ _ _ _ context final prefixPath continuation =>
      exact ⟨preWord, [], context, final, by simp,
        prefixPath, ⟨next, gamma, htransition, by simp⟩, continuation⟩

/-- Exact factorization for a split-right list introduction. -/
public theorem listIntroductionRun_split (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix preWord : List T}
    {q middle target : State M} {Z : StackSymbol M}
    {gamma : List (StackSymbol M)}
    (hparent : ActiveSpine M p
      (PDA_to_CFG.N.list q (Z :: gamma) target) suffix)
    (hp : (characteristicGrammar M).DerivesRightmost
      (p ++ [symbol.nonterminal (PDA_to_CFG.N.single q Z middle)])
      (preWord.map symbol.terminal)) :
    ListIntroductionRun M preWord suffix q Z middle gamma target := by
  obtain ⟨beforeWord, segmentWord, hpre, hbase, hsegment⟩ :=
    CF_grammar.DerivesRightmost.append_to_terminals_split hp
  have hfocused := focused_of_prehandle M
    (hparent.derivesRightmost M) hbase
  cases hfocused with
  | list _ _ _ _ _ context final prefixPath continuation =>
      have hreturn :=
        (reaches_of_characteristic_derives_single M hsegment).append_stack
          (gamma ++ context)
      refine ⟨beforeWord, segmentWord, gamma ++ context,
        context, final,
        hpre, ?_, ?_, continuation⟩
      · simpa [List.append_assoc] using prefixPath
      · simpa [List.append_assoc] using hreturn

/-- Split-specific factorization retaining the exact hidden-context shape. -/
public theorem listSplitRun (M : DPDA Q T S)
    {p : List (symbol T (Nonterminal M))} {suffix preWord : List T}
    {q middle target : State M} {Z : StackSymbol M}
    {gamma : List (StackSymbol M)}
    (hparent : ActiveSpine M p
      (PDA_to_CFG.N.list q (Z :: gamma) target) suffix)
    (hp : (characteristicGrammar M).DerivesRightmost
      (p ++ [symbol.nonterminal (PDA_to_CFG.N.single q Z middle)])
      (preWord.map symbol.terminal)) :
    ListSplitRun M preWord suffix q Z middle gamma target := by
  obtain ⟨beforeWord, segmentWord, hpre, hbase, hsegment⟩ :=
    CF_grammar.DerivesRightmost.append_to_terminals_split hp
  have hfocused := focused_of_prehandle M
    (hparent.derivesRightmost M) hbase
  cases hfocused with
  | list _ _ _ _ _ context final prefixPath continuation =>
      have hreturn :=
        (reaches_of_characteristic_derives_single M hsegment).append_stack
          (gamma ++ context)
      refine ⟨beforeWord, segmentWord, context, final,
        hpre, ?_, ?_, continuation⟩
      · simpa [List.append_assoc] using prefixPath
      · simpa [List.append_assoc] using hreturn

end

end DPDA_to_LR
