module

public import Langlib.Grammars.RightRegular.Definition
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Irrational
import Mathlib.Tactic.NormNum.IsCoprime
import Mathlib.Tactic.NormNum.IsSquare
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.ModEq
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.NatFib
import Mathlib.Tactic.NormNum.NatLog
import Mathlib.Tactic.NormNum.NatSqrt
import Mathlib.Tactic.NormNum.Ordinal
import Mathlib.Tactic.NormNum.Parity
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Topology.Sheaves.Init
@[expose]
public section



/-! # Regular Languages

This file defines the class of regular languages via unrestricted grammars
satisfying the right-regular rule-shape property.
-/

variable {T : Type}

/-- An output string has right-regular form if it is one of:
- `[terminal a, nonterminal B]`,
- `[terminal a]`, or
- `[]`. -/
@[expose]
public def right_regular_output {N : Type} (s : List (symbol T N)) : Prop :=
  (∃ a : T, ∃ B : N, s = [symbol.terminal a, symbol.nonterminal B]) ∨
  (∃ a : T, s = [symbol.terminal a]) ∨
  s = []

/-- An unrestricted grammar is right-regular if every rule is context-free
and has right-regular output. -/
@[expose]
public def grammar_right_regular (g : grammar T) : Prop :=
  ∀ r ∈ g.rules,
    r.input_L = [] ∧ r.input_R = [] ∧ right_regular_output r.output_string

/-- A language is regular if it is generated by some right-regular unrestricted grammar. -/
@[expose]
public def is_RG (L : Language T) : Prop :=
  ∃ g : grammar T, grammar_right_regular g ∧ grammar_language g = L

/-- Legacy characterization of regular languages via `RG_grammar`. -/
@[expose]
public def is_RG_via_rg (L : Language T) : Prop :=
  ∃ g : RG_grammar T, RG_language g = L

/-- The class of regular languages. -/
@[expose]
public def RG : Set (Language T) :=
  setOf is_RG
