import Langlib.Grammars.RightRegular.Definition
import Langlib.Grammars.Unrestricted.Definition

/-! # Regular Languages

This file defines the class of regular languages via unrestricted grammars
satisfying the right-regular rule-shape property.
-/

variable {T : Type}

/-- An output string has right-regular form if it is one of:
- `[terminal a, nonterminal B]`,
- `[terminal a]`, or
- `[]`. -/
def right_regular_output {N : Type} (s : List (symbol T N)) : Prop :=
  (∃ a : T, ∃ B : N, s = [symbol.terminal a, symbol.nonterminal B]) ∨
  (∃ a : T, s = [symbol.terminal a]) ∨
  s = []

/-- An unrestricted grammar is right-regular if every rule is context-free
and has right-regular output. -/
def grammar_right_regular (g : grammar T) : Prop :=
  ∀ r ∈ g.rules,
    r.input_L = [] ∧ r.input_R = [] ∧ right_regular_output r.output_string

/-- A language is regular if it is generated by some right-regular unrestricted grammar. -/
def is_RG (L : Language T) : Prop :=
  ∃ g : grammar T, grammar_right_regular g ∧ grammar_language g = L

/-- Legacy characterization of regular languages via `RG_grammar`. -/
def is_RG_via_rg (L : Language T) : Prop :=
  ∃ g : RG_grammar T, RG_language g = L

/-- The class of regular languages. -/
def RG : Set (Language T) :=
  setOf is_RG
