module

public import Langlib.Grammars.LR.Equivalence.DPDAToLR.ProductivePositionAssembly
public import Langlib.Grammars.LR.Equivalence.DPDAToLR.ProductivePositions

/-!
# Deterministic pushdown automata have LR(1) grammars

The productive characteristic grammar of a normalized DPDA is LR(1).  The
normalization separates the first final-state visit from the remainder of a
computation; exact active-spine synchronization then makes both visible
introducing edges and empty returns unique with one symbol of lookahead.
-/

@[expose]
public section

open Language

namespace DPDA_to_LR

noncomputable section

variable {Q T S : Type} [Fintype Q] [Fintype T] [Fintype S]

/-- The productive characteristic grammar constructed from a DPDA is LR(1). -/
public theorem characteristicGrammar_isLR1 (M : DPDA Q T S) :
    (characteristicGrammar M).IsLRk 1 :=
  characteristicGrammar_isLR1_of_productivePositions M
    (productivePairedVisibleAnchorPositionsEqual M)

end

end DPDA_to_LR

variable {T : Type} [Fintype T]

/-- Every language accepted by a DPDA is generated by an LR(1) grammar. -/
public theorem is_LRk_one_of_is_DPDA {L : Language T}
    (h : is_DPDA L) : is_LRk 1 L := by
  rcases h with ⟨Q, S, hQ, hS, M, hM⟩
  letI : Fintype Q := hQ
  letI : Fintype S := hS
  exact ⟨DPDA_to_LR.characteristicGrammar M,
    DPDA_to_LR.characteristicGrammar_isLR1 M,
    (DPDA_to_LR.characteristicGrammar_language M).trans hM⟩

/-- Consequently every DPDA language belongs to the existential
finite-lookahead LR class. -/
public theorem is_LR_of_is_DPDA {L : Language T}
    (h : is_DPDA L) : is_LR L :=
  is_LR_of_is_LRk (is_LRk_one_of_is_DPDA h)

end
