import Mathlib
import Langlib.Classes.RecursivelyEnumerable.Definition
import Langlib.Grammars.Unrestricted.Toolbox
import Langlib.Automata.Turing.Equivalence.TMToGrammar.Construction
import Langlib.Automata.Turing.Equivalence.TMToGrammar.Helpers

/-! # Soundness of the TM → Grammar Construction

This file proves that the grammar `tmToGrammar` constructed from a TM0 machine is
**sound**: it only generates words on which the TM halts.

## Proof strategy

We define a "terminal content" function `terminalContent` that extracts, from each symbol
in a sentential form, the original input character it represents. This function is
invariant under all simulation and cleanup grammar rules (but increases during generation).

We then define a forward invariant `GI` with five constructors:
- `initial`: the start symbol
- `generating`: generation phase
- `simulating`: simulation phase (tracks TM configuration correspondence)
- `cleanup`: post-halt cleanup (tracks `terminalContent = w` and TM halts on `w`)
- `done`: terminal-only form

The key insight is that `cleanup` uses `terminalContent` instead of tracking a derivation
to a terminal form. This avoids the non-confluence issue in the cleanup phase.
-/

open Turing TMtoGrammarNT Relation

variable {T : Type} [DecidableEq T] [Fintype T]
         {Λ : Type} [Inhabited Λ] [DecidableEq Λ] [Fintype Λ]

/-! ### Terminal content -/

/-- Extract the "original input character" from a grammar symbol.
Terminals contribute their value. Nonterminals contribute their `orig` field (if `some`).
Boundary markers, `start`, `genMore`, and `none`-orig nonterminals contribute nothing. -/
def symbolOriginal : symbol T (TMtoGrammarNT T Λ) → Option T
  | .terminal t => some t
  | .nonterminal (cell (some t) _) => some t
  | .nonterminal (headCell _ (some t) _) => some t
  | .nonterminal (haltCell (some t)) => some t
  | _ => none

/-- The "terminal content" of a sentential form: the list of original input characters.
This is invariant under simulation and cleanup rules. -/
def terminalContent (sf : List (symbol T (TMtoGrammarNT T Λ))) : List T :=
  sf.filterMap (symbolOriginal (Λ := Λ))

theorem terminalContent_nil : terminalContent (T := T) (Λ := Λ) [] = [] := by
  simp [terminalContent]

theorem terminalContent_cons (s : symbol T (TMtoGrammarNT T Λ))
    (sf : List (symbol T (TMtoGrammarNT T Λ))) :
    terminalContent (s :: sf) =
      (match symbolOriginal (Λ := Λ) s with | some t => [t] | none => []) ++
      terminalContent sf := by
  simp [terminalContent, List.filterMap_cons]
  cases symbolOriginal (Λ := Λ) s <;> simp

theorem terminalContent_append (sf₁ sf₂ : List (symbol T (TMtoGrammarNT T Λ))) :
    terminalContent (sf₁ ++ sf₂) = terminalContent sf₁ ++ terminalContent sf₂ := by
  simp [terminalContent, List.filterMap_append]

theorem terminalContent_terminal_map (w : List T) :
    terminalContent (Λ := Λ) (w.map symbol.terminal) = w := by
  induction w with
  | nil => simp [terminalContent]
  | cons t ts ih =>
    simp only [terminalContent, List.map_cons, List.filterMap_cons, symbolOriginal]
    simp only [terminalContent] at ih
    simp [ih]

/-
`terminalContent` is preserved by every grammar rule whose `input_N` is
not `start` or `genMore`.
-/
theorem terminalContent_rule_preserved
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hns : r.input_N ≠ start)
    (hng : r.input_N ≠ genMore) :
    terminalContent (Λ := Λ) (r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R) =
    terminalContent r.output_string := by
  -- By definition of `tmToGrammar`, the rules are generated by combining the generationRules, simulationRules, and cleanupRules.
  have h_rules : (tmToGrammar T Λ M).rules = generationRules T Λ M ++ simulationRules T Λ M ++ cleanupRules T Λ M := by
    rfl;
  simp_all +decide [ terminalContent ];
  rcases hr with ( hr | hr | hr );
  · unfold generationRules at hr; aesop;
  · unfold simulationRules at hr;
    rw [ List.mem_flatMap ] at hr; obtain ⟨ q, _, hr ⟩ := hr; rw [ List.mem_flatMap ] at hr; obtain ⟨ γ, _, hr ⟩ := hr; rcases h : M q γ with ( _ | ⟨ q', _ | _ ⟩ ) <;> simp_all +decide ;
    · cases ‹Dir› <;> simp_all +decide [ List.mem_append, List.mem_flatMap ];
      · rcases hr with ( ⟨ a, ha, b, hb, c, hc, rfl ⟩ | ⟨ a, ha, rfl ⟩ ) <;> simp_all +decide [ List.filterMap_cons ];
        · cases b <;> cases c <;> cases a <;> cases γ <;> simp +decide [ symbolOriginal ] at ha hb hc ⊢;
        · cases a <;> cases γ <;> rfl;
      · rcases hr with ( ⟨ a, ha, b, hb, c, hc, rfl ⟩ | ⟨ a, ha, rfl ⟩ ) <;> simp_all +decide [ List.filterMap ];
        · cases a <;> cases b <;> cases c <;> rfl;
        · cases a <;> cases γ <;> rfl;
    · rcases hr with ⟨ a, _, rfl ⟩ ; simp +decide [ symbolOriginal ] ;
      cases a <;> cases ‹Option T› <;> simp +decide [ symbolOriginal ] at *;
  · revert hr;
    unfold cleanupRules;
    simp +decide [ allOptT ] at * ; aesop ( simp_config := { decide := true } ) ;

/-
If a sentential form has no `start` or `genMore` nonterminals,
any grammar transform preserves `terminalContent`.
-/
theorem terminalContent_preserved
    (sf sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (htrans : grammar_transforms (tmToGrammar T Λ M) sf sf')
    (hns : ∀ s ∈ sf, s ≠ symbol.nonterminal start)
    (hng : ∀ s ∈ sf, s ≠ symbol.nonterminal genMore) :
    terminalContent sf' = terminalContent sf := by
  obtain ⟨ r, hr, u, v, hu, hv ⟩ := htrans;
  -- By `terminalContent_rule_preserved`, the terminal content of `r.input_L ++ [nonterminal r.input_N] ++ r.input_R` is equal to the terminal content of `r.output_string`.
  have h_term_content : terminalContent (r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R) = terminalContent r.output_string := by
    apply terminalContent_rule_preserved; assumption; exact (by
    contrapose! hns; aesop;); exact (by
    grind);
  grind +locals

/-! ### Terminal-only forms can't be transformed -/

/-- Terminal-only forms can't be transformed. -/
theorem no_transform_terminal (g : grammar T) (w : List T) :
    ∀ sf', ¬grammar_transforms g (w.map symbol.terminal) sf' := by
  intro sf' ⟨r, _, u, v, heq, _⟩
  have : symbol.nonterminal r.input_N ∈ w.map symbol.terminal := by
    rw [heq]; simp [List.mem_append]
  simp [List.mem_map] at this

/-- Derivation from terminal form is trivial. -/
theorem derives_terminal_id (g : grammar T) (w : List T)
    (sf : List (symbol T g.nt))
    (h : grammar_derives g (w.map symbol.terminal) sf) :
    sf = w.map symbol.terminal := by
  induction h with
  | refl => rfl
  | tail _ htrans ih =>
    exfalso; exact no_transform_terminal g w _ (ih ▸ htrans)

/-- No rule has `cell` as `input_N`. -/
theorem no_cell_rule (M : Turing.TM0.Machine (Option T) Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (orig cur : Option T) (hN : r.input_N = cell orig cur) : False := by
  unfold tmToGrammar at hr
  unfold generationRules simulationRules cleanupRules at hr
  aesop

/-! ### The corrected forward invariant -/

/-- Whether a symbol is a nonterminal. -/
def isNonterminal : symbol T N → Prop
  | .terminal _ => False
  | .nonterminal _ => True

/-- The forward invariant for the `tmToGrammar` construction.

This invariant tracks five phases:
1. **initial**: The start symbol `[S]`.
2. **generating**: Building the initial configuration `[LB, genMore, cells..., RB]`.
3. **simulating**: Simulating TM steps. Tracks correspondence with actual TM configs.
4. **cleanup**: Post-halt phase. Tracks `terminalContent = w` where TM halts on `w`.
5. **done**: Terminal-only form `w.map terminal` where TM halts on `w`.
-/
inductive GI (M : Turing.TM0.Machine (Option T) Λ) :
    List (symbol T (TMtoGrammarNT T Λ)) → Prop where
  | initial :
      GI M [symbol.nonterminal start]
  | generating (ts : List T) :
      GI M ([symbol.nonterminal leftBound, symbol.nonterminal genMore] ++
            (ts.map fun t => symbol.nonterminal (cell (some t) (some t))) ++
            [symbol.nonterminal rightBound])
  | simulating (tc : @TwoTrackConfig T Λ) (tmCfg : Turing.TM0.Cfg (Option T) Λ)
      (hcorr : TMCorresponds tc tmCfg)
      (hreach : Turing.Reaches (Turing.TM0.step M)
        (Turing.TM0.init ((extractInput (twoTrackOriginals tc)).map some)) tmCfg) :
      GI M (encodeTwoTrack tc)
  | cleanup (sf : List (symbol T (TMtoGrammarNT T Λ))) (w : List T)
      (hhalt : (Turing.TM0.eval M (w.map Option.some)).Dom)
      (hcontent : terminalContent sf = w)
      (hhas_nt : ∃ s, s ∈ sf ∧ isNonterminal s)
      (hno_start : ∀ s ∈ sf, s ≠ symbol.nonterminal start)
      (hno_genMore : ∀ s ∈ sf, s ≠ symbol.nonterminal genMore)
      (hno_headCell : ∀ s ∈ sf, ∀ q orig cur,
        s ≠ symbol.nonterminal (headCell q orig cur)) :
      GI M sf
  | done (w : List T)
      (hhalt : (Turing.TM0.eval M (w.map Option.some)).Dom) :
      GI M (w.map symbol.terminal)

/-! ### Terminal halts -/

/-
If a terminal-only form satisfies `GI`, then TM halts on that input.
-/
theorem GI_terminal_halts (M : Turing.TM0.Machine (Option T) Λ) (w : List T)
    (h : GI M (w.map symbol.terminal)) :
    (Turing.TM0.eval M (w.map Option.some)).Dom := by
  contrapose! h with h_contra
  generalize_proofs at *;
  intro h_gi
  generalize_proofs at *; (
  -- If the GI condition holds for the terminal-only form, then by definition, the TM must halt on that input.
  have h_halts : (Turing.TM0.eval M (w.map Option.some)).Dom := by
    have := h_gi
    obtain ⟨w', hw'⟩ : ∃ w' : List T, GI M (w'.map symbol.terminal) ∧ w' = w ∧ (Turing.TM0.eval M (w'.map Option.some)).Dom := by
      have h_halts : ∀ {sf : List (symbol T (TMtoGrammarNT T Λ))}, GI M sf → (∃ w' : List T, GI M (w'.map symbol.terminal) ∧ w' = terminalContent sf ∧ (Turing.TM0.eval M (w'.map Option.some)).Dom) ∨ (∃ s ∈ sf, isNonterminal s) := by
        intro sf hsf
        induction' hsf with sf hsf ih
        generalize_proofs at *; (
        exact Or.inr ⟨ _, List.mem_singleton_self _, by tauto ⟩);
        · exact Or.inr ⟨ symbol.nonterminal leftBound, by simp +decide, by tauto ⟩;
        · exact Or.inr ⟨ symbol.nonterminal leftBound, by simp +decide [ encodeTwoTrack ], by simp +decide [ isNonterminal ] ⟩;
        · exact Or.inr ‹_›;
        · exact Or.inl ⟨ _, GI.done _ ‹_›, by rw [ terminalContent_terminal_map ], ‹_› ⟩
      generalize_proofs at *; (
      specialize h_halts h_gi; simp_all +decide [ terminalContent_terminal_map ] ;
      exact h_halts.elim fun x hx => by cases hx.2;)
    generalize_proofs at *; (
    grind +ring)
  generalize_proofs at *; (
  contradiction))

/-! ### Preservation lemmas -/

/-
Invariant preserved from initial state.
-/
theorem GI_preserved_initial (M : Turing.TM0.Machine (Option T) Λ)
    (sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (htrans : grammar_transforms (tmToGrammar T Λ M) [symbol.nonterminal start] sf') :
    GI M sf' := by
  obtain ⟨ r, hr, u, v, h ⟩ := htrans;
  rcases u with ( _ | ⟨ a, u ⟩ ) <;> simp_all +decide [ List.append_assoc ];
  rcases r with ⟨ L, N, R, S ⟩ ; rcases L with ( _ | ⟨ a, L ⟩ ) <;> rcases R with ( _ | ⟨ b, R ⟩ ) <;> simp_all +decide [ List.append_assoc ] ;
  rcases h with ⟨ ⟨ rfl, rfl ⟩, rfl ⟩ ; simp_all +decide [ tmToGrammar ] ;
  rcases hr with ( hr | hr | hr );
  · unfold generationRules at hr; simp_all +decide [ List.append_assoc ] ;
    exact GI.generating [ ];
  · unfold simulationRules at hr; aesop;
  · unfold cleanupRules at hr; aesop;

/-
No rule with input_N = leftBound has empty input_L and input_R starting with genMore.
-/
theorem no_leftBound_rule_genMore_context (M : Turing.TM0.Machine (Option T) Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = leftBound) :
    r.input_L = [] ∧
    (r.input_R = [symbol.nonterminal rightBound] ∨
     ∃ orig, r.input_R = [symbol.nonterminal (haltCell orig)]) := by
  unfold tmToGrammar at hr;
  unfold generationRules simulationRules cleanupRules at hr; aesop;

/-
No rule with input_N = rightBound has input_L that is a cell or genMore.
-/
theorem no_rightBound_rule_cell_context (M : Turing.TM0.Machine (Option T) Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = rightBound) :
    ∃ orig, r.input_L = [symbol.nonterminal (haltCell orig)] := by
  unfold tmToGrammar at hr;
  unfold generationRules simulationRules cleanupRules at hr; aesop;

/-
All rules with input_N = genMore.
-/
theorem genMore_rules_classification (M : Turing.TM0.Machine (Option T) Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = genMore) :
    (r.input_L = [] ∧ r.input_R = [] ∧
     (∃ t : T, r.output_string = [symbol.nonterminal genMore,
       symbol.nonterminal (cell (some t) (some t))])) ∨
    (r.input_L = [] ∧ r.input_R = [] ∧
     (∃ t : T, r.output_string = [symbol.nonterminal
       (headCell (default : Λ) (some t) (some t))])) ∨
    (r.input_L = [] ∧ r.input_R = [symbol.nonterminal rightBound] ∧
     r.output_string = [symbol.nonterminal (headCell (default : Λ) none none),
       symbol.nonterminal rightBound]) := by
  unfold tmToGrammar at hr;
  unfold generationRules simulationRules cleanupRules at hr; aesop;

/-
No nonterminal from {start, headCell, haltCell} appears in the generating form.
-/
theorem gen_form_no_start_head_halt (ts : List T)
    (s : symbol T (TMtoGrammarNT T Λ))
    (hs : s ∈ ([symbol.nonterminal leftBound, symbol.nonterminal genMore] ++
       (ts.map fun t => symbol.nonterminal (cell (some t) (some t))) ++
       [symbol.nonterminal rightBound])) :
    s = symbol.nonterminal leftBound ∨
    s = symbol.nonterminal genMore ∨
    (∃ t, s = symbol.nonterminal (cell (some t) (some t))) ∨
    s = symbol.nonterminal rightBound := by
  grind

/-
Invariant preserved from generating state.
-/
theorem GI_preserved_generating (M : Turing.TM0.Machine (Option T) Λ)
    (ts : List T)
    (sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (htrans : grammar_transforms (tmToGrammar T Λ M)
      ([symbol.nonterminal leftBound, symbol.nonterminal genMore] ++
       (ts.map fun t => symbol.nonterminal (cell (some t) (some t))) ++
       [symbol.nonterminal rightBound]) sf') :
    GI M sf' := by
  obtain ⟨ r, hr, u, v, heq, rfl ⟩ := htrans;
  -- Show that r.input_N must be one of the nonterminals in the sentential form.
  have h_nonterminals : r.input_N = leftBound ∨ r.input_N = genMore ∨ (∃ t, r.input_N = cell (some t) (some t)) ∨ r.input_N = rightBound := by
    replace heq := congr_arg ( fun x => symbol.nonterminal r.input_N ∈ x ) heq ; simp_all +decide [ List.mem_append ] ;
    grind;
  rcases h_nonterminals with ( h | h | ⟨ t, h ⟩ | h );
  · have := no_leftBound_rule_genMore_context M r hr h; simp_all +decide ;
    rcases u with ( _ | ⟨ _, _ | u ⟩ ) <;> simp_all +decide;
    · grind;
    · grind +suggestions;
  · rcases u with ( _ | ⟨ a, _ | ⟨ b, u ⟩ ⟩ ) <;> simp_all +decide;
    · have := genMore_rules_classification M r hr ‹_›; aesop;
    · have h_genMore_rules : r.input_L = [] ∧ r.input_R = [] ∧ (∃ t : T, r.output_string = [symbol.nonterminal genMore, symbol.nonterminal (cell (some t) (some t))]) ∨ r.input_L = [] ∧ r.input_R = [] ∧ (∃ t : T, r.output_string = [symbol.nonterminal (headCell (default : Λ) (some t) (some t))]) ∨ r.input_L = [] ∧ r.input_R = [symbol.nonterminal rightBound] ∧ r.output_string = [symbol.nonterminal (headCell (default : Λ) none none), symbol.nonterminal rightBound] := by
        apply genMore_rules_classification M r hr h;
      rcases h_genMore_rules with ( ⟨ h₁, h₂, t, h₃ ⟩ | ⟨ h₁, h₂, t, h₃ ⟩ | ⟨ h₁, h₂, h₃ ⟩ ) <;> simp_all +decide;
      · convert GI.generating ( t :: ts ) using 1;
        aesop;
      · convert GI.simulating ( initTwoTrack ( t :: ts ) ) _ _ _ using 1;
        rotate_left;
        exact inferInstance;
        exact Turing.TM0.init ( List.map some ( t :: ts ) );
        · exact?;
        · convert Relation.ReflTransGen.refl using 1;
          rotate_left;
          exact Turing.TM0.Cfg ( Option T ) Λ;
          exact fun _ _ => True;
          exact Turing.TM0.init ( List.map some ( t :: ts ) );
          simp +decide [ extractInput, twoTrackOriginals, initTwoTrack ];
          simp +decide [ Function.comp_def, List.filterMap_eq_map ];
          exact iff_of_true ( Relation.ReflTransGen.refl ) ( Relation.ReflTransGen.refl );
        · unfold encodeTwoTrack initTwoTrack; aesop;
      · rcases ts with ( _ | ⟨ t, ts ⟩ ) <;> simp_all +decide [ List.map ];
        rw [ ← heq.1 ];
        convert GI.simulating _ _ _ _ using 1;
        rotate_left;
        exact ⟨ [ ], default, none, none, [ ] ⟩;
        exact Turing.TM0.init [ ];
        · constructor <;> aesop;
        · exact Relation.ReflTransGen.refl;
        · rfl;
    · grind +suggestions;
  · have := no_cell_rule M r hr ( some t ) ( some t ) ; aesop;
  · -- By definition of `no_rightBound_rule_cell_context`, we know that `r.input_L = [symbol.nonterminal (haltCell orig)]` for some `orig`.
    obtain ⟨orig, horig⟩ : ∃ orig, r.input_L = [symbol.nonterminal (haltCell orig)] := by
      apply no_rightBound_rule_cell_context M r hr h;
    rcases u with ( _ | ⟨ a, _ | ⟨ b, u ⟩ ⟩ ) <;> simp_all +decide;
    grind +suggestions

/-
Every symbol in `encodeTwoTrack tc` is a nonterminal of type leftBound, cell, headCell, or rightBound.
-/
theorem encodeTwoTrack_mem_classification (tc : @TwoTrackConfig T Λ)
    (s : symbol T (TMtoGrammarNT T Λ))
    (hs : s ∈ encodeTwoTrack tc) :
    s = symbol.nonterminal leftBound ∨
    (∃ orig cur, s = symbol.nonterminal (cell orig cur)) ∨
    s = symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur) ∨
    s = symbol.nonterminal rightBound := by
  contrapose! hs;
  unfold encodeTwoTrack; aesop;

/-
In `encodeTwoTrack tc`, leftBound is the first symbol and is not followed by rightBound.
-/
theorem encodeTwoTrack_second_not_rightBound (tc : @TwoTrackConfig T Λ) :
    ¬ ∃ v, encodeTwoTrack tc =
      [symbol.nonterminal leftBound, symbol.nonterminal rightBound] ++ v := by
  unfold encodeTwoTrack;
  cases tc.leftCells <;> simp +decide

/-
No leftBound rule can fire on encodeTwoTrack tc (the required contexts don't match).
-/
theorem no_leftBound_on_encodeTwoTrack (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = leftBound)
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R ++ v) :
    False := by
  obtain ⟨hL, hR⟩ := no_leftBound_rule_genMore_context M r hr hN
  simp [hL, hN] at heq
  rcases hR with hR | ⟨orig, hR⟩
  · -- r.input_R = [rightBound]
    simp [hR] at heq
    rcases u with ( _ | ⟨ s, u ⟩ ) <;> simp_all +decide;
    · exact absurd heq ( by exact fun h => encodeTwoTrack_second_not_rightBound tc ⟨ v, h ⟩ );
    · have h_contradiction : ∀ s ∈ List.tail (encodeTwoTrack tc), s ≠ symbol.nonterminal leftBound := by
        unfold encodeTwoTrack; simp +decide ;
        rintro s ( ⟨ a, b, hab, rfl ⟩ | rfl | ⟨ a, b, hab, rfl ⟩ | rfl ) <;> simp +decide [ * ];
      aesop
  · -- r.input_R = [haltCell orig]
    simp [hR] at heq
    -- haltCell must appear in encodeTwoTrack tc, but it doesn't
    have : symbol.nonterminal (haltCell orig) ∈ encodeTwoTrack tc := by
      rw [heq]; simp
    have := encodeTwoTrack_mem_classification tc _ this
    simp +decide at this

/-
No rightBound rule can fire on encodeTwoTrack tc.
-/
theorem no_rightBound_on_encodeTwoTrack (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = rightBound)
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R ++ v) :
    False := by
  -- By no_rightBound_rule_cell_context, if r.input_N = rightBound then r.input_L = [nonterminal (haltCell orig)] for some orig.
  obtain ⟨orig, horig⟩ : ∃ orig, r.input_L = [symbol.nonterminal (haltCell orig)] := by
    exact?;
  have := encodeTwoTrack_mem_classification tc ( symbol.nonterminal ( haltCell orig ) ) ; simp_all +decide ;

/-
All headCell rules in tmToGrammar are either simulation rules or cleanup rules.
Specifically, if r.input_N = headCell q orig cur, then either:
(a) M q cur = some (q', action) and the rule is a simulation rule, or
(b) M q cur = none and the rule converts headCell to haltCell.
-/
theorem headCell_rule_classification (M : Turing.TM0.Machine (Option T) Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (q : Λ) (orig cur : Option T)
    (hN : r.input_N = headCell q orig cur) :
    (∃ q' action, M q cur = some (q', action)) ∨
    (M q cur = none ∧ r.input_L = [] ∧ r.input_R = [] ∧
     r.output_string = [symbol.nonterminal (haltCell orig)]) := by
  simp [tmToGrammar] at hr ⊢;
  rcases hr with ( hr | hr | hr );
  · unfold generationRules at hr; aesop;
  · unfold simulationRules at hr; aesop;
  · unfold cleanupRules at hr; aesop;

set_option maxHeartbeats 800000 in
/-- Detailed classification of simulation rules matching headCell q orig cur
when M q cur = some (q', action). -/
theorem sim_rule_detailed_classification (M : Turing.TM0.Machine (Option T) Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (q : Λ) (orig cur : Option T)
    (hN : r.input_N = headCell q orig cur)
    (q' : Λ) (action : Turing.TM0.Stmt (Option T))
    (hMqa : M q cur = some (q', action)) :
    -- Write
    (∃ γ', action = Turing.TM0.Stmt.write γ' ∧
      r.input_L = [] ∧ r.input_R = [] ∧
      r.output_string = [symbol.nonterminal (headCell q' orig γ')]) ∨
    -- Move right with neighbor
    (action = Turing.TM0.Stmt.move Dir.right ∧
      ∃ o' c', r.input_L = [] ∧
        r.input_R = [symbol.nonterminal (cell o' c')] ∧
        r.output_string = [symbol.nonterminal (cell orig cur),
                           symbol.nonterminal (headCell q' o' c')]) ∨
    -- Move right at boundary
    (action = Turing.TM0.Stmt.move Dir.right ∧
      r.input_L = [] ∧
      r.input_R = [symbol.nonterminal rightBound] ∧
      r.output_string = [symbol.nonterminal (cell orig cur),
                         symbol.nonterminal (headCell q' none none),
                         symbol.nonterminal rightBound]) ∨
    -- Move left with neighbor
    (action = Turing.TM0.Stmt.move Dir.left ∧
      ∃ o'' c'', r.input_L = [symbol.nonterminal (cell o'' c'')] ∧
        r.input_R = [] ∧
        r.output_string = [symbol.nonterminal (headCell q' o'' c''),
                           symbol.nonterminal (cell orig cur)]) ∨
    -- Move left at boundary
    (action = Turing.TM0.Stmt.move Dir.left ∧
      r.input_L = [symbol.nonterminal leftBound] ∧
      r.input_R = [] ∧
      r.output_string = [symbol.nonterminal leftBound,
                         symbol.nonterminal (headCell q' none none),
                         symbol.nonterminal (cell orig cur)]) := by
  revert r;
  simp [tmToGrammar];
  intro r hr hN;
  rcases hr with ( hr | hr | hr );
  · unfold generationRules at hr;
    grind;
  · unfold simulationRules at hr; aesop;
  · unfold cleanupRules at hr; aesop;

/-
In encodeTwoTrack tc, no cell/leftBound/rightBound/haltCell symbol equals a headCell symbol.
-/
theorem encodeTwoTrack_no_headCell_outside_head (tc : @TwoTrackConfig T Λ)
    (s : symbol T (TMtoGrammarNT T Λ))
    (hs : s ∈ [symbol.nonterminal leftBound] ++
          tc.leftCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ++
          tc.rightCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ++
          [symbol.nonterminal rightBound]) :
    ∀ q orig cur, s ≠ symbol.nonterminal (headCell q orig cur) := by
  grind

/-
The headCell symbol appears exactly once in encodeTwoTrack tc,
so the split u ++ [headCell] ++ v is unique.
-/
theorem encodeTwoTrack_unique_split (tc : @TwoTrackConfig T Λ)
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ v) :
    u = [symbol.nonterminal leftBound] ++ tc.leftCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ∧
    v = tc.rightCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ++ [symbol.nonterminal rightBound] := by
  simp_all +decide [ encodeTwoTrack ];
  rw [ eq_comm ] at heq;
  rw [ List.append_eq_cons_iff ] at heq;
  rcases heq with ( ⟨ rfl, heq ⟩ | ⟨ as', rfl, heq ⟩ ) <;> simp_all +decide [ List.append_assoc ];
  grind +suggestions

set_option maxHeartbeats 800000 in
theorem sim_rule_write_case (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tc' : @TwoTrackConfig T Λ)
    (q' : Λ) (γ' : Option T)
    (hMqa : M tc.headState tc.headCur = some (q', Turing.TM0.Stmt.write γ'))
    (h_step : stepTwoTrack M tc = some tc')
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [] ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ [] ++ v) :
    u ++ [symbol.nonterminal (headCell q' tc.headOrig γ')] ++ v = encodeTwoTrack tc' := by
  have h_split : u = [symbol.nonterminal leftBound] ++ tc.leftCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ∧ v = tc.rightCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ++ [symbol.nonterminal rightBound] := by
    apply encodeTwoTrack_unique_split;
    simpa using heq;
  unfold stepTwoTrack at h_step;
  unfold encodeTwoTrack; aesop;

set_option maxHeartbeats 800000 in
theorem sim_rule_move_right_case (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tc' : @TwoTrackConfig T Λ)
    (q' : Λ) (o' c' : Option T)
    (hMqa : M tc.headState tc.headCur = some (q', Turing.TM0.Stmt.move Dir.right))
    (h_step : stepTwoTrack M tc = some tc')
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [] ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ [symbol.nonterminal (cell o' c')] ++ v) :
    u ++ [symbol.nonterminal (cell tc.headOrig tc.headCur), symbol.nonterminal (headCell q' o' c')] ++ v = encodeTwoTrack tc' := by
  -- Apply the uniqueness of the split to conclude the proof.
  have h_split : u = [symbol.nonterminal leftBound] ++ tc.leftCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ∧
    [symbol.nonterminal (cell o' c')] ++ v = tc.rightCells.map (fun p => symbol.nonterminal (cell p.1 p.2)) ++ [symbol.nonterminal rightBound] := by
      apply encodeTwoTrack_unique_split;
      simpa using heq;
  unfold stepTwoTrack at h_step; simp_all +decide ;
  cases h : tc.rightCells <;> simp_all +decide [ encodeTwoTrack ];
  grind

set_option maxHeartbeats 800000 in
theorem sim_rule_move_right_boundary_case (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tc' : @TwoTrackConfig T Λ)
    (q' : Λ)
    (hMqa : M tc.headState tc.headCur = some (q', Turing.TM0.Stmt.move Dir.right))
    (h_step : stepTwoTrack M tc = some tc')
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [] ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ [symbol.nonterminal rightBound] ++ v) :
    u ++ [symbol.nonterminal (cell tc.headOrig tc.headCur), symbol.nonterminal (headCell q' none none), symbol.nonterminal rightBound] ++ v = encodeTwoTrack tc' := by
  have := encodeTwoTrack_unique_split tc u ( [ symbol.nonterminal rightBound ] ++ v ) ?_;
  · cases h : tc.rightCells <;> simp_all +decide [ encodeTwoTrack ];
    unfold stepTwoTrack at h_step; aesop;
  · grind

set_option maxHeartbeats 800000 in
theorem sim_rule_move_left_case (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tc' : @TwoTrackConfig T Λ)
    (q' : Λ) (o'' c'' : Option T)
    (hMqa : M tc.headState tc.headCur = some (q', Turing.TM0.Stmt.move Dir.left))
    (h_step : stepTwoTrack M tc = some tc')
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [symbol.nonterminal (cell o'' c'')] ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ [] ++ v) :
    u ++ [symbol.nonterminal (headCell q' o'' c''), symbol.nonterminal (cell tc.headOrig tc.headCur)] ++ v = encodeTwoTrack tc' := by
  have := encodeTwoTrack_unique_split tc ( u ++ [ symbol.nonterminal ( cell o'' c'' ) ] ) v; simp_all +decide [ encodeTwoTrack ] ;
  rcases h : tc.leftCells.reverse with ( _ | ⟨ x, _ | ⟨ y, l ⟩ ⟩ ) <;> simp_all +decide [ stepTwoTrack ];
  · cases u <;> aesop;
  · rcases u with ( _ | ⟨ _, _ | u ⟩ ) <;> simp_all +decide [ List.append_eq_cons_iff ];
    aesop;
  · rw [ ← h_step ] ; simp +decide [ h ] ;
    replace this := congr_arg List.reverse this.1; simp_all +decide [ List.reverse_append ] ;

set_option maxHeartbeats 800000 in
theorem sim_rule_move_left_boundary_case (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tc' : @TwoTrackConfig T Λ)
    (q' : Λ)
    (hMqa : M tc.headState tc.headCur = some (q', Turing.TM0.Stmt.move Dir.left))
    (h_step : stepTwoTrack M tc = some tc')
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [symbol.nonterminal leftBound] ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ [] ++ v) :
    u ++ [symbol.nonterminal leftBound, symbol.nonterminal (headCell q' none none), symbol.nonterminal (cell tc.headOrig tc.headCur)] ++ v = encodeTwoTrack tc' := by
  have := encodeTwoTrack_unique_split tc;
  specialize this ( u ++ [ symbol.nonterminal leftBound ] ) v ; simp +decide [ heq ] at this ⊢;
  cases u <;> simp_all +decide [ encodeTwoTrack ];
  · unfold stepTwoTrack at h_step; aesop;
  · cases h : tc.leftCells.reverse <;> aesop

set_option maxHeartbeats 1600000 in
/-- When a simulation rule fires on encodeTwoTrack tc, the result is encodeTwoTrack tc'
for some tc' with stepTwoTrack M tc = some tc'. -/
theorem sim_rule_gives_encodeTwoTrack (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = headCell tc.headState tc.headOrig tc.headCur)
    (hM : ∃ q' action, M tc.headState tc.headCur = some (q', action))
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R ++ v) :
    ∃ tc', stepTwoTrack M tc = some tc' ∧
           u ++ r.output_string ++ v = encodeTwoTrack tc' := by
  obtain ⟨q', action, hMqa⟩ := hM
  have h_step : ∃ tc', stepTwoTrack M tc = some tc' := by
    unfold stepTwoTrack; simp [hMqa]
    rcases action with (_ | _)
    · rename_i d; rcases d with (_ | _)
      · rcases tc.leftCells.reverse with (_ | _) <;> simp
      · rcases tc.rightCells with (_ | _) <;> simp
    · simp
  obtain ⟨tc', h_step⟩ := h_step
  use tc', h_step
  have hclass := sim_rule_detailed_classification M r hr tc.headState tc.headOrig tc.headCur hN q' action hMqa
  rw [hN] at heq
  rcases hclass with ⟨γ', rfl, hL, hR, hout⟩ | ⟨rfl, o', c', hL, hR, hout⟩ | ⟨rfl, hL, hR, hout⟩ | ⟨rfl, o'', c'', hL, hR, hout⟩ | ⟨rfl, hL, hR, hout⟩
  · simp only [hL, hR, hout]; exact sim_rule_write_case M tc tc' q' γ' hMqa h_step u v (by simpa [hL, hR] using heq)
  · simp only [hL, hR, hout]; exact sim_rule_move_right_case M tc tc' q' o' c' hMqa h_step u v (by simpa [hL, hR] using heq)
  · simp only [hL, hR, hout]; exact sim_rule_move_right_boundary_case M tc tc' q' hMqa h_step u v (by simpa [hL, hR] using heq)
  · simp only [hL, hR, hout]; exact sim_rule_move_left_case M tc tc' q' o'' c'' hMqa h_step u v (by simpa [hL, hR] using heq)
  · simp only [hL, hR, hout]; exact sim_rule_move_left_boundary_case M tc tc' q' hMqa h_step u v (by simpa [hL, hR] using heq)

/-
When the TM halts (M q γ = none), a transform on encodeTwoTrack tc
produces a form satisfying the cleanup invariant.
-/
theorem halt_rule_gives_cleanup (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ)
    (r : grule T (TMtoGrammarNT T Λ))
    (hr : r ∈ (tmToGrammar T Λ M).rules)
    (hN : r.input_N = headCell tc.headState tc.headOrig tc.headCur)
    (hM : M tc.headState tc.headCur = none)
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ r.input_L ++ [symbol.nonterminal r.input_N] ++ r.input_R ++ v) :
    r.input_L = [] ∧ r.input_R = [] ∧
    r.output_string = [symbol.nonterminal (haltCell tc.headOrig)] := by
  have := headCell_rule_classification M r hr tc.headState tc.headOrig tc.headCur hN;
  aesop

/-
The TM0.eval halts when TM reaches a halting config.
-/
theorem tm_eval_dom_of_reaches_halt
    (M : Turing.TM0.Machine (Option T) Λ)
    (l : List (Option T))
    (tmCfg : Turing.TM0.Cfg (Option T) Λ)
    (hreach : Turing.Reaches (Turing.TM0.step M) (Turing.TM0.init l) tmCfg)
    (hhalt : Turing.TM0.step M tmCfg = none) :
    (Turing.TM0.eval M l).Dom := by
  convert hhalt using 1;
  simp +decide [ Part.dom_iff_mem ];
  constructor <;> intro h <;> simp_all +decide [ TM0.eval ];
  use tmCfg;
  grind +suggestions

/-
The terminalContent of encodeTwoTrack tc equals extractInput (twoTrackOriginals tc).
-/
theorem terminalContent_encodeTwoTrack (tc : @TwoTrackConfig T Λ) :
    terminalContent (encodeTwoTrack tc) = extractInput (twoTrackOriginals tc) := by
  induction' tc with q t_notion l_notionCells l_notionCell r_notion cellea_r_numberCells pa_rnumberCells_one pa_rnumberCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two pa_rnumberOfCells_one pa_rnumberOfCells_two
  apply Eq.symm; exact (by
  induction' q with cell cells ih generalizing l_notionCells l_notionCell t_notion <;> simp_all +decide [ terminalContent, twoTrackOriginals, encodeTwoTrack ];
  · induction r_notion <;> simp_all +decide [ extractInput ];
    · cases l_notionCells <;> rfl;
    · cases ‹Option T × Option T›.1 <;> cases ‹Option T × Option T›.2 <;> simp_all +decide [ List.filterMap_cons ];
      · cases l_notionCells <;> cases l_notionCell <;> tauto;
      · cases l_notionCells <;> cases l_notionCell <;> simp_all +decide [ symbolOriginal ];
      · cases l_notionCells <;> cases l_notionCell <;> simp_all +decide [ symbolOriginal ];
      · cases l_notionCells <;> cases l_notionCell <;> simp_all +decide [ symbolOriginal ];
  · cases cell.1 <;> simp_all +decide [ extractInput ];
    · convert ih t_notion l_notionCells l_notionCell using 1;
    · convert congr_arg ( fun x => ‹T› :: x ) ( ih t_notion l_notionCells l_notionCell ) using 1)

/-
Symbols from encodeTwoTrack tc are never start, genMore, or haltCell.
-/
theorem encodeTwoTrack_no_start (tc : @TwoTrackConfig T Λ) (s : symbol T (TMtoGrammarNT T Λ))
    (hs : s ∈ encodeTwoTrack tc) : s ≠ symbol.nonterminal start := by
  contrapose! hs;
  unfold encodeTwoTrack; aesop;

theorem encodeTwoTrack_no_genMore (tc : @TwoTrackConfig T Λ) (s : symbol T (TMtoGrammarNT T Λ))
    (hs : s ∈ encodeTwoTrack tc) : s ≠ symbol.nonterminal genMore := by
  rcases s with ( _ | _ | _ | _ | _ | _ | _ | _ | _ ) <;> (unfold encodeTwoTrack at hs; simp_all +decide [ List.mem_cons ] ;)

/-
TM0.step M tmCfg from TMCorresponds.
-/
theorem tm_step_of_corresponds
    (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tmCfg : Turing.TM0.Cfg (Option T) Λ)
    (hcorr : TMCorresponds tc tmCfg)
    (h_Mqc : M tc.headState tc.headCur = none) :
    Turing.TM0.step M tmCfg = none := by
  have h_step_none : tmCfg.q = tc.headState ∧ tmCfg.Tape.head = tc.headCur := by
    exact ⟨ hcorr.state_eq.symm, hcorr.head_eq.symm ⟩;
  unfold TM0.step; aesop;

/-
In encodeTwoTrack tc, the only headCell is at a specific position. If we remove it,
no headCell remains.
-/
theorem encodeTwoTrack_no_headCell_in_parts (tc : @TwoTrackConfig T Λ)
    (u v : List (symbol T (TMtoGrammarNT T Λ)))
    (heq : encodeTwoTrack tc = u ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ v)
    (s : symbol T (TMtoGrammarNT T Λ))
    (hs : s ∈ u ∨ s ∈ v)
    (q : Λ) (orig cur : Option T) :
    s ≠ symbol.nonterminal (headCell q orig cur) := by
  contrapose! hs;
  unfold encodeTwoTrack at heq; simp_all +decide [ List.append_assoc ] ;
  rcases u with ( _ | ⟨ a, u ⟩ ) <;> rcases v with ( _ | ⟨ b, v ⟩ ) <;> simp_all +decide [ List.sublist_append_iff ];
  · replace heq := congr_arg List.reverse heq.2 ; simp_all +decide [ List.reverse_append ];
  · rcases u with ( _ | ⟨ a, u ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
    · rcases tc with ⟨ ⟨ l₁, l₂ ⟩, q, o₁, o₂, ⟨ r₁, r₂ ⟩ ⟩ ; aesop;
      · aesop;
      · cases heq.2;
      · aesop;
    · rcases heq with ⟨ rfl, heq ⟩;
      rcases tc with ⟨ leftCells, headState, headOrig, headCur, rightCells ⟩;
      rcases leftCells with ( _ | ⟨ x, leftCells ⟩ ) <;> simp_all +decide [ List.map ];
      · grind +suggestions;
      · induction leftCells generalizing u <;> simp_all +decide [ List.map ];
        · rcases u with ( _ | ⟨ a, u ⟩ ) <;> simp_all +decide [ List.map ];
          · grind +splitImp;
          · rcases rightCells with ( _ | ⟨ x, rightCells ⟩ ) <;> simp_all +decide [ List.map ];
            · rcases u with ( _ | ⟨ a, u ⟩ ) <;> simp_all +decide [ List.map ];
            · induction u generalizing b v <;> simp_all +decide [ List.map ];
              grind;
        · rcases u with ( _ | ⟨ a, u ⟩ ) <;> simp_all +decide [ List.map ];
          grind

/-
TM0.step when M gives some action.
-/
theorem tm_step_some_of_corresponds
    (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tmCfg : Turing.TM0.Cfg (Option T) Λ)
    (hcorr : TMCorresponds tc tmCfg)
    (q' : Λ) (action : Turing.TM0.Stmt (Option T))
    (h_Mqc : M tc.headState tc.headCur = some (q', action)) :
    ∃ tmCfg', Turing.TM0.step M tmCfg = some tmCfg' := by
  unfold TM0.step;
  have := hcorr.state_eq; have := hcorr.head_eq; aesop;

set_option maxHeartbeats 1600000 in
/-- Invariant preserved from simulating state. -/
theorem GI_preserved_simulating (M : Turing.TM0.Machine (Option T) Λ)
    (tc : @TwoTrackConfig T Λ) (tmCfg : Turing.TM0.Cfg (Option T) Λ)
    (hcorr : TMCorresponds tc tmCfg)
    (hreach : Turing.Reaches (Turing.TM0.step M)
      (Turing.TM0.init ((extractInput (twoTrackOriginals tc)).map some)) tmCfg)
    (sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (htrans : grammar_transforms (tmToGrammar T Λ M) (encodeTwoTrack tc) sf') :
    GI M sf' := by
  obtain ⟨r, hr, u, v, heq, rfl⟩ := htrans
  -- r.input_N must appear in encodeTwoTrack tc
  have h_in : symbol.nonterminal r.input_N ∈ encodeTwoTrack tc := by
    rw [heq]; simp [List.mem_append]
  -- Classify the nonterminal
  have h_class := encodeTwoTrack_mem_classification tc _ h_in
  rcases h_class with h_lb | ⟨orig, cur, h_cell⟩ | h_hc | h_rb
  · -- leftBound: contradiction
    have hN : r.input_N = leftBound := by
      have := h_lb; simp [symbol.nonterminal.injEq] at this; exact this
    exact absurd (no_leftBound_on_encodeTwoTrack M tc r hr hN u v heq) id
  · -- cell: contradiction
    have hN : r.input_N = cell orig cur := by
      have := h_cell; simp [symbol.nonterminal.injEq] at this; exact this
    exact absurd (no_cell_rule M r hr orig cur hN) id
  · -- headCell: main case
    have hN : r.input_N = headCell tc.headState tc.headOrig tc.headCur := by
      have := h_hc; simp [symbol.nonterminal.injEq] at this; exact this
    rcases h_Mqc : M tc.headState tc.headCur with _ | ⟨q', action⟩
    · -- TM halts: cleanup
      have h_halt := halt_rule_gives_cleanup M tc r hr hN h_Mqc u v heq
      obtain ⟨hL, hR, hO⟩ := h_halt
      -- sf' = u ++ [haltCell tc.headOrig] ++ v, TM halts
      -- This is the cleanup phase
      -- Since the transformation replaces the headCell with a haltCell, we need to show that the haltCell is in the GI.
      have h_haltCell_in_GI : GI M (u ++ [symbol.nonterminal (haltCell tc.headOrig)] ++ v) := by
        have h_terminalContent : terminalContent (u ++ [symbol.nonterminal (haltCell tc.headOrig)] ++ v) = extractInput (twoTrackOriginals tc) := by
          have h_terminalContent : terminalContent (u ++ [symbol.nonterminal (headCell tc.headState tc.headOrig tc.headCur)] ++ v) = terminalContent (encodeTwoTrack tc) := by
            aesop
          generalize_proofs at *; (
          convert h_terminalContent.trans ( terminalContent_encodeTwoTrack tc ) using 1
          generalize_proofs at *; (
          cases tc.headOrig <;> cases tc.headCur <;> simp +decide [ terminalContent ] at h_Mqc ⊢;
          · rfl;
          · rfl;
          · rfl;
          · exact?))
        apply_rules [ GI.cleanup ];
        · exact tm_eval_dom_of_reaches_halt M _ _ hreach ( tm_step_of_corresponds M tc tmCfg hcorr h_Mqc );
        · exact ⟨ symbol.nonterminal ( haltCell tc.headOrig ), by simp +decide, by simp +decide [ isNonterminal ] ⟩;
        · intro s hs; contrapose! hs; simp_all +decide [ encodeTwoTrack_no_start ] ;
          exact ⟨ fun h => by have := encodeTwoTrack_no_start tc ( symbol.nonterminal start ) ( heq.symm ▸ List.mem_append_left _ h ) ; contradiction, fun h => by have := encodeTwoTrack_no_start tc ( symbol.nonterminal start ) ( heq.symm ▸ List.mem_append_right _ ( List.mem_cons_of_mem _ h ) ) ; contradiction ⟩;
        · intro s hs; contrapose! hs; simp_all +decide [ encodeTwoTrack ] ;
          have h_no_genMore : ∀ s ∈ encodeTwoTrack tc, s ≠ symbol.nonterminal genMore := by
            -- By definition of `encodeTwoTrack`, the genMore nonterminal is not present in the encoded two-track configuration.
            intros s hs
            apply encodeTwoTrack_no_genMore tc s hs
          generalize_proofs at *; (
          unfold encodeTwoTrack at h_no_genMore; aesop;);
        · intros s hs q orig cur h_eq
          have h_headCell_in_parts : s ∈ u ∨ s ∈ v := by
            grind +ring
          generalize_proofs at *; (
          exact encodeTwoTrack_no_headCell_in_parts tc u v ( by aesop ) s h_headCell_in_parts q orig cur ( by aesop ))
      generalize_proofs at *; (
      aesop)
    · -- TM continues: simulation
      obtain ⟨tc', hstep, hsf⟩ := sim_rule_gives_encodeTwoTrack M tc r hr hN ⟨q', action, h_Mqc⟩ u v heq
      rw [hsf]
      -- Use tm_step_some_of_corresponds to get ⟨tmCfg', h_tm_step⟩.
      obtain ⟨tmCfg', h_tm_step⟩ : ∃ tmCfg', Turing.TM0.step M tmCfg = some tmCfg' := by
        exact?;
      -- Apply the GI.simulating constructor with the given parameters.
      apply GI.simulating tc' tmCfg' (by
      have := corresponds_step_some M tc tmCfg tmCfg' hcorr h_tm_step; aesop;) (by
      convert Relation.ReflTransGen.tail hreach h_tm_step using 1;
      rw [ stepTwoTrack_preserves_extractInput M tc tc' hstep ])
  · -- rightBound: contradiction
    have hN : r.input_N = rightBound := by
      have := h_rb; simp [symbol.nonterminal.injEq] at this; exact this
    exact absurd (no_rightBound_on_encodeTwoTrack M tc r hr hN u v heq) id

/-
Invariant preserved from cleanup state.
-/
theorem GI_preserved_cleanup (M : Turing.TM0.Machine (Option T) Λ)
    (sf sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (w : List T)
    (hhalt : (Turing.TM0.eval M (w.map Option.some)).Dom)
    (hcontent : terminalContent sf = w)
    (hhas_nt : ∃ s, s ∈ sf ∧ isNonterminal s)
    (hno_start : ∀ s ∈ sf, s ≠ symbol.nonterminal start)
    (hno_genMore : ∀ s ∈ sf, s ≠ symbol.nonterminal genMore)
    (hno_headCell : ∀ s ∈ sf, ∀ q orig cur,
      s ≠ symbol.nonterminal (headCell q orig cur))
    (htrans : grammar_transforms (tmToGrammar T Λ M) sf sf') :
    GI M sf' := by
  obtain ⟨ r, hr ⟩ := htrans;
  -- Since $r$ is in the rules of $tmToGrammar T Λ M$, it must be one of the rules in the grammar.
  obtain ⟨hr₁, u, v, hu, hv⟩ := hr
  have hr₂ : r ∈ (tmToGrammar T Λ M).rules := by
    exact hr₁
  have hr₃ : r ∈ (generationRules T Λ M) ∨ r ∈ (simulationRules T Λ M) ∨ r ∈ (cleanupRules T Λ M) := by
    exact by rw [ show ( tmToGrammar T Λ M ).rules = ( generationRules T Λ M ) ++ ( simulationRules T Λ M ) ++ ( cleanupRules T Λ M ) by rfl ] at hr₂; aesop;
  rcases hr₃ with (hr₃ | hr₃ | hr₃);
  · unfold generationRules at hr₃; simp_all +decide ;
    grind +ring;
  · unfold simulationRules at hr₃;
    rw [ List.mem_flatMap ] at hr₃;
    rcases hr₃ with ⟨ q, hq, hr₃ ⟩ ; rw [ List.mem_flatMap ] at hr₃ ; rcases hr₃ with ⟨ γ, hγ, hr₃ ⟩ ; rcases h : M q γ with ( _ | ⟨ q', _ | _ ⟩ ) <;> simp_all +decide [ List.mem_map ] ;
    · cases ‹Dir› <;> simp_all +decide [ List.mem_flatMap, List.mem_map ];
      · grind;
      · grind +ring;
    · grind;
  · -- Since $r$ is in the cleanupRules, we know that $r.input_N$ is a nonterminal that is not start, genMore, or headCell.
    have hr₄ : r.input_N ≠ start ∧ r.input_N ≠ genMore ∧ ∀ q orig cur, r.input_N ≠ headCell q orig cur := by
      grind +ring;
    -- Since $r$ is in the cleanupRules, we know that $r.output_string$ does not contain any start, genMore, or headCell nonterminals.
    have hr₅ : ∀ s ∈ r.output_string, s ≠ symbol.nonterminal start ∧ s ≠ symbol.nonterminal genMore ∧ ∀ q orig cur, s ≠ symbol.nonterminal (headCell q orig cur) := by
      unfold cleanupRules at hr₃; simp +decide at hr₃;
      rcases hr₃ with ( ⟨ a, ha, b, hb, hr₃ ⟩ | ⟨ a, ha, b, hb, c, hc, hr₃ ⟩ | ⟨ a, ha, b, hb, c, hc, hr₃ ⟩ | ⟨ a, hr₃ ⟩ | hr₃ | hr₃ | ⟨ a, ha, hr₃ ⟩ | ⟨ a, ha, hr₃ ⟩ ) <;> simp +decide [ hr₃ ] at hr₂ ⊢;
      all_goals subst_vars; simp +decide [ TMtoGrammarNT.haltCell ] at hr₄ ⊢;
      cases h : M a b <;> simp +decide [ h ] at hr₃ ⊢;
      grind +ring;
    by_cases h : ∃ s ∈ u ++ r.output_string ++ v, isNonterminal s <;> simp_all +decide [ GI ];
    · apply GI.cleanup;
      exact hhalt;
      · rw [ ← hcontent, terminalContent_append, terminalContent_append ];
        rw [ ← terminalContent_append, ← terminalContent_append ];
        apply terminalContent_preserved;
        any_goals assumption;
        · exact ⟨ r, hr₂, u, v, by aesop ⟩;
        · grind +ring;
        · grind +ring;
      · exact ⟨ h.choose, by simpa using h.choose_spec.1, h.choose_spec.2 ⟩;
      · grind +ring;
      · grind +ring;
      · grind +splitIndPred;
    · convert GI.done w hhalt using 1;
      have h_terminalContent : terminalContent (u ++ (r.output_string ++ v)) = w := by
        have h_terminalContent : terminalContent (u ++ (r.output_string ++ v)) = terminalContent (u ++ (r.input_L ++ symbol.nonterminal r.input_N :: (r.input_R ++ v))) := by
          apply terminalContent_preserved;
          any_goals assumption;
          · exact ⟨ r, hr₂, u, v, by simp +decide [ List.append_assoc ] ⟩;
          · grind +ring;
          · grind;
        exact h_terminalContent.trans hcontent;
      have h_terminalContent : ∀ s ∈ u ++ (r.output_string ++ v), ∃ t : T, s = symbol.terminal t := by
        intro s hs; specialize h s; rcases s with ( _ | _ ) <;> simp_all +decide ;
        grind +locals;
      have h_terminalContent : ∀ {l : List (symbol T (TMtoGrammarNT T Λ))}, (∀ s ∈ l, ∃ t : T, s = symbol.terminal t) → l = List.map symbol.terminal (terminalContent l) := by
        intros l hl; induction' l with s l ih <;> simp +decide [ *, terminalContent ] ;
        rcases hl s ( by simp +decide ) with ⟨ t, rfl ⟩ ; simp +decide [ symbolOriginal ] ; exact ih fun s hs => hl s ( by simp +decide [ hs ] ) ;
      grind

/-- Invariant preserved from done state (vacuously true). -/
theorem GI_preserved_done (M : Turing.TM0.Machine (Option T) Λ)
    (w : List T)
    (hhalt : (Turing.TM0.eval M (w.map Option.some)).Dom)
    (sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (htrans : grammar_transforms (tmToGrammar T Λ M) (w.map symbol.terminal) sf') :
    GI M sf' := by
  exfalso
  exact no_transform_terminal (tmToGrammar T Λ M) w sf' htrans

/-- The invariant is preserved by grammar transforms. -/
theorem GI_preserved (M : Turing.TM0.Machine (Option T) Λ)
    (sf sf' : List (symbol T (TMtoGrammarNT T Λ)))
    (hinv : GI M sf) (htrans : grammar_transforms (tmToGrammar T Λ M) sf sf') :
    GI M sf' := by
  cases hinv with
  | initial => exact GI_preserved_initial M sf' htrans
  | generating ts => exact GI_preserved_generating M ts sf' htrans
  | simulating tc tmCfg hcorr hreach =>
    exact GI_preserved_simulating M tc tmCfg hcorr hreach sf' htrans
  | cleanup _ w hhalt hcontent hhas_nt hns hng hhc =>
    exact GI_preserved_cleanup M _ sf' w hhalt hcontent hhas_nt hns hng hhc htrans
  | done w hhalt => exact GI_preserved_done M w hhalt sf' htrans

/-- Every reachable form satisfies the invariant. -/
theorem GI_reachable (M : Turing.TM0.Machine (Option T) Λ)
    (sf : List (symbol T (TMtoGrammarNT T Λ)))
    (h : grammar_derives (tmToGrammar T Λ M) [symbol.nonterminal start] sf) :
    GI M sf := by
  induction h with
  | refl => exact GI.initial
  | tail _ htrans ih => exact GI_preserved M _ _ ih htrans

/-! ### Main soundness theorem -/

/-- **Soundness**: If the grammar generates `w`, then TM halts on `w`. -/
theorem tmToGrammar_halts_of_generates
    (M : Turing.TM0.Machine (Option T) Λ) (w : List T)
    (h : grammar_generates (tmToGrammar T Λ M) w) :
    (Turing.TM0.eval M (w.map Option.some)).Dom :=
  GI_terminal_halts M w (GI_reachable M _ h)

/-- The grammar constructed from a TM generates exactly the TM's language. -/
theorem tmToGrammar_correct (M : Turing.TM0.Machine (Option T) Λ) (w : List T) :
    w ∈ grammar_language (tmToGrammar T Λ M) ↔
      (Turing.TM0.eval M (w.map Option.some)).Dom :=
  ⟨tmToGrammar_halts_of_generates M w, tmToGrammar_generates_of_halts M w⟩
