module

/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import Langlib.Classes.ContextFree.Examples.AnBn
public import Langlib.Grammars.LR.Definition
import Mathlib

@[expose]
public section

/-! # `a^n b^n` as an LR Language

This file proves that the context-free grammar `cfg_anbn` for `{a^n b^n}` is
LR(0), and hence that the language is LR.

## Main results

- `cfg_anbn_isLRk_zero` — the grammar `cfg_anbn` is LR(0)
- `anbn_is_LRk_zero` — `{a^n b^n}` is generated by an LR(0) grammar
- `anbn_is_LR` — `{a^n b^n}` is an LR language
-/

open CF_grammar List

/-! ### Rightmost sentential forms of `cfg_anbn`

The grammar `cfg_anbn` has rules `S → aSb` and `S → ε` with a single
nonterminal `()`. Every sentential form has at most one nonterminal,
so every derivation step is automatically rightmost. The reachable
rightmost forms are exactly `aⁿ S bⁿ` and `aⁿ bⁿ`.
-/

/-- Rightmost sentential form predicate for `cfg_anbn`: either `aⁿ S bⁿ` or `aⁿ bⁿ`. -/
private def anbn_rm_form (w : List (symbol Bool Unit)) : Prop :=
  (∃ n : ℕ, w = (replicate n false).map symbol.terminal ++
    [symbol.nonterminal ()] ++
    (replicate n true).map symbol.terminal) ∨
  (∃ n : ℕ, w = (replicate n false ++ replicate n true).map symbol.terminal)

/-- The initial sentential form `[S]` is a rightmost form (n = 0). -/
private lemma anbn_rm_form_initial :
    anbn_rm_form [symbol.nonterminal ()] := by
  left; exact ⟨0, by simp⟩

private lemma anbn_rm_form_step {u v : List (symbol Bool Unit)}
    (hu : anbn_rm_form u) (hstep : cfg_anbn.ProducesRightmost u v) :
    anbn_rm_form v := by
      rcases hu with ( ⟨ n, rfl ⟩ | ⟨ n, rfl ⟩ );
      · rcases hstep with ⟨ r, hr, p, lookahead, hp, hv ⟩ ; simp_all +decide [ cfg_anbn ] ;
        rcases hr with ( rfl | rfl ) <;> simp +decide [ List.append_eq_append_iff ] at hp ⊢;
        · rcases hp with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h₁, h₂ ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
          · cases as <;> simp_all +decide [ anbn_rm_form ];
            · left; use n + 1; simp_all +decide [ List.replicate ] ;
              exact Nat.recOn n ( by simp +decide ) fun n ihn => by simp +decide [ List.replicate ] at ihn ⊢ ; aesop;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ b, bs ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
            · refine' Or.inl ⟨ n + 1, _ ⟩ ; simp +decide [ ← h₁, List.replicate_add ];
              exact Nat.recOn n rfl fun n ih => by simp +decide [ List.replicate ] at * ; aesop;
            · replace h₂ := congr_arg List.toFinset h₂.2; rw [ Finset.ext_iff ] at h₂; specialize h₂ ( symbol.nonterminal () ) ; aesop;
        · rcases hp with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h, h' ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
          · rcases as with ( _ | ⟨ a, as ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
            · exact Or.inr ⟨ n, by aesop ⟩;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ b, bs ⟩ ) <;> simp_all +decide [ List.append_eq_append_iff ];
            · exact Or.inr ⟨ n, by aesop ⟩;
            · replace h' := congr_arg List.toFinset h'.2; rw [ Finset.ext_iff ] at h'; specialize h' ( symbol.nonterminal () ) ; aesop;
      · rcases hstep with ⟨ r, hr, p, lookahead, hp, hv ⟩;
        replace hp := congr_arg List.toFinset hp; rw [ Finset.ext_iff ] at hp; specialize hp ( symbol.nonterminal r.1 ) ; aesop;

/-- Every rightmost derivation from `[S]` produces a rightmost form. -/
private lemma anbn_rm_form_of_derivesRightmost {w : List (symbol Bool Unit)}
    (h : cfg_anbn.DerivesRightmost [symbol.nonterminal ()] w) :
    anbn_rm_form w := by
  induction h with
  | refl => exact anbn_rm_form_initial
  | tail _ hstep ih => exact anbn_rm_form_step ih hstep

private lemma anbn_rm_config {p : List (symbol Bool Unit)} {s : List Bool}
    (h : cfg_anbn.DerivesRightmost [symbol.nonterminal cfg_anbn.initial]
      (p ++ [symbol.nonterminal ()] ++ s.map symbol.terminal)) :
    ∃ n : ℕ, p = (replicate n false).map symbol.terminal ∧
              s = replicate n true := by
                have := anbn_rm_form_of_derivesRightmost h;
                rcases this with ( ⟨ n, hn ⟩ | ⟨ n, hn ⟩ ) <;> simp_all +decide [ List.append_assoc ];
                · have := congr_arg List.reverse hn; norm_num [ List.reverse_append ] at this;
                  replace this := congr_arg ( fun x => x.takeWhile ( fun y => y ≠ symbol.nonterminal () ) ) this ; simp_all +decide [ List.takeWhile_append ];
                  split_ifs at this <;> simp_all +decide [ List.takeWhile_eq_self_iff ];
                  · replace this := congr_arg List.reverse this ; simp_all +decide [ List.reverse_replicate ];
                    exact List.map_injective_iff.mpr ( by aesop_cat ) ( this.trans ( by aesop_cat ) );
                  · replace this := congr_arg List.length this ; simp_all +decide [ List.length_replicate ];
                    rw [ List.takeWhile_eq_self_iff.mpr ] at this <;> aesop;
                · replace hn := congr_arg ( fun x => x.count ( symbol.nonterminal () ) ) hn ; simp_all +decide [ List.count_replicate ] ;

/-- The grammar `cfg_anbn` is LR(0). -/
public theorem cfg_anbn_isLRk_zero : cfg_anbn.IsLRk 0 := by
  intro r₁ r₂ hr₁ hr₂ p₁ p₂ core s₁ s₂ h₁ h₂ h₃ h₄ h₅; cases h₅;
  cases' anbn_rm_config h₁ with n₁ hn₁ ; cases' anbn_rm_config h₂ with n₂ hn₂ ; simp_all +decide [ cfg_anbn ];
  cases hr₁ <;> cases hr₂ <;> simp_all +decide [ cfg_anbn ];
  · replace h₃ := congr_arg List.length h₃ ; replace h₄ := congr_arg List.length h₄ ; simp_all +decide;
    lia;
  · replace h₄ := congr_arg List.reverse h₄ ; simp_all +decide [ List.reverse_append ];
    replace h₄ := congr_arg List.toFinset h₄ ; simp_all +decide [ Finset.ext_iff ];
    specialize h₄ ( symbol.nonterminal () ) ; aesop;
  · replace h₄ := congr_arg List.reverse h₄ ; simp_all +decide [ List.reverse_append ];
    replace h₄ := congr_arg List.toFinset h₄ ; simp_all +decide [ Finset.ext_iff ];
    specialize h₄ ( symbol.nonterminal () ) ; aesop;
  · replace h₃ := congr_arg List.length h₃ ; replace h₄ := congr_arg List.length h₄ ; aesop

/-- The language `{aⁿbⁿ}` is generated by an LR(0) grammar. -/
public theorem anbn_is_LRk_zero : is_LRk 0 anbn :=
  ⟨cfg_anbn, cfg_anbn_isLRk_zero, CF_language_cfg_anbn⟩

/-- The language `{aⁿbⁿ}` is an LR language. -/
public theorem anbn_is_LR : is_LR anbn :=
  is_LR_of_is_LRk anbn_is_LRk_zero
