module

/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import Langlib.Classes.ContextFree.Examples.AnBn
public import Langlib.Grammars.LR.Definition
import Mathlib

@[expose]
public section

/-! # `a^n b^n` as an LR Language

This file proves that the context-free grammar `cfg_anbn` for `{a^n b^n}` is
LR(1), and hence that the language is LR.

## Main results

- `cfg_anbn_isLRk_one` — the grammar `cfg_anbn` is LR(1)
- `anbn_is_LRk_one` — `{a^n b^n}` is generated by an LR(1) grammar
- `anbn_is_LR` — `{a^n b^n}` is an LR language
-/

open CF_grammar List

/-! ### Rightmost sentential forms of `cfg_anbn`

The grammar `cfg_anbn` has rules `S → aSb` and `S → ε` with a single
nonterminal `()`. Every sentential form has at most one nonterminal,
so every derivation step is automatically rightmost. The reachable
rightmost forms are exactly `aⁿ S bⁿ` and `aⁿ bⁿ`.
-/

/-- Rightmost sentential form predicate for `cfg_anbn`: either `aⁿ S bⁿ` or `aⁿ bⁿ`. -/
private def anbn_rm_form (w : List (symbol Bool Unit)) : Prop :=
  (∃ n : ℕ, w = (replicate n false).map symbol.terminal ++
    [symbol.nonterminal ()] ++
    (replicate n true).map symbol.terminal) ∨
  (∃ n : ℕ, w = (replicate n false ++ replicate n true).map symbol.terminal)

/-- The initial sentential form `[S]` is a rightmost form (n = 0). -/
private lemma anbn_rm_form_initial :
    anbn_rm_form [symbol.nonterminal ()] := by
  left; exact ⟨0, by simp⟩

private lemma anbn_rm_form_step {u v : List (symbol Bool Unit)}
    (hu : anbn_rm_form u) (hstep : cfg_anbn.ProducesRightmost u v) :
    anbn_rm_form v := by
      rcases hu with ( ⟨ n, rfl ⟩ | ⟨ n, rfl ⟩ );
      · rcases hstep with ⟨ r, hr, p, lookahead, hp, hv ⟩ ; simp_all +decide [ cfg_anbn ] ;
        rcases hr with ( rfl | rfl ) <;> simp +decide [ List.append_eq_append_iff ] at hp ⊢;
        · rcases hp with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h₁, h₂ ⟩ ) <;> simp_all +decide [  ];
          · cases as <;> simp_all +decide [ anbn_rm_form ];
            · left; use n + 1; simp_all +decide [ List.replicate ] ;
              exact Nat.recOn n ( by simp +decide ) fun n ihn => by simp +decide [ List.replicate ] at ihn ⊢ ; aesop;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ b, bs ⟩ ) <;> simp_all +decide [  ];
            · refine' Or.inl ⟨ n + 1, _ ⟩ ; simp +decide [ ← h₁, List.replicate_add ];
              exact Nat.recOn n rfl fun n ih => by simp +decide [ List.replicate ] at * ; aesop;
            · replace h₂ := congr_arg List.toFinset h₂.2; rw [ Finset.ext_iff ] at h₂; specialize h₂ ( symbol.nonterminal () ) ; aesop;
        · rcases hp with ( ⟨ as, rfl, h ⟩ | ⟨ bs, h, h' ⟩ ) <;> simp_all +decide [  ];
          · rcases as with ( _ | ⟨ a, as ⟩ ) <;> simp_all +decide [  ];
            · exact Or.inr ⟨ n, by aesop ⟩;
            · replace h := congr_arg List.toFinset h.2; rw [ Finset.ext_iff ] at h; specialize h ( symbol.nonterminal () ) ; aesop;
          · rcases bs with ( _ | ⟨ b, bs ⟩ ) <;> simp_all +decide [  ];
            · exact Or.inr ⟨ n, by aesop ⟩;
            · replace h' := congr_arg List.toFinset h'.2; rw [ Finset.ext_iff ] at h'; specialize h' ( symbol.nonterminal () ) ; aesop;
      · rcases hstep with ⟨ r, hr, p, lookahead, hp, hv ⟩;
        replace hp := congr_arg List.toFinset hp; rw [ Finset.ext_iff ] at hp; specialize hp ( symbol.nonterminal r.1 ) ; aesop;

/-- Every rightmost derivation from `[S]` produces a rightmost form. -/
private lemma anbn_rm_form_of_derivesRightmost {w : List (symbol Bool Unit)}
    (h : cfg_anbn.DerivesRightmost [symbol.nonterminal ()] w) :
    anbn_rm_form w := by
  induction h with
  | refl => exact anbn_rm_form_initial
  | tail _ hstep ih => exact anbn_rm_form_step ih hstep

private lemma anbn_rm_config {p : List (symbol Bool Unit)} {s : List Bool}
    (h : cfg_anbn.DerivesRightmost [symbol.nonterminal cfg_anbn.initial]
      (p ++ [symbol.nonterminal ()] ++ s.map symbol.terminal)) :
    ∃ n : ℕ, p = (replicate n false).map symbol.terminal ∧
              s = replicate n true := by
                have := anbn_rm_form_of_derivesRightmost h;
                rcases this with ( ⟨ n, hn ⟩ | ⟨ n, hn ⟩ ) <;> simp_all +decide [ List.append_assoc ];
                · have := congr_arg List.reverse hn; norm_num [ List.reverse_append ] at this;
                  replace this := congr_arg ( fun x => x.takeWhile ( fun y => y ≠ symbol.nonterminal () ) ) this ; simp_all +decide [ List.takeWhile_append ];
                  split_ifs at this <;> simp_all +decide [  ];
                  · replace this := congr_arg List.reverse this ; simp_all +decide [ List.reverse_replicate ];
                    exact List.map_injective_iff.mpr ( by aesop_cat ) ( this.trans ( by aesop_cat ) );
                  · replace this := congr_arg List.length this ; simp_all +decide [ List.length_replicate ];
                    rw [ List.takeWhile_eq_self_iff.mpr ] at this <;> aesop;
                · replace hn := congr_arg ( fun x => x.count ( symbol.nonterminal () ) ) hn ; simp_all +decide [ List.count_replicate ] ;

/-- Projecting an augmented prefix to terminals reflects that the original
prefix already consisted of exactly those terminals. -/
private lemma projectAugmentString_eq_map_terminal
    {p : List (symbol Bool (Option Unit))} {w : List Bool}
    (h : cfg_anbn.projectAugmentString p = w.map symbol.terminal) :
    p = w.map symbol.terminal := by
  induction p generalizing w with
  | nil =>
      simp [CF_grammar.projectAugmentString] at h ⊢
      exact h
  | cons a p ih =>
      cases w with
      | nil => simp [CF_grammar.projectAugmentString] at h
      | cons b w =>
          cases a with
          | terminal a =>
              simp only [CF_grammar.projectAugmentString, List.map_cons,
                CF_grammar.projectAugmentSymbol, symbol.terminal.injEq,
                List.cons.injEq] at h ⊢
              exact ⟨h.1, ih h.2⟩
          | nonterminal A =>
              cases A <;> simp [CF_grammar.projectAugmentString,
                CF_grammar.projectAugmentSymbol] at h

private abbrev anbnFresh : symbol Bool (Option Unit) :=
  symbol.nonterminal none

/-- The first augmented step consumes the fresh start nonterminal. -/
private lemma anbn_first_step_no_fresh
    {v : List (symbol Bool (Option Unit))}
    (h : cfg_anbn.augment.ProducesRightmost [anbnFresh] v) :
    anbnFresh ∉ v := by
  rcases h with ⟨r, hr, p, s, hu, hv⟩
  simp [CF_grammar.augment, CF_grammar.augmentStartRule,
    CF_grammar.augmentRule, cfg_anbn] at hr
  rcases hr with rfl | rfl | rfl
  · have hl := congrArg List.length hu
    simp at hl
    have hp : p = [] := List.eq_nil_of_length_eq_zero (by omega)
    subst p
    simp at hu
    subst s
    simp [hv, anbnFresh]
  · have hl := congrArg List.length hu
    simp at hl
    have hp : p = [] := List.eq_nil_of_length_eq_zero (by omega)
    subst p
    simp at hu
  · have hl := congrArg List.length hu
    simp at hl
    have hp : p = [] := List.eq_nil_of_length_eq_zero (by omega)
    subst p
    simp at hu

/-- Once the fresh start has been consumed, no augmented rule can reintroduce it. -/
private lemma anbn_step_no_fresh
    {u v : List (symbol Bool (Option Unit))} (hu : anbnFresh ∉ u)
    (h : cfg_anbn.augment.ProducesRightmost u v) : anbnFresh ∉ v := by
  rcases h with ⟨r, hr, p, s, hsrc, hv⟩
  simp [CF_grammar.augment, CF_grammar.augmentStartRule,
    CF_grammar.augmentRule, cfg_anbn] at hr
  rcases hr with rfl | rfl | rfl
  · exfalso
    apply hu
    rw [hsrc]
    simp [anbnFresh]
  · intro hf
    rw [hv] at hf
    simp [anbnFresh] at hf
    apply hu
    rw [hsrc]
    simp [anbnFresh, hf]
  · intro hf
    rw [hv] at hf
    simp [anbnFresh] at hf
    apply hu
    rw [hsrc]
    simp [anbnFresh, hf]

/-- A reachable augmented form is either the untouched fresh start or contains
no occurrence of it. -/
private lemma anbn_reachable_fresh_cases
    {v : List (symbol Bool (Option Unit))}
    (h : cfg_anbn.augment.DerivesRightmost [anbnFresh] v) :
    v = [anbnFresh] ∨ anbnFresh ∉ v := by
  induction h with
  | refl => exact Or.inl rfl
  | tail _ hstep ih =>
      right
      rcases ih with rfl | hn
      · exact anbn_first_step_no_fresh hstep
      · exact anbn_step_no_fresh hn hstep

/-- A reachable handle headed by the fresh start is the initial configuration. -/
private lemma anbn_fresh_config
    {p : List (symbol Bool (Option Unit))} {s : List Bool}
    (h : cfg_anbn.augment.DerivesRightmost [anbnFresh]
      (p ++ [anbnFresh] ++ s.map symbol.terminal)) :
    p = [] ∧ s = [] := by
  rcases anbn_reachable_fresh_cases h with heq | hn
  · have hl := congrArg List.length heq
    simp at hl
    have hp : p = [] := List.eq_nil_of_length_eq_zero (by omega)
    subst p
    simp at heq
    exact ⟨rfl, heq⟩
  · exfalso
    apply hn
    simp [anbnFresh]

/-- Projecting an augmented original-start configuration recovers the existing
rightmost-form classification for `cfg_anbn`. -/
private lemma anbn_augmented_config
    {p : List (symbol Bool (Option Unit))} {s : List Bool}
    (h : cfg_anbn.augment.DerivesRightmost [anbnFresh]
      (p ++ [symbol.nonterminal (some ())] ++ s.map symbol.terminal)) :
    ∃ n : ℕ, p = (replicate n false).map symbol.terminal ∧
      s = replicate n true := by
  have hproject := cfg_anbn.derivesRightmost_project_augment h
  have hproject' :
      cfg_anbn.DerivesRightmost [symbol.nonterminal cfg_anbn.initial]
        (cfg_anbn.projectAugmentString p ++ [symbol.nonterminal ()] ++
          s.map symbol.terminal) := by
    simpa [anbnFresh, CF_grammar.projectAugmentString,
      CF_grammar.projectAugmentSymbol, List.map_append] using hproject
  obtain ⟨n, hp, hs⟩ := anbn_rm_config hproject'
  exact ⟨n, projectAugmentString_eq_map_terminal hp, hs⟩

/-- One-symbol lookahead makes the boundary between the false and true blocks unique. -/
private lemma anbn_boundary_unique {n m : ℕ} {y : List Bool}
    (hform : replicate m false ++ replicate m true = replicate n false ++ y)
    (hlook : (replicate n true).take 1 = y.take 1) : n = m := by
  cases n with
  | zero =>
      simp only [replicate_zero, nil_append, take_nil] at hform hlook
      have hy : y = [] := by
        cases y with
        | nil => rfl
        | cons a y => simp at hlook
      rw [hy] at hform
      have hlen := congrArg List.length hform
      simp at hlen
      omega
  | succ n =>
      have hy : ∃ y', y = true :: y' := by
        cases y with
        | nil => simp [replicate_succ] at hlook
        | cons a y' =>
            have ha : a = true := by simpa [replicate_succ] using hlook.symm
            exact ⟨y', by rw [ha]⟩
      rcases hy with ⟨y', hy⟩
      rw [hy] at hform
      have hprefix := congrArg (List.takeWhile (fun b => b = false)) hform
      simp [replicate_succ] at hprefix
      have hlen := congrArg List.length hprefix
      simp at hlen
      omega

/-- A recursive handle's unique nonterminal determines its prefix length. -/
private lemma anbn_recursive_prefix_unique {n m : ℕ} {y : List Bool}
    (hform :
      (replicate m false).map (symbol.terminal (N := Option Unit)) ++
          [symbol.terminal false, symbol.nonterminal (some ()), symbol.terminal true] ++
          (replicate m true).map symbol.terminal =
      (replicate n false).map symbol.terminal ++
          [symbol.terminal false, symbol.nonterminal (some ()), symbol.terminal true] ++
          y.map symbol.terminal) : n = m := by
  have hprefix := congrArg
    (List.takeWhile (fun z => z ≠ symbol.nonterminal (some ()))) hform
  simp at hprefix
  omega

/-- The grammar `cfg_anbn` is LR(1). -/
public theorem cfg_anbn_isLRk_one : cfg_anbn.IsLRk 1 := by
  change cfg_anbn.augment.CoreIsLRk 1
  intro r₁ r₂ hr₁ hr₂ p₁ p₂ s₁ s₂ y hd₁ hd₂ hform hlook
  simp [CF_grammar.augment, CF_grammar.augmentStartRule,
    CF_grammar.augmentRule, cfg_anbn] at hr₁ hr₂
  rcases hr₁ with rfl | rfl | rfl <;> rcases hr₂ with rfl | rfl | rfl
  · obtain ⟨rfl, rfl⟩ := anbn_fresh_config hd₁
    obtain ⟨rfl, rfl⟩ := anbn_fresh_config hd₂
    exact ⟨rfl, rfl⟩
  · obtain ⟨rfl, rfl⟩ := anbn_fresh_config hd₁
    obtain ⟨n₂, rfl, rfl⟩ := anbn_augmented_config hd₂
    simp only [List.nil_append] at hform
    cases n₂ <;> simp [replicate_succ] at hform
  · obtain ⟨rfl, rfl⟩ := anbn_fresh_config hd₁
    obtain ⟨n₂, rfl, rfl⟩ := anbn_augmented_config hd₂
    simp only [List.nil_append, List.append_nil] at hform
    cases n₂ <;> simp [replicate_succ] at hform
  · obtain ⟨n₁, rfl, rfl⟩ := anbn_augmented_config hd₁
    obtain ⟨rfl, rfl⟩ := anbn_fresh_config hd₂
    simp only [List.nil_append] at hform
    cases n₁ <;> simp [replicate_succ] at hform
  · obtain ⟨n₁, rfl, rfl⟩ := anbn_augmented_config hd₁
    obtain ⟨n₂, rfl, rfl⟩ := anbn_augmented_config hd₂
    have hn := anbn_recursive_prefix_unique hform
    subst n₂
    exact ⟨rfl, rfl⟩
  · obtain ⟨n₁, rfl, rfl⟩ := anbn_augmented_config hd₁
    obtain ⟨n₂, rfl, rfl⟩ := anbn_augmented_config hd₂
    have hmem : symbol.nonterminal (some ()) ∈
        (replicate n₁ false).map (symbol.terminal (N := Option Unit)) ++
          [symbol.terminal false, symbol.nonterminal (some ()), symbol.terminal true] ++
          y.map symbol.terminal := by simp
    rw [← hform] at hmem
    simp at hmem
  · obtain ⟨n₁, rfl, rfl⟩ := anbn_augmented_config hd₁
    obtain ⟨rfl, rfl⟩ := anbn_fresh_config hd₂
    simp only [List.nil_append, List.append_nil] at hform
    have hmem :
        (symbol.nonterminal (T := Bool) (some ()) : symbol Bool (Option Unit)) ∈
          [symbol.nonterminal (some ())] := by simp
    have hform' :
        ([symbol.nonterminal (some ())] : List (symbol Bool (Option Unit))) =
          (replicate n₁ false).map symbol.terminal ++ y.map symbol.terminal := by
      simpa using hform
    rw [hform'] at hmem
    simp at hmem
  · obtain ⟨n₁, rfl, rfl⟩ := anbn_augmented_config hd₁
    obtain ⟨n₂, rfl, rfl⟩ := anbn_augmented_config hd₂
    have hmem : symbol.nonterminal (some ()) ∈
        (replicate n₂ false).map (symbol.terminal (N := Option Unit)) ++
          [symbol.terminal false, symbol.nonterminal (some ()), symbol.terminal true] ++
          (replicate n₂ true).map symbol.terminal := by simp
    rw [hform] at hmem
    simp at hmem
  · obtain ⟨n₁, rfl, rfl⟩ := anbn_augmented_config hd₁
    obtain ⟨n₂, rfl, rfl⟩ := anbn_augmented_config hd₂
    have hwords : replicate n₂ false ++ replicate n₂ true =
        replicate n₁ false ++ y := by
      have hmap :
          (replicate n₂ false ++ replicate n₂ true).map
              (symbol.terminal (N := Option Unit)) =
            (replicate n₁ false ++ y).map symbol.terminal := by
        simpa [List.map_append] using hform
      exact List.map_injective_iff.mpr (by aesop_cat) hmap
    have hn := anbn_boundary_unique hwords (by simpa [CF_grammar.lrLookahead] using hlook)
    subst n₂
    exact ⟨rfl, rfl⟩

/-- The language `{aⁿbⁿ}` is generated by an LR(1) grammar. -/
public theorem anbn_is_LRk_one : is_LRk 1 anbn :=
  ⟨cfg_anbn, cfg_anbn_isLRk_one, CF_language_cfg_anbn⟩

/-- The language `{aⁿbⁿ}` is an LR language. -/
public theorem anbn_is_LR : is_LR anbn :=
  is_LR_of_is_LRk anbn_is_LRk_one
