import Mathlib
import Langlib.Classes.ContextFree.Basics.Inclusion

/-! # Context-Free Grammars as Unrestricted Grammars

This file gives an alternative characterization of context-free grammars as
unrestricted grammars satisfying an additional structural property on their rules.

## Overview

A standard unrestricted grammar has rules of the form
  `input_L ++ [nonterminal input_N] ++ input_R → output_string`
where there are no restrictions on the relationship between the left- and right-hand sides.

A context-free grammar is one where each rule has no context: i.e., for every rule,
  `input_L = []` and `input_R = []`.
In other words, each rule rewrites a single nonterminal `A` to a string `γ`,
independently of the surrounding context.

This file defines this property as `grammar_context_free` on `grammar T`, defines
`is_CF_unrestricted` as the class of languages generated by such grammars, and proves
equivalence with the existing `is_CF` definition based on `CF_grammar`.

## Main declarations

- `grammar_context_free` — predicate on unrestricted grammars
- `is_CF_unrestricted` — language class induced by context-free unrestricted grammars
- `is_CF_iff_is_CF_unrestricted` — equivalence with the standard definition
-/

open List Relation

variable {T : Type}

/-! ## Definition -/

/-- An unrestricted grammar is *context-free* if for every rule, the left context
    `input_L` and the right context `input_R` are both empty. This means each rule
    rewrites a single nonterminal to a string, independently of the surrounding symbols. -/
def grammar_context_free (g : grammar T) : Prop :=
  ∀ r ∈ g.rules, r.input_L = [] ∧ r.input_R = []

/-- A language is generated by some context-free unrestricted grammar. -/
def is_CF_unrestricted (L : Language T) : Prop :=
  ∃ g : grammar T, grammar_context_free g ∧ grammar_language g = L

/-! ## Forward direction: CF_grammar → context-free unrestricted grammar -/

/-- The unrestricted grammar obtained from a context-free grammar (via `grammar_of_cfg`)
    satisfies the context-free property. -/
theorem grammar_of_cfg_context_free (g : CF_grammar T) :
    grammar_context_free (grammar_of_cfg g) := by
  intro r hr
  simp [grammar_of_cfg] at hr
  obtain ⟨_, _, _, rfl⟩ := hr
  exact ⟨rfl, rfl⟩

/-- Every context-free language is generated by a context-free unrestricted grammar. -/
theorem is_CF_implies_is_CF_unrestricted {L : Language T} (h : is_CF L) :
    is_CF_unrestricted L := by
  obtain ⟨g, rfl⟩ := h
  exact ⟨grammar_of_cfg g, grammar_of_cfg_context_free g,
    (CF_language_eq_grammar_language g).symm⟩

/-! ## Backward direction: context-free unrestricted grammar → CF_grammar -/

/-- Convert an unrestricted grammar rule (from a context-free unrestricted grammar)
    into a context-free rule (a pair of nonterminal and output string). -/
def cfrule_of_grule (r : grule T N) : N × List (symbol T N) :=
  (r.input_N, r.output_string)

/-- Construct a `CF_grammar` from a context-free unrestricted grammar. -/
def cfg_of_grammar (g : grammar T) (_hg : grammar_context_free g) :
    CF_grammar T where
  nt := g.nt
  initial := g.initial
  rules := g.rules.map cfrule_of_grule

/-
A single step in the constructed `CF_grammar` corresponds to a step in the original
    unrestricted grammar, and vice versa.
-/
lemma cfg_of_grammar_transforms_iff (g : grammar T) (hg : grammar_context_free g)
    (w₁ w₂ : List (symbol T g.nt)) :
    CF_transforms (cfg_of_grammar g hg) w₁ w₂ ↔ grammar_transforms g w₁ w₂ := by
  constructor;
  · rintro ⟨ r, u, v, hr, rfl, rfl ⟩;
    unfold cfg_of_grammar at hr;
    simp +zetaDelta at *;
    rcases hr with ⟨ a, ha, rfl ⟩ ; exact ⟨ a, ha, u, v, by have := hg a ha; aesop ⟩ ;
  · rintro ⟨ r, hr, u, v, rfl, rfl ⟩;
    use ( r.input_N, r.output_string );
    simp +zetaDelta at *;
    exact ⟨ List.mem_map.mpr ⟨ r, hr, rfl ⟩, u ++ r.input_L, r.input_R ++ v, by simp +decide [ hg r hr ], by simp +decide [ hg r hr ] ⟩

/-- The derivation relation of the constructed `CF_grammar` coincides with that of the
    original unrestricted grammar. -/
lemma cfg_of_grammar_derives_iff (g : grammar T) (hg : grammar_context_free g)
    (w₁ w₂ : List (symbol T g.nt)) :
    CF_derives (cfg_of_grammar g hg) w₁ w₂ ↔ grammar_derives g w₁ w₂ := by
  constructor
  · intro h
    induction h with
    | refl => exact grammar_deri_self
    | tail _ step ih =>
      exact grammar_deri_of_deri_tran ih ((cfg_of_grammar_transforms_iff g hg _ _).mp step)
  · intro h
    induction h with
    | refl => exact CF_deri_self
    | tail _ step ih =>
      exact CF_deri_of_deri_tran ih ((cfg_of_grammar_transforms_iff g hg _ _).mpr step)

/-- The language of the constructed `CF_grammar` equals that of the original grammar. -/
theorem cfg_of_grammar_language_eq (g : grammar T) (hg : grammar_context_free g) :
    CF_language (cfg_of_grammar g hg) = grammar_language g := by
  ext w
  simp only [CF_language, grammar_language, cfg_of_grammar]
  exact cfg_of_grammar_derives_iff g hg _ _

/-- Every language generated by a context-free unrestricted grammar is context-free. -/
theorem is_CF_unrestricted_implies_is_CF {L : Language T} (h : is_CF_unrestricted L) :
    is_CF L := by
  obtain ⟨g, hg, rfl⟩ := h
  exact ⟨cfg_of_grammar g hg, cfg_of_grammar_language_eq g hg⟩

/-! ## Equivalence -/

/-- A language is context-free if and only if it is generated by an unrestricted grammar
    satisfying the context-free property (empty left and right context in every rule). -/
theorem is_CF_iff_is_CF_unrestricted {L : Language T} :
    is_CF L ↔ is_CF_unrestricted L :=
  ⟨is_CF_implies_is_CF_unrestricted, is_CF_unrestricted_implies_is_CF⟩