import Mathlib
import Langlib.Grammars.ContextFree.Toolbox
import Langlib.Grammars.Unrestricted.Toolbox
import Langlib.Classes.ContextFree.Definition

/-! # Context-Free Grammars as Unrestricted Grammars

This file gives an alternative characterization of context-free grammars as
unrestricted grammars satisfying an additional structural property on their rules.

## Overview

A standard unrestricted grammar has rules of the form
  `input_L ++ [nonterminal input_N] ++ input_R → output_string`
where there are no restrictions on the relationship between the left- and right-hand sides.

A context-free grammar is one where each rule has no context: i.e., for every rule,
  `input_L = []` and `input_R = []`.
In other words, each rule rewrites a single nonterminal `A` to a string `γ`,
independently of the surrounding context.

This file proves that the unrestricted characterization agrees with the legacy
definition via `CF_grammar`.

## Main declarations

- `is_CF_via_cfg` — legacy language class induced by `CF_grammar`
- `is_CF_via_cfg_implies_is_CF` — conversion to the default unrestricted characterization
- `is_CF_implies_is_CF_via_cfg` — extraction of a legacy witness
- `is_CF_iff_is_CF_via_cfg` — equivalence of the two characterizations
-/

open List Relation

variable {T : Type}

/-! ## Forward direction: CF_grammar → context-free unrestricted grammar -/

/-- Convert a context-free grammar to the corresponding unrestricted grammar
with empty left and right contexts in every rule. -/
def grammar_of_cfg (g : CF_grammar T) : grammar T :=
  grammar.mk g.nt g.initial (List.map (fun r : g.nt × List (symbol T g.nt) =>
    grule.mk [] r.fst [] r.snd) g.rules)

lemma CF_language_eq_grammar_language (g : CF_grammar T) :
    CF_language g = grammar_language (grammar_of_cfg g) := by
  unfold CF_language
  unfold grammar_language
  ext1 w
  rw [Set.mem_setOf_eq]
  unfold grammar_generates
  constructor
  ·
    have indu :
        ∀ v : List (symbol T g.nt),
          CF_derives g [symbol.nonterminal g.initial] v →
            grammar_derives (grammar_of_cfg g) [symbol.nonterminal (grammar_of_cfg g).initial] v := by
      clear w
      intros v hypo
      induction hypo with
      | refl =>
          apply grammar_deri_self
      | tail _ step ih =>
          apply grammar_deri_of_deri_tran
          · exact ih
          unfold CF_transforms at step
          unfold grammar_transforms
          delta grammar_of_cfg
          dsimp only
          rcases step with ⟨r, u, w, rin, bef, aft⟩
          use grule.mk [] r.fst [] r.snd
          constructor
          ·
            rw [List.mem_map]
            exact ⟨r, rin, rfl⟩
          ·
            use u
            use w
            constructor
            · simpa [List.append_nil] using bef
            · simpa [List.append_nil] using aft
    exact indu (List.map symbol.terminal w)
  ·
    have indu :
        ∀ v : List (symbol T g.nt),
          grammar_derives (grammar_of_cfg g) [symbol.nonterminal (grammar_of_cfg g).initial] v →
            CF_derives g [symbol.nonterminal g.initial] v := by
      clear w
      intros v hypo
      induction hypo with
      | refl =>
          apply CF_deri_self
      | tail _ step ih =>
          apply CF_deri_of_deri_tran
          · exact ih
          unfold grammar_transforms at step
          unfold CF_transforms
          delta grammar_of_cfg at step
          dsimp only at step
          rcases step with ⟨r, rin, u, w, bef, aft⟩
          rcases (List.mem_map.1 rin) with ⟨r', new_rule_in, new_rule_def⟩
          rw [← new_rule_def] at bef aft
          refine ⟨r', u, w, new_rule_in, ?_, ?_⟩
          · simpa [List.append_nil] using bef
          · simpa [List.append_nil] using aft
    exact indu (List.map symbol.terminal w)

/-- The unrestricted grammar obtained from a context-free grammar (via `grammar_of_cfg`)
    satisfies the context-free property. -/
theorem grammar_of_cfg_context_free (g : CF_grammar T) :
    grammar_context_free (grammar_of_cfg g) := by
  intro r hr
  simp [grammar_of_cfg] at hr
  obtain ⟨_, _, _, rfl⟩ := hr
  exact ⟨rfl, rfl⟩

/-- Every language generated by a legacy context-free grammar satisfies the default
    unrestricted characterization. -/
theorem is_CF_via_cfg_implies_is_CF {L : Language T} (h : is_CF_via_cfg L) :
    is_CF L := by
  obtain ⟨g, rfl⟩ := h
  exact ⟨grammar_of_cfg g, grammar_of_cfg_context_free g,
    (CF_language_eq_grammar_language g).symm⟩

/-! ## Backward direction: context-free unrestricted grammar → CF_grammar -/

/-- Convert an unrestricted grammar rule (from a context-free unrestricted grammar)
    into a context-free rule (a pair of nonterminal and output string). -/
def cfrule_of_grule (r : grule T N) : N × List (symbol T N) :=
  (r.input_N, r.output_string)

/-- Construct a `CF_grammar` from a context-free unrestricted grammar. -/
def cfg_of_grammar (g : grammar T) (_hg : grammar_context_free g) :
    CF_grammar T where
  nt := g.nt
  initial := g.initial
  rules := g.rules.map cfrule_of_grule

/-
A single step in the constructed `CF_grammar` corresponds to a step in the original
    unrestricted grammar, and vice versa.
-/
lemma cfg_of_grammar_transforms_iff (g : grammar T) (hg : grammar_context_free g)
    (w₁ w₂ : List (symbol T g.nt)) :
    CF_transforms (cfg_of_grammar g hg) w₁ w₂ ↔ grammar_transforms g w₁ w₂ := by
  constructor;
  · rintro ⟨ r, u, v, hr, rfl, rfl ⟩;
    unfold cfg_of_grammar at hr;
    simp +zetaDelta at *;
    rcases hr with ⟨ a, ha, rfl ⟩ ; exact ⟨ a, ha, u, v, by have := hg a ha; aesop ⟩ ;
  · rintro ⟨ r, hr, u, v, rfl, rfl ⟩;
    use ( r.input_N, r.output_string );
    simp +zetaDelta at *;
    exact ⟨ List.mem_map.mpr ⟨ r, hr, rfl ⟩, u ++ r.input_L, r.input_R ++ v, by simp +decide [ hg r hr ], by simp +decide [ hg r hr ] ⟩

/-- The derivation relation of the constructed `CF_grammar` coincides with that of the
    original unrestricted grammar. -/
lemma cfg_of_grammar_derives_iff (g : grammar T) (hg : grammar_context_free g)
    (w₁ w₂ : List (symbol T g.nt)) :
    CF_derives (cfg_of_grammar g hg) w₁ w₂ ↔ grammar_derives g w₁ w₂ := by
  constructor
  · intro h
    induction h with
    | refl => exact grammar_deri_self
    | tail _ step ih =>
      exact grammar_deri_of_deri_tran ih ((cfg_of_grammar_transforms_iff g hg _ _).mp step)
  · intro h
    induction h with
    | refl => exact CF_deri_self
    | tail _ step ih =>
      exact CF_deri_of_deri_tran ih ((cfg_of_grammar_transforms_iff g hg _ _).mpr step)

/-- The language of the constructed `CF_grammar` equals that of the original grammar. -/
theorem cfg_of_grammar_language_eq (g : grammar T) (hg : grammar_context_free g) :
    CF_language (cfg_of_grammar g hg) = grammar_language g := by
  ext w
  simp only [CF_language, grammar_language, cfg_of_grammar]
  exact cfg_of_grammar_derives_iff g hg _ _

/-- Every language satisfying the default unrestricted characterization is generated by
    a legacy context-free grammar. -/
theorem is_CF_implies_is_CF_via_cfg {L : Language T} (h : is_CF L) :
    is_CF_via_cfg L := by
  obtain ⟨g, hg, rfl⟩ := h
  exact ⟨cfg_of_grammar g hg, cfg_of_grammar_language_eq g hg⟩

/-! ## Equivalence -/

/-- The default unrestricted characterization of context-freeness agrees with the legacy
    `CF_grammar` characterization. -/
theorem is_CF_iff_is_CF_via_cfg {L : Language T} :
    is_CF L ↔ is_CF_via_cfg L :=
  ⟨is_CF_implies_is_CF_via_cfg, is_CF_via_cfg_implies_is_CF⟩
