module

public import Langlib.Automata.LinearBounded.Cofunctional.Resources
public import Langlib.Automata.LinearBounded.FiniteReachabilityCounting
public import Mathlib.Data.Fintype.Sigma
public import Mathlib.Logic.Equiv.Fin.Basic
import Mathlib.Tactic

@[expose]
public section

/-!
# Linearly bounded nondeterministic choice

This file isolates a positive restricted frontier of the first LBA problem.  Suppose that every
accepted input has an accepting run taking only linearly many choices out of genuine branch
configurations.
Between two such configurations the run is deterministic, but it may still have exponential
length.

The finite-graph development below makes the required deterministic replay precise:

* a fixed finite type names the possible local moves;
* a branch event is charged only when a vertex has two **distinct** successors;
* deterministic stretches are traversed by a partial single-valued successor;
* every deterministic stretch can be abandoned after `Fintype.card V` steps;
* a bounded list of branch choices therefore determines a finite replay.

For an LBA on a tape of width `n + 1`, a branch schedule of length at most `(n + 1) * c` fits in
one same-width track with cell alphabet `Fin c → Option Move`.  The counter for one deterministic
stretch also fits in one same-width track, by the existing configuration-row capacity theorem.
Both alphabets are fixed once the machine and constant `c` are fixed.

The final result is an exact finite deterministic-search specification for machines satisfying
the semantic bounded-choice promise.  It is not a concrete `DLBA.Machine` compiler: the repository
still lacks reusable deterministic sweep microcode for reading the packed schedule, enumerating
it, and simulating one LBA move.
-/

open Classical Relation

/-! ## Finite choice graphs -/

/-- A directed graph whose local outgoing moves are named by a fixed choice alphabet. -/
public structure FiniteChoiceGraph (V Choice : Type*) where
  next : V → Choice → Option V

namespace FiniteChoiceGraph

variable {V Choice : Type*} (G : FiniteChoiceGraph V Choice)

/-- The directed edge relation generated by the named local choices. -/
public def Edge (old new : V) : Prop :=
  ∃ choice, G.next old choice = some new

/-- A genuine branch vertex has two distinct successor vertices.

Different choice names leading to the same successor do not count as nondeterminism. -/
public def Branching (vertex : V) : Prop :=
  ∃ left right, G.Edge vertex left ∧ G.Edge vertex right ∧ left ≠ right

/-- An edge leaving a nonbranching vertex. -/
public def DeterministicStep (old new : V) : Prop :=
  G.Edge old new ∧ ¬ G.Branching old

/-- The deterministic-step relation is single-valued. -/
public theorem deterministicStep_functional
    {old left right : V}
    (hleft : G.DeterministicStep old left)
    (hright : G.DeterministicStep old right) :
    left = right := by
  by_contra hne
  exact hleft.2 ⟨left, right, hleft.1, hright.1, hne⟩

/-- Choose the unique deterministic successor, when one exists. -/
public noncomputable def deterministicNext (vertex : V) : Option V := by
  exact if h : ∃ next, G.DeterministicStep vertex next
    then some (Classical.choose h)
    else none

/-- A chosen deterministic successor is a genuine deterministic edge. -/
public theorem deterministicStep_of_deterministicNext_eq_some
    {old new : V} (hnext : G.deterministicNext old = some new) :
    G.DeterministicStep old new := by
  simp only [deterministicNext] at hnext
  split at hnext
  · next h =>
      have hchosen : Classical.choose h = new := Option.some.inj hnext
      rw [← hchosen]
      exact Classical.choose_spec h
  · simp at hnext

/-- Every deterministic edge is the chosen deterministic successor. -/
public theorem deterministicNext_eq_some_of_deterministicStep
    {old new : V} (hstep : G.DeterministicStep old new) :
    G.deterministicNext old = some new := by
  simp only [deterministicNext]
  split
  · next h =>
      apply congrArg some
      exact G.deterministicStep_functional (Classical.choose_spec h) hstep
  · next h =>
      exact False.elim (h ⟨new, hstep⟩)

/-- Deterministic successor lookup is exactly the deterministic-step relation. -/
public theorem deterministicNext_eq_some_iff {old new : V} :
    G.deterministicNext old = some new ↔ G.DeterministicStep old new :=
  ⟨G.deterministicStep_of_deterministicNext_eq_some,
    G.deterministicNext_eq_some_of_deterministicStep⟩

/-- Follow the deterministic successor for an exact number of steps. -/
public noncomputable def follow
    (G : FiniteChoiceGraph V Choice) (source : V) : ℕ → Option V
  | 0 => some source
  | steps + 1 => (G.follow source steps).bind G.deterministicNext

@[simp]
public theorem follow_zero (source : V) :
    G.follow source 0 = some source := rfl

public theorem follow_succ (source : V) (steps : ℕ) :
    G.follow source (steps + 1) =
      (G.follow source steps).bind G.deterministicNext := rfl

/-- Successful deterministic traversal gives ordinary deterministic reachability. -/
public theorem deterministicReaches_of_follow_eq_some
    {source target : V} {steps : ℕ}
    (hfollow : G.follow source steps = some target) :
    ReflTransGen G.DeterministicStep source target := by
  induction steps generalizing target with
  | zero =>
      simp only [follow] at hfollow
      cases hfollow
      exact .refl
  | succ steps ih =>
      rw [G.follow_succ] at hfollow
      obtain ⟨previous, hprevious, hnext⟩ :=
        Option.bind_eq_some_iff.mp hfollow
      exact (ih hprevious).tail
        (G.deterministicStep_of_deterministicNext_eq_some hnext)

/-- A padded deterministic path can be replayed in no more steps than its padding bound. -/
public theorem exists_follow_of_paddedPath
    {source target : V} {fuel : ℕ}
    (hpath : FiniteReachabilityCounting.PaddedPath
      G.DeterministicStep source fuel target) :
    ∃ steps ≤ fuel, G.follow source steps = some target := by
  induction hpath with
  | zero =>
      exact ⟨0, Nat.zero_le 0, rfl⟩
  | @succ fuel old new hpath hmove ih =>
      obtain ⟨steps, hsteps, hfollow⟩ := ih
      rcases hmove with rfl | hstep
      · exact ⟨steps, hsteps.trans (Nat.le_succ fuel), hfollow⟩
      · refine ⟨steps + 1, Nat.succ_le_succ hsteps, ?_⟩
        rw [G.follow_succ, hfollow]
        simpa using G.deterministicNext_eq_some_of_deterministicStep hstep

variable [Fintype V] [DecidableEq V]

/-- Every reachable endpoint of a deterministic stretch occurs within one complete
configuration-space traversal.  This is the formal cycle cutoff used by replay. -/
public theorem deterministicReaches_iff_exists_follow_le_card
    (source target : V) :
    ReflTransGen G.DeterministicStep source target ↔
      ∃ steps ≤ Fintype.card V, G.follow source steps = some target := by
  letI : DecidableRel G.DeterministicStep := Classical.decRel _
  constructor
  · intro hreach
    have hmem :
        target ∈ FiniteReachabilityCounting.reached
          G.DeterministicStep source (Fintype.card V) :=
      (FiniteReachabilityCounting.mem_reached_card_iff
        (edge := G.DeterministicStep) (source := source)).2 hreach
    have hpath :
        FiniteReachabilityCounting.PaddedPath
          G.DeterministicStep source (Fintype.card V) target :=
      (FiniteReachabilityCounting.mem_reached_iff_paddedPath
        (edge := G.DeterministicStep) (source := source)).1 hmem
    exact G.exists_follow_of_paddedPath hpath
  · rintro ⟨steps, _, hfollow⟩
    exact G.deterministicReaches_of_follow_eq_some hfollow

/-- Searching every deterministic iterate through the configuration-space cardinality finds
every endpoint satisfying a chosen stopping predicate.  Its contrapositive is the cycle/dead-end
rule used by the deterministic simulator. -/
public theorem exists_deterministicReaches_iff_exists_follow_le_card
    (source : V) (stop : V → Prop) :
    (∃ target, ReflTransGen G.DeterministicStep source target ∧ stop target) ↔
      ∃ steps ≤ Fintype.card V, ∃ target,
        G.follow source steps = some target ∧ stop target := by
  constructor
  · rintro ⟨target, hreach, hstop⟩
    obtain ⟨steps, hsteps, hfollow⟩ :=
      (G.deterministicReaches_iff_exists_follow_le_card source target).1 hreach
    exact ⟨steps, hsteps, target, hfollow, hstop⟩
  · rintro ⟨steps, _, target, hfollow, hstop⟩
    exact ⟨target, G.deterministicReaches_of_follow_eq_some hfollow, hstop⟩

/-! ## Branch traces and bounded deterministic replay -/

/-- A path split into deterministic stretches and explicitly named branch choices. -/
public inductive BranchTrace (G : FiniteChoiceGraph V Choice) :
    List Choice → V → V → Prop
  | finish {source target : V}
      (path : ReflTransGen G.DeterministicStep source target) :
      BranchTrace G [] source target
  | branch {source junction next target : V} {choice : Choice} {choices : List Choice}
      (detPath : ReflTransGen G.DeterministicStep source junction)
      (isBranch : G.Branching junction)
      (take : G.next junction choice = some next)
      (rest : BranchTrace G choices next target) :
      BranchTrace G (choice :: choices) source target

omit [Fintype V] [DecidableEq V] in
/-- Extending a branch trace by a nonbranching edge extends its final deterministic stretch. -/
public theorem BranchTrace.tail_deterministic
    {choices : List Choice} {source old new : V}
    (trace : G.BranchTrace choices source old)
    (hnot : ¬ G.Branching old) (hedge : G.Edge old new) :
    G.BranchTrace choices source new := by
  induction trace with
  | finish detPath =>
      exact .finish (detPath.tail ⟨hedge, hnot⟩)
  | branch detPath isBranch take rest ih =>
      exact .branch detPath isBranch take (ih hnot hedge)

omit [Fintype V] [DecidableEq V] in
/-- Extending a branch trace at a genuine branch appends its choice to the schedule. -/
public theorem BranchTrace.tail_branch
    {choices : List Choice} {source old new : V}
    (trace : G.BranchTrace choices source old)
    (hbranch : G.Branching old) {choice : Choice}
    (htake : G.next old choice = some new) :
    G.BranchTrace (choices ++ [choice]) source new := by
  induction trace with
  | finish detPath =>
      exact .branch detPath hbranch htake (.finish .refl)
  | branch detPath isBranch take rest ih =>
      exact .branch detPath isBranch take (ih hbranch htake)

omit [Fintype V] [DecidableEq V] in
/-- Forgetting the schedule from a branch trace gives ordinary graph reachability. -/
public theorem BranchTrace.reaches
    {choices : List Choice} {source target : V}
    (trace : G.BranchTrace choices source target) :
    ReflTransGen G.Edge source target := by
  induction trace with
  | finish detPath =>
      exact detPath.mono fun _ _ hstep => hstep.1
  | branch detPath _ take rest ih =>
      have hprefix : ReflTransGen G.Edge _ _ :=
        detPath.mono fun _ _ hstep => hstep.1
      exact (hprefix.tail ⟨_, take⟩).trans ih

omit [Fintype V] [DecidableEq V] in
/-- Every ordinary finite path has a schedule recording exactly its genuine branch events. -/
public theorem exists_branchTrace_of_reaches
    {source target : V} (hreach : ReflTransGen G.Edge source target) :
    ∃ choices, G.BranchTrace choices source target := by
  induction hreach with
  | refl =>
      exact ⟨[], .finish .refl⟩
  | @tail middle target hreach hedge ih =>
      obtain ⟨choices, trace⟩ := ih
      by_cases hbranch : G.Branching middle
      · obtain ⟨choice, htake⟩ := hedge
        exact ⟨choices ++ [choice],
          BranchTrace.tail_branch G trace hbranch htake⟩
      · exact ⟨choices,
          BranchTrace.tail_deterministic G trace hbranch hedge⟩

/-- A branch trace whose deterministic stretches have all been reduced to bounded replay
lengths. -/
public inductive ReplayTrace (G : FiniteChoiceGraph V Choice) :
    List Choice → V → V → Prop
  | finish {source target : V} (steps : ℕ)
      (steps_le : steps ≤ Fintype.card V)
      (follow_eq : G.follow source steps = some target) :
      ReplayTrace G [] source target
  | branch {source junction next target : V} {choice : Choice} {choices : List Choice}
      (steps : ℕ)
      (steps_le : steps ≤ Fintype.card V)
      (follow_eq : G.follow source steps = some junction)
      (isBranch : G.Branching junction)
      (take : G.next junction choice = some next)
      (rest : ReplayTrace G choices next target) :
      ReplayTrace G (choice :: choices) source target

/-- Replace every deterministic segment in a branch trace by its bounded replay length. -/
public theorem replayTrace_of_branchTrace
    {choices : List Choice} {source target : V}
    (trace : G.BranchTrace choices source target) :
    G.ReplayTrace choices source target := by
  induction trace with
  | finish detPath =>
      obtain ⟨steps, hsteps, hfollow⟩ :=
        (G.deterministicReaches_iff_exists_follow_le_card _ _).1 detPath
      exact .finish steps hsteps hfollow
  | branch detPath isBranch take rest ih =>
      obtain ⟨steps, hsteps, hfollow⟩ :=
        (G.deterministicReaches_iff_exists_follow_le_card _ _).1 detPath
      exact .branch steps hsteps hfollow isBranch take ih

omit [DecidableEq V] in
/-- A bounded replay trace expands back to an ordinary branch trace. -/
public theorem branchTrace_of_replayTrace
    {choices : List Choice} {source target : V}
    (trace : G.ReplayTrace choices source target) :
    G.BranchTrace choices source target := by
  induction trace with
  | finish steps _ follow_eq =>
      exact .finish (G.deterministicReaches_of_follow_eq_some follow_eq)
  | branch steps _ follow_eq isBranch take rest ih =>
      exact .branch
        (G.deterministicReaches_of_follow_eq_some follow_eq)
        isBranch take ih

/-- Ordinary reachability is exactly existence of a finite bounded replay schedule. -/
public theorem reaches_iff_exists_replayTrace (source target : V) :
    ReflTransGen G.Edge source target ↔
      ∃ choices, G.ReplayTrace choices source target := by
  constructor
  · intro hreach
    obtain ⟨choices, trace⟩ := G.exists_branchTrace_of_reaches hreach
    exact ⟨choices, G.replayTrace_of_branchTrace trace⟩
  · rintro ⟨choices, trace⟩
    exact (G.branchTrace_of_replayTrace trace).reaches

/-! ## Finite schedule enumeration -/

/-- A schedule containing at most `budget` choices. -/
public abbrev Schedule (Choice : Type*) (budget : ℕ) :=
  Σ length : Fin (budget + 1), Fin length.val → Choice

/-- Convert a bounded schedule to its choice list. -/
public def Schedule.toList {budget : ℕ} (schedule : Schedule Choice budget) :
    List Choice :=
  List.ofFn schedule.2

@[simp]
public theorem Schedule.length_toList {budget : ℕ}
    (schedule : Schedule Choice budget) :
    schedule.toList.length = schedule.1.val := by
  simp [Schedule.toList]

/-- Turn a list whose length is within the budget into a finite schedule. -/
public def Schedule.ofList {budget : ℕ} (choices : List Choice)
    (hchoices : choices.length ≤ budget) : Schedule Choice budget :=
  ⟨⟨choices.length, by omega⟩, fun i => choices.get i⟩

@[simp]
public theorem Schedule.toList_ofList {budget : ℕ} (choices : List Choice)
    (hchoices : choices.length ≤ budget) :
    (Schedule.ofList choices hchoices).toList = choices := by
  exact List.ofFn_get choices

/-- Acceptance witnessed by at most `budget` genuine branch events. -/
public def AcceptsWithChoices
    (accept : V → Bool) (source : V) (budget : ℕ) : Prop :=
  ∃ schedule : Schedule Choice budget, ∃ target,
    G.ReplayTrace schedule.toList source target ∧ accept target = true

omit [DecidableEq V] in
/-- Bounded-choice acceptance is sound for ordinary reachability acceptance. -/
public theorem acceptsWithChoices_imp
    (accept : V → Bool) {source : V} {budget : ℕ}
    (haccept : G.AcceptsWithChoices accept source budget) :
    ∃ target, ReflTransGen G.Edge source target ∧ accept target = true := by
  obtain ⟨schedule, target, trace, hfinal⟩ := haccept
  exact ⟨target, (G.branchTrace_of_replayTrace trace).reaches, hfinal⟩

/-- Every accepting finite path has some finite branch-event budget. -/
public theorem accepts_iff_exists_acceptsWithChoices
    (accept : V → Bool) (source : V) :
    (∃ target, ReflTransGen G.Edge source target ∧ accept target = true) ↔
      ∃ budget, G.AcceptsWithChoices accept source budget := by
  constructor
  · rintro ⟨target, hreach, hfinal⟩
    obtain ⟨choices, trace⟩ :=
      (G.reaches_iff_exists_replayTrace source target).1 hreach
    refine ⟨choices.length, Schedule.ofList choices (Nat.le_refl _), target, ?_, hfinal⟩
    simpa using trace
  · rintro ⟨budget, haccept⟩
    exact G.acceptsWithChoices_imp accept haccept

/-- Exhaustively search the finite schedule and target spaces.

This definition is noncomputable only because the graph itself is presented abstractly and the
proof relation is decided classically.  It records the exact finite deterministic search that a
concrete transition-table implementation must realize. -/
public noncomputable def acceptsWithChoicesSearch
    (G : FiniteChoiceGraph V Choice)
    [Fintype Choice] (accept : V → Bool) (source : V) (budget : ℕ) : Bool := by
  classical
  exact Finset.univ.toList.any fun schedule : Schedule Choice budget =>
    Finset.univ.toList.any fun target : V =>
      decide (G.ReplayTrace schedule.toList source target ∧ accept target = true)

omit [DecidableEq V] in
/-- Correctness of exhaustive bounded-schedule search. -/
public theorem acceptsWithChoicesSearch_eq_true_iff
    [Fintype Choice] (accept : V → Bool) (source : V) (budget : ℕ) :
    G.acceptsWithChoicesSearch accept source budget = true ↔
      G.AcceptsWithChoices accept source budget := by
  classical
  simp [acceptsWithChoicesSearch, AcceptsWithChoices]

/-! ## Same-width schedule and segment-counter resources -/

/-- One same-width schedule cell stores `choicesPerCell` optional branch choices. -/
public abbrev PackedChoiceCell (Choice : Type*) (choicesPerCell : ℕ) :=
  Fin choicesPerCell → Option Choice

/-- Pack a schedule of length at most `width * choicesPerCell` into exactly `width` cells. -/
public def Schedule.packTape {width choicesPerCell : ℕ}
    (schedule : Schedule Choice (width * choicesPerCell)) :
    Fin width → PackedChoiceCell Choice choicesPerCell :=
  fun cell slot =>
    let flat := finProdFinEquiv (cell, slot)
    if h : flat.val < schedule.1.val
      then some (schedule.2 ⟨flat.val, h⟩)
      else none

/-- Every actual schedule entry is recovered from its packed same-width slot. -/
public theorem Schedule.packTape_recovers
    {width choicesPerCell : ℕ}
    (schedule : Schedule Choice (width * choicesPerCell))
    (index : Fin schedule.1.val) :
    let flat : Fin (width * choicesPerCell) :=
      ⟨index.val, by
        have hlength : schedule.1.val ≤ width * choicesPerCell := by
          omega
        exact lt_of_lt_of_le index.isLt hlength⟩
    let cellSlot := finProdFinEquiv.symm flat
    schedule.packTape cellSlot.1 cellSlot.2 = some (schedule.2 index) := by
  dsimp only
  simp only [Schedule.packTape, finProdFinEquiv.apply_symm_apply]
  split
  · congr
  · next h => exact False.elim (h index.isLt)

omit [DecidableEq V] in
/-- If finite vertices inject into width-`n` rows over `A`, a base-`Option A` counter of the
same width has room for every vertex count, including the endpoint. -/
public theorem card_lt_fuelCapacity_of_injective
    {A : Type*} [Fintype A] {width : ℕ} (hwidth : 0 < width)
    (encode : V → Fin width → A) (hinjective : Function.Injective encode) :
    Fintype.card V < (RowNumeral.fuelCodec A).radix ^ width := by
  have hcard :
      Fintype.card V ≤ Fintype.card (Fin width → A) :=
    Fintype.card_le_of_injective encode hinjective
  have hrows :
      Fintype.card (Fin width → A) = Fintype.card A ^ width :=
    Fintype.card_pi_const A width
  rw [hrows] at hcard
  exact hcard.trans_lt
    (RowNumeral.rowCapacity_lt_fuelCapacity A hwidth)

omit [DecidableEq V] in
/-- Every deterministic-segment depth up to the vertex-space cardinality has a same-width
fuel-row representation. -/
public theorem exists_fuelRow_of_le_card
    {A : Type*} [Fintype A] {width value : ℕ} (hwidth : 0 < width)
    (encode : V → Fin width → A) (hinjective : Function.Injective encode)
    (hvalue : value ≤ Fintype.card V) :
    ∃ row : List (Option A), row.length = width ∧
      (RowNumeral.fuelCodec A).value row = value := by
  exact (RowNumeral.fuelCodec A).exists_row_of_value
    (lt_of_le_of_lt hvalue
      (card_lt_fuelCapacity_of_injective
        (V := V) hwidth encode hinjective))

end FiniteChoiceGraph

/-! ## LBA specialization -/

namespace LBA

namespace BoundedNondeterminism

variable {Γ Λ : Type*}

/-- The fixed choice alphabet naming every possible LBA transition triple. -/
public abbrev BranchChoice (Γ Λ : Type*) :=
  Λ × Γ × DLBA.Dir

/-- The finite choice graph on width-bounded LBA configurations. -/
public noncomputable def cfgGraph
    (M : LBA.Machine Γ Λ) {n : ℕ} :
    FiniteChoiceGraph (DLBA.Cfg Γ Λ n) (BranchChoice Γ Λ) where
  next cfg move :=
    if move ∈ M.transition cfg.state cfg.tape.read then
      some ⟨move.1, (cfg.tape.write move.2.1).moveHead move.2.2⟩
    else none

/-- The choice-graph edge relation is exactly one LBA step. -/
public theorem cfgGraph_edge_iff
    (M : LBA.Machine Γ Λ) {n : ℕ}
    (old new : DLBA.Cfg Γ Λ n) :
    (cfgGraph M).Edge old new ↔ LBA.Step M old new := by
  constructor
  · rintro ⟨move, hmove⟩
    simp only [cfgGraph] at hmove
    split at hmove
    · next henabled =>
        refine ⟨move.1, move.2.1, move.2.2, henabled, ?_⟩
        exact Option.some.inj hmove |>.symm
    · simp at hmove
  · rintro ⟨state, symbol, direction, henabled, rfl⟩
    have henabled' :
        (state, symbol, direction) ∈
          M.transition old.state (old.tape.contents old.tape.head) := by
      simpa only [DLBA.BoundedTape.read] using henabled
    refine ⟨(state, symbol, direction), ?_⟩
    simp [cfgGraph, henabled']

/-- A branch event in the configuration graph is exactly the existence of two distinct
one-step LBA successors. -/
public theorem cfgGraph_branching_iff
    (M : LBA.Machine Γ Λ) {n : ℕ}
    (cfg : DLBA.Cfg Γ Λ n) :
    (cfgGraph M).Branching cfg ↔
      ∃ left right,
        LBA.Step M cfg left ∧ LBA.Step M cfg right ∧ left ≠ right := by
  constructor
  · rintro ⟨left, right, hleft, hright, hne⟩
    exact ⟨left, right,
      (cfgGraph_edge_iff M cfg left).1 hleft,
      (cfgGraph_edge_iff M cfg right).1 hright, hne⟩
  · rintro ⟨left, right, hleft, hright, hne⟩
    exact ⟨left, right,
      (cfgGraph_edge_iff M cfg left).2 hleft,
      (cfgGraph_edge_iff M cfg right).2 hright, hne⟩

variable [Fintype Γ] [Fintype Λ] [DecidableEq Γ] [DecidableEq Λ]

/-- LBA acceptance witnessed by at most `budget` choices out of genuine branch configurations. -/
public def AcceptsWithChoiceEvents
    (M : LBA.Machine Γ Λ) {n : ℕ}
    (source : DLBA.Cfg Γ Λ n) (budget : ℕ) : Prop :=
  (cfgGraph M).AcceptsWithChoices
    (fun cfg => M.accept cfg.state) source budget

omit [DecidableEq Γ] [DecidableEq Λ] in
/-- Bounded-choice acceptance is sound for ordinary nondeterministic LBA acceptance. -/
public theorem accepts_of_acceptsWithChoiceEvents
    (M : LBA.Machine Γ Λ) {n budget : ℕ}
    {source : DLBA.Cfg Γ Λ n}
    (haccept : AcceptsWithChoiceEvents M source budget) :
    LBA.Accepts M source := by
  obtain ⟨target, hreach, hfinal⟩ :=
    (cfgGraph M).acceptsWithChoices_imp
      (fun cfg => M.accept cfg.state) haccept
  exact ⟨target,
    hreach.mono fun old new hedge => (cfgGraph_edge_iff M old new).1 hedge,
    hfinal⟩

/-- Every accepting LBA run uses some finite number of genuine branch events. -/
public theorem accepts_iff_exists_acceptsWithChoiceEvents
    (M : LBA.Machine Γ Λ) {n : ℕ}
    (source : DLBA.Cfg Γ Λ n) :
    LBA.Accepts M source ↔
      ∃ budget, AcceptsWithChoiceEvents M source budget := by
  change LBA.Accepts M source ↔
    ∃ budget, (cfgGraph M).AcceptsWithChoices
      (fun cfg => M.accept cfg.state) source budget
  rw [← (cfgGraph M).accepts_iff_exists_acceptsWithChoices
    (fun cfg => M.accept cfg.state) source]
  constructor
  · rintro ⟨target, hreach, hfinal⟩
    exact ⟨target,
      hreach.mono fun old new hstep => (cfgGraph_edge_iff M old new).2 hstep,
      hfinal⟩
  · rintro ⟨target, hreach, hfinal⟩
    exact ⟨target,
      hreach.mono fun old new hedge => (cfgGraph_edge_iff M old new).1 hedge,
      hfinal⟩

/-- Exhaustive finite search over bounded LBA branch schedules. -/
public noncomputable def acceptsWithChoiceEventsSearch
    (M : LBA.Machine Γ Λ) {n : ℕ}
    (source : DLBA.Cfg Γ Λ n) (budget : ℕ) : Bool :=
  (cfgGraph M).acceptsWithChoicesSearch
    (fun cfg => M.accept cfg.state) source budget

omit [DecidableEq Γ] [DecidableEq Λ] in
/-- Correctness of exhaustive bounded LBA schedule search. -/
public theorem acceptsWithChoiceEventsSearch_eq_true_iff
    (M : LBA.Machine Γ Λ) {n : ℕ}
    (source : DLBA.Cfg Γ Λ n) (budget : ℕ) :
    acceptsWithChoiceEventsSearch M source budget = true ↔
      AcceptsWithChoiceEvents M source budget :=
  (cfgGraph M).acceptsWithChoicesSearch_eq_true_iff
    (fun cfg => M.accept cfg.state) source budget

variable {T : Type*} [Fintype T] [DecidableEq T]

/-- Semantic promise that every accepted endmarker input has a witness using at most a fixed
number `choicesPerCell` of branch events per physical tape cell. -/
public def HasLinearAcceptingChoiceBound
    (M : LBA.Machine (LBA.EndAlpha T Γ) Λ)
    (choicesPerCell : ℕ) : Prop :=
  ∀ input,
    LBA.Accepts M (LBA.initCfgEnd M input) →
      AcceptsWithChoiceEvents M (LBA.initCfgEnd M input)
        ((input.length + 2) * choicesPerCell)

omit [DecidableEq Γ] [DecidableEq Λ] [DecidableEq T] in
/-- Under the linear-choice promise, exhaustive bounded schedule replay decides acceptance
exactly.

This is the semantic finite-search specification used by the paper simulation argument.  It does
not construct the low-level same-tape `DLBA.Machine` that performs the schedule enumeration and
replay sweeps. -/
public theorem acceptsWithChoiceEventsSearch_linear_eq_true_iff
    (M : LBA.Machine (LBA.EndAlpha T Γ) Λ)
    {choicesPerCell : ℕ}
    (hbound : HasLinearAcceptingChoiceBound M choicesPerCell)
    (input : List T) :
    acceptsWithChoiceEventsSearch M (LBA.initCfgEnd M input)
        ((input.length + 2) * choicesPerCell) = true ↔
      LBA.Accepts M (LBA.initCfgEnd M input) := by
  rw [acceptsWithChoiceEventsSearch_eq_true_iff]
  constructor
  · exact accepts_of_acceptsWithChoiceEvents M
  · exact hbound input

/-- A schedule satisfying the linear choice bound packs into one track of exactly the physical
tape width. -/
public def packLinearSchedule
    (choicesPerCell : ℕ) {n : ℕ}
    (schedule :
      FiniteChoiceGraph.Schedule (BranchChoice Γ Λ) ((n + 1) * choicesPerCell)) :
    Fin (n + 1) →
      FiniteChoiceGraph.PackedChoiceCell (BranchChoice Γ Λ) choicesPerCell :=
  schedule.packTape

/-- The full deterministic-stretch counter for width-`n + 1` LBA configurations fits into a
same-width fuel row. -/
public theorem exists_segmentFuelRow
    {n value : ℕ} (hvalue : value ≤ Fintype.card (DLBA.Cfg Γ Λ n)) :
    ∃ row : List (Option (LBA.RowCell Unit Γ Λ)),
      row.length = n + 1 ∧
        (RowNumeral.fuelCodec (LBA.RowCell Unit Γ Λ)).value row = value :=
  LBA.CofunctionalResources.exists_fuelRow_of_le_card_cfg n value hvalue

/-- Every deterministic stretch of an LBA is found before the same-width fuel counter
overflows.  The implementation may use this larger, directly detectable cutoff instead of
computing the exact configuration-space cardinality. -/
public theorem deterministicStretch_replay_lt_fuelCapacity
    (M : LBA.Machine Γ Λ) {n : ℕ}
    {source target : DLBA.Cfg Γ Λ n}
    (hreach :
      ReflTransGen (cfgGraph M).DeterministicStep source target) :
    ∃ steps <
        (RowNumeral.fuelCodec (LBA.RowCell Unit Γ Λ)).radix ^ (n + 1),
      (cfgGraph M).follow source steps = some target := by
  obtain ⟨steps, hsteps, hfollow⟩ :=
    ((cfgGraph M).deterministicReaches_iff_exists_follow_le_card
      source target).1 hreach
  exact ⟨steps,
    lt_of_le_of_lt hsteps
      (LBA.CofunctionalResources.card_cfg_lt_fuelCapacity n),
    hfollow⟩

end BoundedNondeterminism

end LBA

end
