module

public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.GroupTheory.Perm.Basic
public import Mathlib.Logic.Relation
public import Mathlib.Logic.Relator
import Mathlib.Tactic.DeriveFintype

@[expose]
public section

/-!
# Reachability generated by total permutations

A family of total permutation generators acts on a finite vertex type.  Direct every generator
edge forward.  Although inverse generators are not included explicitly, each inverse action is a
finite forward power of the same permutation.  It follows that reflexive-transitive reachability
is symmetric: the reachable components are relational orbits.

This is a relational result.  It neither constructs nor analyzes a logspace reachability
algorithm.  The final section also records the corresponding obstruction to replacing partial
bijection layers by total permutations while preserving directed reachability.
-/

namespace PermutationReachability

open Relation

universe u v w

/-- The forward edge relation generated by one permutation. -/
@[expose]
public def PowerEdge {V : Type u} (permutation : Equiv.Perm V) : V → V → Prop :=
  fun source target => permutation source = target

/-- Repeated forward edges realize every nonnegative power of a permutation. -/
public theorem reaches_pow {V : Type u} (permutation : Equiv.Perm V) (source : V) (n : ℕ) :
    ReflTransGen (PowerEdge permutation) source ((permutation ^ n) source) := by
  induction n with
  | zero =>
      simpa using
        (ReflTransGen.refl : ReflTransGen (PowerEdge permutation) source source)
  | succ n ih =>
      apply ih.tail
      change permutation ((permutation ^ n) source) = (permutation ^ (n + 1)) source
      rw [pow_succ']
      rfl

/-- On a finite vertex type, the inverse permutation is a nonnegative forward power of the
permutation itself. -/
public theorem inv_eq_pow_orderOf_sub_one
    {V : Type u} [Finite V] (permutation : Equiv.Perm V) :
    permutation⁻¹ = permutation ^ (orderOf permutation - 1) := by
  symm
  apply eq_inv_of_mul_eq_one_left
  rw [← pow_succ, Nat.sub_add_cancel (orderOf_pos permutation), pow_orderOf_eq_one]

/-- On a finite vertex type, a single forward permutation edge can be reversed by finitely many
forward edges of the same permutation.

Concretely, after the edge `source → permutation source`, applying the permutation
`orderOf permutation - 1` more times returns to `source`. -/
public theorem reverse_powerEdge_reaches
    {V : Type u} [Finite V] (permutation : Equiv.Perm V) {source target : V}
    (hstep : PowerEdge permutation source target) :
    ReflTransGen (PowerEdge permutation) target source := by
  subst target
  have hreturn :
      (permutation ^ (orderOf permutation - 1)) (permutation source) = source := by
    rw [← inv_eq_pow_orderOf_sub_one]
    exact permutation.symm_apply_apply source
  simpa [hreturn] using
    reaches_pow permutation (permutation source) (orderOf permutation - 1)

/-- The union of the forward edges of an indexed family of permutation generators. -/
@[expose]
public def GeneratorEdge {V : Type u} {Color : Type v}
    (generator : Color → Equiv.Perm V) : V → V → Prop :=
  fun source target => ∃ color, generator color source = target

/-- Every generator edge can be reversed inside the forward reflexive-transitive closure. -/
public theorem reverse_generatorEdge_reaches
    {V : Type u} {Color : Type v} [Finite V]
    (generator : Color → Equiv.Perm V) {source target : V}
    (hstep : GeneratorEdge generator source target) :
    ReflTransGen (GeneratorEdge generator) target source := by
  obtain ⟨color, hcolor⟩ := hstep
  have hreverse := reverse_powerEdge_reaches (generator color) hcolor
  exact hreverse.lift id (fun _ _ hedge => ⟨color, hedge⟩)

/-- If every single edge can be reversed by a forward path, then the entire
reflexive-transitive closure is symmetric. -/
public theorem reflTransGen_symmetric_of_reverse_steps
    {V : Type u} {edge : V → V → Prop}
    (reverse : ∀ {source target}, edge source target →
      ReflTransGen edge target source) :
    Symmetric (ReflTransGen edge) := by
  intro source target hpath
  induction hpath with
  | refl => exact .refl
  | tail _ hstep ih => exact (reverse hstep).trans ih

/-- Forward reachability generated by any indexed family of permutations of a finite type is
symmetric.  In particular this applies to a family indexed by `Fin 2`. -/
public theorem generator_reaches_symmetric
    {V : Type u} {Color : Type v} [Finite V]
    (generator : Color → Equiv.Perm V) :
    Symmetric (ReflTransGen (GeneratorEdge generator)) :=
  reflTransGen_symmetric_of_reverse_steps
    (reverse_generatorEdge_reaches generator)

/-- Add the reverse of every edge to a relation. -/
@[expose]
public def Symmetrize {V : Type u} (edge : V → V → Prop) : V → V → Prop :=
  fun source target => edge source target ∨ edge target source

/-- For permutation generators on a finite type, explicitly adding reverse generator edges does
not change reflexive-transitive reachability. -/
public theorem generator_reaches_iff_symmetrized_reaches
    {V : Type u} {Color : Type v} [Finite V]
    (generator : Color → Equiv.Perm V) (source target : V) :
    ReflTransGen (GeneratorEdge generator) source target ↔
      ReflTransGen (Symmetrize (GeneratorEdge generator)) source target := by
  constructor
  · intro hpath
    exact hpath.lift id (fun _ _ hstep => Or.inl hstep)
  · intro hpath
    induction hpath with
    | refl => exact .refl
    | tail _ hstep ih =>
        rcases hstep with hforward | hbackward
        · exact ih.tail hforward
        · exact ih.trans (reverse_generatorEdge_reaches generator hbackward)

/-! ## Obstruction to reachability-preserving totalization -/

/-- If a directed relation is encoded into a finite total-permutation system, every original edge
is simulated by a permutation path, and reachability between encoded original vertices reflects
back to original reachability, then original reflexive-transitive reachability was already
symmetric.

The target type may contain auxiliary vertices, the encoding need not be surjective, and an
original edge may be simulated by multiple generator steps. -/
public theorem reachability_encoding_into_permutations_forces_symmetric
    {V : Type u} {W : Type v} {Color : Type w} [Finite W]
    (edge : V → V → Prop) (generator : Color → Equiv.Perm W)
    (encode : V → W)
    (simulates : ∀ {source target}, edge source target →
      ReflTransGen (GeneratorEdge generator) (encode source) (encode target))
    (reflects : ∀ {source target},
      ReflTransGen (GeneratorEdge generator) (encode source) (encode target) →
        ReflTransGen edge source target) :
    Symmetric (ReflTransGen edge) := by
  intro source target hpath
  have htotal : ReflTransGen (GeneratorEdge generator)
      (encode source) (encode target) := by
    induction hpath with
    | refl => exact .refl
    | tail _ hstep ih => exact ih.trans (simulates hstep)
  exact reflects (generator_reaches_symmetric generator htotal)

/-- If a total-permutation system contains every original edge and introduces no new reachable
pairs, then original reflexive-transitive reachability was already symmetric.

Thus totalizing partial-bijection layers by permutations cannot preserve a genuinely directed
reachability relation. -/
public theorem reachability_preserving_totalization_forces_symmetric
    {V : Type u} {Color : Type w} [Finite V]
    (edge : V → V → Prop) (generator : Color → Equiv.Perm V)
    (edge_sub_generator : ∀ {source target}, edge source target →
      GeneratorEdge generator source target)
    (reflects : ∀ {source target},
      ReflTransGen (GeneratorEdge generator) source target →
        ReflTransGen edge source target) :
    Symmetric (ReflTransGen edge) := by
  apply reachability_encoding_into_permutations_forces_symmetric
    edge generator id
  · intro source target hstep
    exact .single (edge_sub_generator hstep)
  · exact reflects

/-- The two vertices of the minimal one-way partial-bijection example. -/
public inductive OneWayVertex where
  | source
  | target
deriving DecidableEq, Fintype

/-- The relation containing only the directed edge `source → target`. -/
@[expose]
public def OneWayEdge : OneWayVertex → OneWayVertex → Prop
  | .source, .target => True
  | _, _ => False

/-- The one-way edge is a partial bijection. -/
public theorem oneWay_biUnique : Relator.BiUnique OneWayEdge := by
  constructor <;>
    intro first second pivot hfirst hsecond <;>
    cases first <;> cases second <;> cases pivot <;>
    simp [OneWayEdge] at hfirst hsecond ⊢

/-- The one-way edge gives forward reachability. -/
public theorem oneWay_reaches_forward :
    ReflTransGen OneWayEdge .source .target :=
  .single trivial

/-- The target of the one-way edge cannot reach its source. -/
public theorem oneWay_not_reaches_backward :
    ¬ ReflTransGen OneWayEdge .target .source := by
  intro hpath
  rcases hpath.cases_head with hequal | ⟨next, hstep, _⟩
  · cases hequal
  · cases next <;> simp [OneWayEdge] at hstep

/-- The one-way partial bijection cannot be extended to any indexed family of total permutations
without introducing a new reachable pair. -/
public theorem no_reachability_preserving_totalization_of_oneWay
    {Color : Type w} (generator : Color → Equiv.Perm OneWayVertex)
    (edge_sub_generator : ∀ {old new}, OneWayEdge old new →
      GeneratorEdge generator old new) :
    ¬ (∀ {old new},
      ReflTransGen (GeneratorEdge generator) old new →
        ReflTransGen OneWayEdge old new) := by
  intro reflects
  have hsymmetric := reachability_preserving_totalization_forces_symmetric
    OneWayEdge generator edge_sub_generator reflects
  exact oneWay_not_reaches_backward (hsymmetric oneWay_reaches_forward)

/-- Even auxiliary vertices and multi-step simulations cannot encode the one-way partial
bijection into a finite total-permutation action while reflecting reachability between encoded
original vertices. -/
public theorem no_reachability_preserving_permutation_encoding_of_oneWay
    {W : Type v} {Color : Type w} [Finite W]
    (generator : Color → Equiv.Perm W) (encode : OneWayVertex → W)
    (simulates : ∀ {old new}, OneWayEdge old new →
      ReflTransGen (GeneratorEdge generator) (encode old) (encode new)) :
    ¬ (∀ {old new},
      ReflTransGen (GeneratorEdge generator) (encode old) (encode new) →
        ReflTransGen OneWayEdge old new) := by
  intro reflects
  have hsymmetric := reachability_encoding_into_permutations_forces_symmetric
    OneWayEdge generator encode simulates reflects
  exact oneWay_not_reaches_backward (hsymmetric oneWay_reaches_forward)

end PermutationReachability
