module

public import Langlib.Examples.UnaryA2PowSucc
import Mathlib.Tactic

@[expose]
public section

/-!
# A naive additive word-length pumping barrier

This module isolates one elementary candidate route toward a language-level pumping argument.
`HasBoundedAdditiveLengthPump` says that, beyond one fixed positive threshold, every accepted
word has a positive bounded length increment whose every nonnegative multiple occurs as the
length of some accepted word.  It deliberately records only lengths; it does not assert that the
new words arise by pumping a common factorization of the original word.

Every unary powers-of-two language generated by a chosen letter fails this property because
adding any positive increment smaller than the chosen power of two lands strictly between two
consecutive powers.  No finiteness or nonemptiness assumption is needed beyond the supplied
letter.

This is **not** a separation of LBA from DLBA.  In particular, this repository does not currently
prove `is_DLBA unaryPow2`, and it does not prove that every DLBA language satisfies
`HasBoundedAdditiveLengthPump`.  If a deterministic-LBA presentation of `unaryPow2` is later
formalized, the theorem below would instead show that this naive property cannot be a necessary
DLBA invariant.
-/

/-- A length-only additive pumping property with one global positive bound.  The increment may
depend on the accepted word, while the pumped word may depend on the multiplier. -/
public def HasBoundedAdditiveLengthPump {T : Type} (L : Language T) : Prop :=
  ∃ pumpingLength : Nat, 0 < pumpingLength ∧
    ∀ word : List T, word ∈ L → pumpingLength ≤ word.length →
      ∃ increment : Nat, 1 ≤ increment ∧ increment ≤ pumpingLength ∧
        ∀ multiplier : Nat, ∃ pumped : List T,
          pumped ∈ L ∧
            pumped.length = word.length + multiplier * increment

/-- The powers-of-two unary language generated by `letter`. -/
public def unaryPow2At {T : Type} (letter : T) : Language T :=
  fun word => ∃ exponent : Nat,
    word = List.replicate ((2 : Nat) ^ (exponent + 1)) letter

/-- Over any alphabet, the powers-of-two unary language generated by a chosen letter has no
bounded additive length pump. -/
public theorem unaryPow2At_not_hasBoundedAdditiveLengthPump
    {T : Type} (letter : T) :
    ¬ HasBoundedAdditiveLengthPump (unaryPow2At letter) := by
  rintro ⟨pumpingLength, _hpumpingLengthPositive, hpump⟩
  let word := List.replicate ((2 : Nat) ^ (pumpingLength + 1)) letter
  have hword : word ∈ unaryPow2At letter := ⟨pumpingLength, rfl⟩
  have hpumpingLengthLtPower :
      pumpingLength < (2 : Nat) ^ (pumpingLength + 1) := by
    exact (Nat.lt_succ_self pumpingLength).trans
      (Nat.lt_two_pow_self (n := pumpingLength + 1))
  have hwordLong : pumpingLength ≤ word.length := by
    simpa [word] using hpumpingLengthLtPower.le
  obtain ⟨increment, hincrementPositive, hincrementBound, hpumpIncrement⟩ :=
    hpump word hword hwordLong
  obtain ⟨pumped, hpumped, hpumpedLength⟩ := hpumpIncrement 1
  obtain ⟨exponent, hpumpedWord⟩ := hpumped
  have hpumpedPowerLength :
      pumped.length = (2 : Nat) ^ (exponent + 1) := by
    rw [hpumpedWord]
    simp
  have hpumpedLength' :
      pumped.length = (2 : Nat) ^ (pumpingLength + 1) + increment := by
    simpa [word] using hpumpedLength
  have hincrementLtPower :
      increment < (2 : Nat) ^ (pumpingLength + 1) :=
    hincrementBound.trans_lt hpumpingLengthLtPower
  have hlower :
      (2 : Nat) ^ (pumpingLength + 1) < (2 : Nat) ^ (exponent + 1) := by
    rw [← hpumpedPowerLength, hpumpedLength']
    omega
  have hupper :
      (2 : Nat) ^ (exponent + 1) < (2 : Nat) ^ (pumpingLength + 2) := by
    calc
      (2 : Nat) ^ (exponent + 1) =
          (2 : Nat) ^ (pumpingLength + 1) + increment := by
        rw [← hpumpedPowerLength]
        exact hpumpedLength'
      _ < (2 : Nat) ^ (pumpingLength + 1) +
          (2 : Nat) ^ (pumpingLength + 1) :=
        Nat.add_lt_add_left hincrementLtPower _
      _ = (2 : Nat) ^ (pumpingLength + 2) := by
        rw [show pumpingLength + 2 = (pumpingLength + 1) + 1 by omega, pow_succ]
        omega
  have hexponentLower : pumpingLength + 1 < exponent + 1 :=
    (pow_lt_pow_iff_right₀ (by decide : (1 : Nat) < 2)).mp hlower
  have hexponentUpper : exponent + 1 < pumpingLength + 2 :=
    (pow_lt_pow_iff_right₀ (by decide : (1 : Nat) < 2)).mp hupper
  omega

/-- The existing Bool-valued `unaryPow2` is the specialization generated by `false`. -/
public theorem unaryPow2At_false_eq_unaryPow2 :
    unaryPow2At false = unaryPow2 := rfl

/-- The existing Bool unary powers-of-two language has no bounded additive length pump. -/
public theorem unaryPow2_not_hasBoundedAdditiveLengthPump :
    ¬ HasBoundedAdditiveLengthPump unaryPow2 := by
  rw [← unaryPow2At_false_eq_unaryPow2]
  exact unaryPow2At_not_hasBoundedAdditiveLengthPump false

end
