import Grammars.Classes.Unrestricted.Basics.Toolbox
import Grammars.Utilities.LanguageOperations

/-! # RE Closure Under Terminal Bijection

This file proves closure of recursively enumerable languages under bijective
renaming of terminals.

The key construction is `bijection_grammar`, which maps terminals in all rule
components via an equivalence `π : T₁ ≃ T₂`. The main result
`bijection_grammar_language` shows that this grammar generates exactly the
π-image of the original language. This is then used by the context-free and
context-sensitive bijection proofs via commutativity with their respective
embeddings.

## Main declarations

- `map_symbol`
- `bijection_grule`
- `bijection_grammar`
- `bijection_grammar_language`
- `RE_of_bijemap_RE`
-/

variable {T₁ T₂ : Type}

/-- Map a symbol along a terminal equivalence, leaving nonterminals unchanged. -/
def map_symbol {N : Type} (π : T₁ ≃ T₂) : symbol T₁ N → symbol T₂ N
  | symbol.terminal t => symbol.terminal (π t)
  | symbol.nonterminal n => symbol.nonterminal n

/-- Map a symbol back along the inverse equivalence. -/
def map_symbol_inv {N : Type} (π : T₁ ≃ T₂) : symbol T₂ N → symbol T₁ N
  | symbol.terminal t => symbol.terminal (π.symm t)
  | symbol.nonterminal n => symbol.nonterminal n

@[simp]
lemma map_symbol_inv_map_symbol {N : Type} (π : T₁ ≃ T₂) (s : symbol T₁ N) :
    map_symbol_inv π (map_symbol π s) = s := by
  cases s <;> simp [map_symbol, map_symbol_inv]

@[simp]
lemma map_symbol_map_symbol_inv {N : Type} (π : T₁ ≃ T₂) (s : symbol T₂ N) :
    map_symbol π (map_symbol_inv π s) = s := by
  cases s <;> simp [map_symbol, map_symbol_inv]

/-- Map an unrestricted grammar rule along a terminal equivalence. -/
def bijection_grule {N : Type} (π : T₁ ≃ T₂) (r : grule T₁ N) : grule T₂ N :=
  grule.mk (r.input_L.map (map_symbol π)) r.input_N
    (r.input_R.map (map_symbol π)) (r.output_string.map (map_symbol π))

/-- Map an unrestricted grammar along a terminal equivalence. -/
def bijection_grammar (g : grammar T₁) (π : T₁ ≃ T₂) : grammar T₂ :=
  grammar.mk g.nt g.initial (g.rules.map (bijection_grule π))

/-- The bijection grammar generates exactly the π-image of the original language.
    This is the core result from which all class-specific bijection closure theorems
    are derived. -/
theorem bijection_grammar_language (g : grammar T₁) (π : T₁ ≃ T₂) :
    grammar_language (bijection_grammar g π) = Language.bijemapLang (grammar_language g) π := by
  ext w;
  constructor;
  · -- By definition of `bijection_grule`, we know that if `w` is derived from `g` using `π`, then `w` is in the language generated by `g` under `π`.
    have h_derives : ∀ (u v : List (symbol T₂ g.nt)), grammar_derives (bijection_grammar g π) u v → grammar_derives g (List.map (map_symbol_inv π) u) (List.map (map_symbol_inv π) v) := by
      intro u v h;
      induction h;
      · constructor;
      · rename_i h₁ h₂ h₃;
        obtain ⟨ r, hr, u', v', hu, hv ⟩ := h₂;
        obtain ⟨ r', hr', rfl ⟩ := List.mem_map.mp hr;
        convert h₃.tail _ using 1;
        use r';
        simp_all +decide [ bijection_grule ];
        use List.map (map_symbol_inv π) u', List.map (map_symbol_inv π) v';
        simp +decide [ Function.comp, map_symbol_inv_map_symbol ];
        exact ⟨ by congr <;> ext <;> aesop, by ext; aesop ⟩;
    -- Apply the hypothesis `h_derives` to the derivation from the initial symbol to `w` in the bijection grammar.
    intro h_deriv
    have h_deriv_g : grammar_derives g (List.map (map_symbol_inv π) [symbol.nonterminal g.initial]) (List.map (map_symbol_inv π) (List.map (symbol.terminal) w)) := by
      exact h_derives _ _ h_deriv;
    have h_deriv_g : grammar_derives g [symbol.nonterminal g.initial] (List.map (symbol.terminal) (List.map (π.symm) w)) := by
      convert h_deriv_g using 1 ; aesop;
    exact h_deriv_g;
  · intro hw;
    -- By definition of `bijection_grule`, we know that if `w` is in the language of `g`, then `map_symbol π w` is in the language of `bijection_grammar g π`.
    have h_bijection : ∀ (w : List (symbol T₁ g.nt)), grammar_derives g [symbol.nonterminal g.initial] w → grammar_derives (bijection_grammar g π) [symbol.nonterminal g.initial] (List.map (map_symbol π) w) := by
      intro w hw;
      induction hw;
      · constructor;
      · rename_i b c hb hc ih;
        obtain ⟨ r, hr, u, v, rfl, rfl ⟩ := hc;
        convert ih.tail _ using 1;
        use bijection_grule π r;
        unfold bijection_grammar bijection_grule; aesop;
    convert h_bijection _ hw using 1;
    simp +decide [ map_symbol, List.map_map ];
    rw [ show ( map_symbol π ∘ symbol.terminal ∘ ⇑π.symm ) = symbol.terminal from funext fun x => by simp +decide [ map_symbol ] ] ; aesop

/-- The class of RE languages is closed under bijective terminal renaming. -/
theorem RE_of_bijemap_RE (π : T₁ ≃ T₂) (L : Language T₁) :
    is_RE L → is_RE (Language.bijemapLang L π) := by
  rintro ⟨g, hgL⟩
  exact ⟨bijection_grammar g π, by rw [bijection_grammar_language, hgL]⟩

/-- The converse direction. -/
theorem RE_of_bijemap_RE_rev (π : T₁ ≃ T₂) (L : Language T₁) :
    is_RE (Language.bijemapLang L π) → is_RE L := by
  intro h
  have h' := RE_of_bijemap_RE π.symm _ h
  simpa using h'

/-- A language is RE iff its image under a bijection of terminal alphabets is RE. -/
@[simp] theorem RE_bijemap_iff_RE (π : T₁ ≃ T₂) (L : Language T₁) :
    is_RE (Language.bijemapLang L π) ↔ is_RE L := by
  constructor
  · exact RE_of_bijemap_RE_rev π L
  · exact RE_of_bijemap_RE π L