module

/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license; see licenses/Apache-2.0.txt.
-/
public import Langlib.Utilities.ComputabilityPredicates
public import Langlib.Classes.ContextFree.Decidability.Helper
public import Langlib.Classes.ContextFree.Basics.EncodedCFG
import Mathlib.Computability.Primrec.List
@[expose]
public section



/-! # Encoded Right-Regular Grammars

This file introduces a concrete encoded representation of *right-regular* grammars
(`EncodedRG`) that is `Primcodable`, together with the language it denotes
(`regularLanguageOf`). It is the shared scaffolding for the uniform computability
results proved in `Decidability/Membership.lean` and `Decidability/Emptiness.lean`.

Every right-regular grammar is in particular a context-free grammar, so an
`EncodedRG` maps (via `toCFG`, a primitive-recursive translation) into the encoded
context-free grammars `EncodedCFG`, and `regularLanguageOf` is defined as the
context-free language of that image. The two uniform results are then obtained by
composing the already-established uniform CF results
(`contextFree_computableMembership`, `contextFree_computableEmptiness`) with the
primitive-recursive map `toCFG`.

Restricting the rule shape to the right-regular productions `A → a B`, `A → a`,
`A → ε` guarantees that every code denotes a *regular* language, so this is a
faithful encoding of the regular class (and conversely every regular language is
generated by some right-regular grammar, hence representable).

## Main definitions

- `EncodedRG` — the encoded right-regular grammar type
- `EncodedRG.toCFG` — translation to `EncodedCFG`
- `EncodedRG.regularLanguageOf` — the denoted language
-/

namespace Regular

variable {T : Type}

/-- An encoded right-regular grammar over terminal alphabet `T`.

The underlying type is `ℕ × ℕ × List (ℕ × Option (T × Option ℕ))`:
- the first `ℕ` is the number of nonterminals minus one (so the nonterminal type is
  `Fin (numNT + 1)`, always nonempty), matching `EncodedCFG`;
- the second `ℕ` is the index of the initial nonterminal;
- each rule `(lhs, body)` has `body : Option (T × Option ℕ)` encoding exactly one of
  the three right-regular shapes:
  - `none` — the rule `lhs → ε`;
  - `some (a, none)` — the rule `lhs → a`;
  - `some (a, some B)` — the rule `lhs → a B`.

Because each component is built from `ℕ`, `Option`, `×` and `List`, the type inherits
`Primcodable` from the standard Mathlib instances (given `Primcodable T`). -/
public def EncodedRG (T : Type) := ℕ × ℕ × List (ℕ × Option (T × Option ℕ))

namespace EncodedRG

public instance [Primcodable T] : Primcodable (EncodedRG T) :=
  inferInstanceAs (Primcodable (ℕ × ℕ × List (ℕ × Option (T × Option ℕ))))

/-- The right-hand side of a rule body in `EncodedCFG` symbol format. -/
public def bodyToRHS : Option (T × Option ℕ) → List (ℕ ⊕ T)
  | none => []
  | some (a, none) => [Sum.inr a]
  | some (a, some B) => [Sum.inr a, Sum.inl B]

/-- Translate an encoded right-regular grammar to an encoded context-free grammar.

The nonterminal count and initial index are kept; each right-regular rule body is
expanded to its context-free right-hand side via `bodyToRHS`. -/
public def toCFG (c : EncodedRG T) : EncodedCFG T :=
  (c.1, c.2.1, c.2.2.map (fun r => (r.1, bodyToRHS r.2)))

/-- The language denoted by an encoded right-regular grammar: the context-free
language of its context-free image. -/
public def regularLanguageOf (c : EncodedRG T) : Language T :=
  contextFreeLanguageOf (toCFG c)

/-! ## Primitive recursiveness of the translation -/

/-- The `some`-branch of `bodyToRHS` (case analysis on the optional next nonterminal)
is primitive recursive. -/
public theorem bodyToRHS_some_primrec [Primcodable T] :
    Primrec (fun p : T × Option ℕ => bodyToRHS (some p)) := by
  refine (Primrec.option_casesOn (o := fun p => p.2)
    (f := fun p => [Sum.inr p.1])
    (g := fun p B => [Sum.inr p.1, Sum.inl B])
    Primrec.snd ?_ ?_).of_eq ?_
  · -- `none` next nonterminal: `[Sum.inr p.1]`
    exact Primrec.list_cons.comp (Primrec.sumInr.comp Primrec.fst) (Primrec.const [])
  · -- `some B`: input `(p, B)`, build `[Sum.inr p.1, Sum.inl B]`
    exact Primrec.list_cons.comp
      (Primrec.sumInr.comp (Primrec.fst.comp Primrec.fst))
      (Primrec.list_cons.comp (Primrec.sumInl.comp Primrec.snd) (Primrec.const []))
  · intro p
    rcases p with ⟨a, _ | B⟩ <;> rfl

/-- `bodyToRHS` is primitive recursive. -/
public theorem bodyToRHS_primrec [Primcodable T] :
    Primrec (bodyToRHS : Option (T × Option ℕ) → List (ℕ ⊕ T)) := by
  refine (Primrec.option_casesOn (o := id)
    (f := fun _ => ([] : List (ℕ ⊕ T)))
    (g := fun _ p => bodyToRHS (some p))
    Primrec.id (Primrec.const []) ?_).of_eq ?_
  · exact bodyToRHS_some_primrec.comp Primrec.snd
  · intro o
    rcases o with _ | p <;> rfl

/-- `toCFG` is primitive recursive. -/
public theorem toCFG_primrec [Primcodable T] :
    Primrec (toCFG : EncodedRG T → EncodedCFG T) := by
  refine Primrec.pair Primrec.fst (Primrec.pair (Primrec.fst.comp Primrec.snd) ?_)
  refine Primrec.list_map (Primrec.snd.comp Primrec.snd) ?_
  refine Primrec₂.mk ?_
  refine Primrec.pair (Primrec.fst.comp Primrec.snd)
    (bodyToRHS_primrec.comp (Primrec.snd.comp Primrec.snd))

end EncodedRG

end Regular
