module

public import Langlib.Classes.ContextSensitive.Definition
public import Langlib.Classes.ContextSensitive.Basics.NonContracting
public import Langlib.Classes.ContextSensitive.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.RecursivelyEnumerable.Basics.Lifting
import Langlib.Grammars.NonContracting.Definition
import Langlib.Grammars.NonContracting.Equivalence.ContextSensitive
import Langlib.Grammars.Unrestricted.Toolbox
import Mathlib.Tactic
@[expose]
public section



/-! # Context-sensitive languages: adjoining the empty word

If `L` is generated by a non-contracting unrestricted grammar (equivalently, by an ε-free
context-sensitive grammar), then `{ε} ∪ L` is context-sensitive.

The construction adds a fresh start symbol `S' = none` on top of the grammar `g₀`, together
with the two rules `S' → ε` and `S' → S₀`.  The original rules are lifted unchanged along
`some : g₀.nt → Option g₀.nt`, so they remain non-contracting and `S'` never occurs on a
right-hand side — exactly the side condition the broad definition of `is_CS` requires when
the `S → ε` rule is present.

This is the closure lemma used to handle the `acceptEmpty = true` branch of `LBA ⊆ CS`. -/

namespace ContextSensitiveEmptyWord

variable {T : Type}

/-- `g₀` with a fresh start symbol `none`, plus rules `none → ε` and `none → S₀`,
the original rules lifted along `some`. -/
@[expose]
def addEmpty_grammar (g₀ : grammar T) : grammar T :=
  grammar.mk (Option g₀.nt) none (
    ⟨[], none, [], []⟩ ::
    ⟨[], none, [], [symbol.nonterminal (some g₀.initial)]⟩ ::
    List.map (lift_rule_ some) g₀.rules)

/-- `g₀` lifts into `addEmpty_grammar g₀` along `some`, with `id` as the (total) sink. -/
@[expose]
def lg (g₀ : grammar T) : lifted_grammar_ T where
  g₀ := g₀
  g := addEmpty_grammar g₀
  lift_nt := some
  sink_nt := id
  lift_inj := Option.some_injective _
  sink_inj := fun _ _ h => Or.inl h
  lift_nt_sink := fun _ => rfl
  corresponding_rules := by
    intro r hr
    simp only [addEmpty_grammar, List.mem_cons, List.mem_map]
    exact Or.inr (Or.inr ⟨r, hr, rfl⟩)
  preimage_of_rules := by
    rintro r ⟨hr, n₀, hn₀⟩
    simp only [addEmpty_grammar, List.mem_cons, List.mem_map] at hr
    rcases hr with rfl | rfl | ⟨r₀, hr₀, rfl⟩
    · simp at hn₀
    · simp at hn₀
    · exact ⟨r₀, hr₀, rfl⟩

/-! ### The grammar is context-sensitive -/

theorem addEmpty_context_sensitive (g₀ : grammar T) (h : grammar_noncontracting g₀) :
    grammar_context_sensitive (addEmpty_grammar g₀) := by
  constructor
  · -- every rule is the `S' → ε` rule or non-contracting
    intro r hr
    simp only [addEmpty_grammar, List.mem_cons, List.mem_map] at hr
    rcases hr with rfl | rfl | ⟨r₀, hr₀, rfl⟩
    · exact Or.inl ⟨rfl, rfl, rfl, rfl⟩
    · exact Or.inr (by simp [grule_noncontracting])
    · refine Or.inr ?_
      have := h r₀ hr₀
      simpa [grule_noncontracting, lift_rule_, lift_string_, List.length_map] using this
  · -- `S' = none` does not occur on any right-hand side
    intro _ r hr
    simp only [addEmpty_grammar, List.mem_cons, List.mem_map] at hr
    rcases hr with rfl | rfl | ⟨r₀, hr₀, rfl⟩
    · simp [addEmpty_grammar]
    · simp [addEmpty_grammar]
    · simp only [lift_rule_, lift_string_]
      intro hmem
      rw [List.mem_map] at hmem
      obtain ⟨s, _, hs⟩ := hmem
      cases s <;> simp [lift_symbol_, addEmpty_grammar] at hs

/-! ### Language equality -/

theorem mem_addEmpty_nil (g₀ : grammar T) :
    ([] : List T) ∈ grammar_language (addEmpty_grammar g₀) := by
  change grammar_generates (addEmpty_grammar g₀) []
  unfold grammar_generates
  apply grammar_deri_of_tran
  exact ⟨⟨[], none, [], []⟩, by simp [addEmpty_grammar], [], [],
    by simp [addEmpty_grammar], by simp [addEmpty_grammar]⟩

theorem mem_addEmpty_of_mem {g₀ : grammar T} {w : List T}
    (hw : w ∈ grammar_language g₀) :
    w ∈ grammar_language (addEmpty_grammar g₀) := by
  change grammar_generates g₀ w at hw
  change grammar_generates (addEmpty_grammar g₀) w
  unfold grammar_generates at hw ⊢
  refine grammar_deri_of_tran_deri (g := addEmpty_grammar g₀)
    (v := [symbol.nonterminal (some g₀.initial)]) ?_ ?_
  · exact ⟨⟨[], none, [], [symbol.nonterminal (some g₀.initial)]⟩,
      by simp [addEmpty_grammar], [], [], by simp [addEmpty_grammar], by simp [addEmpty_grammar]⟩
  · have lifted := lift_deri_ (lg g₀) hw
    rw [lift_string_map_terminal_] at lifted
    exact lifted

theorem disj_of_mem_addEmpty {g₀ : grammar T} {w : List T}
    (ass : w ∈ grammar_language (addEmpty_grammar g₀)) :
    w = [] ∨ w ∈ grammar_language g₀ := by
  change grammar_generates (addEmpty_grammar g₀) w at ass
  unfold grammar_generates at ass
  cases grammar_tran_or_id_of_deri (g := addEmpty_grammar g₀) ass with
  | inl hyp =>
      -- `[S'] = map terminal w` is impossible.
      exfalso
      cases w with
      | nil => simp [addEmpty_grammar] at hyp
      | cons hd tl => have := congrArg List.head? hyp; simp [addEmpty_grammar] at this
  | inr hyp =>
      rcases hyp with ⟨i, ⟨r, rin, u, v, bef, aft⟩, deri⟩
      -- The initial sentential form is the singleton `[S']`, forcing `u = v = []`.
      have uv_nil : u = [] ∧ v = [] := by
        have bl := congrArg List.length bef
        simp [List.length_append] at bl
        constructor <;> (rw [← List.length_eq_zero_iff]; omega)
      rw [uv_nil.1, List.nil_append, uv_nil.2, List.append_nil] at bef aft
      -- ... and the contexts to be empty too.
      have LR_nil : r.input_L = [] ∧ r.input_R = [] := by
        have bl := congrArg List.length bef
        simp [List.length_append] at bl
        constructor <;> (rw [← List.length_eq_zero_iff]; omega)
      rw [LR_nil.1, LR_nil.2, List.nil_append, List.append_nil] at bef
      -- `bef : [S'] = [nonterminal r.input_N]`, hence `r.input_N = none`.
      have same_nt : r.input_N = none :=
        (symbol.nonterminal.inj (List.head_eq_of_cons_eq bef)).symm
      simp only [addEmpty_grammar, List.mem_cons, List.mem_map] at rin
      rcases rin with rfl | rfl | ⟨r₀, hr₀, rfl⟩
      · -- `S' → ε`: the next form is `[]`, which derives only `[]`.
        left
        rw [aft] at deri
        cases grammar_tran_or_id_of_deri (g := addEmpty_grammar g₀) deri with
        | inl h =>
            change ([] : List (symbol T (Option g₀.nt))) = List.map symbol.terminal w at h
            exact List.map_eq_nil_iff.1 h.symm
        | inr h =>
            exfalso
            rcases h with ⟨j, ⟨r', _, u', v', bef', _⟩, _⟩
            have := congrArg List.length bef'
            simp only [List.length_append, List.length_cons, List.length_nil] at this
            omega
      · -- `S' → S₀`: sink the rest of the derivation back into `g₀`.
        right
        rw [aft] at deri
        change grammar_generates g₀ w
        unfold grammar_generates
        convert sink_deri_ (lg g₀) deri (by
          intro a ha
          simp only [List.mem_singleton] at ha
          subst ha
          exact ⟨g₀.initial, rfl⟩)
        exact (sink_string_map_terminal_ (lg g₀).sink_nt w).symm
      · -- A lifted rule cannot rewrite `S' = none`.
        exact absurd same_nt (by simp [lift_rule_])

theorem grammar_language_addEmpty (g₀ : grammar T) :
    grammar_language (addEmpty_grammar g₀) = (fun w => w = [] ∨ grammar_language g₀ w) := by
  ext w
  constructor
  · exact disj_of_mem_addEmpty
  · rintro (rfl | hw)
    · exact mem_addEmpty_nil g₀
    · exact mem_addEmpty_of_mem hw

end ContextSensitiveEmptyWord

open ContextSensitiveEmptyWord in
/-- **Adjoining `ε` to a non-contracting language stays context-sensitive.** -/
theorem is_CS_insert_empty_of_noncontracting {T : Type} (g₀ : grammar T)
    (h : grammar_noncontracting g₀) :
    is_CS (fun w => w = [] ∨ grammar_language g₀ w) :=
  ⟨addEmpty_grammar g₀, addEmpty_context_sensitive g₀ h, grammar_language_addEmpty g₀⟩

open ContextSensitiveEmptyWord in
/-- **Adjoining `ε` to an ε-free context-sensitive language stays context-sensitive.** -/
theorem is_CS_insert_empty_of_CS_grammar {T : Type} (g : CS_grammar T) :
    is_CS (fun w => w = [] ∨ CS_language g w) := by
  have hnc : grammar_noncontracting (grammar_of_csg g) := CS_is_noncontracting g
  have hlang : grammar_language (grammar_of_csg g) = CS_language g :=
    (CS_language_eq_grammar_language g).symm
  have := is_CS_insert_empty_of_noncontracting (grammar_of_csg g) hnc
  rwa [hlang] at this

/-- **Adjoining `ε` to an ε-free context-sensitive language stays context-sensitive.**

This variant starts from the broad `is_CS` predicate rather than an explicit
context-preserving grammar witness. It removes the optional empty-word rule using
`exists_noncontracting_offEmpty_of_CS`, then re-adds `ε` with a fresh start symbol. -/
theorem is_CS_insert_empty_of_is_CS_not_nil {T : Type} {L : Language T}
    (hL : is_CS L) (hne : [] ∉ L) :
    is_CS (fun w => w = [] ∨ L w) := by
  obtain ⟨g, hg, hlang⟩ := hL
  obtain ⟨g₀, _hfin, hnc, hlang₀⟩ := exists_noncontracting_offEmpty_of_CS g hg
  have hnonempty : grammar_language g₀ = L := by
    rw [hlang₀, hlang]
    ext w
    constructor
    · intro hw
      exact hw.1
    · intro hw
      refine ⟨hw, ?_⟩
      intro hwε
      rw [Set.mem_singleton_iff] at hwε
      exact hne (by simpa [hwε] using hw)
  have hAdd := is_CS_insert_empty_of_noncontracting g₀ hnc
  convert hAdd using 1
  rw [hnonempty]

/-- **Adjoining `ε` to any context-sensitive language stays context-sensitive.**

If `ε` is already present this is just the same language; otherwise it is the ε-free
case above. -/
theorem is_CS_insert_empty_of_is_CS {T : Type} {L : Language T} (hL : is_CS L) :
    is_CS (fun w => w = [] ∨ L w) := by
  by_cases hε : ([] : List T) ∈ L
  · have hEq : (fun w => w = [] ∨ L w) = L := by
      ext w
      constructor
      · rintro (rfl | hw)
        · exact hε
        · exact hw
      · intro hw
        exact Or.inr hw
    rwa [hEq]
  · exact is_CS_insert_empty_of_is_CS_not_nil hL hε
