module

public import Mathlib.Computability.Language
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Irrational
import Mathlib.Tactic.NormNum.IsCoprime
import Mathlib.Tactic.NormNum.IsSquare
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.ModEq
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.NatFib
import Mathlib.Tactic.NormNum.NatLog
import Mathlib.Tactic.NormNum.NatSqrt
import Mathlib.Tactic.NormNum.Ordinal
import Mathlib.Tactic.NormNum.Parity
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Topology.Sheaves.Init
@[expose]
public section



/-! # Indexed Grammar Definitions

This file defines indexed grammars (Aho, 1968), their derivation relation, and the induced
language predicate.

An indexed grammar extends context-free grammars by attaching a *stack of flags* (index symbols)
to each nonterminal in a sentential form. Productions can push flags onto, or pop flags from,
these stacks.

## Main declarations

- `IndexedGrammar` — the grammar structure
- `IndexedGrammar.SententialForm` — sentential forms with stacked nonterminals
- `IndexedGrammar.Transforms` — one-step derivation
- `IndexedGrammar.Derives` — reflexive–transitive closure of `Transforms`
- `IndexedGrammar.Language` — the generated language

## References

* A. V. Aho, "Indexed grammars — an extension of context-free grammars", *JACM* 15(4), 1968.
-/

open Relation List

/-- A symbol on the right-hand side of an indexed production.
    A nonterminal can optionally have a flag pushed onto its inherited stack. -/
public inductive IRhsSymbol (T : Type) (N : Type) (F : Type) where
  | terminal : T → IRhsSymbol T N F
  | nonterminal : N → Option F → IRhsSymbol T N F
deriving DecidableEq

/-- A production rule of an indexed grammar.

- `lhs` : the nonterminal on the left-hand side.
- `consume` : if `some f`, the rule can only fire when `f` is on top of the nonterminal's
  stack, and pops it; if `none`, no flag is consumed.
- `rhs` : the right-hand side; each nonterminal inherits the (possibly modified) stack of
  the left-hand side, with an optional additional flag push. -/
public structure IRule (T : Type) (N : Type) (F : Type) where
  lhs : N
  consume : Option F
  rhs : List (IRhsSymbol T N F)

/-- An indexed grammar that generates words over the alphabet `T`.

- `nt` : type of nonterminals
- `flag` : type of index symbols (flags)
- `initial` : the start nonterminal
- `rules` : the list of production rules -/
public structure IndexedGrammar (T : Type) where
  nt : Type
  flag : Type
  initial : nt
  rules : List (IRule T nt flag)

variable {T : Type}

namespace IndexedGrammar

/-- A symbol in a sentential form of an indexed grammar: either a terminal or a nonterminal
    equipped with its current flag stack. -/
public inductive ISym (g : IndexedGrammar T) where
  | terminal : T → ISym g
  | indexed : g.nt → List g.flag → ISym g

/-- Expand the right-hand side of a rule, distributing the given stack `σ` to every
    nonterminal (and pushing any specified flag on top). -/
@[expose]
public def expandRhs (g : IndexedGrammar T) (rhs : List (IRhsSymbol T g.nt g.flag))
    (σ : List g.flag) : List (ISym g) :=
  rhs.map fun s =>
    match s with
    | IRhsSymbol.terminal t => ISym.terminal t
    | IRhsSymbol.nonterminal n none => ISym.indexed n σ
    | IRhsSymbol.nonterminal n (some f) => ISym.indexed n (f :: σ)

/-- One step of indexed-grammar transformation. -/
@[expose]
public def Transforms (g : IndexedGrammar T) (w₁ w₂ : List (ISym g)) : Prop :=
  ∃ (r : IRule T g.nt g.flag) (u v : List (ISym g)) (σ : List g.flag),
    r ∈ g.rules ∧
    (match r.consume with
     | none   => w₁ = u ++ [ISym.indexed r.lhs σ] ++ v
     | some f => w₁ = u ++ [ISym.indexed r.lhs (f :: σ)] ++ v) ∧
    w₂ = u ++ expandRhs g r.rhs σ ++ v

/-- Any number of steps of indexed-grammar transformation. -/
@[expose]
public def Derives (g : IndexedGrammar T) : List (ISym g) → List (ISym g) → Prop :=
  ReflTransGen (Transforms g)

/-- A word (list of terminals) is generated by the grammar if it can be derived from the
    initial nonterminal (with empty stack). -/
@[expose]
public def Generates (g : IndexedGrammar T) (w : List T) : Prop :=
  Derives g [ISym.indexed g.initial []] (w.map ISym.terminal)

/-- The language generated by the grammar. -/
@[expose]
public def Language (g : IndexedGrammar T) : _root_.Language T :=
  setOf (Generates g)

-- -----------------------------------------------------------------------
-- Basic derivation combinators (mirroring the project's CF/CS toolbox)
-- -----------------------------------------------------------------------

theorem deri_self (g : IndexedGrammar T) (w : List (ISym g)) :
    Derives g w w :=
  ReflTransGen.refl

theorem deri_of_tran {g : IndexedGrammar T} {w₁ w₂ : List (ISym g)}
    (h : Transforms g w₁ w₂) : Derives g w₁ w₂ :=
  ReflTransGen.single h

public theorem deri_of_deri_deri {g : IndexedGrammar T} {w₁ w₂ w₃ : List (ISym g)}
    (h₁ : Derives g w₁ w₂) (h₂ : Derives g w₂ w₃) : Derives g w₁ w₃ :=
  h₁.trans h₂

public theorem deri_of_deri_tran {g : IndexedGrammar T} {w₁ w₂ w₃ : List (ISym g)}
    (h₁ : Derives g w₁ w₂) (h₂ : Transforms g w₂ w₃) : Derives g w₁ w₃ :=
  h₁.tail h₂

public theorem deri_of_tran_deri {g : IndexedGrammar T} {w₁ w₂ w₃ : List (ISym g)}
    (h₁ : Transforms g w₁ w₂) (h₂ : Derives g w₂ w₃) : Derives g w₁ w₃ :=
  h₂.head h₁

public theorem deri_with_prefix {g : IndexedGrammar T} (p : List (ISym g))
    {w₁ w₂ : List (ISym g)} (h : Derives g w₁ w₂) :
    Derives g (p ++ w₁) (p ++ w₂) := by
  induction h with
  | refl => exact ReflTransGen.refl
  | tail _ ht ih =>
    apply deri_of_deri_tran ih
    obtain ⟨r, u, v, σ, hr, hlhs, hrhs⟩ := ht
    refine ⟨r, p ++ u, v, σ, hr, ?_, by simp_all [List.append_assoc]⟩
    revert hlhs; cases r.consume <;> intro hlhs <;> simp_all [List.append_assoc]

theorem deri_with_suffix {g : IndexedGrammar T} (s : List (ISym g))
    {w₁ w₂ : List (ISym g)} (h : Derives g w₁ w₂) :
    Derives g (w₁ ++ s) (w₂ ++ s) := by
  induction h with
  | refl => exact ReflTransGen.refl
  | tail _ ht ih =>
    apply deri_of_deri_tran ih
    obtain ⟨r, u, v, σ, hr, hlhs, hrhs⟩ := ht
    refine ⟨r, u, v ++ s, σ, hr, ?_, by simp_all [List.append_assoc]⟩
    revert hlhs; cases r.consume <;> intro hlhs <;> simp_all [List.append_assoc]

/-! ## Uniform stack-suffix extension -/

def ISym.appendStackSuffix {g : IndexedGrammar T} (suffix : List g.flag) : g.ISym → g.ISym
  | ISym.terminal a => ISym.terminal a
  | ISym.indexed A σ => ISym.indexed A (σ ++ suffix)

def appendStackSuffixes {g : IndexedGrammar T} (suffix : List g.flag)
    (w : List g.ISym) : List g.ISym :=
  w.map (ISym.appendStackSuffix suffix)

@[simp] theorem ISym.appendStackSuffix_terminal {g : IndexedGrammar T}
    (suffix : List g.flag) (a : T) :
    ISym.appendStackSuffix (g := g) suffix (ISym.terminal a) = ISym.terminal a := rfl

@[simp] theorem ISym.appendStackSuffix_indexed {g : IndexedGrammar T}
    (suffix : List g.flag) (A : g.nt) (σ : List g.flag) :
    ISym.appendStackSuffix (g := g) suffix (ISym.indexed A σ) =
      ISym.indexed A (σ ++ suffix) := rfl

@[simp] theorem appendStackSuffixes_nil {g : IndexedGrammar T}
    (suffix : List g.flag) :
    appendStackSuffixes (g := g) suffix [] = [] := rfl

@[simp] theorem appendStackSuffixes_cons {g : IndexedGrammar T}
    (suffix : List g.flag) (s : g.ISym) (w : List g.ISym) :
    appendStackSuffixes suffix (s :: w) =
      ISym.appendStackSuffix suffix s :: appendStackSuffixes suffix w := rfl

@[simp] theorem appendStackSuffixes_append {g : IndexedGrammar T}
    (suffix : List g.flag) (u v : List g.ISym) :
    appendStackSuffixes suffix (u ++ v) =
      appendStackSuffixes suffix u ++ appendStackSuffixes suffix v := by
  simp [appendStackSuffixes, List.map_append]

@[simp] theorem appendStackSuffixes_length {g : IndexedGrammar T}
    (suffix : List g.flag) (w : List g.ISym) :
    (appendStackSuffixes suffix w).length = w.length := by
  simp [appendStackSuffixes]

@[simp] theorem appendStackSuffixes_map_terminal {g : IndexedGrammar T}
    (suffix : List g.flag) (w : List T) :
    appendStackSuffixes suffix (w.map fun a => (ISym.terminal a : g.ISym)) =
      w.map fun a => (ISym.terminal a : g.ISym) := by
  induction w with
  | nil => rfl
  | cons a w ih =>
      simp [ih]

@[simp] theorem appendStackSuffixes_expandRhs {g : IndexedGrammar T}
    (suffix : List g.flag) (rhs : List (IRhsSymbol T g.nt g.flag))
    (σ : List g.flag) :
    appendStackSuffixes suffix (g.expandRhs rhs σ) =
      g.expandRhs rhs (σ ++ suffix) := by
  induction rhs with
  | nil => rfl
  | cons s rhs ih =>
      cases s with
      | terminal a =>
          change ISym.terminal a :: appendStackSuffixes suffix (g.expandRhs rhs σ) =
            ISym.terminal a :: g.expandRhs rhs (σ ++ suffix)
          rw [ih]
      | nonterminal A push =>
          cases push with
          | none =>
              change ISym.indexed A (σ ++ suffix) ::
                  appendStackSuffixes suffix (g.expandRhs rhs σ) =
                ISym.indexed A (σ ++ suffix) :: g.expandRhs rhs (σ ++ suffix)
              rw [ih]
          | some f =>
              change ISym.indexed A ((f :: σ) ++ suffix) ::
                  appendStackSuffixes suffix (g.expandRhs rhs σ) =
                ISym.indexed A (f :: (σ ++ suffix)) ::
                  g.expandRhs rhs (σ ++ suffix)
              simp [ih]

theorem transforms_appendStackSuffixes {g : IndexedGrammar T}
    {w₁ w₂ : List g.ISym} (h : g.Transforms w₁ w₂)
    (suffix : List g.flag) :
    g.Transforms (appendStackSuffixes suffix w₁)
      (appendStackSuffixes suffix w₂) := by
  rcases h with ⟨r, u, v, σ, hr, hlhs, hrhs⟩
  refine ⟨r, appendStackSuffixes suffix u, appendStackSuffixes suffix v,
    σ ++ suffix, hr, ?_, ?_⟩
  · cases hc : r.consume with
    | none =>
        rw [hc] at hlhs
        rw [hlhs]
        simp [List.append_assoc]
    | some f =>
        rw [hc] at hlhs
        rw [hlhs]
        simp [List.append_assoc]
  · rw [hrhs]
    simp [List.append_assoc]

theorem derives_appendStackSuffixes {g : IndexedGrammar T}
    {w₁ w₂ : List g.ISym} (h : g.Derives w₁ w₂)
    (suffix : List g.flag) :
    g.Derives (appendStackSuffixes suffix w₁)
      (appendStackSuffixes suffix w₂) := by
  induction h with
  | refl =>
      exact ReflTransGen.refl
  | tail _ hstep ih =>
      exact ih.tail (transforms_appendStackSuffixes hstep suffix)

theorem derives_appendStackSuffix_indexed {g : IndexedGrammar T}
    {A : g.nt} {σ : List g.flag} {w : List g.ISym}
    (h : g.Derives [ISym.indexed A σ] w) (suffix : List g.flag) :
    g.Derives [ISym.indexed A (σ ++ suffix)]
      (appendStackSuffixes suffix w) := by
  simpa using derives_appendStackSuffixes h suffix

theorem derives_appendStackSuffix_to_terminals {g : IndexedGrammar T}
    {A : g.nt} {σ : List g.flag} {w : List T}
    (h : g.Derives [ISym.indexed A σ] (w.map ISym.terminal))
    (suffix : List g.flag) :
    g.Derives [ISym.indexed A (σ ++ suffix)] (w.map ISym.terminal) := by
  simpa using derives_appendStackSuffix_indexed (g := g) h suffix

/-- A grammar has no ε-productions. -/
def NoEpsilon' (g : IndexedGrammar T) : Prop :=
  ∀ r ∈ g.rules, r.rhs ≠ []

theorem transforms_length_le_of_noEpsilon {g : IndexedGrammar T}
    (hne : g.NoEpsilon')
    {w₁ w₂ : List (ISym g)}
    (h : g.Transforms w₁ w₂) : w₁.length ≤ w₂.length := by
  rcases h with ⟨r, u, v, σ, hr, hlhs, hrhs⟩
  have hexpand : 1 ≤ (g.expandRhs r.rhs σ).length := by
    unfold expandRhs
    rw [List.length_map]
    exact Nat.succ_le_of_lt (List.length_pos_of_ne_nil (hne r hr))
  subst w₂
  cases hc : r.consume with
  | none =>
      rw [hc] at hlhs
      subst w₁
      simp [List.length_append]
      omega
  | some f =>
      rw [hc] at hlhs
      subst w₁
      simp [List.length_append]
      omega

theorem derives_length_le_of_noEpsilon {g : IndexedGrammar T}
    (hne : g.NoEpsilon')
    {w₁ w₂ : List (ISym g)}
    (h : g.Derives w₁ w₂) : w₁.length ≤ w₂.length := by
  induction h with
  | refl => exact le_rfl
  | tail _ hstep ih =>
      exact le_trans ih (transforms_length_le_of_noEpsilon hne hstep)

theorem not_generates_nil_of_noEpsilon (g : IndexedGrammar T)
    (hne : g.NoEpsilon') : ¬ g.Generates [] := by
  intro h
  unfold Generates at h
  have hlen := derives_length_le_of_noEpsilon hne h
  simp at hlen

/-- A grammar has terminals isolated: each rule's RHS either is a single terminal,
or consists entirely of nonterminals (with optional flag annotations). -/
def TerminalsIsolated (g : IndexedGrammar T) : Prop :=
  ∀ r ∈ g.rules, (∃ a : T, r.rhs = [IRhsSymbol.terminal a]) ∨
    (∀ s ∈ r.rhs, ∃ n f, s = IRhsSymbol.nonterminal n f)

/-- The start symbol does not appear on the right-hand side of any rule. -/
def StartNotOnRhs' (g : IndexedGrammar T) : Prop :=
  ∀ r ∈ g.rules, ∀ s ∈ r.rhs,
    match s with
    | .nonterminal n _ => n ≠ g.initial
    | .terminal _ => True

/-- A rule has separated flag operations. -/
def IRule.FlagsSeparated (r : IRule T N F) : Prop :=
  -- If it consumes a flag, RHS has exactly one nonterminal with no push
  (r.consume.isSome →
    ∃ B : N, r.rhs = [IRhsSymbol.nonterminal B none]) ∧
  -- If it doesn't consume, at most one nonterminal pushes a flag, or it's a terminal rule
  (r.consume.isNone →
    (∀ s ∈ r.rhs, ∃ n, s = IRhsSymbol.nonterminal n none) ∨
    (∃ B f, r.rhs = [IRhsSymbol.nonterminal B (some f)]) ∨
    (∃ a : T, r.rhs = [IRhsSymbol.terminal a]))

/-- All rules in the grammar have separated flag operations. -/
def FlagsSeparated (g : IndexedGrammar T) : Prop :=
  ∀ r ∈ g.rules, IRule.FlagsSeparated r

/-- A production rule is in normal form with respect to a start symbol `s`. -/
def IRule.IsNF [DecidableEq N] (r : IRule T N F) (s : N) : Prop :=
  (r.consume = none ∧
    ∃ B C : N, r.rhs = [IRhsSymbol.nonterminal B none, IRhsSymbol.nonterminal C none] ∧
      B ≠ s ∧ C ≠ s) ∨
  (∃ f : F, r.consume = some f ∧
    ∃ B : N, r.rhs = [IRhsSymbol.nonterminal B none] ∧ B ≠ s) ∨
  (r.consume = none ∧
    ∃ B : N, ∃ f : F, r.rhs = [IRhsSymbol.nonterminal B (some f)] ∧ B ≠ s) ∨
  (r.consume = none ∧ ∃ a : T, r.rhs = [IRhsSymbol.terminal a])

/-- An indexed grammar is in **normal form** if every production rule is in normal form
with respect to the start symbol. -/
def IsNormalForm (g : IndexedGrammar T) [DecidableEq g.nt] : Prop :=
  ∀ r ∈ g.rules, IRule.IsNF r g.initial

theorem IRule.rhs_ne_nil_of_isNF {N F : Type} [DecidableEq N]
    {r : IRule T N F} {start : N} (h : IRule.IsNF r start) :
    r.rhs ≠ [] := by
  rcases h with hbin | hpop | hpush | hterm
  · rcases hbin with ⟨_, B, C, hrhs, _, _⟩
    rw [hrhs]
    simp
  · rcases hpop with ⟨_, _, B, hrhs, _⟩
    rw [hrhs]
    simp
  · rcases hpush with ⟨_, B, f, hrhs, _⟩
    rw [hrhs]
    simp
  · rcases hterm with ⟨_, a, hrhs⟩
    rw [hrhs]
    simp

theorem IRule.terminalsIsolated_of_isNF {N F : Type} [DecidableEq N]
    {r : IRule T N F} {start : N} (h : IRule.IsNF r start) :
    (∃ a : T, r.rhs = [IRhsSymbol.terminal a]) ∨
      (∀ s ∈ r.rhs, ∃ n f, s = IRhsSymbol.nonterminal n f) := by
  rcases h with hbin | hpop | hpush | hterm
  · rcases hbin with ⟨_, B, C, hrhs, _, _⟩
    right
    intro s hs
    rw [hrhs] at hs
    simp at hs
    rcases hs with rfl | rfl
    · exact ⟨B, none, rfl⟩
    · exact ⟨C, none, rfl⟩
  · rcases hpop with ⟨_, _, B, hrhs, _⟩
    right
    intro s hs
    rw [hrhs] at hs
    simp at hs
    subst s
    exact ⟨B, none, rfl⟩
  · rcases hpush with ⟨_, B, f, hrhs, _⟩
    right
    intro s hs
    rw [hrhs] at hs
    simp at hs
    subst s
    exact ⟨B, some f, rfl⟩
  · rcases hterm with ⟨_, a, hrhs⟩
    left
    exact ⟨a, hrhs⟩

theorem IRule.flagsSeparated_of_isNF {N F : Type} [DecidableEq N]
    {r : IRule T N F} {start : N} (h : IRule.IsNF r start) :
    IRule.FlagsSeparated r := by
  rcases h with hbin | hpop | hpush | hterm
  · rcases hbin with ⟨hc, B, C, hrhs, _, _⟩
    constructor
    · intro hsome
      rw [hc] at hsome
      simp at hsome
    · intro _
      left
      intro s hs
      rw [hrhs] at hs
      simp at hs
      rcases hs with rfl | rfl
      · exact ⟨B, rfl⟩
      · exact ⟨C, rfl⟩
  · rcases hpop with ⟨_, hc, B, hrhs, _⟩
    constructor
    · intro _
      exact ⟨B, hrhs⟩
    · intro hnone
      rw [hc] at hnone
      simp at hnone
  · rcases hpush with ⟨hc, B, f, hrhs, _⟩
    constructor
    · intro hsome
      rw [hc] at hsome
      simp at hsome
    · intro _
      right
      left
      exact ⟨B, f, hrhs⟩
  · rcases hterm with ⟨hc, a, hrhs⟩
    constructor
    · intro hsome
      rw [hc] at hsome
      simp at hsome
    · intro _
      right
      right
      exact ⟨a, hrhs⟩

theorem IRule.startNotOnRhs_of_isNF {N F : Type} [DecidableEq N]
    {r : IRule T N F} {start : N} (h : IRule.IsNF r start) :
    ∀ s ∈ r.rhs,
      match s with
      | IRhsSymbol.nonterminal n _ => n ≠ start
      | IRhsSymbol.terminal _ => True := by
  intro s hs
  rcases h with hbin | hpop | hpush | hterm
  · rcases hbin with ⟨_, B, C, hrhs, hB, hC⟩
    rw [hrhs] at hs
    simp at hs
    rcases hs with rfl | rfl
    · exact hB
    · exact hC
  · rcases hpop with ⟨_, _, B, hrhs, hB⟩
    rw [hrhs] at hs
    simp at hs
    subst s
    exact hB
  · rcases hpush with ⟨_, B, _, hrhs, hB⟩
    rw [hrhs] at hs
    simp at hs
    subst s
    exact hB
  · rcases hterm with ⟨_, a, hrhs⟩
    rw [hrhs] at hs
    simp at hs
    subst s
    trivial

theorem noEpsilon_of_isNormalForm (g : IndexedGrammar T)
    [DecidableEq g.nt] (h : g.IsNormalForm) : g.NoEpsilon' := by
  intro r hr
  exact IRule.rhs_ne_nil_of_isNF
    (T := T) (N := g.nt) (F := g.flag) (r := r) (start := g.initial) (h r hr)

theorem terminalsIsolated_of_isNormalForm (g : IndexedGrammar T)
    [DecidableEq g.nt] (h : g.IsNormalForm) : g.TerminalsIsolated := by
  intro r hr
  exact IRule.terminalsIsolated_of_isNF
    (T := T) (N := g.nt) (F := g.flag) (r := r) (start := g.initial) (h r hr)

theorem flagsSeparated_of_isNormalForm (g : IndexedGrammar T)
    [DecidableEq g.nt] (h : g.IsNormalForm) : g.FlagsSeparated := by
  intro r hr
  exact IRule.flagsSeparated_of_isNF
    (T := T) (N := g.nt) (F := g.flag) (r := r) (start := g.initial) (h r hr)

theorem startNotOnRhs_of_isNormalForm (g : IndexedGrammar T)
    [DecidableEq g.nt] (h : g.IsNormalForm) : g.StartNotOnRhs' := by
  intro r hr s hs
  cases s with
  | terminal t => trivial
  | nonterminal n f =>
      exact IRule.startNotOnRhs_of_isNF
        (T := T) (N := g.nt) (F := g.flag) (r := r) (start := g.initial)
        (h r hr) (IRhsSymbol.nonterminal n f) hs

end IndexedGrammar
