import Mathlib
import Langlib.Classes.ContextSensitive.Basics.Inclusion

/-! # Context-Sensitive Grammars as Unrestricted Grammars

This file gives an alternative characterization of context-sensitive grammars as
unrestricted grammars satisfying an additional structural property on their rules.

## Overview

A standard unrestricted grammar has rules of the form
  `input_L ++ [nonterminal input_N] ++ input_R → output_string`
where there are no restrictions on the relationship between the left- and right-hand sides.

A context-sensitive grammar is one where each rule preserves the context: i.e., for every rule,
  `output_string = input_L ++ γ ++ input_R`
for some non-empty string `γ`. In other words, the context (`input_L` and `input_R`) is
reproduced on the output side, and only the nonterminal in the middle is rewritten (to a
non-empty string).

This file proves that the unrestricted characterization agrees with the legacy
definition via `CS_grammar`.

## Main declarations

- `is_CS_via_csg` — legacy language class induced by `CS_grammar`
- `is_CS_via_csg_implies_is_CS` — conversion to the default unrestricted characterization
- `is_CS_implies_is_CS_via_csg` — extraction of a legacy witness
- `is_CS_iff_is_CS_via_csg` — equivalence of the two characterizations
-/

open List Relation

variable {T : Type}

/-! ## Forward direction: CS_grammar → context-sensitive unrestricted grammar -/

/-- The unrestricted grammar obtained from a context-sensitive grammar (via `grammar_of_csg`)
    satisfies the context-sensitive property. -/
theorem grammar_of_csg_context_sensitive (g : CS_grammar T) :
    grammar_context_sensitive (grammar_of_csg g) := by
  intro r hr
  simp [grammar_of_csg] at hr
  obtain ⟨cr, hcr, rfl⟩ := hr
  exact ⟨cr.output_string, g.output_nonempty cr hcr, by simp [List.append_assoc]⟩

/-- Every language generated by a legacy context-sensitive grammar satisfies the default
    unrestricted characterization. -/
theorem is_CS_via_csg_implies_is_CS {L : Language T} (h : is_CS_via_csg L) :
    is_CS L := by
  obtain ⟨g, rfl⟩ := h
  exact ⟨grammar_of_csg g, grammar_of_csg_context_sensitive g,
    (CS_language_eq_grammar_language g).symm⟩

/-! ## Backward direction: context-sensitive unrestricted grammar → CS_grammar -/

/-- Given an unrestricted grammar `g` satisfying `grammar_context_sensitive`, extract the
    middle portion `γ` for each rule. -/
noncomputable def cs_middle (g : grammar T) (hg : grammar_context_sensitive g)
    (r : grule T g.nt) (hr : r ∈ g.rules) : List (symbol T g.nt) :=
  (hg r hr).choose

lemma cs_middle_ne (g : grammar T) (hg : grammar_context_sensitive g)
    (r : grule T g.nt) (hr : r ∈ g.rules) :
    cs_middle g hg r hr ≠ [] :=
  (hg r hr).choose_spec.1

lemma cs_middle_eq (g : grammar T) (hg : grammar_context_sensitive g)
    (r : grule T g.nt) (hr : r ∈ g.rules) :
    r.output_string = r.input_L ++ cs_middle g hg r hr ++ r.input_R :=
  (hg r hr).choose_spec.2

/-- Convert an unrestricted grammar rule (from a context-sensitive unrestricted grammar)
    into a `csrule`. -/
noncomputable def csrule_of_grule (g : grammar T) (hg : grammar_context_sensitive g)
    (r : grule T g.nt) (hr : r ∈ g.rules) : csrule T g.nt :=
  { context_left := r.input_L
    input_nonterminal := r.input_N
    context_right := r.input_R
    output_string := cs_middle g hg r hr }

/-- Construct a `CS_grammar` from a context-sensitive unrestricted grammar. -/
noncomputable def csg_of_grammar (g : grammar T) (hg : grammar_context_sensitive g) :
    CS_grammar T where
  nt := g.nt
  initial := g.initial
  rules := g.rules.attach.map (fun ⟨r, hr⟩ => csrule_of_grule g hg r hr)
  output_nonempty := by
    intro cr hcr
    rw [List.mem_map] at hcr
    obtain ⟨⟨r, hr⟩, _, rfl⟩ := hcr
    exact cs_middle_ne g hg r hr

/-
A single step in the constructed `CS_grammar` corresponds to a step in the original
    unrestricted grammar, and vice versa.
-/
lemma csg_of_grammar_transforms_iff (g : grammar T) (hg : grammar_context_sensitive g)
    (w₁ w₂ : List (symbol T g.nt)) :
    CS_transforms (csg_of_grammar g hg) w₁ w₂ ↔ grammar_transforms g w₁ w₂ := by
  constructor;
  · rintro ⟨ r, u, v, hcr, hw₁, hw₂ ⟩;
    obtain ⟨ r', hr', rfl ⟩ := List.mem_map.mp hcr;
    use r'.val;
    refine' ⟨ r'.2, u, v, _, _ ⟩ <;> simp_all +decide [ csrule_of_grule ];
    rw [ ← List.append_assoc, ← List.append_assoc, cs_middle_eq ];
  · rintro ⟨ r, hr, u, v, rfl, rfl ⟩;
    use csrule_of_grule g hg r hr;
    refine' ⟨ u, v, _, rfl, _ ⟩;
    · unfold csg_of_grammar; aesop;
    · simp +decide [ csrule_of_grule, cs_middle_eq g hg r hr ]

/-- The derivation relation of the constructed `CS_grammar` coincides with that of the
    original unrestricted grammar. -/
lemma csg_of_grammar_derives_iff (g : grammar T) (hg : grammar_context_sensitive g)
    (w₁ w₂ : List (symbol T g.nt)) :
    CS_derives (csg_of_grammar g hg) w₁ w₂ ↔ grammar_derives g w₁ w₂ := by
  constructor
  · intro h
    induction h with
    | refl => exact grammar_deri_self
    | tail _ step ih =>
      exact grammar_deri_of_deri_tran ih ((csg_of_grammar_transforms_iff g hg _ _).mp step)
  · intro h
    induction h with
    | refl => exact CS_deri_self
    | tail _ step ih =>
      exact CS_deri_of_deri_tran ih ((csg_of_grammar_transforms_iff g hg _ _).mpr step)

/-- The language of the constructed `CS_grammar` equals that of the original grammar. -/
theorem csg_of_grammar_language_eq (g : grammar T) (hg : grammar_context_sensitive g) :
    CS_language (csg_of_grammar g hg) = grammar_language g := by
  ext w
  simp only [grammar_language, csg_of_grammar]
  exact csg_of_grammar_derives_iff g hg _ _

/-- Every language satisfying the default unrestricted characterization is generated by
    a legacy context-sensitive grammar. -/
theorem is_CS_implies_is_CS_via_csg {L : Language T} (h : is_CS L) :
    is_CS_via_csg L := by
  obtain ⟨g, hg, rfl⟩ := h
  exact ⟨csg_of_grammar g hg, csg_of_grammar_language_eq g hg⟩

/-! ## Equivalence -/

/-- The default unrestricted characterization of context-sensitivity agrees with the
    legacy `CS_grammar` characterization. -/
theorem is_CS_iff_is_CS_via_csg {L : Language T} :
    is_CS L ↔ is_CS_via_csg L :=
  ⟨is_CS_implies_is_CS_via_csg, is_CS_via_csg_implies_is_CS⟩
