module

public import Langlib.Classes.ContextSensitive.Definition
public import Langlib.Classes.ContextSensitive.Inclusion.RecursivelyEnumerable
public import Langlib.Grammars.NonContracting.Definition
import Mathlib.Tactic
@[expose]
public section

/-! # Legacy Context-Sensitive Grammars as Broad CSL Grammars

The default `is_CS` class is the broader convention: non-contracting rules, with
an optional distinguished `S → ε` rule.  The older `CS_grammar` structure remains
useful as an ε-free, context-preserving witness.  This file keeps the direction
that still holds: every legacy `CS_grammar` induces a language in the broader
class.
-/

open List Relation

variable {T : Type}

/-- The unrestricted grammar obtained from a legacy `CS_grammar` is non-contracting,
and hence context-sensitive in the broader `S → ε`-optional sense. -/
public theorem grammar_of_csg_context_sensitive (g : CS_grammar T) :
    grammar_context_sensitive (grammar_of_csg g) := by
  apply grammar_context_sensitive_of_noncontracting
  intro r hr
  simp [grammar_of_csg] at hr
  obtain ⟨cr, hcr, rfl⟩ := hr
  have hpos : 0 < cr.output_string.length :=
    List.length_pos_of_ne_nil (g.output_nonempty cr hcr)
  simp [List.length_append]
  omega

/-- Every language generated by a legacy ε-free context-sensitive grammar is in
the broader context-sensitive class. -/
public theorem is_CS_via_csg_implies_is_CS {L : Language T} (h : is_CS_via_csg L) :
    is_CS L := by
  obtain ⟨g, rfl⟩ := h
  exact ⟨grammar_of_csg g, grammar_of_csg_context_sensitive g,
    (CS_language_eq_grammar_language g).symm⟩
