/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import Langlib.Grammars.RightRegular.Definition
import Langlib.Grammars.Unrestricted.Toolbox
import Langlib.Classes.Regular.Definition

/-! # Right-Regular Grammars as Unrestricted Grammars

This file gives an alternative characterization of right-regular grammars as
unrestricted grammars satisfying an additional structural property on their rules.

## Overview

A standard unrestricted grammar has rules of the form
  `input_L ++ [nonterminal input_N] ++ input_R → output_string`
where there are no restrictions on the relationship between the left- and right-hand sides.

A right-regular grammar is one where each rule is context-free (i.e., `input_L = []` and
`input_R = []`) and the output string takes one of three forms:
- `[terminal a, nonterminal B]` for some terminal `a` and nonterminal `B`,
- `[terminal a]` for some terminal `a`, or
- `[]` (the empty string).

This file proves that the unrestricted characterization agrees with the legacy
definition via `RG_grammar`.

## Main declarations

- `is_RG_via_rg` — legacy language class induced by `RG_grammar`
- `is_RG_via_rg_implies_is_RG` — conversion to the default unrestricted characterization
- `is_RG_implies_is_RG_via_rg` — extraction of a legacy witness
- `is_RG_iff_is_RG_via_rg` — equivalence of the two characterizations
-/

open List Relation Classical

variable {T : Type}

/-! ## Forward direction: RG_grammar → right-regular unrestricted grammar -/

/-- Convert an `RG_rule` into a `grule` (unrestricted grammar rule). -/
def grule_of_RG_rule {N : Type} (r : RG_rule T N) : grule T N where
  input_L := []
  input_N := r.lhs
  input_R := []
  output_string := r.output

/-- Build an unrestricted grammar from a right-regular grammar. -/
def grammar_of_RG (g : RG_grammar T) : grammar T where
  nt := g.nt
  initial := g.initial
  rules := g.rules.map grule_of_RG_rule

/-- The unrestricted grammar built from a right-regular grammar satisfies the
    right-regular property. -/
theorem grammar_of_RG_right_regular (g : RG_grammar T) :
    grammar_right_regular (grammar_of_RG g) := by
  intro r hr
  simp only [grammar_of_RG, List.mem_map] at hr
  obtain ⟨rr, _, rfl⟩ := hr
  refine ⟨rfl, rfl, ?_⟩
  cases rr with
  | cons A a B => exact Or.inl ⟨a, B, rfl⟩
  | single A a => exact Or.inr (Or.inl ⟨a, rfl⟩)
  | epsilon A  => exact Or.inr (Or.inr rfl)

/-
A single step in the original `RG_grammar` corresponds to a step in the
    constructed unrestricted grammar.
-/
lemma grammar_of_RG_transforms {g : RG_grammar T}
    {w₁ w₂ : List (symbol T g.nt)}
    (h : RG_transforms g w₁ w₂) :
    grammar_transforms (grammar_of_RG g) w₁ w₂ := by
      obtain ⟨ r, hr, u, v, rfl, rfl ⟩ := h;
      refine' ⟨ _, _, u, v, _ ⟩;
      exact grule_of_RG_rule r;
      · exact List.mem_map.mpr ⟨ r, hr, rfl ⟩;
      · aesop

/-
A single step in the constructed unrestricted grammar corresponds to a step in the
    original `RG_grammar`.
-/
lemma RG_transforms_of_grammar_of_RG {g : RG_grammar T}
    {w₁ w₂ : List (symbol T g.nt)}
    (h : grammar_transforms (grammar_of_RG g) w₁ w₂) :
    RG_transforms g w₁ w₂ := by
      rcases h with ⟨ r, hr, u, v, h₁, h₂ ⟩;
      -- By definition of `grammar_of_RG`, there exists an original `RG_rule` `rr` such that `r = grule_of_RG_rule rr`.
      obtain ⟨rr, hr⟩ : ∃ rr : RG_rule T g.nt, r = grule_of_RG_rule rr := by
        unfold grammar_of_RG at hr; aesop;
      unfold grule_of_RG_rule at hr;
      use rr;
      constructor;
      · convert List.mem_map.mp ‹_›;
        constructor <;> intro h;
        · exact ⟨ rr, h, hr.symm ⟩;
        · obtain ⟨ a, ha, rfl ⟩ := h;
          cases a <;> cases rr <;> cases hr <;> tauto;
      · grind

/-- Derivation in the original `RG_grammar` coincides with derivation in the
    constructed unrestricted grammar. -/
lemma grammar_of_RG_derives_iff (g : RG_grammar T)
    (w₁ w₂ : List (symbol T g.nt)) :
    grammar_derives (grammar_of_RG g) w₁ w₂ ↔ RG_derives g w₁ w₂ := by
  constructor
  · intro h
    induction h with
    | refl => exact RG_deri_self g
    | tail _ step ih =>
      exact RG_deri_of_deri_tran ih (RG_transforms_of_grammar_of_RG step)
  · intro h
    induction h with
    | refl => exact grammar_deri_self
    | tail _ step ih =>
      exact grammar_deri_of_deri_tran ih (grammar_of_RG_transforms step)

/-- The language of the constructed unrestricted grammar equals that of the original
    right-regular grammar. -/
theorem grammar_of_RG_language_eq (g : RG_grammar T) :
    grammar_language (grammar_of_RG g) = RG_language g := by
  ext w
  simp only [grammar_language, RG_language]
  exact grammar_of_RG_derives_iff g _ _

/-- Every language generated by a legacy right-regular grammar satisfies the default
    unrestricted characterization. -/
theorem is_RG_via_rg_implies_is_RG {L : Language T} (h : is_RG_via_rg L) :
    is_RG L := by
  obtain ⟨g, rfl⟩ := h
  exact ⟨grammar_of_RG g, grammar_of_RG_right_regular g,
    grammar_of_RG_language_eq g⟩

/-! ## Backward direction: right-regular unrestricted grammar → RG_grammar -/

/-- Convert an unrestricted grammar rule (from a right-regular grammar) to an `RG_rule`.
    Uses the right-regular output property to determine the rule form. -/
noncomputable def RG_rule_of_grule {N : Type} (r : grule T N)
    (hr : right_regular_output r.output_string) : RG_rule T N :=
  if h₁ : ∃ a : T, ∃ B : N, r.output_string = [symbol.terminal a, symbol.nonterminal B] then
    RG_rule.cons r.input_N h₁.choose h₁.choose_spec.choose
  else if h₂ : ∃ a : T, r.output_string = [symbol.terminal a] then
    RG_rule.single r.input_N h₂.choose
  else
    RG_rule.epsilon r.input_N

lemma RG_rule_of_grule_lhs {N : Type} (r : grule T N)
    (hr : right_regular_output r.output_string) :
    (RG_rule_of_grule r hr).lhs = r.input_N := by
      unfold RG_rule_of_grule;
      split_ifs <;> rfl

lemma RG_rule_of_grule_output {N : Type} (r : grule T N)
    (hr : right_regular_output r.output_string) :
    (RG_rule_of_grule r hr).output = r.output_string := by
      unfold RG_rule_of_grule;
      cases hr <;> aesop

/-- Construct an `RG_grammar` from a right-regular unrestricted grammar. -/
noncomputable def RG_of_grammar (g : grammar T) (hg : grammar_right_regular g) :
    RG_grammar T where
  nt := g.nt
  initial := g.initial
  rules := g.rules.attach.map (fun ⟨r, _hr⟩ => RG_rule_of_grule r (hg r _hr).2.2)

/-
A single step in the constructed `RG_grammar` corresponds to a step in the original
    unrestricted grammar, and vice versa.
-/
lemma RG_of_grammar_transforms_iff (g : grammar T) (hg : grammar_right_regular g)
    (w₁ w₂ : List (symbol T g.nt)) :
    RG_transforms (RG_of_grammar g hg) w₁ w₂ ↔ grammar_transforms g w₁ w₂ := by
      unfold RG_transforms grammar_transforms;
      simp [RG_of_grammar];
      constructor;
      · rintro ⟨ r, hr, u, v, rfl, rfl ⟩;
        simp [RG_rule_of_grule_lhs, RG_rule_of_grule_output];
        have := hg r hr; aesop;
      · rintro ⟨ r, hr, u, v, rfl, rfl ⟩;
        refine' ⟨ r, hr, u, v, _, _ ⟩ <;> simp +decide [ RG_rule_of_grule_lhs, RG_rule_of_grule_output, hg r hr ]

/-- Derivation in the constructed `RG_grammar` coincides with derivation in the original
    unrestricted grammar. -/
lemma RG_of_grammar_derives_iff (g : grammar T) (hg : grammar_right_regular g)
    (w₁ w₂ : List (symbol T g.nt)) :
    RG_derives (RG_of_grammar g hg) w₁ w₂ ↔ grammar_derives g w₁ w₂ := by
  constructor
  · intro h
    induction h with
    | refl => exact grammar_deri_self
    | tail _ step ih =>
      exact grammar_deri_of_deri_tran ih ((RG_of_grammar_transforms_iff g hg _ _).mp step)
  · intro h
    induction h with
    | refl => exact RG_deri_self _
    | tail _ step ih =>
      exact RG_deri_of_deri_tran ih ((RG_of_grammar_transforms_iff g hg _ _).mpr step)

/-- The language of the constructed `RG_grammar` equals that of the original grammar. -/
theorem RG_of_grammar_language_eq (g : grammar T) (hg : grammar_right_regular g) :
    RG_language (RG_of_grammar g hg) = grammar_language g := by
  ext w
  exact RG_of_grammar_derives_iff g hg _ _

/-- Every language satisfying the default unrestricted characterization is generated by
    a legacy right-regular grammar. -/
theorem is_RG_implies_is_RG_via_rg {L : Language T} (h : is_RG L) :
    is_RG_via_rg L := by
  obtain ⟨g, hg, rfl⟩ := h
  exact ⟨RG_of_grammar g hg, RG_of_grammar_language_eq g hg⟩

/-! ## Equivalence -/

/-- The default unrestricted characterization of regularity agrees with the legacy
    `RG_grammar` characterization. -/
theorem is_RG_iff_is_RG_via_rg {L : Language T} :
    is_RG L ↔ is_RG_via_rg L :=
  ⟨is_RG_implies_is_RG_via_rg, is_RG_via_rg_implies_is_RG⟩
