module

public import Langlib.Classes.RecursivelyEnumerable.Definition
public import Langlib.Automata.Turing.Equivalence.GrammarToTM.MembershipComputability
public import Langlib.Automata.Turing.Equivalence.GrammarToTM.MembershipTest
public import Langlib.Automata.Turing.Definition
import Langlib.Automata.Turing.DSL.CodeToTMDirect
import Langlib.Automata.Turing.DSL.SearchProcToTM0
import Langlib.Grammars.Unrestricted.FiniteNonterminals
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Irrational
import Mathlib.Tactic.NormNum.IsCoprime
import Mathlib.Tactic.NormNum.IsSquare
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.ModEq
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.NatFib
import Mathlib.Tactic.NormNum.NatLog
import Mathlib.Tactic.NormNum.NatSqrt
import Mathlib.Tactic.NormNum.Ordinal
import Mathlib.Tactic.NormNum.Parity
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Topology.Sheaves.Init
@[expose]
public section



/-! # Unrestricted Grammars → Turing Machines

This file proves that every language generated by an unrestricted grammar
is TM-recognizable (internally): `RE ⊆ TM`.

## Main results

- `re_implies_tm` — `is_RE L → is_TM L`
  (TM-recognizable)

## Strategy

1. Restrict the grammar to finitely many nonterminals.
2. Show grammar membership is a `Computable₂` search: `w ∈ L ↔ ∃ seq, grammarTest g seq w`.
3. The µ-search is `Nat.Partrec` (via `search_is_partrec`), giving a `Code`.
4. Apply `code_implies_isTM_direct` to get `is_TM L`.

Step 4 uses the direct encoding bridge (`CodeToTMDirect.lean`).
-/

open Turing

/-- Every recursively enumerable language (generated by an unrestricted grammar)
is internally TM-recognizable with **finite states**. -/
public theorem re_implies_tm {T : Type} [DecidableEq T] [Fintype T]
    (L : Language T) (hL : is_RE L) : is_TM L := by
  obtain ⟨g, hg⟩ := hL
  obtain ⟨g', hfin, hlang⟩ := grammar_equivalent_finiteNT g
  haveI : Fintype g'.nt := Fintype.ofFinite _
  haveI : DecidableEq g'.nt := Classical.decEq _
  rw [← hg, hlang]
  -- Get Primcodable instances
  haveI : Primcodable T :=
    Primcodable.ofEquiv (Fin (Fintype.card T)) (Fintype.truncEquivFin T).out
  haveI : Primcodable g'.nt :=
    Primcodable.ofEquiv (Fin (Fintype.card g'.nt)) (Fintype.truncEquivFin g'.nt).out
  -- The grammar test is computable
  have hcomp := grammarTest_computable₂ g'
  -- Get the Code from the Partrec chain
  obtain ⟨c, hc⟩ := search_is_partrec (grammarTest g') hcomp
  -- Apply the direct encoding bridge
  exact code_implies_isTM_direct (grammar_language g') c (fun w => by
    constructor
    · intro hw
      rw [← hc]
      obtain ⟨seq, hseq⟩ := grammarTest_complete g' w hw
      exact ⟨seq, hseq⟩
    · intro hdom
      rw [← hc] at hdom
      obtain ⟨a, ha⟩ := hdom
      exact grammarTest_sound g' a w ha)

/-- Every recursively enumerable language over a finite alphabet is TM-recognizable. -/
public theorem RE_subset_TM {T : Type} [DecidableEq T] [Fintype T] :
    (RE : Set (Language T)) ⊆ TM := by
  intro L hL
  exact re_implies_tm L hL
