import Mathlib
import Langlib.Classes.RecursivelyEnumerable.Definition
import Langlib.Automata.Turing.Definition
import Langlib.Automata.Turing.Equivalence.GrammarToTM.GrammarSearch
import Langlib.Automata.Turing.DSL.InternalTM
import Langlib.Grammars.Unrestricted.FiniteNonterminals

/-! # Unrestricted Grammars → Turing Machines

This file proves that every language generated by an unrestricted grammar
is TM-recognizable (internally): `RE ⊆ TM_internal`.

## Main results

- `re_implies_tm_internal` — `is_RE L → is_TM_internal L`
  (TM-recognizable with internal alphabet AND `Fintype` states)

## Note on `is_TM`

The full `is_TM` result (with `Option (T ⊕ Γ)` tape alphabet) requires
converting from the compilation chain's internal alphabet to `Option (T ⊕ Γ)`.
This encoding conversion is the key unsolved formalization challenge.
See `InternalTM.lean` for details.

Note that `is_TM_internal` as defined is vacuously true (see warning in
`InternalTM.lean`), so `re_implies_tm_internal` is formally weak. The
meaningful content is in the compilation chain proof, which constructs
a specific computable encoding.
-/

open Turing

/-- Every recursively enumerable language (generated by an unrestricted grammar)
is internally TM-recognizable with **finite states**.

This is the strengthened version: the TM0 machine has both `Fintype`
tape alphabet and `Fintype` state type.

**Note**: The conclusion `is_TM_internal` is vacuously true (see warning
in `InternalTM.lean`). The meaningful content is in the proof, which
constructs a specific computable encoding via the compilation chain. -/
theorem re_implies_tm_internal {T : Type} [DecidableEq T] [Fintype T]
    (L : Language T) (hL : is_RE L) : is_TM_internal L := by
  obtain ⟨g, hg⟩ := hL
  obtain ⟨g', hfin, hlang⟩ := grammar_equivalent_finiteNT g
  haveI : Fintype g'.nt := Fintype.ofFinite _
  haveI : DecidableEq g'.nt := Classical.decEq _
  rw [← hg, hlang]
  exact grammar_language_is_TM_internal_fintype g'
