import Langlib.Automata.Turing.Equivalence.GrammarToTM
import Langlib.Automata.Turing.Equivalence.TMToGrammar

/-! # Turing-Recognizable Languages Are Exactly RE Languages

This module packages the two existing directions:

* `re_implies_tm`: unrestricted grammars are TM-recognizable.
* `TM_subset_RE`: TM-recognizable languages are generated by unrestricted grammars.

## Key results

- `TM_eq_RE`: equality of TM-recognizable and recursively enumerable languages.
- `is_TM_iff_is_RE`: pointwise membership equivalence.
-/

/-- The class of TM-recognizable languages is exactly the class of recursively
enumerable languages. -/
theorem TM_eq_RE {T : Type} [DecidableEq T] [Fintype T] :
    (TM : Set (Language T)) = RE := by
  exact Set.Subset.antisymm TM_subset_RE RE_subset_TM

/-- Pointwise version of `TM_eq_RE`. -/
theorem is_TM_iff_is_RE
    {T : Type} [DecidableEq T] [Fintype T]
    (L : Language T) :
    is_TM L ↔ is_RE L := by
  change L ∈ (TM : Set (Language T)) ↔ L ∈ RE
  rw [TM_eq_RE]
