module

public import Langlib.Classes.RecursivelyEnumerable.Definition
public import Langlib.Automata.Turing.Equivalence.TMToGrammar.Construction
public import Langlib.Automata.Turing.Equivalence.TMToGrammar.Soundness
public import Langlib.Automata.Turing.Definition
import Langlib.Grammars.Unrestricted.InverseHomomorphism
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Irrational
import Mathlib.Tactic.NormNum.IsCoprime
import Mathlib.Tactic.NormNum.IsSquare
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.ModEq
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.NatFib
import Mathlib.Tactic.NormNum.NatLog
import Mathlib.Tactic.NormNum.NatSqrt
import Mathlib.Tactic.NormNum.Ordinal
import Mathlib.Tactic.NormNum.Parity
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Topology.Sheaves.Init

@[expose] public section

/-! # Soundness of the TM → Grammar Construction

This file proves that the grammar `tmToGrammar` constructed from a TM0 machine is
**sound**: it only generates words on which the TM halts.

## Proof strategy for `is_TM`

The `is_TM` definition fixes the input embedding into the tape alphabet:
input symbols are written as `some (Sum.inl t)`, while the recognizer may use
additional work symbols from an existential finite alphabet `Γ`.

To reduce to the existing `tmToGrammar` construction (which works with
`Option Δ` for any `Δ`), we:
1. Apply `tmToGrammar (T ⊕ Γ) Λ M` to get a grammar over all tape symbols.
2. Apply `pullbackGrammar` to convert from grammar over `T ⊕ Γ` to grammar
   over `T` via the fixed `Sum.inl` inclusion.
3. Use `pullbackGrammar_language` and `tmToGrammar_correct` to establish
   the language correspondence.
-/

open Turing TMtoGrammarNT Relation

/-- Every TM-recognizable language over a finite alphabet is generated by
an unrestricted grammar. -/
theorem tm_recognizable_implies_re
    {T : Type} [DecidableEq T] [Fintype T]
    (L : Language T) :
    is_TM L → is_RE L := by
  intro ⟨Γ, hΓf, Λ, hΛ, hFin, M, hM⟩
  haveI := hΓf
  haveI : DecidableEq Γ := Classical.decEq Γ
  haveI : DecidableEq Λ := Classical.decEq Λ
  let inputSym : T → T ⊕ Γ := Sum.inl
  -- Use existing tmToGrammar with the full nonblank tape alphabet.
  let g := tmToGrammar (T ⊕ Γ) Λ M
  -- Pull back the grammar from tape symbols to input symbols via the fixed inclusion.
  let g' := GrammarPullback.pullbackGrammar g inputSym
  refine ⟨g', ?_⟩
  ext w
  rw [GrammarPullback.pullbackGrammar_language]
  simp only [grammar_language, Set.mem_setOf_eq, grammar_generates, g]
  constructor
  · intro h
    have := tmToGrammar_halts_of_generates M (w.map inputSym) h
    rw [show (w.map inputSym).map some = w.map (fun t => some (Sum.inl t)) from by
      simp [List.map_map, inputSym]] at this
    exact (hM w).mpr this
  · intro h
    apply tmToGrammar_generates_of_halts
    rw [show (w.map inputSym).map some = w.map (fun t => some (Sum.inl t)) from by
      simp [List.map_map, inputSym]]
    exact (hM w).mp h

theorem TM_subset_RE {T: Type} [DecidableEq T] [Fintype T] : (TM : Set (Language T)) ⊆ RE
  := by
  intro L hL
  have hL' := tm_recognizable_implies_re L
  exact hL' hL
