module

public import Langlib.Automata.LinearBounded.Equivalence.LBAToCSG
public import Langlib.Automata.LinearBounded.Equivalence.LBAToCSG.Completeness
public import Langlib.Automata.LinearBounded.Equivalence.LBAToCSG.Soundness
public import Langlib.Automata.LinearBounded.Equivalence.CSGToLBA
public import Langlib.Classes.ContextSensitive.Definition
public import Langlib.Classes.ContextSensitive.Inclusion.RecursivelyEnumerable
public import Langlib.Classes.ContextSensitive.Inclusion.Recursive
public import Langlib.Classes.ContextSensitive.Closure.EmptyWord
import Mathlib.Tactic
@[expose]
public section



/-!
# Context-Sensitive Languages = LBA Languages

This file states the Myhill–Landweber–Kuroda theorem in its set-level form,

  `CS = LBA`  (`CS_eq_LBA`),

the equality of the class of context-sensitive languages (`CS`, languages generated by
an unrestricted grammar that is non-contracting up to an optional `S → ε` rule) and the
class of languages recognised by a nondeterministic linearly bounded automaton (`LBA`).

The proof is the conjunction of two inclusions:

* `LBA_subset_CS` — Myhill's construction: a CS grammar simulates the LBA's bounded
  computation (`Automata/LinearBounded/Equivalence/LBAToCSG.lean` builds the grammar and
  proves rule membership; the remaining work is the language equality).
* `CS_subset_LBA` — Kuroda's construction: an LBA nondeterministically simulates a
  derivation of the grammar within the linear space provided by the input.

## On the empty word

`LBA.LanguageRecognized` decides membership of `ε` via an explicit `acceptEmpty : Bool`
(the bounded tape has no natural notion of "running on the empty input"). This mirrors the
optional `S → ε` rule in the definition of a context-sensitive grammar, and is precisely
what makes the two classes *equal* rather than merely "equal up to `ε`": both sides decide
`ε` by a finite flag and agree on every non-empty word.

## References

* Kuroda, S.-Y. (1964), "Classes of languages and linear-bounded automata".
* Myhill, J. (1960), "Linear bounded automata".
* Hopcroft, Motwani, Ullman, *Introduction to Automata Theory, Languages, and Computation*,
  Chapter 9.
-/

open MyhillConstruction

variable {T : Type}

/-! ## LBA ⊆ CS (Myhill) -/

/-- **Myhill's construction (core).** The context-sensitive grammar built from an LBA in
`LBAToCSG.lean` generates exactly the non-empty language recognised by the automaton.

This is the genuine content of the LBA → CS direction. The grammar and all of its rule
membership lemmas are already established in `LBAToCSG.lean`; what remains is the
bisimulation between cell-sentential-forms and LBA configurations:

* **completeness** (`⊇`): an accepting LBA run on `w` is mirrored by a derivation
  `start ⇒* map terminal w` — the start rules lay down one `cell` per input symbol, the
  simulation rules track each LBA step (interior moves use the 3-step `cellPending`
  protocol), and the cleanup rules recover the terminals once an accepting state appears;
* **soundness** (`⊆`): conversely every terminal string derivable from `start` arises this
  way, by an invariant stating that every reachable sentential form of `cell`s decodes to a
  configuration reachable by `M` from the initial configuration on `w`. -/
theorem myhill_language_eq
    {Γ Λ : Type} [Fintype T] [Fintype Γ] [Fintype Λ]
    [DecidableEq T] [DecidableEq Γ] [DecidableEq Λ]
    (M : LBA.Machine Γ Λ) (embed : T ↪ Γ) :
    CS_language (myhillGrammar M embed) = LBA.LanguageViaEmbed M embed := by
  funext w
  apply propext
  constructor
  · -- soundness (⊆): every derived terminal word is accepted
    exact MyhillConstruction.myhill_sound M embed w
  · -- completeness (⊇): every accepted word is derived
    exact MyhillConstruction.myhill_complete M embed w

variable [Fintype T] [DecidableEq T]

/-- **LBA ⊆ CS.** Every LBA language is context-sensitive.

The empty word is handled by `is_CS_insert_empty_of_CS_grammar`
(`Classes/ContextSensitive/Closure/EmptyWord.lean`), proved separately. -/
theorem LBA_subset_CS : (LBA : Set (Language T)) ⊆ CS := by
  rintro L ⟨Γ, Λ, hΓ, hΛ, hdΓ, hdΛ, acceptEmpty, M, rfl⟩
  haveI := hΓ; haveI := hΛ; haveI := hdΓ; haveI := hdΛ
  -- The canonical input map `some ∘ Sum.inl` as an embedding into the sum tape alphabet.
  let emb : T ↪ Option (T ⊕ Γ) := ⟨fun t => some (Sum.inl t), fun _ _ h => by simpa using h⟩
  -- The non-empty fragment is exactly the Myhill CS-grammar's language.
  have hcore : LBA.LanguageViaEmbed M ⇑emb = CS_language (myhillGrammar M emb) :=
    (myhill_language_eq M emb).symm
  -- `LanguageRecognized = (acceptEmpty ∧ ·=[]) ∨ LanguageViaEmbed`. Split on the flag.
  show is_CS (LBA.LanguageRecognized M ⇑emb acceptEmpty)
  cases acceptEmpty with
  | false =>
      -- `acceptEmpty = false`: the language is exactly the (ε-free) Myhill language.
      have : LBA.LanguageRecognized M ⇑emb false = CS_language (myhillGrammar M emb) := by
        funext w
        simp only [LBA.LanguageRecognized, Bool.false_eq_true, false_and, false_or, hcore]
      rw [this]
      exact is_CS_via_csg_implies_is_CS ⟨_, rfl⟩
  | true =>
      -- `acceptEmpty = true`: add `ε` to the Myhill language.
      have : LBA.LanguageRecognized M ⇑emb true
          = (fun w => w = [] ∨ CS_language (myhillGrammar M emb) w) := by
        funext w
        simp only [LBA.LanguageRecognized]
        rw [show LBA.LanguageViaEmbed M ⇑emb w = CS_language (myhillGrammar M emb) w
              from congrFun hcore w]
        apply propext
        constructor
        · rintro (⟨_, h⟩ | h)
          · exact Or.inl h
          · exact Or.inr h
        · rintro (h | h)
          · exact Or.inl ⟨trivial, h⟩
          · exact Or.inr h
      rw [this]
      exact is_CS_insert_empty_of_CS_grammar _

/-! ## CS ⊆ LBA (Kuroda) -/

/-- **Kuroda's construction (core).** Every context-sensitive language is recognised by a
nondeterministic LBA.

The genuine content of the CS → LBA direction. Given `is_CS L`, restrict to the
non-contracting core (`Grammars/NonContracting`) with finitely many nonterminals
(`Grammars/ContextSensitive/Basic/FiniteNT.lean`). On input `w` of length `n`, an LBA with a
two-track tape — track 1 the frozen input, track 2 a working sentential form over the
finite grammar-symbol alphabet — nondeterministically applies grammar rules to track 2 and
accepts when track 2 equals track 1. Non-contraction guarantees that every sentential form
of a derivation of `w` has length `≤ n`, so the bounded tape suffices, giving both
directions of the language equality. The empty word is decided by `acceptEmpty`. -/
theorem CS_subset_LBA : (CS : Set (Language T)) ⊆ LBA := by
  classical
  rintro L ⟨g, hg, rfl⟩
  -- Restrict to the ε-free non-contracting finite-NT core `g₀` (Myhill–Kuroda normalisation):
  -- `grammar_language g₀ = grammar_language g \ {[]}`.
  obtain ⟨g₀, hfin, hnc, hlang⟩ := exists_noncontracting_offEmpty_of_CS g hg
  -- Build the simulating LBA for the (ε-free) core language.
  obtain ⟨Γ, Λ, hΓ, hΛ, hdΓ, hdΛ, M, hM⟩ :=
    KurodaConstruction.noncontracting_finite_to_LBA g₀ hfin hnc
  -- `LanguageViaEmbed M = grammar_language g₀ = grammar_language g \ {[]}`.
  rw [hlang] at hM
  -- Decide `ε` with the flag; non-empty words are handled by the bounded computation.
  refine ⟨Γ, Λ, hΓ, hΛ, hdΓ, hdΛ, decide ([] ∈ grammar_language g), M, ?_⟩
  funext w
  apply propext
  simp only [LBA.LanguageRecognized]
  rcases eq_or_ne w [] with rfl | hw
  · -- `w = []`: the bounded tape cannot run, so only the flag decides membership.
    constructor
    · rintro (⟨hb, _⟩ | hv)
      · exact of_decide_eq_true hb
      · obtain ⟨hne, _⟩ := hv; simp at hne
    · intro hmem
      exact Or.inl ⟨by simpa using hmem, rfl⟩
  · -- `w ≠ []`: membership is exactly `LanguageViaEmbed M = grammar_language g \ {[]}`.
    constructor
    · rintro (⟨_, h0⟩ | hv)
      · exact absurd h0 hw
      · have hd := (congrFun hM w) ▸ hv
        exact hd.1
    · intro hmem
      refine Or.inr ?_
      rw [congrFun hM w]
      exact ⟨hmem, by simpa using hw⟩

/-! ## The theorem -/

/-- **Context-sensitive languages are exactly the LBA languages.** -/
theorem CS_eq_LBA : (CS : Set (Language T)) = LBA :=
  Set.Subset.antisymm CS_subset_LBA LBA_subset_CS
