module

public import Langlib.Classes.ContextFree.Inclusion.Indexed
import Langlib.Grammars.ContextFree.Toolbox
import Langlib.Grammars.ContextFree.UnrestrictedCharacterization
import Langlib.Utilities.Tactics

@[expose]
public section

/-!
# Witnesses for failure of indexed-language intersection closure

This file supplies the two positive halves of the standard intersection witness.  Over the
binary alphabet (`false = a`, `true = b`), put

* `indexedIntersectionA = {(a b^n)^m | n,m >= 1}`;
* `indexedIntersectionB = {a b^n (a b*)^(n-1) | n >= 1}`.

The first language is generated by an indexed grammar which chooses `n` on its flag stack and
then copies that stack to an arbitrary positive number of blocks.  The second language is
context-free.  Their intersection is
`indexedIntersectionH = {(a b^n)^n | n >= 1}`.

The separate shrinking-lemma development proves that `indexedIntersectionH` is not indexed.
-/

open List

namespace IndexedIntersectionWitness

/-- The binary block `a b^n`, with `false = a` and `true = b`. -/
public def abBlock (n : Nat) : List Bool :=
  false :: replicate n true

/-- `m` copies of the same block `a b^n`. -/
public def blockPower (n : Nat) : Nat → List Bool
  | 0 => []
  | m + 1 => abBlock n ++ blockPower n m

/-- A sequence of `a b*` blocks whose individual `b`-run lengths are listed in `ns`. -/
public def varyingBlocks : List Nat → List Bool
  | [] => []
  | n :: ns => abBlock n ++ varyingBlocks ns

/-- `{(a b^n)^m | n,m >= 1}`. -/
public def indexedIntersectionA : Language Bool := fun w =>
  ∃ n m : Nat, 0 < n ∧ 0 < m ∧ w = blockPower n m

/-- `{a b^n (a b*)^(n-1) | n >= 1}`. -/
public def indexedIntersectionB : Language Bool := fun w =>
  ∃ n : Nat, ∃ ns : List Nat,
    0 < n ∧ ns.length + 1 = n ∧ w = abBlock n ++ varyingBlocks ns

/-- `{(a b^n)^n | n >= 1}`. -/
public def indexedIntersectionH : Language Bool := fun w =>
  ∃ n : Nat, 0 < n ∧ w = blockPower n n

@[simp] lemma blockPower_zero (n : Nat) : blockPower n 0 = [] := rfl

@[simp] lemma blockPower_succ (n m : Nat) :
    blockPower n (m + 1) = abBlock n ++ blockPower n m := rfl

lemma blockPower_add (n m k : Nat) :
    blockPower n (m + k) = blockPower n m ++ blockPower n k := by
  induction m with
  | zero => simp
  | succ m ih => simp [Nat.succ_add, blockPower, ih, List.append_assoc]

@[simp] lemma varyingBlocks_append (xs ys : List Nat) :
    varyingBlocks (xs ++ ys) = varyingBlocks xs ++ varyingBlocks ys := by
  induction xs with
  | nil => simp [varyingBlocks]
  | cons x xs ih => simp [varyingBlocks, ih, List.append_assoc]

@[simp] lemma count_false_abBlock (n : Nat) : (abBlock n).count false = 1 := by
  have hrep : (replicate n true).count false = 0 := by
    induction n with
    | zero => simp
    | succ n ih => simp [replicate_succ, ih]
  simp [abBlock, hrep]

@[simp] lemma count_false_blockPower (n m : Nat) :
    (blockPower n m).count false = m := by
  induction m with
  | zero => simp
  | succ m ih => simp [blockPower, ih, Nat.add_comm]

@[simp] lemma count_false_varyingBlocks (ns : List Nat) :
    (varyingBlocks ns).count false = ns.length := by
  induction ns with
  | nil => simp [varyingBlocks]
  | cons n ns ih => simp [varyingBlocks, ih, Nat.add_comm]

@[simp] lemma varyingBlocks_replicate (n m : Nat) :
    varyingBlocks (replicate m n) = blockPower n m := by
  induction m with
  | zero => simp [varyingBlocks, blockPower]
  | succ m ih => simp [replicate_succ, varyingBlocks, blockPower, ih]

/-- Number of initial `b`s after discarding the first letter of a word. -/
private def firstBRun (w : List Bool) : Nat :=
  (w.tail.takeWhile id).length

private lemma takeWhile_id_replicate_true (n : Nat) :
    (replicate n true).takeWhile id = replicate n true := by
  induction n with
  | zero => simp
  | succ n ih => simp [replicate_succ, ih]

private lemma takeWhile_id_replicate_true_false (n : Nat) (w : List Bool) :
    (replicate n true ++ false :: w).takeWhile id = replicate n true := by
  induction n with
  | zero => simp
  | succ n ih => simp [replicate_succ, ih]

private lemma firstBRun_blockPower (n m : Nat) (hm : 0 < m) :
    firstBRun (blockPower n m) = n := by
  cases m with
  | zero => omega
  | succ m =>
      cases m with
      | zero => simp [firstBRun, blockPower, abBlock, takeWhile_id_replicate_true]
      | succ k =>
          simp [firstBRun, blockPower, abBlock,
            takeWhile_id_replicate_true_false, List.append_assoc]

private lemma firstBRun_abBlock_varyingBlocks (n : Nat) (ns : List Nat) :
    firstBRun (abBlock n ++ varyingBlocks ns) = n := by
  cases ns with
  | nil => simp [firstBRun, abBlock, varyingBlocks, takeWhile_id_replicate_true]
  | cons q qs =>
      simp [firstBRun, abBlock, varyingBlocks,
        takeWhile_id_replicate_true_false, List.append_assoc]

/-- The two positive witness languages meet in exactly `{(a b^n)^n | n >= 1}`. -/
public theorem indexedIntersectionA_inter_indexedIntersectionB :
    indexedIntersectionA ⊓ indexedIntersectionB = indexedIntersectionH := by
  ext w
  constructor
  · rintro ⟨⟨n, m, hn, hm, hw⟩, q, qs, hq, hlen, hshape⟩
    have hwords : blockPower n m = abBlock q ++ varyingBlocks qs := hw.symm.trans hshape
    have hm_q : m = q := by
      have hc := congrArg (fun x : List Bool => x.count false) hwords
      simp only [count_false_blockPower, List.count_append,
        count_false_abBlock, count_false_varyingBlocks] at hc
      omega
    have hn_q : n = q := by
      have hr := congrArg firstBRun hwords
      simpa [firstBRun_blockPower n m hm,
        firstBRun_abBlock_varyingBlocks q qs] using hr
    refine ⟨n, hn, ?_⟩
    calc
      w = blockPower n m := hw
      _ = blockPower n n := by rw [hm_q, hn_q]
  · rintro ⟨n, hn, rfl⟩
    refine ⟨⟨n, n, hn, hn, rfl⟩, n, replicate (n - 1) n, hn, ?_, ?_⟩
    · simp [Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr (Nat.ne_of_gt hn))]
    · cases n with
      | zero => omega
      | succ k => simp [varyingBlocks_replicate]

/-! ## The indexed grammar for `indexedIntersectionA` -/

public inductive ANT where
  | S | X | Z | Y | P
deriving DecidableEq

public inductive AFlag where
  | count | bottom
deriving DecidableEq

/-- Indexed grammar which chooses a positive common run length and duplicates its stack. -/
public def grammarIndexedIntersectionA : IndexedGrammar Bool where
  nt := ANT
  flag := AFlag
  initial := .S
  rules := [
    { lhs := .S, consume := none,
      rhs := [.nonterminal .X (some .bottom)] },
    { lhs := .X, consume := none,
      rhs := [.nonterminal .Z (some .count)] },
    { lhs := .Z, consume := none,
      rhs := [.nonterminal .Z (some .count)] },
    { lhs := .Z, consume := none,
      rhs := [.nonterminal .Y none] },
    { lhs := .Y, consume := none,
      rhs := [.nonterminal .Y none, .nonterminal .Y none] },
    { lhs := .Y, consume := none,
      rhs := [.terminal false, .nonterminal .P none] },
    { lhs := .P, consume := some .count,
      rhs := [.terminal true, .nonterminal .P none] },
    { lhs := .P, consume := some .bottom, rhs := [] }
  ]

private abbrev AG := grammarIndexedIntersectionA
private abbrev aS (s : List AFlag) : AG.ISym := .indexed .S s
private abbrev aX (s : List AFlag) : AG.ISym := .indexed .X s
private abbrev aZ (s : List AFlag) : AG.ISym := .indexed .Z s
private abbrev aY (s : List AFlag) : AG.ISym := .indexed .Y s
private abbrev aP (s : List AFlag) : AG.ISym := .indexed .P s
private abbrev aa : AG.ISym := .terminal false
private abbrev ab : AG.ISym := .terminal true

private def aStack (n : Nat) : List AFlag :=
  replicate n .count ++ [.bottom]

@[simp] private lemma aStack_zero : aStack 0 = [.bottom] := by simp [aStack]

private lemma aStack_succ (n : Nat) : aStack (n + 1) = .count :: aStack n := by
  simp [aStack, replicate_succ]

private lemma aStepS : AG.Transforms [aS []] [aX (aStack 0)] := by
  refine ⟨⟨.S, none, [.nonterminal .X (some .bottom)]⟩, [], [], [], ?_, rfl, ?_⟩
  · simp [grammarIndexedIntersectionA]
  · simp [IndexedGrammar.expandRhs, aStack]

private lemma aStepX : AG.Transforms [aX (aStack 0)] [aZ (aStack 1)] := by
  refine ⟨⟨.X, none, [.nonterminal .Z (some .count)]⟩,
    [], [], aStack 0, ?_, rfl, ?_⟩
  · simp [grammarIndexedIntersectionA]
  · simp [IndexedGrammar.expandRhs, aStack, replicate_succ]

private lemma aPushZ (n : Nat) :
    AG.Transforms [aZ (aStack n)] [aZ (aStack (n + 1))] := by
  refine ⟨⟨.Z, none, [.nonterminal .Z (some .count)]⟩,
    [], [], aStack n, ?_, rfl, ?_⟩
  · simp [grammarIndexedIntersectionA]
  · simp [IndexedGrammar.expandRhs, aStack_succ]

private lemma aPushZMany (n : Nat) :
    AG.Derives [aZ (aStack 1)] [aZ (aStack (n + 1))] := by
  induction n with
  | zero => exact Relation.ReflTransGen.refl
  | succ n ih => exact ih.tail (aPushZ (n + 1))

private lemma aStepZY (n : Nat) :
    AG.Transforms [aZ (aStack n)] [aY (aStack n)] := by
  refine ⟨⟨.Z, none, [.nonterminal .Y none]⟩, [], [], aStack n, ?_, rfl, ?_⟩
  · simp [grammarIndexedIntersectionA]
  · simp [IndexedGrammar.expandRhs]

private lemma aSplitY (n k : Nat) :
    AG.Derives [aY (aStack n)] (replicate (k + 1) (aY (aStack n))) := by
  induction k with
  | zero => simp; exact Relation.ReflTransGen.refl
  | succ k ih =>
      apply IndexedGrammar.deri_of_tran_deri
      · refine ⟨⟨.Y, none, [.nonterminal .Y none, .nonterminal .Y none]⟩,
          [], [], aStack n, ?_, rfl, rfl⟩
        · simp [grammarIndexedIntersectionA]
      · convert IndexedGrammar.deri_with_prefix [aY (aStack n)] ih using 1 <;>
          simp [replicate_succ]

private lemma aConsumeP (n : Nat) :
    AG.Derives [aP (aStack n)] (replicate n ab) := by
  induction n with
  | zero =>
      exact Relation.ReflTransGen.single ⟨⟨.P, some .bottom, []⟩, [], [], [], by
        simp [grammarIndexedIntersectionA], by simp [aStack], by
        simp [IndexedGrammar.expandRhs]⟩
  | succ n ih =>
      apply IndexedGrammar.deri_of_tran_deri
      · refine ⟨⟨.P, some .count, [.terminal true, .nonterminal .P none]⟩,
          [], [], aStack n, ?_, ?_, rfl⟩
        · simp [grammarIndexedIntersectionA]
        · simp [aStack_succ]
      · convert IndexedGrammar.deri_with_prefix [ab] ih using 1 <;>
          simp [replicate_succ]

private lemma aGenerateBlock (n : Nat) :
    AG.Derives [aY (aStack n)] ((abBlock n).map IndexedGrammar.ISym.terminal) := by
  apply IndexedGrammar.deri_of_tran_deri
  · refine ⟨⟨.Y, none, [.terminal false, .nonterminal .P none]⟩,
      [], [], aStack n, ?_, rfl, rfl⟩
    · simp [grammarIndexedIntersectionA]
  · convert IndexedGrammar.deri_with_prefix [aa] (aConsumeP n) using 1 <;>
      simp [abBlock, replicate_succ]

private lemma aGenerateBlocks (n m : Nat) :
    AG.Derives (replicate m (aY (aStack n)))
      ((blockPower n m).map IndexedGrammar.ISym.terminal) := by
  induction m with
  | zero => simp; exact Relation.ReflTransGen.refl
  | succ m ih =>
      rw [replicate_succ, blockPower_succ, List.map_append]
      exact IndexedGrammar.deri_of_deri_deri
        (IndexedGrammar.deri_with_suffix (replicate m (aY (aStack n))) (aGenerateBlock n))
        (IndexedGrammar.deri_with_prefix
          ((abBlock n).map IndexedGrammar.ISym.terminal) ih)

private lemma indexedIntersectionA_subset_grammar :
    indexedIntersectionA ≤ AG.Language := by
  rintro w ⟨n, m, hn, hm, rfl⟩
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hm)
  show AG.Generates (blockPower (n + 1) (m + 1))
  unfold IndexedGrammar.Generates
  exact IndexedGrammar.deri_of_tran_deri aStepS <|
    IndexedGrammar.deri_of_tran_deri aStepX <|
    IndexedGrammar.deri_of_deri_deri (aPushZMany n) <|
    IndexedGrammar.deri_of_tran_deri (aStepZY (n + 1)) <|
    IndexedGrammar.deri_of_deri_deri (aSplitY (n + 1) m) <|
    aGenerateBlocks (n + 1) (m + 1)

/-! ### A compositional soundness interpretation -/

/-- Number of count flags before the first bottom marker. -/
private def aHeight : List AFlag → Option Nat
  | [] => none
  | .bottom :: _ => some 0
  | .count :: s => (aHeight s).map Nat.succ

@[simp] private lemma aHeight_bottom (s : List AFlag) :
    aHeight (.bottom :: s) = some 0 := rfl

@[simp] private lemma aHeight_count (s : List AFlag) :
    aHeight (.count :: s) = (aHeight s).map Nat.succ := rfl

private def aFrom (lower : Nat) (w : List Bool) : Prop :=
  ∃ n m : Nat, lower ≤ n ∧ 0 < m ∧ w = blockPower n m

private def aSymSem : AG.ISym → List Bool → Prop
  | .terminal t, w => w = [t]
  | .indexed .S _, w => aFrom 1 w
  | .indexed .X s, w => ∃ n, aHeight (.count :: s) = some n ∧ aFrom n w
  | .indexed .Z s, w => ∃ n, aHeight s = some n ∧ aFrom n w
  | .indexed .Y s, w =>
      ∃ n m : Nat, aHeight s = some n ∧ 0 < m ∧ w = blockPower n m
  | .indexed .P s, w =>
      ∃ n : Nat, aHeight s = some n ∧ w = replicate n true

private def aFormSem : List AG.ISym → List Bool → Prop
  | [], w => w = []
  | x :: xs, w => ∃ u v, aSymSem x u ∧ aFormSem xs v ∧ w = u ++ v

private lemma aFormSem_append (xs ys : List AG.ISym) (w : List Bool) :
    aFormSem (xs ++ ys) w ↔
      ∃ u v, aFormSem xs u ∧ aFormSem ys v ∧ w = u ++ v := by
  induction xs generalizing w with
  | nil => simp [aFormSem]
  | cons x xs ih =>
      simp only [List.cons_append, aFormSem]
      constructor
      · rintro ⟨p, q, hp, hq, rfl⟩
        obtain ⟨u, v, hu, hv, rfl⟩ := (ih q).mp hq
        exact ⟨p ++ u, v, ⟨p, u, hp, hu, rfl⟩, hv, by simp [List.append_assoc]⟩
      · rintro ⟨u, v, ⟨p, q, hp, hq, rfl⟩, hv, rfl⟩
        exact ⟨p, q ++ v, hp, (ih (q ++ v)).mpr ⟨q, v, hq, hv, rfl⟩,
          by simp [List.append_assoc]⟩

@[simp] private lemma aFormSem_singleton (x : AG.ISym) (w : List Bool) :
    aFormSem [x] w ↔ aSymSem x w := by
  simp [aFormSem]

private lemma aFormSem_terminals (w : List Bool) :
    aFormSem (w.map IndexedGrammar.ISym.terminal) w := by
  induction w with
  | nil => simp [aFormSem]
  | cons x xs ih => exact ⟨[x], xs, rfl, ih, rfl⟩

private lemma aFormSem_context {lhs : AG.ISym} {rhs u v : List AG.ISym}
    (hsound : ∀ w, aFormSem rhs w → aSymSem lhs w) {w : List Bool}
    (h : aFormSem (u ++ rhs ++ v) w) :
    aFormSem (u ++ [lhs] ++ v) w := by
  rw [List.append_assoc] at h
  obtain ⟨wu, wrv, hu, hrv, rfl⟩ := (aFormSem_append u (rhs ++ v) w).mp h
  obtain ⟨wr, wv, hr, hv, rfl⟩ := (aFormSem_append rhs v wrv).mp hrv
  rw [List.append_assoc]
  apply (aFormSem_append u ([lhs] ++ v) _).mpr
  refine ⟨wu, wr ++ wv, hu, ?_, by simp [List.append_assoc]⟩
  exact (aFormSem_append [lhs] v _).mpr
    ⟨wr, wv, aFormSem_singleton lhs wr |>.mpr (hsound wr hr), hv, rfl⟩

private lemma aRuleSound (r : IRule Bool ANT AFlag)
    (hr : r ∈ AG.rules) (s : List AFlag) (w : List Bool)
    (h : aFormSem (AG.expandRhs r.rhs s) w) :
    aSymSem (.indexed r.lhs (match r.consume with | none => s | some f => f :: s)) w := by
  simp only [grammarIndexedIntersectionA, List.mem_cons, List.not_mem_nil,
    or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · have h' : aSymSem (aX (.bottom :: s)) w := by
      exact (aFormSem_singleton _ _).mp (by
        simpa [IndexedGrammar.expandRhs] using h)
    change aSymSem (aS s) w
    simpa [aSymSem, aHeight, aFrom] using h'
  · have h' : aSymSem (aZ (.count :: s)) w := by
      exact (aFormSem_singleton _ _).mp (by
        simpa [IndexedGrammar.expandRhs] using h)
    change aSymSem (aX s) w
    simpa only [aSymSem] using h'
  · have h' : aSymSem (aZ (.count :: s)) w := by
      exact (aFormSem_singleton _ _).mp (by
        simpa [IndexedGrammar.expandRhs] using h)
    change aSymSem (aZ s) w
    simp only [aSymSem] at h' ⊢
    rcases h' with ⟨k, hk, q, m, hq, hm, rfl⟩
    cases hs : aHeight s with
    | none => simp [hs] at hk
    | some j =>
        simp [hs] at hk
        subst k
        exact ⟨j, rfl, q, m, Nat.le_trans (Nat.le_succ j) hq, hm, rfl⟩
  · have h' : aSymSem (aY s) w := by
      exact (aFormSem_singleton _ _).mp (by
        simpa [IndexedGrammar.expandRhs] using h)
    change aSymSem (aZ s) w
    simp only [aSymSem] at h' ⊢
    rcases h' with ⟨n, m, hn, hm, rfl⟩
    exact ⟨n, hn, n, m, Nat.le_refl n, hm, rfl⟩
  · have h' : aFormSem [aY s, aY s] w := by
      simpa [IndexedGrammar.expandRhs] using h
    obtain ⟨u, v, hu, hv, rfl⟩ :=
      (aFormSem_append [aY s] [aY s] w).mp h'
    rw [aFormSem_singleton] at hu hv
    change aSymSem (aY s) (u ++ v)
    change ∃ n m, aHeight s = some n ∧ 0 < m ∧ u = blockPower n m at hu
    change ∃ n m, aHeight s = some n ∧ 0 < m ∧ v = blockPower n m at hv
    rcases hu with ⟨n₁, m₁, hs₁, hm₁, rfl⟩
    rcases hv with ⟨n₂, m₂, hs₂, hm₂, rfl⟩
    have hn : n₁ = n₂ := by simpa [hs₁] using hs₂
    subst n₂
    refine ⟨n₁, m₁ + m₂, hs₁, Nat.add_pos_left hm₁ _, ?_⟩
    exact (blockPower_add n₁ m₁ m₂).symm
  · have h' : aFormSem [aa, aP s] w := by
      simpa [IndexedGrammar.expandRhs] using h
    obtain ⟨u, v, hu, hv, rfl⟩ :=
      (aFormSem_append [aa] [aP s] w).mp h'
    rw [aFormSem_singleton] at hu hv
    change u = [false] at hu
    change ∃ n, aHeight s = some n ∧ v = replicate n true at hv
    subst u
    rcases hv with ⟨n, hn, rfl⟩
    change aSymSem (aY s) ([false] ++ replicate n true)
    refine ⟨n, 1, hn, Nat.zero_lt_one, ?_⟩
    simp [blockPower, abBlock]
  · have h' : aFormSem [ab, aP s] w := by
      simpa [IndexedGrammar.expandRhs] using h
    obtain ⟨u, v, hu, hv, rfl⟩ :=
      (aFormSem_append [ab] [aP s] w).mp h'
    rw [aFormSem_singleton] at hu hv
    change u = [true] at hu
    change ∃ n, aHeight s = some n ∧ v = replicate n true at hv
    subst u
    rcases hv with ⟨n, hn, rfl⟩
    change aSymSem (aP (.count :: s)) ([true] ++ replicate n true)
    refine ⟨n + 1, ?_, ?_⟩
    · simpa [hn]
    · simp [replicate_succ]
  · have hw : w = [] := by simpa [IndexedGrammar.expandRhs, aFormSem] using h
    subst w
    change aSymSem (aP (.bottom :: s)) []
    exact ⟨0, rfl, rfl⟩

private lemma aTransforms_sound {x y : List AG.ISym} (hxy : AG.Transforms x y)
    {w : List Bool} (hy : aFormSem y w) : aFormSem x w := by
  rcases hxy with ⟨r, u, v, s, hr, hx, rfl⟩
  cases hc : r.consume with
  | none =>
      rw [hc] at hx
      rw [hx]
      exact aFormSem_context (fun z hz => by
        simpa [hc] using aRuleSound r hr s z hz) hy
  | some f =>
      rw [hc] at hx
      rw [hx]
      exact aFormSem_context (fun z hz => by
        simpa [hc] using aRuleSound r hr s z hz) hy

private lemma aDerives_sound {x y : List AG.ISym} (hxy : AG.Derives x y)
    {w : List Bool} (hy : aFormSem y w) : aFormSem x w := by
  induction hxy with
  | refl => exact hy
  | tail _ ht ih => exact ih (aTransforms_sound ht hy)

private lemma grammar_subset_indexedIntersectionA :
    AG.Language ≤ indexedIntersectionA := by
  intro w hw
  have hs := aDerives_sound hw (aFormSem_terminals w)
  rw [aFormSem_singleton] at hs
  change aSymSem (aS []) w at hs
  change aFrom 1 w at hs
  rcases hs with ⟨n, m, hn, hm, rfl⟩
  exact ⟨n, m, by omega, hm, rfl⟩

/-- The indexed grammar generates exactly the first witness language. -/
public theorem grammarIndexedIntersectionA_language :
    grammarIndexedIntersectionA.Language = indexedIntersectionA := by
  exact le_antisymm grammar_subset_indexedIntersectionA
    indexedIntersectionA_subset_grammar

/-- The language `{(a b^n)^m | n,m >= 1}` is indexed. -/
public theorem indexedIntersectionA_isIndexed : is_Indexed indexedIntersectionA :=
  ⟨grammarIndexedIntersectionA, grammarIndexedIntersectionA_language⟩

/-! ## The context-free grammar for `indexedIntersectionB` -/

public inductive BNT where
  | S | C | D
deriving DecidableEq

/-- Context-free grammar for `a b^n (a b*)^(n-1)`, `n >= 1`. -/
public def grammarIndexedIntersectionB : CF_grammar Bool where
  nt := BNT
  initial := .S
  rules := [
    (.S, [.terminal false, .terminal true, .nonterminal .C]),
    (.C, [.terminal true, .nonterminal .C, .terminal false, .nonterminal .D]),
    (.C, []),
    (.D, [.terminal true, .nonterminal .D]),
    (.D, [])
  ]

private abbrev BG := grammarIndexedIntersectionB
private abbrev bS : symbol Bool BNT := .nonterminal .S
private abbrev bC : symbol Bool BNT := .nonterminal .C
private abbrev bD : symbol Bool BNT := .nonterminal .D
private abbrev ba : symbol Bool BNT := .terminal false
private abbrev bb : symbol Bool BNT := .terminal true

private def cWord (ns : List Nat) : List Bool :=
  replicate ns.length true ++ varyingBlocks ns

private lemma bStepS : CF_transforms BG [bS] [ba, bb, bC] := by
  exact ⟨(.S, [.terminal false, .terminal true, .nonterminal .C]), [], [],
    by simp [grammarIndexedIntersectionB], rfl, rfl⟩

private lemma bStepC : CF_transforms BG [bC] [bb, bC, ba, bD] := by
  exact ⟨(.C, [.terminal true, .nonterminal .C, .terminal false, .nonterminal .D]),
    [], [], by simp [grammarIndexedIntersectionB], rfl, rfl⟩

private lemma bStopC : CF_transforms BG [bC] [] := by
  exact ⟨(.C, []), [], [], by simp [grammarIndexedIntersectionB], rfl, rfl⟩

private lemma bStepD : CF_transforms BG [bD] [bb, bD] := by
  exact ⟨(.D, [.terminal true, .nonterminal .D]), [], [],
    by simp [grammarIndexedIntersectionB], rfl, rfl⟩

private lemma bStopD : CF_transforms BG [bD] [] := by
  exact ⟨(.D, []), [], [], by simp [grammarIndexedIntersectionB], rfl, rfl⟩

private lemma bGenerateD (n : Nat) :
    CF_derives BG [bD] ((replicate n true).map symbol.terminal) := by
  induction n with
  | zero => simpa using CF_deri_of_tran bStopD
  | succ n ih =>
      apply CF_deri_of_tran_deri bStepD
      convert CF_deri_with_prefix [bb] ih using 1 <;> simp [replicate_succ]

private lemma bGenerateC (ns : List Nat) :
    CF_derives BG [bC] ((cWord ns).map symbol.terminal) := by
  induction ns using List.reverseRecOn with
  | nil => simpa [cWord] using CF_deri_of_tran bStopC
  | append_singleton ns q ih =>
      apply CF_deri_of_tran_deri bStepC
      have hc := CF_deri_with_prefix_and_postfix [bb] [ba, bD] ih
      apply CF_deri_of_deri_deri hc
      have hd := CF_deri_with_prefix
        (bb :: (cWord ns).map symbol.terminal ++ [ba]) (bGenerateD q)
      convert hd using 1 <;>
        simp [cWord, varyingBlocks, abBlock, List.map_append,
          List.append_assoc, replicate_succ]

private lemma indexedIntersectionB_subset_grammar :
    indexedIntersectionB ≤ CF_language BG := by
  rintro w ⟨n, ns, hn, hlen, rfl⟩
  show CF_generates BG (abBlock n ++ varyingBlocks ns)
  unfold CF_generates CF_generates_str
  apply CF_deri_of_tran_deri bStepS
  have hc := CF_deri_with_prefix [ba, bb] (bGenerateC ns)
  convert hc using 1
  rw [← hlen]
  simp [cWord, abBlock, List.map_append, replicate_succ,
    List.append_assoc]

/-! ### Compositional soundness for the context-free grammar -/

private def bSymSem : symbol Bool BNT → List Bool → Prop
  | .terminal t, w => w = [t]
  | .nonterminal .S, w => w ∈ indexedIntersectionB
  | .nonterminal .C, w => ∃ ns : List Nat, w = cWord ns
  | .nonterminal .D, w => ∃ n : Nat, w = replicate n true

private def bFormSem : List (symbol Bool BNT) → List Bool → Prop
  | [], w => w = []
  | x :: xs, w => ∃ u v, bSymSem x u ∧ bFormSem xs v ∧ w = u ++ v

private lemma bFormSem_append (xs ys : List (symbol Bool BNT)) (w : List Bool) :
    bFormSem (xs ++ ys) w ↔
      ∃ u v, bFormSem xs u ∧ bFormSem ys v ∧ w = u ++ v := by
  induction xs generalizing w with
  | nil => simp [bFormSem]
  | cons x xs ih =>
      simp only [List.cons_append, bFormSem]
      constructor
      · rintro ⟨p, q, hp, hq, rfl⟩
        obtain ⟨u, v, hu, hv, rfl⟩ := (ih q).mp hq
        exact ⟨p ++ u, v, ⟨p, u, hp, hu, rfl⟩, hv,
          by simp [List.append_assoc]⟩
      · rintro ⟨u, v, ⟨p, q, hp, hq, rfl⟩, hv, rfl⟩
        exact ⟨p, q ++ v, hp, (ih (q ++ v)).mpr ⟨q, v, hq, hv, rfl⟩,
          by simp [List.append_assoc]⟩

@[simp] private lemma bFormSem_singleton (x : symbol Bool BNT) (w : List Bool) :
    bFormSem [x] w ↔ bSymSem x w := by
  simp [bFormSem]

private lemma bFormSem_terminals (w : List Bool) :
    bFormSem (w.map symbol.terminal) w := by
  induction w with
  | nil => simp [bFormSem]
  | cons x xs ih => exact ⟨[x], xs, rfl, ih, rfl⟩

private lemma bFormSem_context {lhs : symbol Bool BNT}
    {rhs u v : List (symbol Bool BNT)}
    (hsound : ∀ w, bFormSem rhs w → bSymSem lhs w) {w : List Bool}
    (h : bFormSem (u ++ rhs ++ v) w) :
    bFormSem (u ++ [lhs] ++ v) w := by
  rw [List.append_assoc] at h
  obtain ⟨wu, wrv, hu, hrv, rfl⟩ := (bFormSem_append u (rhs ++ v) w).mp h
  obtain ⟨wr, wv, hr, hv, rfl⟩ := (bFormSem_append rhs v wrv).mp hrv
  rw [List.append_assoc]
  apply (bFormSem_append u ([lhs] ++ v) _).mpr
  refine ⟨wu, wr ++ wv, hu, ?_, by simp [List.append_assoc]⟩
  exact (bFormSem_append [lhs] v _).mpr
    ⟨wr, wv, bFormSem_singleton lhs wr |>.mpr (hsound wr hr), hv, rfl⟩

private lemma bRuleSound (r : BNT × List (symbol Bool BNT))
    (hr : r ∈ BG.rules) (w : List Bool) (h : bFormSem r.2 w) :
    bSymSem (.nonterminal r.1) w := by
  simp only [grammarIndexedIntersectionB, List.mem_cons, List.not_mem_nil,
    or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl
  · have h' : bFormSem [ba, bb, bC] w := h
    obtain ⟨u, rest, hu, hrest, rfl⟩ :=
      (bFormSem_append [ba] [bb, bC] w).mp h'
    obtain ⟨v, z, hv, hz, rfl⟩ :=
      (bFormSem_append [bb] [bC] rest).mp hrest
    rw [bFormSem_singleton] at hu hv hz
    change u = [false] at hu
    change v = [true] at hv
    change ∃ ns, z = cWord ns at hz
    subst u
    subst v
    rcases hz with ⟨ns, rfl⟩
    change [false] ++ ([true] ++ cWord ns) ∈ indexedIntersectionB
    refine ⟨ns.length + 1, ns, Nat.zero_lt_succ _, rfl, ?_⟩
    simp [cWord, abBlock, replicate_succ, List.append_assoc]
  · have h' : bFormSem [bb, bC, ba, bD] w := h
    obtain ⟨u, rest, hu, hrest, rfl⟩ :=
      (bFormSem_append [bb] [bC, ba, bD] w).mp h'
    obtain ⟨v, rest', hv, hrest', rfl⟩ :=
      (bFormSem_append [bC] [ba, bD] rest).mp hrest
    obtain ⟨x, y, hx, hy, rfl⟩ :=
      (bFormSem_append [ba] [bD] rest').mp hrest'
    rw [bFormSem_singleton] at hu hv hx hy
    change u = [true] at hu
    change ∃ ns, v = cWord ns at hv
    change x = [false] at hx
    change ∃ q, y = replicate q true at hy
    subst u
    subst x
    rcases hv with ⟨ns, rfl⟩
    rcases hy with ⟨q, rfl⟩
    refine ⟨ns ++ [q], ?_⟩
    simp [cWord, varyingBlocks, abBlock, replicate_succ, List.append_assoc]
  · have hw : w = [] := by simpa [bFormSem] using h
    subst w
    exact ⟨[], by simp [cWord, varyingBlocks]⟩
  · have h' : bFormSem [bb, bD] w := h
    obtain ⟨u, v, hu, hv, rfl⟩ :=
      (bFormSem_append [bb] [bD] w).mp h'
    rw [bFormSem_singleton] at hu hv
    change u = [true] at hu
    change ∃ n, v = replicate n true at hv
    subst u
    rcases hv with ⟨n, rfl⟩
    exact ⟨n + 1, by simp [replicate_succ]⟩
  · have hw : w = [] := by simpa [bFormSem] using h
    subst w
    exact ⟨0, rfl⟩

private lemma bTransforms_sound {x y : List (symbol Bool BNT)}
    (hxy : CF_transforms BG x y) {w : List Bool} (hy : bFormSem y w) :
    bFormSem x w := by
  rcases hxy with ⟨r, u, v, hr, rfl, rfl⟩
  exact bFormSem_context (fun z hz => bRuleSound r hr z hz) hy

private lemma bDerives_sound {x y : List (symbol Bool BNT)} (hxy : CF_derives BG x y)
    {w : List Bool} (hy : bFormSem y w) : bFormSem x w := by
  induction hxy with
  | refl => exact hy
  | tail _ ht ih => exact ih (bTransforms_sound ht hy)

private lemma grammar_subset_indexedIntersectionB :
    CF_language BG ≤ indexedIntersectionB := by
  intro w hw
  have hs := bDerives_sound hw (bFormSem_terminals w)
  rw [bFormSem_singleton] at hs
  exact hs

/-- The context-free grammar generates exactly the second witness language. -/
public theorem grammarIndexedIntersectionB_language :
    CF_language grammarIndexedIntersectionB = indexedIntersectionB := by
  exact le_antisymm grammar_subset_indexedIntersectionB
    indexedIntersectionB_subset_grammar

/-- The language `a b^n (a b*)^(n-1)`, `n >= 1`, is context-free. -/
public theorem indexedIntersectionB_isContextFree : is_CF indexedIntersectionB :=
  is_CF_via_cfg_implies_is_CF
    ⟨grammarIndexedIntersectionB, grammarIndexedIntersectionB_language⟩

/-- The second witness is indexed, since every context-free language is indexed. -/
public theorem indexedIntersectionB_isIndexed : is_Indexed indexedIntersectionB :=
  is_Indexed_of_is_CF indexedIntersectionB_isContextFree

end IndexedIntersectionWitness
